### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by VictorPinas** [wasmerio/wasmer#1000]
Thanks for proposing a new feature!

### Motivation

A clear and concise description of what the motivation for the new feature is, and what problem it is solving.

### Proposed solution

A clear and concise description of the feature you would like to add, and how it solves the motivating problem.

### Alternatives

A clear and concise description of any alternative solutions or features you've considered, and why you're proposed solution is better.

**Comment by syrusakbary** [comment]
This issue seems a duplicate of #950. Closing it :)
