### ISSUE TITLE
Is it possible to resume after a panic?

### ISSUE THREAD

**Issue by Michael-F-Bryan** [wasmerio/wasmer#1049]
I know the wasmer runtime will detect when a host function (i.e. something passed in using `imports!()`) panics and translate that to a `RuntimeError` (presumably around [here](https://github.com/wasmerio/wasmer/blob/71b342e5b1348b310d96266dfdff7a7bcd76c159/lib/runtime-core/src/typed_func.rs#L496-L513)). Is it possible for the top-level caller to use `std::panic::resume_unwind()` to continue panicking?

The `data` in `RuntimeError::Error` is `Box<Any>`, whereas `std::panic::resume_unwind()` expects `Box<dyn Any + Send>`.

I guess one possible solution is to match on the result of `call()` and then explicitly `panic!()` if a runtime error was detected. That would let us continue crashing, but would also mean we lose the original backtrace.

This may be related to #986 or #827.

**Comment by nlewycky** [comment]
I think as a library we don't want to take down the program that's using us by default, though we should make it easy to turn that RuntimeError back into a panic! with the stack information if, as the host program, that's what you want to do.

Maybe it's as simple as making `RuntimeError::Error` a `Box<Any + Send>`?

**Comment by Michael-F-Bryan** [comment]
I think it would be. Or maybe add an extra `HostFunctionPanicked(Box<dyn Any + Send>)` variant to `RuntimeError`? That way you won't accidentally try to resume a `Box<dyn Any + Send>` which isn't actually a panic, and can differentiate between whether a function panicked or just returned an error.
