### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by seamlik** [wasmerio/wasmer#105]
The latest release is 0.1.4 while the crate on `crates.io` is 0.1.0. Considering `wasmer` is just a single program, `crates.io` should be a perfect place to distribute it. Why left it behind?

**Comment by seamlik** [comment]
That's great news!

**Comment by syrusakbary** [comment]
Reopening this ticket, we will close it once the new packages are published :)

**Comment by syrusakbary** [comment]
Hi,

We just published new crates for the wasmer libs:
* [wasmer-runtime](https://crates.io/crates/wasmer-runtime/)
* [wasmer-runtime-core](https://crates.io/crates/wasmer-runtime-core/)
* [wasmer-clif-backend](https://crates.io/crates/wasmer-clif-backend/)

In general, you would only need to use wasmer-runtime.

Here is an example repo on how to use it from Rust (we are still updating it, so probably tomorrow will be completely usable):
https://github.com/wasmerio/wasmer-rust-example
