### ISSUE TITLE
Instance is Send even if it contains !Send host functions

### ISSUE THREAD

**Issue by sfackler** [wasmerio/wasmer#1074]
### Describe the bug

In `wasmer-runtime` 0.11, Instance is always `Send`, but it can contain host functions which are not `Send`.

### Steps to reproduce

Here's an example program that sends an instance containing a non-Send value (Rc) to another thread:

```rust
use wasmer_runtime::{imports, func};
use std::rc::Rc;
use std::thread;
use std::cell::RefCell;

fn main() {
    let module = &[];
    
    let non_send_state = Rc::new(RefCell::new(1i32));
    let imports = imports! {
        "env" => {
            "foobar" => func!({
                let non_send_state = non_send_state.clone();
                move || *non_send_state.borrow()
            }),
        },
    };

    let instance = wasmer_runtime::instantiate(module, &imports).unwrap();

    thread::spawn(move || drop(instance));
}

```

### Expected behavior

It should not compile.

### Actual behavior

It does compile.

### Additional context

The implementations of ExternalFunction need to add a `+ Send` to the `Fn` type parameter.

**Comment by MarkMcCaskey** [comment]
Thanks for reporting this!  I think it slipped through the cracks a bit due to timing, but I've just made a PR to fix it!

**Comment by Hywan** [comment]
Thanks for the bug report, and sorry for the timing!
