### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by wedataintelligence** [wasmerio/wasmer#1085]
Thanks for proposing a new feature!

### Motivation

A clear and concise description of what the motivation for the new feature is, and what problem it is solving.

### Proposed solution

A clear and concise description of the feature you would like to add, and how it solves the motivating problem.

### Alternatives

A clear and concise description of any alternative solutions or features you've considered, and why you're proposed solution is better.

**Comment by MarkMcCaskey** [comment]
Hey!  Thanks for your interest in the project but it looks like you forgot to fill out the issue template.  Feel free to reopen the issue or file another one if you have a feature request.
