### ISSUE TITLE
Add method for reading C-style strings from WasmPtr

### ISSUE THREAD

**Issue by MarkMcCaskey** [wasmerio/wasmer#1086]
Suggested [on spectrum](https://spectrum.chat/wasmer/general/read-string-from-wasm-emscriptens-internal-utils~923a9bb9-4b33-4a23-b9ae-daa5b038f312) .

This is a very good idea, we should support getting a slice from a null-terminated array and probably have a function that just returns a `&str` too.  Edge cases to watch out for are null bytes in UTF-8 may be valid if in code point.  If that is the case, then we'll want to have a helper method specifically for reading UTF-8 from a WasmPtr with a null terminator.  ASCII can probably go through CStr

**Comment by srenatus** [comment]
>  Edge cases to watch out for are null bytes in UTF-8 may be valid if in code point.

From searching the internet, I've come to believe that the only valid code point containing null is null. If that is correct, I don't see how we should differentiate the terminating null from a "non terminating" one. The only way to get an utf8 string from wasm memory that may contain null is the existing one, knowing offset and length.

Am I missing something?

Happy to take a stab at this, but can't make promises wrt. time ;)
