### ISSUE TITLE
Error message looks broken when WAT file fails to parse

### ISSUE THREAD

**Issue by renatoathaydes** [wasmerio/wasmer#1107]
### Describe the bug

```sh
echo "`wasmer -V` | `rustc -V` | `uname -m`"

wasmer 0.11.0 | rustc 1.32.0 (9fda7c223 2019-01-16) | x86_64
```

As shown below, both on `ZShell` and `bash`, the error output is broken on Linux:

![Screenshot from 2019-12-23 17-16-02](https://user-images.githubusercontent.com/1901277/71368407-28f37a00-25a8-11ea-9909-e98563c916a6.png)

### Steps to reproduce

Create a broken WAT file, then try to run it with wasmer.

Example broken WAT file (`example.wat`):

```wat
(module
  
  (export "main" (func $main))

  (func $main (param $n i64)
  ())

  (func $other (param $a))
 
)
```

Run:

```
wasmer example.wat
```

### Expected behavior

Should print something more readable like this:

```
Error: Can't convert from wast to wasm: Error(Parse("example.wast:6:4: error: unexpected token ")", expected an instr.
  ())
   ^
example.wast:8:25: error: unexpected token ")", expected i32, i64, f32, f64, v128 or anyref.
  (func $other (param $a))
```

### Actual behavior

Wasmer actual output:

```
Error: Can't convert from wast to wasm: Error(Parse("example.wast:6:4: error: unexpected token \")\", expected an instr.\n  ())\n   ^\nexample.wast:8:25: error: unexpected token \")\", expected i32, i64, f32, f64, v128 or anyref.\n  (func $other (param $a))\n 
```

**Comment by MarkMcCaskey** [comment]
Thanks for the report!  I agree, it'd be nice if this error message was more readable...

It seems that this is a known issue in wabt-rs https://github.com/pepyakin/wabt-rs/blob/master/src/lib.rs#L35-L40 

I believe we can fix it on our side though...
