### ISSUE TITLE
/usr/bin/ld: cannot find -lwasmer_runtime_c_api

### ISSUE THREAD

**Issue by louisliu2048** [wasmerio/wasmer#1116]
I want to Integration the wasmer into fabric chaincode, but when I instantiate the wasm chaincode, I got this:
![image](https://user-images.githubusercontent.com/35095310/71821334-d26c5c80-30cc-11ea-93a5-e61d8d157f5b.png)

/usr/bin/ld: cannot find -lwasmer_runtime_c_api
collect2: error: ld returned 1 exit status

Any suggestion for me?

**Comment by MarkMcCaskey** [comment]
It looks like it can't find the C library.  I don't have a ton of context here, did you download from our release page or build the C library with the features you want?

It looks like it's called ` libwasmer_runtime_c_api` on Unix-likes and ` wasmer_runtime_c_api.dll` on Windows.

Can you add more information about the linking command you ran?

**Comment by louisliu2048** [comment]
> It looks like it can't find the C library. I don't have a ton of context here, did you download from our release page or build the C library with the features you want?
> 
> It looks like it's called ` libwasmer_runtime_c_api` on Unix-likes and ` wasmer_runtime_c_api.dll` on Windows.
> 
> Can you add more information about the linking command you ran?

Thx！It seems that there are some issuie need to be resolve before the hyperledger fabric peer can support cgo.

**Comment by MarkMcCaskey** [comment]
Oh yeah, needing to use cgo is an unfortunate limitation of using non-Go code from Go.

I'm going to close this issue for now, but feel free to reopen it or file another one if you run into issues using Wasmer!
