### ISSUE TITLE
allow_missing_functions doesn't work in release mode

### ISSUE THREAD

**Issue by slipher** [wasmerio/wasmer#1118]
In release mode, the `allow_missing_functions` option does not work as expected. Instantiation fails with a lot of `ImportNotFound` errors even with the field set to true.

Code to repro is [here](github.com/slipher/wasmer-bug). Steps:

```
git clone https://github.com/slipher/wasmer-bug
cd wasmer-bug
cargo build --release
target/release/sandbox cgame.wasm
```

In debug mode (`cargo build && target/debug/sandbox cgame.wasm`) it works as expected. I observed the same behavior of working only in debug mode on Windows and Linux machines.

**Comment by Hywan** [comment]
The bug is solved in the `master` branch. A new release is coming soon :-).

**Comment by Hywan** [comment]
Thanks for the detailed bub report!
