### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by j209** [wasmerio/wasmer#1132]
We can use java in wasmer.how about kotlin?

**Comment by Hywan** [comment]
Java support is in progress. Kotlin is a solid candidate for a next iteration :-)!

**Comment by jershell** [comment]
Kotlin native has wasm target.  https://kotlinlang.org/docs/reference/native-overview.html (WebAssembly (wasm32)). How I can run my wasm module assembled by kn?

**Comment by Hywan** [comment]
@j209 Closing in favor of https://github.com/wasmerio/wasmer-java/issues/39. `wasmer-java` exists, but some users are experiencing issue with Kotlin. Your help is welcome there!

**Comment by Hywan** [comment]
@jershell I don't see WebAssembly mentionned in this document :-). Maybe it's because of https://discuss.kotlinlang.org/t/state-of-webassembly-in-kotlin/18348?
