### ISSUE TITLE
Make wabt an optional dependency

### ISSUE THREAD

**Issue by losfair** [wasmerio/wasmer#1178]
Currently we depend on `wabt` for tests and various type definitions. However `wabt` requires a C++ compiler to build, which is not included in the [musl](https://www.musl-libc.org/) toolchain.

This issue is blocking https://github.com/wasmerio/wasmer/issues/1173 , and needs to be fixed.

**Comment by nlewycky** [comment]
Why doesn't the musl toolchain include a C++ compiler? More broadly, is there documentation covering what it means to be a rust toolchain and why it includes a C++ compiler or how we should depend on C++ code from rust if it's not part of the rust toolchain package, etc?

**Comment by losfair** [comment]
Related:

- https://github.com/rust-lang/cargo/issues/3359
- https://github.com/emk/rust-musl-builder/issues/53

I tried symlinking `g++` to `musl-g++` but it doesn't work:

```
error: could not find native static library `stdc++`, perhaps an -L flag is missing?

error: aborting due to previous error

error: could not compile `wabt-sys`
```

musl is a libc implementation and does not include C++ standard libraries. To depend on C++ code w/o dynamic linking I think we need to modify the build system to use a native C++ compiler, but there can be ABI incompability issues.
