### ISSUE TITLE
Is it possible to trace WASI calls?

### ISSUE THREAD

**Issue by vshymanskyy** [wasmerio/wasmer#1182]
It looks like I need to trace WASI calls (with argument values) for debugging purposes. Is it possible with Wasmer currently?
I see some flags like `--call-trace` `--block-trace` , but they appear to do nothing.

**Comment by MarkMcCaskey** [comment]
Wasmer has an opt-in `debug` feature and `debug` flag, but you will have to compile Wasmer to use them.

If you're using the Wasmer CLI, you can compile with `--features "debug"` and then run with the `--debug` flag (flag not needed prior to 0.13.0 I believe) to get debug output which will show WASI calls and some extra information.  Unfortunately this is a bit ad-hoc right now.  Something I've thought about for a bit now is that it'd be nice to create a procedural macro to do the tracing of syscalls automatically, it's just not something I've spent the time to do yet.

If you're using Wasmer as a library then:
- if you're using a version below 0.13.0 (please upgrade if possible and let us know if you run into issues. But if you can't...), you can compile with the `debug` feature and get printed output the same as with the CLI
- if you're using an up-to-date version (0.13.1 at the time of writing), you can use a logger which works with the traits in the [log crate](https://crates.io/crates/log), this gives you the ability to easily filter and get only the log messages you actually care about as well.

----

The current log messages are built ad-hoc to solve common issues that we've run into, if they're missing information that you'd like to have, please make a pull request or file an issue so we can improve them!
