### ISSUE TITLE
The `import!` macro should be a trait you can derive on functions

### ISSUE THREAD

**Issue by icefoxen** [wasmerio/wasmer#120]
...because it would be rad.  I'm imagining something like, opposed to your example (https://medium.com/wasmer/executing-webassembly-in-your-rust-application-d5cd32e8ce46):

```rust
#[derive(Wasmable)]
fn print_str(x: u32, y: u32) {
   ...
}

 let import_object = ImportObject::from(vec![
    ("env", print_str),
]);
```

Not sure about the details.  Seems like it should be possible though.

More specifically, I often find that using macros to define DSL's for building stuff to be a pain in the long run.  Either using builders or derives ends up easier to find and deal with, at least IMO.  It's a matter of taste though.

**Comment by lachlansneff** [comment]
That would be rad! My original idea was to add an attribute-like procedural macro that would have a similar function, but I decided on a normal macro for timing-related reasons.

If you want to take this on, we can provide mentoring, advice, and help!

**Comment by icefoxen** [comment]
Ahahaha wow, I do *not* have time to work on it.  XD

...though I've never written a derive that complicated, so it might be fun.  Hmmmm...

No, I have way too many little side-projects going on as it is.  Not now, at least.  Sorry.

**Comment by lachlansneff** [comment]
No worries. We'll likely work on this or something similar at some point, though there are more pressing issues to tackle beforehand.
