### ISSUE TITLE
"Illegal instruction" error the second time a panic is caught (Windows-only?)

### ISSUE THREAD

**Issue by hrydgard** [wasmerio/wasmer#1204]
When a panic happens in the "Instance" during a `.call()`, a Result is correctly returned with a `RuntimeError: WebAssembly trap occured during runtime: unreachable`. (Not sure about "unreachable", but whatever).

However, on Windows, when this happens a second time in the execution of the host process, you instead get an "Illegal Instruction" exception and the host process dies.

```
error: process didn't exit successfully: `target\debug\rust_embedder_app.exe` (exit code: 0xc000001d, STATUS_ILLEGAL_INSTRUCTION)
Illegal instruction
```

### Steps to reproduce

This can be reproduced very easily using https://github.com/wasmerio/wasmer-rust-example:

Simply make the following changes:

To `src/lib.rs`: Replace the last few lines of main() with:

```rust

    for _i in 0..2 {
        // Compile our webassembly into an `Instance`.
        let instance = instantiate(WASM, &import_object)?;

        // Call our exported function!
        instance.call("hello_wasm", &[])?;
        if let Err(err) = instance.call("please_panic", &[]) {
            println!("Got a panic! {:?}", err);
        }
    }

    Ok(())
```

To `wasm-sample-app/src/lib.rs`: Add the following to the end:
```rust
#[no_mangle]
pub extern "C" fn please_panic() {
    panic!("OK, panicking!");
}
```

Then build the sample app using `cargo build --release` in its directory, go back up and `cargo run`:

```
Hello, World!
0: Hello, World!
2: Hello, World!
Got a panic! RuntimeError: WebAssembly trap occurred during runtime: unreachable
Hello, World!
2: Hello, World!
4: Hello, World!
error: process didn't exit successfully: `target\debug\rust_embedder_app.exe` (exit code: 0xc000001d, STATUS_ILLEGAL_INSTRUCTION)
Illegal instruction
```

This is with Wasmer 0.13.1 (which is what the wasmer-rust-example currently uses).

Note: edited to add language syntax highlighting

**Comment by syrusakbary** [comment]
Thanks for the detailed report!

**Comment by MarkMcCaskey** [comment]
I've just confirmed that commenting out [these lines](https://github.com/wasmerio/wasmer/blob/master/lib/win-exception-handler/exception_handling/exception_handling.c#L32-L35) fixes the issue.

Those lines look like they're there to prevent another bug... I'll look into it more.  The issue seems to be that `alreadyHandlingException` is never reset
