### ISSUE TITLE
Make wabt optional

### ISSUE THREAD

**Issue by Schmeckinger** [wasmerio/wasmer#121]
Would it be possible to make wabt/wat optional and put it in default features, so you can turn it off with ```default-features = false```?

**Comment by lachlansneff** [comment]
Yeah, this is related to a different issue we're having where we're building the spectests everytime wasmer-runtime-core is built. We're working on a solution which should prevent wabt from being compiled everytime as well.

**Comment by lachlansneff** [comment]
This is implemented on the master branch now! The `runtime` (and `runtime-core`) crate don't require wabt as a dependency anymore.
