### ISSUE TITLE
Creating and using Vec in wasm module causes panic

### ISSUE THREAD

**Issue by csos95** [wasmerio/wasmer#123]
Hi, I am playing around with using the rust runtime to create plugins and I have run into an issue with creating and putting values in a vector.

For a minimal reproduction, take the example [here](https://github.com/wasmerio/wasmer-rust-example) then create and push to a vector inside the hello_wasm function.
```rust
#[no_mangle]
pub extern fn hello_wasm() {
    // Call the function we just imported and pass in
    // the offset of our string and its length as parameters.
    let mut vec = Vec::new();
    for i in 0..10 {
        vec.push(i);
    }
    unsafe {
        print_str(HELLO.as_ptr(), HELLO.len());
    }
}
```
When you run it now, it will panic when you try to instantiate the wasm module.

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:355:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:211
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:491
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:398
   6: rust_begin_unwind
             at src/libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:95
   8: core::panicking::panic
             at src/libcore/panicking.rs:59
   9: wasmer_clif_backend::resolver::FuncResolverBuilder::finalize
  10: wasmer_clif_backend::module::Module::compile
  11: <wasmer_clif_backend::CraneliftCompiler as wasmer_runtime_core::backend::Compiler>::compile
  12: wasmer_runtime_core::compile_with
  13: wasmer_runtime::instantiate
  14: application::main
  15: std::rt::lang_start::{{closure}}
  16: std::panicking::try::do_call
             at src/libstd/rt.rs:59
             at src/libstd/panicking.rs:310
  17: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:102
  18: std::rt::lang_start_internal
             at src/libstd/panicking.rs:289
             at src/libstd/panic.rs:398
             at src/libstd/rt.rs:58
  19: main
  20: __libc_start_main
  21: _start
```

EDIT: I stepped through with gdb and it looks like it is panicking on [this line](https://github.com/wasmerio/wasmer/blob/7632beced824ed835f26ef7c105105f49384317d/lib/clif-backend/src/resolver.rs#L116)

EDIT2: The same thing happens when I try to use a hashmap
```rust
use std::collections::HashMap;
#[no_mangle]
pub extern fn hello_wasm() {
    // Call the function we just imported and pass in
    // the offset of our string and its length as parameters.
    let mut hashmap: HashMap<u8, u8> = HashMap::new();
    hashmap.insert(0, 0);
    unsafe {
        print_str(HELLO.as_ptr(), HELLO.len());
    }
}
```

**Comment by lachlansneff** [comment]
Hi, thanks for using Wasmer!

We've looked into this and it turns out to be related to a bug we've seen in the past. One of our PRs has the fix, but it hasn't been merged yet. We're going to merge that fix specifically.

If you're interested in the internals of how this works:

When we resolve a function index to an address in [`resolver.rs`], we forgot to offset its index by the number of imported functions. In Wasm, the imported and local functions share the same index space, but imports always come first. [Here] is the specific commit that fixes this.

[`resolver.rs`]: https://github.com/wasmerio/wasmer/blob/59ce7ea54bf1b27e8e941d65628429200206b222/lib/clif-backend/src/resolver.rs#L116
[Here]: https://github.com/wasmerio/wasmer/pull/114/commits/3e9ef57d9dec82ff7b4a16af1d4e408c11fabfdf

**Comment by lachlansneff** [comment]
We've just published the fixed version to crates.io. Give it a try and let us know if anything else breaks! :)
