### ISSUE TITLE
Add `deny(clippy::missing_safety_doc)` to all crates

### ISSUE THREAD

**Issue by MarkMcCaskey** [wasmerio/wasmer#1230]
As discussed in #1219

Implemented for wasi in #1229 

`unsafe` requires manual verification that the function is being used correctly.  In order to be able to manually verify, we must document which in invariants must be upheld.  This is usually done in the `# Safety` section of a doc comment.

- [ ] Runtime core
- [ ] Runtime
- [ ] Clif backend
- [ ] LLVM backend
- [ ] Singlepass backend
- [ ] Middleware common
- [ ] Runtime C API (need to discus whether or not this makes sense as these safety comments will be exported to the C API -- probably a good thing, but perhaps it'll be too verbose)
- [x] WASI - #1229 
- [ ] Emscripten

To implement this, simply add `#![deny(clippy::missing_safety_doc)]` to the root of the crate and fix the errors reported by running `cargo clippy`

**Comment by Hywan** [comment]
Still relevant even if all crates have been renamed.

**Comment by epilys** [comment]
This was implemented in 5339f7cdaebe9295e2657d7ed2fe48053c620f92 which was merged into `master`. Now all default clippy lints are `deny` by default and it's part of the CI check for new PRs
