### ISSUE TITLE
Embedding wasm runtime to Dart VM using wasmer

### ISSUE THREAD

**Issue by bitbeast18** [wasmerio/wasmer#1239]
### Motivation
I'm interested in exploring the possibility of integrating Wasmer with Dart to be able to provide a wasm runtime for running wasm compiled modules alongside the Dart code. This is coming from a project idea at [GSoC 2020](https://github.com/dart-lang/sdk/wiki/Dart-GSoC-2020-Project-Ideas#idea-integrate-wasm-runtime-into-dart-vm).

Also, some directions towards achieving this would be helpful. I'd love to work on it.

**Comment by syrusakbary** [comment]
Hi @bitbeast18,

That would be a great addition indeed. I think @liamappelbe might be able to assist you on that since he did some work on that front!

Let us know if we can be off any help!
Note: We created some nice documentation on the Wasmer C API integration, that might be useful for this case:

https://docs.wasmer.io/integrations/c/

**Comment by liamappelbe** [comment]
Hi @bitbeast18,

Thanks for taking an interest in Dart's GSoC projects. I wasn't aware that WASM integration was one of the proposed projects. Unfortunately this would be replicating existing work that I and some other folks have done. So I've let the organizers know and they'll come up with another idea instead. Sorry for the confusion.

**Comment by syrusakbary** [comment]
Closing the issue for now :)

**Comment by bitbeast18** [comment]
> Hi @bitbeast18,
> 
> Thanks for taking an interest in Dart's GSoC projects. I wasn't aware that WASM integration was one of the proposed projects. Unfortunately this would be replicating existing work that I and some other folks have done. So I've let the organizers know and they'll come up with another idea instead. Sorry for the confusion.

Thanks for the clarification @liamappelbe .

**Comment by gedw99** [comment]
its sot of already done here: https://github.com/rodydavis/flutter_wasm_interop/blob/ffi/example/src/lib.rs
