### ISSUE TITLE
Support For Pinebook Pro (Manjaro ARM)

### ISSUE THREAD

**Issue by CuriousTommy** [wasmerio/wasmer#1266]
### Summary

I want to try and run wasmer on my Pinebook Pro (running Manjaro ARM), but it seems like the script does not provide support for it. Would it be possible to add support for it?

### Additional details
The output the script gave
```
$ curl https://get.wasmer.io -sSfL | sh
which: no wasmer in (/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
Installing Wasmer and WAPM!

> Getting wasmer releases... ✓
which: no wasmer in (/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
> Downloading 0.14.1 release...
######################################################################## 100.0%
> Your architecture is not yet supported (linux-arm64).
> Please open an issue on the project if you would like to use wasmer in your project: https://github.com/wasmerio/wasmer
```

**Comment by icefoxen** [comment]
For reference, you can build wasmer from source on Pinebook Pro using the instructions [here](https://docs.wasmer.io/ecosystem/wasmer/building-from-source).

**Comment by syrusakbary** [comment]
Yup. We will also release the binaries for ARM in next releases automatically.

**Comment by syrusakbary** [comment]
The releases for ARM are now working properly.

You can check them on the latest release: `0.16.0`:
https://github.com/wasmerio/wasmer/releases/tag/0.16.1

And... the install script should now work automatically in those devices!

```bash
curl https://get.wasmer.io -sSfL | sh
```

Closing the issue! (feel free to reopen if is not working for you)

**Comment by CuriousTommy** [comment]
@syrusakbary I tested the script on my Pinebook Pro, it works great!
