### ISSUE TITLE
Support /_wasmer/dev/tty/input

### ISSUE THREAD

**Issue by richardanaya** [wasmerio/wasmer#1275]
Support terminal raw mode with a new device

### Motivation

Enable applications like CLI text editors and roguelikes

### Proposed solution

Mirror the experimental I/O framebuffer input into one for TTY.

Reading - be able to read a byte at a time

Writing - be able to write the input mode from DEFAULT to RAW and back again.

### Alternatives

There's no alternative i'm aware of currently.  stdin only allows input once enter is pressed.

**Comment by Hywan** [comment]
Still relevant.
