### ISSUE TITLE
Wasmer panics after 16K / 32K runs

### ISSUE THREAD

**Issue by sasurobert** [wasmerio/wasmer#1279]
We are using go-ext-wasm and wasmerio, version from master + a few changes from our part and after thousands of consequent runs wasmer rust panic with memory issues.

A few error messages from wasmer directly:

```
could not create wasmer instance: link error: unable to create memory: UnableToCreateMemory
...
thread '<unnamed>' panicked at 'Could not allocate a larger buffer: Os { code: 12, kind: Other, message: "Cannot allocate memory" }',
...
memory allocation of [139280] bytes failed SIGABRT: abort
...
thread '<unnamed>' panicked at 'cannot set code memory to executable', lib/runtime-core/src/loader.rs:189:13
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace.
```

We run go-ext wasmer stateless, cleaning the memory every time, before and after run, HOWEVER we found a memory leak in wasmerio, some of the memory is not cleaned.

This is the zone the code panics: https://github.com/ElrondNetwork/wasmer/blob/c207b318dadce2e21d3e9c42dbed7a1e06ee073c/lib/runtime-core/src/trampoline_x64.rs#L22
Did anyone has the same problem ?

The issue can be reproduced by using the following test code in go-ext-wasmer: (benchmarks/wasmer folder)

```go
func Test_Wasmer_Fibonacci_Recursive(t *testing.T) {
	wasmBytes := GetBytes("fib_recursive.wasm")

	for i := 0; i < 40000; i++ {
		fmt.Println("number of runs " + strconv.Itoa(i))
		instance, _ := wasmer.NewInstance(wasmBytes)
		result, _ := instance.Exports["app_main"](nil)

		_ = result
	}
}
```

**Comment by Hywan** [comment]
Thanks for the bug report. We will take a look at it!

**Comment by syrusakbary** [comment]
@losfair can you take a look at this?

**Comment by syrusakbary** [comment]
Note: I'm not sure if this is a Rust issue, or a Go issue. It might be that we are allocating memory in Rust, but Go doesn't know how to free it.
If that's the case this link might be useful (calling `defer C.free(unsafe.Pointer(...)) `): https://stackoverflow.com/questions/35507467/cgo-how-to-free-memory-allocated-in-c-using-malloc-from-go-to-avoid-memory-leak

**Comment by losfair** [comment]
A quick search in `go-ext-wasm` yields no `runtime.SetFinalizer` calls that release a `Instance`. Seems that we are not freeing the instance created by `wasmer.NewInstance`.

**Comment by Hywan** [comment]
An instance must be closed with [`instance.Close()`](https://pkg.go.dev/github.com/wasmerio/go-ext-wasm/wasmer?tab=doc#Instance.Close).

**Comment by sasurobert** [comment]
Thanks. This resolved the issue.

**Comment by robinvanemden** [comment]
@sasurobert did this indeed resolve your issue? We currently encounter the same problem, and have been unable to resolve it. See [here](https://github.com/wasmerio/go-ext-wasm/issues/82).

@syrusakbary any suggestions are more than welcome 👍
