### ISSUE TITLE
Q: embed into C++

### ISSUE THREAD

**Issue by geloizi** [wasmerio/wasmer#128]
It's it possible to use wasmer from a native application written in C++?

**Comment by lachlansneff** [comment]
This is something we're working on, stay tuned!

**Comment by geloizi** [comment]
One more question - what is the advantage of wasmer over webassembly built into V8 js engine? It's it faster/needs less memory? Also what about concurrency? 

P.S. you need a mailing list 😀

**Comment by lachlansneff** [comment]
Wasmer is designed from the ground up to be extremely configurable for the use-case at hand. There are advantages to both, we have a much smaller codebase than v8 and have a nicer api, if I say so myself. We don't yet support wasm's future threading support, but we will when the time comes.

As for a mailing list, we were going to announce this on Monday, but we putting our public forum at https://spectrum.chat/wasmer!

**Comment by syrusakbary** [comment]
Related PR: #135

**Comment by syrusakbary** [comment]
@geloizi we are working on this issue in the #135 PR.
Please let us know if you have any suggestion on the API :)

**Comment by dio** [comment]
OMG this is cool!

**Comment by syrusakbary** [comment]
Our C/C++ API is now merged and usable!

We wrote about it here: https://medium.com/wasmer/running-webassembly-from-any-language-5741f6320ccd

You can also find our example repo for the C integration: https://github.com/wasmerio/wasmer-c-api

Closing the issue :)
