### ISSUE TITLE
run the nginx.wasm on kernel loader

### ISSUE THREAD

**Issue by yz89** [wasmerio/wasmer#1296]
### Summary

How to run the `nginx.wasm` on kernel loader ?

Was `nginx.wasm` generated by Emscripten?

### Additional details
system:
ubuntu 18.04

command: 
`wasmer run --backend singlepass --loader local nginx.wasm -- -p . -c nginx.conf`

error:
Error: Can't instantiate loader module: LinkError([ImportNotFound { namespace: "env", name: "memory" }, ImportNotFound { namespace: "env", name: "table" }, ImportNotFound { namespace: "env", name: "memoryBase" }, ImportNotFound { namespace: "env", name: "tableBase" }, ImportNotFound { namespace: "env", name: "DYNAMICTOP_PTR" }, ImportNotFound { namespace: "env", name: "tempDoublePtr" }, ImportNotFound { namespace: "env", name: "ABORT" }, ImportNotFound { namespace: "env", name: "STACKTOP" }, ImportNotFound { namespace: "env", name: "STACK_MAX" }, ImportNotFound { namespace: "global", name: "NaN" }, ImportNotFound { namespace: "global", name: "Infinity" }])

**Comment by losfair** [comment]
Hello,

From the error message it looks like `nginx.wasm` is built with Emscripten. The kernel loader only supports the WASI host interface and Emscripten is not supported (and it's unlikely to be supported, since it would be too complex to be implemented as a part of the kernel safely).

**Comment by yz89** [comment]
Thank you for your reply.

Is this make sense if I provide the Emscripten env for the kernel loader. I change the code and use `emscripten_env` as `import_object`.
