### ISSUE TITLE
Improve structure of wasitest tests

### ISSUE THREAD

**Issue by MarkMcCaskey** [wasmerio/wasmer#1309]
Wasitests were updated in #1300.  Currently things are lexically scoped (for example: `snapshot1_<test-name>`), ideally these should use the module system (like `snapshot1::<test_name>`).

As part of this change, we'll need to handle this in the ignores file too.  And the overall structure can be changed so that we generate in chunks based on the WASI version.

**Comment by syrusakbary** [comment]
Our WASI tests are greatly improved in the refactor. Thus, we can close this issue once it lands

**Comment by syrusakbary** [comment]
Closing issue since the refactor has now landed in `master`.
