### ISSUE TITLE
Inconsistent use of `const` in memory pointer in C API

### ISSUE THREAD

**Issue by MarkMcCaskey** [wasmerio/wasmer#1314]
Reported in https://github.com/wasmerio/docs.wasmer.io/issues/43.

```
  const wasmer_memory_t *memory = wasmer_instance_context_memory(ctx, 0);
  wasmer_memory_data_length(memory);
```

Causes a warning on Clang (OSX) and is possibly an error with GCC on Linux.  `wasmer_instance_context_memory` returns a `const wasmer_memory_t*` but `wasmer_memory_data_length` wants a `wasmer_memory_t*`.

This bug is affecting our documentation examples, ideally we should be testing these in CI on both sides.  See https://github.com/wasmerio/docs.wasmer.io/issues/46 for the issue on fixing CI on the docs repo side.

**Comment by Hywan** [comment]
@syrusakbary and I have already discussed to test the documentation, but testing Doxygen examples isn't that easy. Thanks for the bug report though! #1335 is fixing it.
