### ISSUE TITLE
Replace Slack link with a working one in readme

### ISSUE THREAD

**Issue by frank-dspeed** [wasmerio/wasmer#1319]
### Describe the bug
Replace Slack link with a working one in readme

### Steps to reproduce
click on slack inside the readme

### Expected behavior

shows registration page
### Actual behavior
shows link not valid anymore

**Comment by MarkMcCaskey** [comment]
Thanks for the report and sorry about the delay!  This slipped through the cracks, but we've just pushed a fix which will hopefully keep working.  I'll leave this issue open for another few weeks in case the problem reoccurs.

**Comment by syrusakbary** [comment]
This should be fixed. Closing :)
