### ISSUE TITLE
Document contribution process

### ISSUE THREAD

**Issue by MarkMcCaskey** [wasmerio/wasmer#1323]
The issue came up [on spectrum](https://spectrum.chat/wasmer/general/can-i-a-non-member-of-the-repository-run-tests-via-bors~633b641c-a70e-488a-9432-a82a6bdba556) that we don't document how to run tests, for example, or how to deal with our release process in general.

We should create a small document and link to it in visible places (possibly by updating the issue filing template) that explains how bors works, links to bors's documentation, and gives information on the rest of our process.

**Comment by Hywan** [comment]
Closing since we have https://github.com/wasmerio/wasmer/blob/master/CONTRIBUTING.md, introduced in https://github.com/wasmerio/wasmer/pull/684 and updated later.
