### ISSUE TITLE
Success stories compiling databases?

### ISSUE THREAD

**Issue by armarti** [wasmerio/wasmer#133]
This is a very interesting project, and I’m searching for a way to use it. 

I’d really like to try building a graph database in a browser. ArangoDB is a graph database built on C++ and javascript so it seems like a nice place to start. 

Question is, have you been able to build any other native DBs with wasmer, e.g. postgres or sqlite?

**Comment by syrusakbary** [comment]
@armarti we are working on getting SQLite working with wasmer (compiled with emscripten).
Here's an example of how to compile SQLite to be executed browser-side: https://github.com/mandel59/sqlite-wasm/

You can probably use Emscripten as well to compile ArangoDB to WebAssembly, and run it on the browser. Or use wasmer to execute it server-side :)

**Comment by armarti** [comment]
Right of course, that's what I meant. Thanks a ton for the links. I'll have a look.

**Comment by syrusakbary** [comment]
As of right now, we were able to compile and successfully run the following DBs:
* [sqlite](https://github.com/mackyle/sqlite): https://wapm.io/package/sqlite (WASI)
* [tidb](https://github.com/pingcap/tidb): https://wapm.io/package/lucklove/tidb (WASI)

Both are actually usable from the native wapm CLI (installed when installing Wasmer) and also the [online WebAssembly shell](https://webassembly.sh).

**Comment by syrusakbary** [comment]
Closing the issue. Future readers: feel free to comment here with use cases of DBs in WebAssembly!
