### ISSUE TITLE
Allow disabling cranelift verifier explicitely

### ISSUE THREAD

**Issue by webmaster128** [wasmerio/wasmer#1330]
### Motivation

At [CosmWasm](https://github.com/CosmWasm/cosmwasm) we use debug builds of wasmer+cranelift for integration testing smart contracts that have been compiled to Wasm files before. Due to [a change in the cranelift backend with debug assertions](https://github.com/wasmerio/wasmer/commit/5e3147db0882e26db70c962d3e3cd0b62d8281cb#diff-02f9535bb166cb207b858de844a0c257R46), those tests now run significantly slower than before. Cranelift is our default backend for development purposes since it compiles with Rust stable. In order to increase the experience for smart contract developers, it would be great to be able to disable verifier independent of the build mode.

### Proposed solution

There are two solutions that come to my mind:
1. Reconsider the decision to enable the verifyier by default whenever Wasmer is build with debug assertions. Maybe it makes sense to allow enabling it explicitely.
2. Create a flag that allows disabling the verifier, which overrides the defaults

### Alternatives

It turns out that is it [possible to override](https://doc.rust-lang.org/cargo/reference/profiles.html#overrides) `wasmer-clif-backend`'s build settings via:

```
[profile.dev.package.wasmer-clif-backend]
debug-assertions = false
opt-level = 1
```

However, this assumes the cranelift specific verifier is always bound to `cfg!(debug_assertions)`.

Also this override seems to be doable in the final project only, and the package `cosmwasm-vm` cannot set this for all of its users.

### Additional context

- Discussion in CosmWasm: https://github.com/CosmWasm/cosmwasm/issues/155
- Example integration test: [VM](https://github.com/CosmWasm/cosmwasm/blob/v0.7.2/packages/vm/Cargo.toml#L14-L39), [smart contract](https://github.com/CosmWasm/cosmwasm/blob/v0.7.2/contracts/hackatom/Cargo.toml#L23-L38), [integration test](https://github.com/CosmWasm/cosmwasm/blob/v0.7.2/contracts/hackatom/tests/integration.rs), [build and run command](https://github.com/CosmWasm/cosmwasm/blob/v0.7.2/contracts/hackatom/.cargo/config#L4)

**Comment by MarkMcCaskey** [comment]
Thanks for letting us know!  I agree that it would be good to have a way to toggle these off in debug mode.  I think we'll want to keep it on by default in debug mode for now, but we can add an opt-out!

**Comment by MarkMcCaskey** [comment]
The solution I created in #1332 adds an option to the `CompilerConfig` struct, which means you'll have to use `compile_with_config` or `compile_with_config_with` to pass it in but you should be able to write:
```Rust
let compiler_config = CompilerConfig {
   disable_debug_mode_verification: true,
   ..Default::default()
};
```

and then pass that in and everything should just work!

**Comment by webmaster128** [comment]
This works (https://github.com/CosmWasm/cosmwasm/pull/186/commits/d36403179e008cda347a36074cd8afa17bd84b40). Thanks a lot for the quick update!
