### ISSUE TITLE
Should it work with invoke?

### ISSUE THREAD

**Issue by aleksmelnikov** [wasmerio/wasmer#1344]
### Describe the bug

```sh
echo "`wasmer -V` | `rustc -V` | `uname -m`"
wasmer 0.16.2 | rustc 1.42.0 (b8cedc004 2020-03-09) | x86_64
```

```sh
echo "`wasmtime -V` | `rustc -V` | `uname -m`"
wasmtime 0.12.0 | rustc 1.42.0 (b8cedc004 2020-03-09) | x86_64
```

### Steps to reproduce
1. create a simple library crate
```
$cat a/src/lib.rs

#[no_mangle]
pub extern "C" fn funca() {
   println!("funca");
}
```
2. compile the crate

`$cargo build --manifest-path=a/Cargo.toml --target wasm32-wasi`

3. run `wasmer` with `invoke`

`$wasmer run --invoke funca a/target/wasm32-wasi/debug/a.wasm`

### Expected behavior

`funca`

### Actual behavior

`Error: ExportNotFound { name: "_start" }`

### Additional context
`Wasmtime` can invoke this crate without errors:
```
$wasmtime run --invoke funca a/target/wasm32-wasi/debug/a.wasm
funca
```

**Comment by MarkMcCaskey** [comment]
Thanks for the report!

Background information is that currently `invoke` only works with Wasm modules with no ABIs in Wasmer.  Additionally WASI modules are not valid, in general, until `_start` has been called.  So even if we allowed this it would break in cases that use WASI APIs that require setup until WASI is updated to work without having to call `_start` first (I believe this is a work in progress!).

Perhaps it is more ergonomic to attempt to `invoke` functions regardless of missing imports/exports.  Some of the edge cases here might be tricky... but perhaps we can just print a warning message letting the user know that it may not work.

**Comment by aleksmelnikov** [comment]
@MarkMcCaskey , I have changed my code to:

```
$cat a/src/lib.rs

#[no_mangle]
pub extern "C" fn funca() {
   println!("funca");
}

#[no_mangle]
pub extern "C" fn _start() {
}
```
Then I can run with invoke:
```
$wasmer run --invoke funca a/target/wasm32-wasi/debug/a.wasm
WARNING: Invoking aribtrary functions with WASI is not officially supported in the WASI standard yet.  Use this feature at your own risk!
funca
funca([]) returned []

$wasmer run --enable-all --invoke funca a/target/wasm32-wasi/debug/a.wasm
WARNING: Invoking aribtrary functions with WASI is not officially supported in the WASI standard yet.  Use this feature at your own risk!
funca
funca([]) returned []
```
Thank you. And maybe it will be usefull to have an option to hide the warning and `funca([]) returned []`.
