### ISSUE TITLE
Improve WASI docs/extended basic example docs

### ISSUE THREAD

**Issue by MarkMcCaskey** [wasmerio/wasmer#1348]
Inspired by #1347, we should have more complete documentation on the process of getting started and resolving various types.  In particular, the intro to the wasmer-wasi docs should be more detailed and include more examples and the specific methods and types should have more cross-links to make exploration simpler.

**Comment by syrusakbary** [comment]
We have added a WASI example on the refactor. Once it lands, the example url will be:
https://github.com/wasmerio/wasmer/blob/master/examples/wasi.rs

**Comment by syrusakbary** [comment]
Closing the issue since we added the example and improved a bit the docs.
