### ISSUE TITLE
OCI compatible wrapper for wasmer

### ISSUE THREAD

**Issue by dippynark** [wasmerio/wasmer#1352]
### Motivation

Similar to issues https://github.com/bytecodealliance/wasmtime/issues/358 and https://github.com/dmcgowan/containerd-wasm/issues/2 it'd be great to have an [OCI runtime compatible](https://github.com/opencontainers/runtime-spec/blob/master/spec.md) wrapper for wasmer to allow containerd and in particular Kubernetes to run wasi/wasm modules.

I have been working on a fork of https://github.com/dmcgowan/containerd-wasm (https://github.com/dippynark/containerd-shim-wasm) to run wasmer instances which works okay, but it ignores a lot of the OCI runtime spec (for example namespaces and cgroups). Implementing this properly would be very valuable.

Some of the questions I hope this issue would answer:
- Is this functionality wanted (in particular the ability to run wasm modules on Kubernetes clusters which is where my personal interest in this feature is) 
- Is running wasm instances in the way mandated by the OCI runtime spec appropriate? (it feels flexible enough to support the different potential implementations, but maybe not)
- Are there other options in development/planned that'd provide the same functionality

### Proposed solution

A new binary (maybe called runwc to align with [runsc](https://github.com/google/gvisor/tree/master/runsc) and runc) that can be executed from a shim (like linked above) that respects the OCI runtime spec and runs wasm modules. These wasm modules could be run either by executing the wasmer binary directly (similarly to the implementations linked above) or using the [go library](https://github.com/wasmerio/go-ext-wasm).

### Alternatives

My main interest in this feature is for a Kubernetes integration to allow users to run wasm modules on their clusters. A [CRI](https://kubernetes.io/blog/2016/12/container-runtime-interface-cri-in-kubernetes/) implementation could be used to integrate with the kubelet but afaik this would only allow a cluster node to be all wasm containers or all 'normal' containers. Integration with containerd via a shim would allow 'normal' containers and wasm containers to run side-by-side on the same node, as well as the amount of code needing to be written to be smaller.

Krustlet (https://github.com/deislabs/krustlet) is also a cool project that replaces the entire kubelet with one that has wasm runtime as a first class concept.

**Comment by syrusakbary** [comment]
> Is this functionality wanted (in particular the ability to run wasm modules on Kubernetes clusters which is where my personal interest in this feature is)

Yes, I think few enterprises are looking into the space :)

> Is running wasm instances in the way mandated by the OCI runtime spec appropriate? (it feels flexible enough to support the different potential implementations, but maybe not)

I think the OCI runtime spec should be good enough for running Wasm instances. There are few things that need improvement on the Wasm implementation layer, but I think is something we should all drive towards. So adding an OCI layer on top will ensure we go towards a great direction.

> Are there other options in development/planned that'd provide the same functionality

As you mentioned, there are two ways of running Wasm within Kubernetes:
* OCI approach: it can run side by side with other container engines within the same cluster
* CRI approach: it defines a Wasm-only cluster for running Wasm.

The OCI approach seems to be leaner for starting things up and generating traction for Wasm on the server side. I think the CRI approach can come later once that traction is generated.

Other than that, I have not much feedback other that we are super excited about this proposal. Specially the `runwc` approach!
Let us know how we can start helping 🙂

**Comment by dippynark** [comment]
Awesome, good to get some verification, makes sense to me starting with OCI compatibility too - a few questions:
- Where would this binary live? As the implementation may be similar for other wasm runtimes, I think it'd make sense to create a separate github.com/wasmerio/runwc repo at some point which includes a go-library (go-runwc) for interacting with the wrapper
- When running multiple wasm modules in the same Pod, should they always be separate wasmer instances or would sharing an instance allow greater interoperability (I'm thinking if/when fork and inter-process communication is implemented in [wasi](https://github.com/WebAssembly/WASI), maybe that is only possible if the modules are running under the same wasm runtime instance). Maybe the ability to share instances could come from a future wasm specific CRI implementation
- If we go for separate wasm runtime instances, would it make sense to just execute wasmer inside runc containers for now? That way the implementation would be very simple and the wrapper would effectively just prepend `wasmer` to the list of arguments in a call to runc

The final bullet feels like a bit of hack (I guess the wamer binary would need to be bind mounted into each container which would potentially go against the OCI spec) but I can't see how runwc would be implemented too differently anyway.

**Comment by gattytto** [comment]
yes! this is absolutely the way it should be archieved. I would love to test every release of it.

Right now I'm using cri-o as a container engine, inside LXD containers. /etc/crio/crio.conf has a "runtimes" table which makes it easy to add oci-compliant runtimes like gVisor, so I'd love to add a wasm runtime here.

this makes testing very easy by just creating a deployment yaml for a test pod with a single container with the "runtimeClassName" set to whatever we name the wasm runtime, of course pointed to the missing link: the runwsm binary that I hope you can provide.

**Comment by syrusakbary** [comment]
We have created an `#oci` channel in the Wasmer community slack to allow for a bit faster communication.

Join it here! https://slack.wasmer.io :)

**Comment by syrusakbary** [comment]
Wasmer support was merged in crun a few weeks ago:
https://github.com/containers/crun/pull/742

Do you think this fulfill the requirements for closing the ticket @dippynark ?

**Comment by gattytto** [comment]
> Wasmer support was merged in crun a few weeks ago: [containers/crun#742](https://github.com/containers/crun/pull/742)
> 
> Do you think this fulfill the requirements for closing the ticket @dippynark ?

[this](https://github.com/containers/crun/issues/829#issuecomment-1001556024) could be blocking

**Comment by flouthoc** [comment]
@gattytto This is an issue is with `CRI` implementation but crun works around this by adding new annotations which supports `side-cars` and feature is added here: https://github.com/containers/crun/pull/886

**Comment by gattytto** [comment]
thanks yes I guess that closes the issue as there won't be a need of a separate wasm oci implementation if other runtimes that are oci compliant support wasm natively through the annotation. Thank you for the support

**Comment by syrusakbary** [comment]
Awesome, closing the ticket now.
