### ISSUE TITLE
Is producing an emscripten static library "libwasmer.a" possible ?

### ISSUE THREAD

**Issue by o-micron** [wasmerio/wasmer#1377]
### Summary
I would like to compile the [wasmer-c-api hello-world example](https://docs.wasmer.io/integrations/c/examples/hello-world) with `Emscripten`
To do that I have to link with `libwasmer.a` from the `wasmer-c-api`.
Emscripten wouldn't understand that x86 "libwasmer.a" .. 
I currently can't find one compiled with emscripten, is there any examples on how to compile wasmer with emcc ?

**Comment by MarkMcCaskey** [comment]
It's not currently possible to compile wasmer itself to Wasm, unfortunately.  If it were possible, it'd be missing many important features (like the ability to JIT compile and execute machine code), but with an interpreter this wouldn't be that difficult to do.

If you want to use emscripten compiled Wasm _from_ wasmer, that is certainly possible.  Our C API can be compiled with support for the emscripten ABI:

`make capi-emscripten` should build the libraries and header file to do that.

If that doesn't answer your question or you run into any issues, feel free to reopen this issue!

**Comment by o-micron** [comment]
@MarkMcCaskey great, thank you !
