### ISSUE TITLE
DynamicFunc on Windows

### ISSUE THREAD

**Issue by Hywan** [wasmerio/wasmer#1387]
For the moment, `wasmer_runtime_core::DynamicFunc` works only on Unix and x86-64 architecture. It should be extended to Windows, as requested in https://github.com/wasmerio/python-ext-wasm/pull/140.

**Comment by syrusakbary** [comment]
This should be solved in the refactor.

**Comment by syrusakbary** [comment]
This issue is now fixed in the refactor. The `DynamicFunc` (now `Func::new`) is now fully supported in Windows.
