### ISSUE TITLE
Create example of storing instance and functions

### ISSUE THREAD

**Issue by MarkMcCaskey** [wasmerio/wasmer#1402]
Requested on slack, relevant link: https://github.com/wasmerio/wasmer/issues/748#issuecomment-529058931

Put `Instance` in a struct along with some functions as an example.  This is likely to be a very common use case.

**Comment by Hywan** [comment]
Since Wasmer 1.0 and more in 2.0, there is nothing particular to do to achieve that, e.g. within `wasmer-python`, https://github.com/wasmerio/wasmer-python/blob/a7f59acf9ccca2002cd4d58bf6f66829b285b58f/packages/api/src/instance.rs#L87-L89.

Closing this issue :-).
