### ISSUE TITLE
API for using middleware with cranelift

### ISSUE THREAD

**Issue by webmaster128** [wasmerio/wasmer#1418]
Right now we use the following code to create a singlepass compiler with a middleware chain:

```rust
pub fn compile(code: &[u8]) -> VmResult<Module> {
    compile_with(code, compiler().as_ref()).context(CompileErr {})
}

pub fn compiler() -> Box<dyn Compiler> {
    let c: StreamingCompiler<wasmer_singlepass_backend::ModuleCodeGenerator, _, _, _, _> =
        StreamingCompiler::new(move || {
            let mut chain = MiddlewareChain::new();
            chain.push(DeterministicMiddleware::new());
            chain.push(metering::Metering::new(GAS_LIMIT));
            chain
        });
    Box::new(c)
}
```

However, trying to do the same thing (minus the metering) with cranelift does not work due to a missing export:

```rust
pub fn compiler() -> Box<dyn Compiler> {
    let c: StreamingCompiler<wasmer_clif_backend::ModuleCodeGenerator, _, _, _, _> =
        StreamingCompiler::new(move || {
            let mut chain = MiddlewareChain::new();
            chain.push(DeterministicMiddleware::new());
            chain
        });
    Box::new(c)
}
```

It seems like there is only the 4-element type

```rust
/// Streaming compiler implementation for the Cranelift backed. Compiles web assembly binary into
/// machine code.
pub type CraneliftCompiler = SimpleStreamingCompilerGen<
    code::CraneliftModuleCodeGenerator,
    code::CraneliftFunctionCodeGenerator,
    signal::Caller,
    code::CodegenError,
>;
```

exposed and `wasmer_clif_backend::code::CraneliftModuleCodeGenerator` is private.

If this a missing feature or am I doing something wrong here?

**Comment by syrusakbary** [comment]
Hi @webmaster128,

We currently don't support middleware in Cranelift. However we will ship soon support for it! :)

**Comment by webmaster128** [comment]
Ah cool, thanks. No rush. Good to know I did not miss something obvious.

**Comment by syrusakbary** [comment]
We are currently refactoring Wasmer.
I'm happy to announce that this feature (using middleware with Cranelift) is now supported there :)

**Comment by syrusakbary** [comment]
We are in the process to add full support for middleware in the refactor.
Right now, only one thing is missing, but the good news is that middleware is supported across every compiler :)

**Comment by webmaster128** [comment]
Assuming this is done on current master by now. Will open more specific issues when I run into trouble.
