### ISSUE TITLE
Closure context isn't used in Func dynamic dispatching

### ISSUE THREAD

**Issue by michaelvoronov** [wasmerio/wasmer#1419]
I have multi-modules setup where some modules have exports and some imports. Each module is corresponded to its own instantiated Instance object. Then I try to link import with corresponded exports and stumbled with the fact that closure context doesn't used in Func dynamic dispatching - Func is dispatching only by its signature (according to [this](https://github.com/wasmerio/wasmer/blob/d23a3f3d1cd2037e0c9f1df113e7871d519007f0/lib/runtime-core/src/typed_func.rs#L753)). So, it breaks my [approach](https://github.com/fluencelabs/fce/blob/master/src/vm/frank.rs#L52) and I belive that this behaviour is anti-intuitive, because passing closure I am expecting that excatly it will be called, not some random closure with the same type.

I suggest to pass closure context (`func_env`) with `vmctx` to the [wrap](https://github.com/wasmerio/wasmer/blob/d23a3f3d1cd2037e0c9f1df113e7871d519007f0/lib/runtime-core/src/typed_func.rs#L734) function to dispatch both by closure context and closure signature.

If you approve this change, I can make a PR.

P.S. To confirm that issue in this, I have instrumented Wasmer in several places, and on the setup with 4 modules (each from `sqlite`, `redis`, `sqlite1` export 5 functions, and last one imports all these 15 funcs) I have such state of `vm_functions` in the end of `ImportBacking::new`:

<img width="841" alt="Screenshot 2020-05-03 at 13 27 54" src="https://user-images.githubusercontent.com/11981714/80920191-d8bace80-8d76-11ea-9043-79b1f9321d2a.png">

Here you can see, that function with the same name have the same `func` value (signature) and different context. And only the first 5 different functions from imports of 4th module is called - not matter to which module they belong to, in this example only `sqlite1::allocate`, `redis::invoke`, `redis::deallocate`, `redis::store`, `redis::load` could be called.

Related to #757.

**Comment by MarkMcCaskey** [comment]
@Hywan @syrusakbary you guys probably have more context here than I do

**Comment by Hywan** [comment]
Hmm, I think yes, this is an unexpected behavior. Please open a PR, and we will iterate on it!

**Comment by syrusakbary** [comment]
I believe this is solved in the refactor that is coming soon.

**Comment by syrusakbary** [comment]
This should be solved by the refactor @michaelvoronov, that is now in `master`. Let us know if that's not the case!
