### ISSUE TITLE
Make Func clonable

### ISSUE THREAD

**Issue by michaelvoronov** [wasmerio/wasmer#1420]
### Motivation

I have multi-modules setup where each module has corresponded Instance and want to share `ImportObject` between modules. In its turn `ImportObject` contains funcs with [callbacks](https://github.com/fluencelabs/fce/blob/master/src/vm/frank.rs#L52), where callback is a `Func`. So to improve sharing it would be great to have a possibility to clone functions. From the logical point of view it is equal to call of `instance.exports.get` second time.

### Proposed solution

Make Func clonable. It could be achived just by adding the clone directive. I have already tested and are using in my branch.

Related to https://github.com/wasmerio/wasmer/issues/757.

**Comment by syrusakbary** [comment]
Yeah, there is a downside on the future which is that the Function environments have to be clonable, but that's should be good to fix on the future!

Happy to merge the improvement upstream!
