### ISSUE TITLE
Memory safety error when using DynamicFunc

### ISSUE THREAD

**Issue by tessi** [wasmerio/wasmer#1430]
First let me thank you for all your hard work in this project and especially for DynamicFunc support, which allowed me to support function imports in [wasmex](https://github.com/tessi/wasmex).

I am currently [implementing WASI support](https://github.com/tessi/wasmex/pull/18) and consistently get memory related errors when running a WASI/WASM file with a WASI imports object where one method was overwritten with a dynamic func.

Background is that I want to use the default WASI wasmer implementations, but be able to overwrite some functions from Elixir using DynamicFunc. This is especially useful e.g. when capturing output or testing wasi modules (mocking time or get_random).

----

Copy and paste the result of executing the following in your shell, so we can know the version of wasmer, Rust (if available) and architecture of your environment.

```sh
❯ echo "`wasmer -V` | `rustc -V` | `uname -m`"
zsh: command not found: wasmer
 | rustc 1.43.0 (4fb7144ed 2020-04-20) | x86_64
```

Not using the wasmer CLI, but linking to [the latest commit on master](https://github.com/wasmerio/wasmer/commit/77de93ec0e0521d06477b00389321ef8e9ea6ebf) at the time of writing in my `Cargo.toml`.

### Steps to reproduce

I created a small Rust program [over here](https://github.com/tessi/wasmer_dynamic_func_bug_demo) which serves as a minimal example.
You could also run tests (`mix test`) when checking out [the wasmex PR](https://github.com/tessi/wasmex/pull/18) but the project is more complex and would require you to install elixir.
Let's better continue with the minimal example :)

* git-clone `https://github.com/tessi/wasmer_dynamic_func_bug_demo.git`
* run `cargo run`

### Expected behavior

The WASM program runs using the DynamicFunc `random_get`. The output to stdout should be similar to:

```
Hello from the WASI test program!

Arguments:

Environment:

Current Time (Since Unix Epoch):
1588971316

Random Number: 2067160955
```

### Actual behavior

Instead of executing the `random_get` DynamicFunc import, wasmer crashes with one of three different memory-related errors

Error 1: `memory allocation failed`
<details><code><pre>
❯ RUST_BACKTRACE=full cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/wasmer_demo`
Hello from the WASI test program!

Arguments:

Environment:

Current Time (Since Unix Epoch):
1588966859

wasmer_demo(3275,0x10fee1dc0) malloc: can't allocate region
:*** mach_vm_map(size=3377586554535936, flags: 60000100) failed (error code=3)
wasmer_demo(3275,0x10fee1dc0) malloc: *** set a breakpoint in malloc_error_break to debug
memory allocation of 3377586554535936 bytes failed[1]    3275 abort      RUST_BACKTRACE=full cargo run
</pre></code></details>

Error 2: `capacity overflow`
<details><code><pre>
❯ RUST_BACKTRACE=full cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/wasmer_demo`
Hello from the WASI test program!

Arguments:

Environment:

Current Time (Since Unix Epoch):
1588966878

thread 'main' panicked at 'capacity overflow', src/liballoc/raw_vec.rs:750:5
stack backtrace:
   0:        0x105f3d06f - std::sys_common::at_exit_imp::push::h9d2b273ed4ea5358
   1:        0x105f5b48e - <&mut W as core::fmt::Write>::write_fmt::h25d58e21bc6e71c9
   2:        0x105f3a717 - std::io::Write::write_fmt::hf0a8cad0ca2251e3
   3:        0x105f3f07a - std::panicking::default_hook::{{closure}}::h166f557a03fd111a
   4:        0x105f3edbc - std::panicking::default_hook::h16057d891db6b023
   5:        0x105f3f6e8 - <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get::hb0321a5224bfb474
   6:        0x105f3f2b2 - std::panicking::try::do_call::h7c88c220bfff6b21
   7:        0x105f6bd6f - std::panicking::begin_panic::h1eb3d94191b6aea5
   8:        0x105f6bcc7 - std::panicking::begin_panic::h1eb3d94191b6aea5
   9:        0x105f54f8c - alloc::raw_vec::RawVec<T,A>::reserve_internal::h03d9a4879d77c9ff
  10:        0x105dd9d87 - alloc::raw_vec::alloc_guard::ha062a71d21d85229
  11:        0x105e4fcba - alloc::vec::SetLenOnDrop::new::h3f87c66392359504
  12:        0x105e52b80 - alloc::vec::SetLenOnDrop::new::h3f87c66392359504
  13:        0x105e543ac - alloc::vec::SetLenOnDrop::new::h3f87c66392359504
  14:        0x105e560df - alloc::vec::SetLenOnDrop::new::h3f87c66392359504
  15:        0x105e33847 - std::io::impls::<impl std::io::Read for &[u8]>::read_exact::h5e50e7b5129762aa
  16:        0x105e00b41 - wasmer_runtime_core::typed_func::DynamicFunc::new::do_enter_host_polymorphic::h9d3da410403150e4
  17:        0x105e010a2 - wasmer_runtime_core::typed_func::DynamicFunc::new::do_enter_host_polymorphic::{{closure}}::h73ae26eb50750d45
fatal runtime error: failed to initiate panic, error 5
[1]    3412 abort      RUST_BACKTRACE=full cargo run
</pre></code></details>

Error 3: `segmentation violation`
<details><code><pre>
❯ RUST_BACKTRACE=full cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/wasmer_demo`
Hello from the WASI test program!

Arguments:

Environment:

Current Time (Since Unix Epoch):
1588966927

[/Users/tessi/.cargo/git/checkouts/wasmer-f11f30e62739aa29/77de93e/lib/runtime-core/src/instance.rs:609] &error = InvokeError(
    UnknownTrap {
        address: 0,
        signal: "segmentation violation",
    },
)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RuntimeError: InvokeError(UnknownTrap { address: 0, signal: "segmentation violation" })', src/main.rs:27:5
stack backtrace:
   0:        0x1062d606f - std::sys_common::at_exit_imp::push::h9d2b273ed4ea5358
   1:        0x1062f448e - <&mut W as core::fmt::Write>::write_fmt::h25d58e21bc6e71c9
   2:        0x1062d3717 - std::io::Write::write_fmt::hf0a8cad0ca2251e3
   3:        0x1062d807a - std::panicking::default_hook::{{closure}}::h166f557a03fd111a
   4:        0x1062d7dbc - std::panicking::default_hook::h16057d891db6b023
   5:        0x1062d86e8 - <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get::hb0321a5224bfb474
   6:        0x1062d82b2 - std::panicking::try::do_call::h7c88c220bfff6b21
   7:        0x106304d6f - std::panicking::begin_panic::h1eb3d94191b6aea5
   8:        0x106304c75 - std::panicking::begin_panic::h1eb3d94191b6aea5
   9:        0x105c1df60 - core::result::Result<T,E>::unwrap::hc3f82c8fcbaa85e6
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libcore/result.rs:1003
  10:        0x105c1a5a8 - wasmer_demo::main::h15487e35983c1498
                               at src/main.rs:27
  11:        0x105c1c9de - std::rt::lang_start::{{closure}}::hca85ff321b4abf32
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/rt.rs:67
  12:        0x1062d81b8 - std::panicking::try::do_call::h7c88c220bfff6b21
  13:        0x1062db64b - panic_unwind::dwarf::eh::read_encoded_pointer::h37bb3f695deaeae6
  14:        0x1062d8bba - std::panicking::rust_panic_without_hook::h6ca5ec7e0059bf4e
  15:        0x105c1c9c1 - std::rt::lang_start::h23aabe723db67e46
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/rt.rs:67
  16:        0x105c1a702 - wasmer_demo::main::h15487e35983c1498
</pre></code></details>

### Additional context

I tried to debug the issue, but wasn't able to fix it. I believe the bug surfaces [near line 322 of typed_func.rs](https://github.com/wasmerio/wasmer/blob/4a37bac7e1484c4dfe1d595d36486b3c8c9998ba/lib/runtime-core/src/typed_func.rs#L322) where the DynamicFunc tries to prepare function arguments.

I can see `println!()` statements working before line 322, but none directly after.

**Comment by tessi** [comment]
Hey @MarkMcCaskey many thanks for adding labels and a proper title :)

To help me plan my WASI feature, it would be really helpful to know the priority of this bug. Is it something on your list to solve soon or a less important bug in your eyes? If it's a less prioritized issue, I'd schedule my work differently.

I'm afraid I can't solve this bug on my own, but please let me know if there is anything I can further help you with.

**Comment by syrusakbary** [comment]
I believe this is now fixed in `master`. Could you help testing it @tessi ? Thanks!

**Comment by tessi** [comment]
I tried, but couldn't reproduce it anymore. Will take a closer look at the issue again when implementing wasi support for wasmex.

The pandemic crossed some of my plans and schedules, though. So that might not happen very soon. Also sorry for answering late here :)

**Comment by tessi** [comment]
☝️ with that being said, I think we can close the issue ✅ 

many thanks for taking a look!

**Comment by tessi** [comment]
Update: I got some steps forward in WASI support and had to refactor the code that originally caused the issue to use the new wasmer 1.0 API. I can now confirm it works without triggering that bug 💯
