### ISSUE TITLE
Return AtomicCell from WasmPtr deref

### ISSUE THREAD

**Issue by dotxlem** [wasmerio/wasmer#1431]
### Motivation

In my use case, I wanted to be able to write to the memory referenced by the `WasmPtr` from an async function which is likely running in another thread. 

The existing implementation of Deref for `WasmPtr` returns a reference to a slice of `Cell`s, which are not `Sync`.

### Proposed solution

I was able to solve the issue [in my fork](https://github.com/dotxlem/wasmer/tree/atomic_cell), by using crossbeam's `AtomicCell`, which is `Sync`. [The change](https://github.com/dotxlem/wasmer/commit/9ff40d39377c8e9c9be0e70a9f3504c27d1424a0) is essentially a find-and-replace operation.

I don't know if that is necessarily the best solution, but I wanted to propose here that there be some way to return thread-safe references to WASM memory, even if not the one I came up with.

**Comment by MarkMcCaskey** [comment]
This is a very good point: we haven't fully defined our interfaces for memory access from multiple threads.

I don't know if we want to use AtomicCell by default, but something like it should probably be part of our API.  We have some notion of shared vs unshared memory already so perhaps we could use that.

**Comment by dotxlem** [comment]
Yeah, I went with AtomicCell just because it seemed like the quickest route to something that worked, but I don't actually need it in all the places it's now returned.

> We have some notion of shared vs unshared memory already so perhaps we could use that.

Can you point me towards what you're referring to here? I wouldn't mind having another go at doing this properly (time pending) -- I'd rather not have to depend on a fork for too long.

Which reminds me, I opened up the project I'm using Wasmer for [here](https://github.com/akkoro/assemblylift) -- mentioning it in case its useful for you or anyone to see it in code.

**Comment by Hywan** [comment]
Still relevant.

**Comment by syrusakbary** [comment]
Small update. This is already fixed on the `wasmer3` branch

**Comment by epilys** [comment]
> Small update. This is already fixed on the `wasmer3` branch

Shouldn't we close this issue then?
