### ISSUE TITLE
Different compilation results on different platforms

### ISSUE THREAD

**Issue by moshababo** [wasmerio/wasmer#1432]
Using wasmer in the [svm](https://github.com/spacemeshos/svm) project, currently with Single-pass compiler backend, we’re getting different compilation results on different platforms.

To quickly see this, you can check our GitHub Actions CI results for this commit: https://github.com/spacemeshos/svm/commit/4053f69a153aa9cad04e43811e2c8e33d85513f7

The `svm_runtime_exec_app` test passes on macOS, but [fails](https://github.com/spacemeshos/svm/runs/642475996#step:6:420) on Ubuntu. Here’s the inner error msg returned by wasmer upon compilation, which complains about the imports signature:

```
2 link errors: (1 of 2) Incorrect import signature, namespace: env, name: inc_balance, expected signature: [I64, I32, I32] -> [], found signature: [I64, I64, I32] -> [] (2 of 2) Incorrect import signature, namespace: env, name: mul_balance, expected signature: [I64, I32, I32] -> [], found signature: [I64, I64, I32] -> [])
```

The respective `wast` code can be found here: https://github.com/spacemeshos/svm/blob/master/crates/svm-runtime-c-api/tests/wasm/update-balance.wast#L9. And indeed both imports signature is `[I64, I32, I32] -> []`.

At runtime, here’s where the import functions are created: https://github.com/spacemeshos/svm/blob/master/crates/svm-runtime-c-api/tests/api_tests.rs#L84. And again, both imports signature is `[I64, I32, I32] -> []`.

So it’s not clear to us why on Ubuntu the compiler finds the ` [I64, I64, I32] -> []` signature and fails.

**Comment by syrusakbary** [comment]
Thanks for the detailed report, we will take a look soon!

**Comment by moshababo** [comment]
We've managed to do some refactoring which makes it fail only on `release` build mode in Ubuntu, but doing so before the code path even reaches wasmer.
So I think it's safe to close this for now. 

More info can be found here: https://github.com/spacemeshos/svm/compare/linux-test-fails 

Thanks!
