### ISSUE TITLE
Add WasiVersion::Auto

### ISSUE THREAD

**Issue by MarkMcCaskey** [wasmerio/wasmer#1435]
It could be very useful to have a variant which causes the internals to detect the version of WASI and make everything just work.

This could be particularly useful for our language extensions, allowing them to set it as the default value if one is not specified to make it easier to get things up and running early on.

Needs some research on the impact of things like error return values, but otherwise should be simple.

**Comment by Hywan** [comment]
We have 2 “tools” to achieve that:

1. https://github.com/wasmerio/wasmer/pull/1029 that provides `WasiVersion::Latest` (if we are sure it's always the latest version)
2. [`get_wasi_version`](https://docs.rs/wasmer-wasi/2.0.0/wasmer_wasi/fn.get_wasi_version.html) that returns the detected version of a WASI module.

This latter can replace `WasiVersion::Auto` and makes more sense.

I'm closing this issue.
