### ISSUE TITLE
Julia language integration. 

### ISSUE THREAD

**Issue by Zenleaf** [wasmerio/wasmer#1446]
Would love to have Julia integration for Wasmer. Is there any work on this? 

If not any pointers on where to start to help develop it?

**Comment by Hywan** [comment]
Hey there :-),
It's not on our todo list for the moment, but why not, Julia is an interesting project!

I can mentor you to accomplish this. I think the best way to approach this is to use [our C API](https://github.com/wasmerio/wasmer/tree/master/lib/runtime-c-api) ([documentation lands here](https://wasmerio.github.io/wasmer/c/runtime-c-api/)).

I'm not super familar with Julia, but if I remember correctly, it's quite easy to call C code from it.

There is also the [`jlrs`](https://crates.io/crates/jlrs) crate, but it aims at calling Julian from Rust, and we want the opposite.

Thoughts?

**Comment by Zenleaf** [comment]
Thanks Hywan, yes Julia has an excellent interop with C. Will go through the docs and get back to you. This is an awesome project! And the Julia community will greatly benefit.

I will get back to you, will definitely need help.

**Comment by Hywan** [comment]
Still relevant.

**Comment by syrusakbary** [comment]
@Pangoraw did an awesome work on Wasmer.jl (Wasmer integration in Julia).

I've added it to the list of supported languages, for easier reference for any newcomer to the repo:
9f92666a0dfd88fc2c639374e148542759d9289d

Happy to close this issue as done! :)
