### ISSUE TITLE
Support for 32-bit Windows

### ISSUE THREAD

**Issue by whitequark** [wasmerio/wasmer#1450]
### Motivation

When you are installing Python on Windows, http://python.org suggests a 32-bit installer even on a 64-bit system, it is not trivial to find a 64-bit installer if you don't know exactly what to look for, and AFAIK there is no way to directly link to a 64-bit installer either.

I would like to distribute a native dependency of my Python project on PyPI by compiling it to WASM and depending on a WASM runtime binary wheels. This requires a WASM runtime that includes binary wheels for 32-bit Windows. Right now I am using [wasmtime-py](https://github.com/bytecodealliance/wasmtime-py), which also does not work on 32-bit platforms.

### Proposed solution

Add support for 32-bit Windows.

### Alternatives

The current alternative I'm considering is using wasm2c, checking in the generated source, and building Python binary wheels myself using `build_ext`. This eliminates the need to maintain build scripts for three platforms, but is otherwise also quite laborous.

### Additional context

I've added limited support for 32-bit x86 platforms to Cranelift but it does not include SEH and so doesn't work on Windows.

The dependency I'm packaging is [here](https://github.com/nmigen/nmigen-yosys).

**Comment by syrusakbary** [comment]
This work has been partially achieved in this fork:

https://github.com/PerfectLaugh/wasmer

Perhaps it will be good to adopt it in Wasmer

**Comment by Berrysoft** [comment]
Are there someone still working on this issue?
