### ISSUE TITLE
wasi_unstable vs wasi_snapshot_preview1

### ISSUE THREAD

**Issue by donovano** [wasmerio/wasmer#1451]
### Summary

I have a WASM file written in C++ compiled with clang which produces "wasi_unstable" WASI. This WASM module does some file IO. A Wasmer host running this WASM module works as expected.

Then I have a rust WASM module, implementing the same functionality as the C++ one, that when compiled with `cargo build --release --target wasm32-wasi` produces "wasi_snapshot_preview1" WASI. The same Wasmer host that runs the C++ compiled WASM fails to perform the file IO in this case. 

I notice there are differences in the WASM code e.g. the `wasi_unstable` uses `fd_fdstat_get` but the `wasi_snapshot_preview1` doesnt. 

Is there some way to compile the rust module differently to produce WASI code similar to the clang or is there something else on the Wasmer host that needs to be done to work with the `wasi_snapshot_preview1`?

### Additional details

The `wasi_snapshot_preview1` fails in the wasmer's `wasi::path_open` implementation - it seems to not find the file. I notice that the `wasi_unstable` calls `wasi::fd_fdstat_get` prior to the  `wasi::path_open` whereas `wasi_snapshot_preview1` does not. Also note that this exact same `wasi_snapshot_preview1` WASM module works as expected with another non-Wasmer WASM host.

**Comment by MarkMcCaskey** [comment]
Thanks for the report!  Sorry about the delay by the way, I didn't see this issue until just now.

It sounds like there may be a bug in Wasmer:

- `wasi_unstable` is the older version of WASI and `wasi_snapshot_preview1` is the latest version of WASI.  It's possible that the specific version of the toolchain you're using has a bug in it too, but that's less likely if you're using stable.

Notably in Wasmer our implementations of `wasi_unstable` and `wasi_snapshot_preview1` share almost all the same code so it's rare to see a bug in one but not the other.  Can you post the Wasm files/source code so we can look into this more?

**Comment by donovano** [comment]
Hi, solved the problem. `unstable` seems to not require it but `snapshot_preview1` requires that you preopen folder for guest. Thanks.
