### ISSUE TITLE
link_name attribute usage

### ISSUE THREAD

**Issue by HaronK** [wasmerio/wasmer#1454]
### Summary

I'm trying to instantiate a wasm file built from Rust source but getting error about namespaces.

### Additional details

So here is a simple Wasm source:

```rust
// wasm.rs
extern "C" {
    #[link_name = "ns1"]
    fn _ns1_func1();
    #[link_name = "ns1"]
    fn _ns1_func2();
}
extern "C" {
    #[link_name = "ns2"]
    fn _ns2_func1();
    #[link_name = "ns2"]
    fn _ns2_func2();
}

...
```

and host:
```rust
// host.rs
fn ns1_func1() {}
fn ns1_func2() {}
fn ns2_func1() {}
fn ns2_func2() {}

let mut import_object = ImportObject::new();

let mut ns1 = Namespace::new();
ns1.insert("_ns1_func1", func!(ns1_func1));
ns1.insert("_ns1_func2", func!(ns1_func2));
import_object.register("ns1", ns1);

let mut ns2 = Namespace::new();
ns2.insert("_ns2_func1", func!(ns2_func1));
ns2.insert("_ns2_func2", func!(ns2_func2));
import_object.register("ns2", ns2);

let instance = instantiate(wasm_bytes, &import_object).expect("failed to instantiate wasm module");

...
```
As you can see I'm using dynamic host function registration. I found the description of how to do it [here](https://github.com/wasmerio/wasmer/issues/1251).
So now when I try to run it I'm getting following error:

`
thread 'main' panicked at 'failed to instantiate wasm module: LinkError([ImportNotFound { namespace: "env", name: "ns2" }, ImportNotFound { namespace: "env", name: "ns1" }])', src\main.rs:32:1
`

Am I misunderstand meaning of namespaces or I just use them in a wrong way?

**Comment by HaronK** [comment]
I found the solution.
Originally I was following recommendation at the bottom of this [page](https://docs.wasmer.io/integrations/rust/examples/host-functions) to use `#[link_name = "namespace"]` attribute to specify function's namespace. But according to this [example](https://github.com/wasmerio/docs.wasmer.io/blob/fc8878b5a6873549ac9506fc54ded0c64a748164/integrations/shared/rust/host-functions.rs#L7-L11) I have to use `#[link(wasm_import_module = "namespace")]` attribute to do that.

**Comment by HaronK** [comment]
Closing this question.

**Comment by MarkMcCaskey** [comment]
Thanks for the report and sorry about the issue!  It looks like that's a mistake in our docs, I'll add it to my todo list to correct that today!
