### ISSUE TITLE
Support for MinGW-like compilers (GNU on windows)

### ISSUE THREAD

**Issue by sigmasoldi3r** [wasmerio/wasmer#1461]
### Summary

Is there a way to compile Wasmer for windows, but using GNU compilers? (Any config tweak maybe?)

### Additional details

Right now I'm on a project that is being built with MinGW and precompiled binaries cannot be used due to differences between MSVC and MinGW libs (`__CxxFrameHandler3` is missing).

I'm trying to compile it on my own but when running make it will attempt to use MSVC compiler, and thus fail (I don't have MSVC compilers).

Thanks for this great project!

**Comment by sigmasoldi3r** [comment]
I have seen now that the docs mention MinGW on windows: https://docs.wasmer.io/integrations/c/setup#windows
But despite that the linker complains about this:

```
F:/msys2-mingw-w64-x86_64-clang-llvm-lld-compiler_rt-8.0.1/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: F:/lib/wasmer/lib/wasmer.lib(wasmparser-68d28f1633ad19b7.wasmparser.95joskp1-cgu.0.rcgu.o):wasmparser.95joskp:(.xdata[$cppxdata$_ZN10wasmparser19operators_validator17OperatorValidator3new17h72c7a3674caf2da8E]+0x20): more undefined references to `__CxxFrameHandler3' follow
```

**Comment by sigmasoldi3r** [comment]
Sorry to bother again, but after configuring rust for Windows/GNU I've got another error:

```
wasmer_clif_backen:(.text+0x7843): undefined reference to `__chkstk'
```

**Comment by zesterer** [comment]
We're having the same problem when cross-compiling Windows binaries from Linux using GCC.

**Comment by Hywan** [comment]
Which version are you using?

**Comment by zesterer** [comment]
We're using `0.17.1`.

**Comment by Hywan** [comment]
Wasmer 1.0.0-beta1 lands in this repository now. I know you'll need to migrate, but I think it's worth trying!

**Comment by zesterer** [comment]
Thanks for the information. We're generally not too scared of using new or pre-release builds so we might switch to this if it ends up working for us.

**Comment by Qix-** [comment]
Is there any information about how to build wasmer for windows via mingw-w64 on ubuntu, for example? None of the incantations for `make` seem to change anything about the build configuration, and the wasmer docs don't seem to mention cross-compilation.

**Comment by Hywan** [comment]
We support Windows in a MinGW environment with Wasmer 2.0 (and some versions before that).

(@zesterer Funny to see you here, we were talking about https://github.com/zesterer/ariadne on Twitter a couple of hours ago ;-))

**Comment by zesterer** [comment]
> We support Windows in a MinGW environment with Wasmer 2.0 (and some versions before that).

That's great to hear!

> (@zesterer Funny to see you here, we were talking about https://github.com/zesterer/ariadne on Twitter a couple of hours ago ;-))

Small world, eh?
