### ISSUE TITLE
InvokeError/TrapCode/Unreachable failure

### ISSUE THREAD

**Issue by HaronK** [wasmerio/wasmer#1470]
I'm working on relatively complex library that is using Wasmer and getting following error:

`
thread 'main' panicked at 'Failed to execute 'my_func' function: InvokeError(TrapCode { code: Unreachable, srcloc: 202855 })', src/main.rs:32:1
`

My code is pretty complex and is using memory(0) to transfer data to/from Wasm and also lazy_static for keeping persistent data inside wasm.

I was investigating source code of wasmer_runtime_core and looks like error comes from [fault.rs:425](https://github.com/wasmerio/wasmer/blob/7fb4002585c236cb49e629cc05a33bebd3f60f76/lib/runtime-core/src/fault.rs#L425-L429).
I was trying to understand where this error originates from but without any luck.

Can anybody tell me where this error can come from or at least how to investigate it?

**Comment by kaimast** [comment]
Did you ever figure this out?

**Comment by kaimast** [comment]
Okay... I think this error most likely means that your WASM code panics and there is no panic handler installed.

**Comment by Hywan** [comment]
This code has been rewritten from scratch for the new Wasmer 2.0 version. Can you please give it another try?

**Comment by HaronK** [comment]
Hi. I'll try a new version and let you know.

**Comment by HaronK** [comment]
It looks like updating my code to Wasmer 2.0 will take some time so I think it's better to close this issue for now. If I will be able to reproduce this problem again I reopen this issue or create a new one.

**Comment by Hywan** [comment]
Agree with your proposal.
