### ISSUE TITLE
Loading wasm built with C++ fails: missing fd_close and fd_seek

### ISSUE THREAD

**Issue by ivannp** [wasmerio/wasmer#1471]
### Describe the bug

A simple wasm module loads when build with C, malloc and free, but fails to load when build with C++, new and delete. The runtime error from wasmer is:

`Error: 3 link errors: (1 of 3) Import not found, namespace: wasi_snapshot_preview1, name: fd_close (2 of 3) Import not found, namespace: wasi_snapshot_preview1, name: fd_seek (3 of 3) Import not found, namespace: wasi_snapshot_preview1, name: fd_write`

The relevant snippet from the module:

```
#include <cstdlib>

__attribute__((export_name("AllocateMemory")))
extern "C" void* AllocateMemory(int n) {
    return malloc(n);
    // return new uint8_t[n];
}

__attribute__((export_name("FreeMemory")))
extern "C" void FreeMemory(uint8_t *p) {
    // delete [] p;
    free(p);
}

```
Changing the implementation of _AllocateMemory_ and _FreeMemory_ to _new_ and _delete_ causes the problem.

The module was compiled using the latest wasi-sdk.

**Comment by michaelvoronov** [comment]
Hi! It seems that you should explicitly enable WASI in Wasmer, you could find the example [here](https://github.com/wasmerio/wasmer/blob/e19dbbee1db998542faca5f420eb3b3c5a915e20/examples/plugin.rs#L144).

Btw, highly likely that these imports come from [here](https://github.com/WebAssembly/wasi-libc/blob/9bb4cc5c411af8453cbef69c137a4c2337714d89/libc-top-half/musl/src/stdio/stdin.c#L11-L13) and if don't really need an access to your OS from a wasm code you could use [stubs](https://github.com/fluencelabs/redis/blob/wasm/src/sdk/syscalls_stubs.c) for these imports.

**Comment by ivannp** [comment]
Solved it - thanks!

The call to wasmer_wasi_generate_import_object_for_version seems to return Unknown, which, when passed to _wasmer_module_import_instantiate(&instance, module, importObj)_ throws an error. I change to passing Version::Latest instead, and this seems to work. What is the right approach for the _version_ to use?
