### ISSUE TITLE
wasmer 0.17.0 OSX builds failed

### ISSUE THREAD

**Issue by chenrui333** [wasmerio/wasmer#1476]
### Describe the bug

In the wamser brew formula bump (https://github.com/Homebrew/homebrew-core/pull/55376), it failed to build on OSX machines.

```
error[E0308]: mismatched types
   --> lib/api/src/lib.rs:148:25
    |
148 |         fn default() -> Self {
    |            -------      ^^^^ expected enum `compiler::Backend`, found `()`
    |            |
    |            implicitly returns `()` as its body has no tail or `return` expression

error[E0308]: mismatched types
   --> lib/api/src/lib.rs:263:30
    |
263 |               Backend::Auto => {
    |  ______________________________^
264 | |                 #[cfg(feature = "default-backend-singlepass")]
265 | |                 return Some(Box::new(
266 | |                     wasmer_singlepass_backend::SinglePassCompiler::new(),
...   |
271 | |                 return Some(Box::new(wasmer_llvm_backend::LLVMCompiler::new()));
272 | |             }
    | |_____________^ expected enum `std::option::Option`, found `()`
    |
    = note:   expected enum `std::option::Option<std::boxed::Box<(dyn wasmer_runtime_core::backend::Compiler + 'static)>>`
            found unit type `()`
```

### Steps to reproduce

The native build logs are in here
- [catalina log](https://github.com/Homebrew/homebrew-core/pull/55376/checks?check_run_id=791463126)
- [mojave log](https://github.com/Homebrew/homebrew-core/pull/55376/checks?check_run_id=791463139)
- [high-sierra log](https://github.com/Homebrew/homebrew-core/pull/55376/checks?check_run_id=791463143)

**Comment by syrusakbary** [comment]
This should be resolved in the latest code in `master`.

Closing issue

**Comment by chenrui333** [comment]
Can you point out the fix commit or commits so that I can adopt to fix the my build? Thanks!
