### ISSUE TITLE
Compatibility with Alpine Linux

### ISSUE THREAD

**Issue by RReverser** [wasmerio/wasmer#1482]
Thanks for proposing a new feature!

### Motivation

Many tiny Docker deployments use Alpine Linux as its base to reduce size of images and containers. Currently, wasmer is incompatible with such environments because it's compiled against glibc.

### Proposed solution

Provide a build of wasmer that can work with musl libc as well.

### Additional context

For background, initially I stumbled upon this due to non-sensical error after installation:

```bash
/ # ls /root/.wasmer/bin/wasmer
/root/.wasmer/bin/wasmer
/ # /root/.wasmer/bin/wasmer
sh: /root/.wasmer/bin/wasmer: not found
```

After searching around, I found explanation of a similar issue as well a workaround that creates a symbolic link for musl libc pretending to be full one: https://stackoverflow.com/questions/34729748/installed-go-binary-not-found-in-path-on-alpine-linux-docker

That helped a bit, but there are still missing functions due to differences in libc implementations:

```bash
/ # mkdir /lib64
/ # ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2
/ # /root/.wasmer/bin/wasmer
Error relocating /root/.wasmer/bin/wasmer: __snprintf_chk: symbol not found
Error relocating /root/.wasmer/bin/wasmer: mallinfo: symbol not found
Error relocating /root/.wasmer/bin/wasmer: __fprintf_chk: symbol not found
Error relocating /root/.wasmer/bin/wasmer: __vsnprintf_chk: symbol not found
Error relocating /root/.wasmer/bin/wasmer: __longjmp_chk: symbol not found
```

Hence, I think it would be best if wasmer would be built against musl as well.

**Comment by syrusakbary** [comment]
Thanks for creating the issue @RReverser!

It seems the not-found symbols are all related to the emscripten integration. Perhaps we can shape it so we don't require those or adapt them to be compatible with musl.
We could also create a new binary that is built without emscripten support (probably the simplest solution).

Would the latter suffice for your use case?

**Comment by RReverser** [comment]
Yeah that sounds reasonable.

**Comment by krasin** [comment]
Just saw an announce of Wasmer 1.0 (congrats!) and tried it locally on an Alpine Linux dev laptop. Did not work, same reasons:

```
$ ldd ~/.wasmer/bin/wasmer 
	/lib64/ld-linux-x86-64.so.2 (0x7fc4e2942000)
	libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7fc4e2942000)
	librt.so.1 => /lib64/ld-linux-x86-64.so.2 (0x7fc4e2942000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7fc4e2942000)
	libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fc4e2942000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7fc4de7f6000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7fc4de7dc000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fc4e2942000)
Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /home/krasin/.wasmer/bin/wasmer)
Error relocating /home/krasin/.wasmer/bin/wasmer: __snprintf_chk: symbol not found
Error relocating /home/krasin/.wasmer/bin/wasmer: mallinfo: symbol not found
Error relocating /home/krasin/.wasmer/bin/wasmer: __memcpy_chk: symbol not found
Error relocating /home/krasin/.wasmer/bin/wasmer: backtrace_symbols_fd: symbol not found
Error relocating /home/krasin/.wasmer/bin/wasmer: backtrace: symbol not found
Error relocating /home/krasin/.wasmer/bin/wasmer: pthread_getname_np: symbol not found
Error relocating /home/krasin/.wasmer/bin/wasmer: __vsnprintf_chk: symbol not found
Error relocating /home/krasin/.wasmer/bin/wasmer: __longjmp_chk: symbol not found
Error relocating /home/krasin/.wasmer/bin/wasmer: __register_atfork: symbol not found
Error relocating /home/krasin/.wasmer/bin/wasmer: __realpath_chk: symbol not found
Error relocating /home/krasin/.wasmer/bin/wasmer: __sprintf_chk: symbol not found
Error relocating /home/krasin/.wasmer/bin/wasmer: __res_init: symbol not found
```

**Comment by syrusakbary** [comment]
@jubianchi can we disable emscripten when doing the musl build?

**Comment by jubianchi** [comment]
I'll have a look at this today.

**Comment by jubianchi** [comment]
@krasin some update here: I had Wasmer build on musl working.

I'll continue working on that and see how we can produces this builds in our CI pipeline.

**Comment by krasin** [comment]
@jubianchi awesome, thank you for the update!

**Comment by prepperdev** [comment]
Thank you for working on this!

I assume this fix is not yet released, right? This is what I get when following the recommended way to install:

```
curl https://get.wasmer.io -sSfL | sh
...
downloading: wasmer-linux-amd64
Latest release: 1.0.1
Downloading archive from https://github.com/wasmerio/wasmer/releases/download/1.0.1/wasmer-linux-amd64.tar.gz
...
sh: /home/krasin/.wasmer/bin/wasmer: not found
error: wasmer was installed, but doesn't seem to be working :(
```
