### ISSUE TITLE
Use dynasm-rs 1.0 to enable singlepass backend to be compilable on stable Rust 1.45+

### ISSUE THREAD

**Issue by frol** [wasmerio/wasmer#1488]
### Motivation

Compilation on stable Rust release is a major step forward to general stability.

### Proposed solution

Rust 1.45 will stabilize some nightly features that were required for dynasm-rs and with the efforts towards compilation on stable Rust release from dynasm-rs team (https://github.com/CensoredUsername/dynasm-rs/issues/31), dynasm-rs 0.7 is ready to be compilable on stable Rust 1.45. It seems that dynasm-rs is the major if not the only piece requiring nightly Rust features, so with Rust 1.45 and dynasm-rs 0.7 it should be possible to have wasmer singlepass backend to be compilable on stable Rust.

**Comment by repi** [comment]
We just ran into this as well, would be great to upgrade to 0.7 and not require nightly

**Comment by webmaster128** [comment]
This would be a massive improvement for our development flow as well!

**Comment by frol** [comment]
dynasm-rs 1.0 is released targeting stable Rust 1.45+ https://github.com/CensoredUsername/dynasm-rs/issues/31 :tada:

**Comment by MarkMcCaskey** [comment]
This should now work with the Wasmer refactor on master and singlepass published at https://crates.io/crates/wasmer-compiler-singlepass !

Unfortunately we don't have docs to aid in the transition between the old wasmer and the new wasmer yet, but stay tuned to #1553 for news on their development.
