### ISSUE TITLE
Cranelift backend support for ARM on Android (and Mac)

### ISSUE THREAD

**Issue by repi** [wasmerio/wasmer#1495]
### Motivation

Wasmer Cranelift-backend support for ARM, for Android and soon also for Mac on Apple Silicon. 

For higher performance on ARM / aarch64 devices than the single-pass backend.

### Proposed solution

Cranelift is actively working on `aarch64` support ([list of issues](https://github.com/bytecodealliance/wasmtime/issues?q=is%3Aissue+aarch64+label%3Acranelift%3Aarea%3Aaarch64+)), integrate latest and see if anything is missing in Cranelift to generate for the `aarch64` ABI and implement support in Wasmer.

### Alternatives

Users can continue to use the single-pass backend on ARM devices, at a quite significant performance penalty.

**Comment by syrusakbary** [comment]
Thanks for creating the issue @repi!

We are working on the new version of Wasmer that will be released to the public soon.
In this new version we are already using the latest version of Cranelift (that also supports Aarch64), and have passed all tests successfully in our ARM servers.

So we just have to wait for a few weeks to see the support upstream! :)

**Comment by repi** [comment]
@syrusakbary thanks, glad to hear it! excited to try out the new version when it comes out

**Comment by syrusakbary** [comment]
We just added support for ARM compilation in our Cranelift compiler.
ARM is also supported automatically in our LLVM compiler as well, thanks to our major effort in the refactor.

Closing the issue!
