### ISSUE TITLE
The mapdir option unexpectedly maps to the current working directory

### ISSUE THREAD

**Issue by caspervonb** [wasmerio/wasmer#1503]
### Describe the bug

Take the following rename(2) test from the [wasi-test](https://github.com/caspervonb/wasi-test) project.

```c
// { "preopens": { "/scratch": "scratch" } }

#include <assert.h>
#include <stdio.h>

int main(void) {
	char oldname[] = "/scratch/oldfile";
	char newname[] = "/scratch/newfile";

	FILE *oldfile = fopen(oldname, "w");
	assert(oldfile != NULL);
	assert(fclose(oldfile) == 0);

	assert(rename(oldname, newname) == 0);

	FILE *newfile = fopen(newname, "r");
	assert(newfile != NULL);
	assert(fclose(newfile) == 0);

	return 0;
}
```

Which gets invoked as the following command

```
 wasmer run --mapdir=/scratch:scratch integration/rename.wasm 
```

```sh
echo "`wasmer -V` | `rustc -V` | `uname -m`"
wasmer 0.16.2 | rustc 1.43.1 (8d69840ab 2020-05-04) | x86_64
```

### Steps to reproduce

1. git clone https://github.com/caspervonb/wasi-test
2. python3 build.py
2. wasmer run --mapdir=/scratch:scratch integration/rename.wasm
4. mkdir scratch
5. ls scratch

### Expected behavior

/scratch to be mapped to ./scratch and it to contain a single file

### Actual behavior

/scratch is mapped to . which contains the created file

**Comment by syrusakbary** [comment]
Thanks for the report @caspervonb !

**Comment by MarkMcCaskey** [comment]
On wasmer on master I can confirm that `wasmer run --mapdir=/scratch:scratch integration/rename.wasm` does not work but `wasmer run --mapdir=scratch:scratch integration/rename.wasm` and `wasmer run --mapdir=./scratch:scratch integration/rename.wasm` seem to.

I'll look into it some more
