### ISSUE TITLE
Ability to create a “null” funcref

### ISSUE THREAD

**Issue by Hywan** [wasmerio/wasmer#1522]
When creating a `Table`, a `TableType { ty: Type::FuncRef, … }` type is required (as first argument), but an initial value too (as second argument). I see `Value::null()` that creates an `ExternRef`, but how to create a “null” function reference?

We can't. We need a new API for that :-).

**Comment by epilys** [comment]
[`null` in the wasm spec is created as an empty function reference, ](https://www.w3.org/TR/2022/WD-wasm-core-2-20220419/syntax/instructions.html#reference-instructions) so you can do `Value::FuncRef(None)` for a null value.
