### ISSUE TITLE
missing relocations in LLVM

### ISSUE THREAD

**Issue by Geal** [wasmerio/wasmer#1532]
hello, I'm currently integrating this new wasmer vesion in our tools at @CleverCloud. I'm opening this issue as a small reminder about those relocations that were not implemented: https://github.com/wasmerio/wasmer-reborn/pull/36/files#diff-688bd7d8e6eea9ea8d755b056b690e46R162
(I encountered them when rewriting my compilation phase)

**Comment by FlorentinDUBOIS** [comment]
Hey :vulcan_salute:,

I put this issue to my todo list :smile:
