### ISSUE TITLE
Add wasmer_version to the C-API

### ISSUE THREAD

**Issue by syrusakbary** [wasmerio/wasmer#1534]
Add a `wasmer_version` function to Wasmer C API.
It will also help to do sanity checks.

`int wasmer_version(void)`

Other functions that could be useful:

* `wasmer_available_compilers`
* `wasmer_available_engines`

**Comment by MarkMcCaskey** [comment]
Adding onto this issue, perhaps we want to use an enum for this purpose.

We should discuss the future of the C API and figure out what pieces are missing.

**Comment by syrusakbary** [comment]
I think versions are normally always reported as strings, I think that's more convenient as enums.

But yeah, for compilers and engines enums is the right approach!
