### ISSUE TITLE
Ctx::memory missing in compatibility wrapper

### ISSUE THREAD

**Issue by webmaster128** [wasmerio/wasmer#1535]
I'm migrating a project using the compatibility wrapper `lib/deprecated/runtime-core`, which turns out to be very very helpful for the migration.

I'm missing a function `vm::Ctx::memory` (https://github.com/wasmerio/wasmer/blob/0.17.1/lib/runtime-core/src/vm.rs#L392-L405). Can this easily be added or is there a different way to get `memory(0)` given a context?

**Comment by webmaster128** [comment]
Is there a chance this can be implemented? For us this could be a major step in the migration to Wasmer Reborn as it would make the codebase compile via `wasmer/lib/deprecated/runtime-core`. From there we can gradually refactor out `runtime-core`.

**Comment by Hywan** [comment]
Hello @webmaster128,

Unfortunately it's not that easy to port the `vm::Ctx::memory` as is. I'll try to see if I can find a nice workaround for it. If you don't have any reply from me in a couple of days, feel free to ping me again!

**Comment by webmaster128** [comment]
Hi @Hywan, initially the compatibility wrapper seemed like a great way to gradually upgrade code until I hit this. In the meantime I gave up using the compatibility wrapper and moved towards to new API. It is not yet fully compiling but we are getting there. So I don't need this feature anymore. Maybe others do, I don't know. Feel free to close it if you think this type of use case is too hard to support.

**Comment by Hywan** [comment]
Thanks @webmaster128 :-).

Yes migrating is not super difficult depending of your project. The compatibility layer is here for casual usages of Wasmer, mostly. I'm going to close that issue for the moment.

If someone else needs this feature, please raise your hand, and I'll be super happy to help and to implement that missing feature!
