### ISSUE TITLE
Swift runtime for Wasmer?

### ISSUE THREAD

**Issue by ryuheechul** [wasmerio/wasmer#1569]
### Summary

I see that there are Python and Ruby extensions (and for many others) to enable use of WASM via Wasmer in those languages. Is there a plan to support create a Swift extension as well?

### Additional details

I've been looking for a way to code core business logics in Rust for a macOS app. I'm interested to see if wasm can fill the gap nicely. I'm about to try [wasm3](https://github.com/wasm3/wasm3) to see if this allows such use case. In the meantime, Wasmer seems to be bridging between languages in that regards, so I was wondering if there will be a plan for Swift, too.

**Comment by MarkMcCaskey** [comment]
It's certainly a possibility!  I haven't had the chance to use Swift yet so I don't know if there are be any reasons why this wouldn't work, but if it can call Rust code or C code then it should be possible!

I'll bring it up to the team, it could be an interesting language to integrate with.

**Comment by Hywan** [comment]
Closing since https://github.com/AlwaysRightInstitute/SwiftyWasmer exists :-). Feel free to re-open if it doesn't satisfy you or if you want to discuss more about it.
