### ISSUE TITLE
Exporting a host function with a callback as parameter

### ISSUE THREAD

**Issue by jovanivanovic** [wasmerio/wasmer#1587]
### Summary

Hello, I am trying to export a function from the host that has a callback function as a parameter. I would like to somehow call that "guest" function in the host, but I didn't have any luck with it. I've seen a PR that added some features regarding the issue and an example, but at this point the example is gone.

### Additional details

This is the function that I am exporting from the host:
```rust
fn SubscribeEvent(ctx: &mut Ctx, func: u32)
{
    logi!("SubscribeEvent Start");
    let func_typed = unsafe { std::mem::transmute(func) };
    
    logi!("Trying to call callback function...");
    ctx.call_with_table_index(func_typed, &[]);
}
```

I am using AssemblyScript to get the wasm file. This is how I use the exported function:
```ts
@external('SubscribeEvent')
export declare function subscribeEvent(callback: () => void): void;

subscribeEvent(() => {
    Console.log('Test'); // This is another host-exported function, but this works fine outside of the callback
});
```

It always fails with this message: 
```
Error when calling invoke: An unknown trap (`segmentation violation`) occured
```

**Comment by syrusakbary** [comment]
HI @jovanivanovic, this should be feasible in the refactor work that landed in master a few weeks ago (although you will need a custom environment rather than using `Ctx`).

**Comment by jovanivanovic** [comment]
Is it possible to get more info on how that custom environment should work or something please?

**Comment by webmaster128** [comment]
In https://github.com/wasmerio/wasmer/issues/1364 and https://github.com/wasmerio/wasmer/issues/638 it was discussed how to call an exported funtion from an import implementation. This is currently possible and in the process of getting a nicer API in https://github.com/wasmerio/wasmer/pull/1739.

But what you describe here is calling a non-exported Wasm internal function (the callback) from the host, right? Is this something that can work, @syrusakbary?

**Comment by Hywan** [comment]
In Wasmer 2.0, it is now possible to declare a host function with, or without, an environment. An environment can hold any kind of data. There is even a `WasmerEnv` trait to help on that. Please see [the documentation of `Function`](https://docs.rs/wasmer/2.0.0/wasmer/struct.Function.html).
