### ISSUE TITLE
Allow using ? operator for custom error types in Function callbacks

### ISSUE THREAD

**Issue by webmaster128** [wasmerio/wasmer#1606]
I'm trying to port an import implementation to Wasmer Reborn. What I have so far is:

```rust
                "db_read" => Function::new_with_env(&store, &u32_to_u32, env.clone(), |env, args| {
                    let key_ptr = args[0].unwrap_i32() as u32;
                    let ptr = do_read::<S, Q>(env, key_ptr)?;
                    Ok(vec![ptr.into()])
                }),
```

where `do_read` returns a `core::result::Result<u32, VmError>`. Now I implemented

```rust
impl Into<wasmer_engine::RuntimeError> for VmError {
    fn into(self) -> wasmer_engine::RuntimeError {
        let msg: String = self.to_string();
        wasmer_engine::RuntimeError::new(msg)
    }
}
```

[`From<T> for U` implies `Into<U> for T`](https://doc.rust-lang.org/std/convert/trait.Into.html) but not the other way round.

Unfortunately the ? operator required `From` to be implemented, not `Into`. I don't know why this was chosen by Rust but I don't think it will change any time soon.

Would it be possible to require `Into<RuntimeError>` instead of `RuntimeError` in the callback like this:

```rust
    pub fn new_with_env<F, Err, Env>(store: &Store, ty: &FunctionType, env: Env, func: F) -> Self
    where
        F: Fn(&mut Env, &[Val]) -> Result<Vec<Val>, Err> + 'static,
        Err: Into<RuntimeError>,
        Env: Sized + 'static,
    {
```

Any other ideas how to deal with such use cases? In our old code, Wasmer did not care about the error type in the callback's `Result`.

**Comment by webmaster128** [comment]
Nevermind, I can implement

```
impl From<VmError> for wasmer_engine::RuntimeError {
    fn from(original: VmError) -> wasmer_engine::RuntimeError {
        let msg: String = original.to_string();
        wasmer_engine::RuntimeError::new(msg)
    }
}
```

I was not expecting to be able to implement for a foreign type, but it works. From my side this can be closed, but since you assigned yourself, @MarkMcCaskey, do you have additional thoughts?

**Comment by MarkMcCaskey** [comment]
@webmaster128 Oh, that's great to hear!  If it's solved on your end then I think it's good, I thought there might be another issue here but I just checked and it doesn't seem to be an issue.

I'll close this then.  Feel free to reopen it if other issues come up
