### ISSUE TITLE
WAPM not included in Linux release

### ISSUE THREAD

**Issue by mmstick** [wasmerio/wasmer#1610]
Only `wasmer` and `wax` are in the tarball

**Comment by syrusakbary** [comment]
Thanks for the report @mmstick. We published a new release for the alpha version and it didn't include wapm by mistake.

I've just fixed the issue by removing the alpha release from Github.
I tested the install command and now is back at installing `0.17.1`.

Now that you have wasmer installed, you can do:

```bash
# This will delete wasmer, forcing the installer
rm ~/.wasmer/bin/wasmer
# Install wasmer again
curl https://get.wasmer.io -sSfL | sh
```

Let me know if that worked!

**Comment by syrusakbary** [comment]
@MarkMcCaskey
