### ISSUE TITLE
Segfault on Win64

### ISSUE THREAD

**Issue by npip99** [wasmerio/wasmer#1611]
### Describe the bug

Windows x86_64 10.0.19041 Build 19041
Wasmer C API Release 0.17.1
C++17

I'm trying to get wasmer running on my system, but it appears to crash with a segmentation error when changing parts of the code that _appear_ to be no-ops. The Wasm I'm running was built with AssemblyScript, but it appears to be an underlying issue with Wasmer rather than AssemblyScript since it's inconsistent between platforms even on the same wasm.

### Steps to reproduce

Using the Wasmer C-API Example:

Works consistently:
```
int32_t add_to_counter(wasmer_instance_context_t *ctx, int32_t value_to_add) {
  //printf("CTX: %p\n", (void*)ctx);
  //const wasmer_memory_t* memory = wasmer_instance_context_memory(ctx, 0);
  //const u8* memory_data = wasmer_memory_data(memory);
  //u32 memory_length = wasmer_memory_data_length(memory);
  //printf("Memory: %p\n", memory);
  //printf("Length: %d\n", memory_length);
  printf("VAL: %d\n", value_to_add);
  //printf("VAL: %p\n", (void*)&value_to_add);
  return counter;
}
```

Crashes consistently:
```
int32_t add_to_counter(wasmer_instance_context_t *ctx, int32_t value_to_add) {
  //printf("CTX: %p\n", (void*)ctx);
  //const wasmer_memory_t* memory = wasmer_instance_context_memory(ctx, 0);
  //const u8* memory_data = wasmer_memory_data(memory);
  //u32 memory_length = wasmer_memory_data_length(memory);
  //printf("Memory: %p\n", memory);
  //printf("Length: %d\n", memory_length);
  printf("VAL: %d\n", value_to_add);
  printf("VAL: %p\n", (void*)&value_to_add);
  return counter;
}
```

Works consistently:
```
int32_t add_to_counter(wasmer_instance_context_t *ctx, int32_t value_to_add) {
  const wasmer_memory_t* memory = wasmer_instance_context_memory(ctx, 0);
  const u8* memory_data = wasmer_memory_data(memory);
  u32 memory_length = wasmer_memory_data_length(memory);
  //printf("Memory: %p\n", memory);
  //printf("Length: %d\n", memory_length);
  //printf("VAL: %d\n", value_to_add);
  //printf("VAL: %p\n", (void*)&value_to_add);
  return counter;
}
```

Crashes consistently:
```
int32_t add_to_counter(wasmer_instance_context_t *ctx, int32_t value_to_add) {
  const wasmer_memory_t* memory = wasmer_instance_context_memory(ctx, 0);
  const u8* memory_data = wasmer_memory_data(memory);
  u32 memory_length = wasmer_memory_data_length(memory);
  //printf("Memory: %p\n", memory);
  printf("Length: %d\n", memory_length);
  printf("Char: %c", memory_data[0]);
  return counter;
}
```

In any of the crash cases, I get `Call error: Error when calling invoke: An unknown trap ('segmentation violation') occured at 0x1E2EF7C35E8`, though the hex address is fairly random each time. It always appears similar to `ctx`, which would had the address `0x000001E1665762A0` in that particular run. What I find interesting is that the crash appears to occur after the function is called, since I'm able to read the entirety of `memory_data` just fine, and able to pass in AssemblyScript strings and Arrays and other data structures and read them correctly from memory_data. So the fault doesn't happen when running the function on the host system, the fault only happens when it goes back to running the webassembly.

The wasm and C++ is essentially out-of-the-box from the Wasm C API example.

```
import env from './env';

function init(a: i32): i32 {
  let b: i32 = 5;
  let ret: i32 = env.add_to_counter(b);
  return 0;
}

export {init};
```

Compiled with `asc main.ts --runtime half -b main.wasm`. The AssmeblyScript to wasm compiler seems to be effective as I'm able to run complex projects with thousands of lines of dynamic AssmeblyScript code on Ubuntu 18.01 with no issues, yet this simple three-line example here fails on Windows.

### Expected behavior

It runs correctly

### Actual behavior

It gives errors

### Additional context

It worked perfectly fine on my Ubuntu 18.01 system, this issue only occurs on Windows.
This type of behavior in response to seemingly no-op code _sounds_ like the optimizer is being aggressive. However the exact same results occur consistently across -O0 / -Ofast / -O2 and with link-time optimizations enabled and disabled. I also attempted several ABIs such as __fastcall and adding extern "C" but the results were consistently the same with the same code causing the same crashes. 

UPDATE:

This appears to crash by the same set of errors when using wapm out-of-the-box.

```PS C:\Users\*****\OneDrive\Documents\programming> wapm install huhn/did-cli
[INFO] Installing huhn/did-cli@0.0.1
Package installed successfully to wapm_packages!
PS C:\Users\*****\OneDrive\Documents\programming> wapm run did-cli
did-cli 0.1
huhn <huhn@einfachIOTA.de>
This doc string acts as a help message when the user runs '--help' as do all doc strings on fields

USAGE:
    did-cli [FLAGS] [OPTIONS] <input> <SUBCOMMAND>

ARGS:
    <input>    Some input. Because this isn't an Option<T> it's required to be used

FLAGS:
    -h, --help       Prints help information
    -v, --verbose    A level of verbosity, and can be used multiple times
    -V, --version    Prints version information

OPTIONS:
    -c, --config <config>    Sets a custom config file. Could have been an Option<T> with no default too [default:
                             default.conf]

SUBCOMMANDS:
    generate-seed    A subcommand for generate a new IOTA seed
    help             Prints this message or the help of the given subcommand(s)
    test             A subcommand for controlling testing
thread 'main' panicked at 'not yet implemented: windows::trigger_trap', lib\clif-backend\src\signal\windows.rs:134:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Error: error: InvokeError(UnknownTrap { address: 140718454488649, signal: "unknown exception code" })
```

I get unknown exception code on example-c-api when I try to ignore the first segmentation fault error and just run the above functions functions again and again.

**Comment by syrusakbary** [comment]
This issue should be fixed in Wasmer 1.0.

Please let us know if that's not the case.
Closing the issue
