### ISSUE TITLE
Rendering of the C/C++ API homepage

### ISSUE THREAD

**Issue by ShalokShalom** [wasmerio/wasmer#1655]
On modern mobile, the sidebar automatically opens up and seems to take half the screen:

![Screenshot_2020-09-28-12-20-33-39_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/6344099/94421019-3f58e280-0185-11eb-861d-6739e8296b7a.jpg)

**Comment by Hywan** [comment]
I reckon you can fold the sidebar. But the layer wasn't aimed to be used on a mobile. I'll check that as soon as I've time.

**Comment by Hywan** [comment]
Our C documentation is now generated with `rustdoc` thanks to [`inline-c`](https://crates.io/crates/inline-c) (see [how to get testable and runnable C examples within `rustdoc`](https://github.com/Hywan/inline-c-rs/tree/50935a9096a316e91e521b25542f4edf7f79bf72#using-inline-c-inside-rust-documentation)).

You can check https://github.com/wasmerio/wasmer/pull/1795 and https://github.com/wasmerio/wasmer/pull/1930 to get further information.

So, Doxygen is going to be removed from our toolbox. Consequently, I'm closing this issue :-).
