### ISSUE TITLE
More testing of our WASI implementation with test suites

### ISSUE THREAD

**Issue by MarkMcCaskey** [wasmerio/wasmer#1664]
We are currently testing WASI with our own test suite at https://github.com/wasmerio/wasi-tests

We should ensure that Wasmer is passing tests on other test suites and perhaps run them in CI if they're not too slow.

List of test suites:

- [x] https://github.com/wasmerio/wasi-tests
- [ ] https://github.com/khronosproject/wasi-test
- [ ] https://wasi.fyi/

**Comment by ptitSeb** [comment]
I think the new snapshot tests improved overall WASI test, even if it's not in a "unit test" way.
I propose this ticket to be closed. @syrusakbary @theduke @Michael-F-Bryan

**Comment by ptitSeb** [comment]
WASI is quite tested already.
