### ISSUE TITLE
Line endings in WASI on Windows

### ISSUE THREAD

**Issue by MarkMcCaskey** [wasmerio/wasmer#1665]
On windows we're getting `\r\n` at the WASI level it seems: when a WASI program reads a file with unix style line endings, it's seeing `\r\n`.  Either Rust stdlib is doing this or perhaps it's the configuration of `git` in GitHub Actions CI.

Either way, we should investigate this and figure out if that is the case and if it is, if it's an issue for cross-platform determinism or not.

There are a handful of tests ignored in `tests/ignore.txt` because of this too, those should be reenabled.

**Comment by rajsite** [comment]
Ran into this with stdin `std::getline(std::cin,str)` on windows terminal using an emscripten compiled (STANDALONE_WASM) wasi module. Not sure if it's an issue or not. If that's what the terminal passes in that's what is passed in I suppose..

**Comment by MarkMcCaskey** [comment]
@rajsite Thanks for letting us know!

My take is that it is a bug: a given WASI Wasm program should execute the same on all platforms to the greatest extent possible... 

Which I think this means that we need to normalize line endings coming in from Windows and normalize them when going out too...
