### ISSUE TITLE
Does Wasmer pass in a preopened directory even when not using `--dir` option?

### ISSUE THREAD

**Issue by yagehu** [wasmerio/wasmer#1675]
### Summary

I wrote a small program in Wasm text format that tries to get the first preopened dirfd. It returns 0 if such an fd is found. When I run the same program in other runtimes (so far I've tried WAVM and Wasmtime), I get a non-zero status code. But if I run it with Wasmer without the `--dir` flag, I get a 0 status code, indicating the program found a preopened dirfd.

```
$ wat2wasm tests/open/main.wat
$ wasmtime run main.wasm      
$ echo $?
8
$ wavm run main.wasm    
$ echo $?           
8
$ wasmer run main.wasm  
$ echo $?
0
```

My question is: Is this behavior expected? Does Wasmer pass in a preopened directory fd even when not using the `--dir` option?

### Additional details

```wat
;; Exit status codes:
;; 
;; - 8: Could not find a preopened fd.
(module
  (type (;0;) (func (param i32 i32 i32 i32 i32 i64 i64 i32 i32) (result i32)))
  (type (;1;) (func))
  (type (;2;) (func (param i32 i32) (result i32)))
  (type (;3;) (func (param i32)))
  (type (;4;) (func (param i32) (result i32)))

  (import "wasi_snapshot_preview1" "fd_prestat_get"
    (func $__wasi_fd_prestat_get (type 2))
  )
  (import "wasi_snapshot_preview1" "path_open"
    (func $__wasi_path_open (type 0))
  )
  (import "wasi_snapshot_preview1" "proc_exit"
    (func $__wasi_proc_exit (type 3))
  )

  (func $_start (type 1)
    (local $dirfd i32)
    (local $errno i32)

    (call $getFirstGoodDirfd (i32.const 0))
    (if
      (i32.ne (local.tee $errno) (i32.const 0))
      (then
        (call $__wasi_proc_exit (i32.const 8))
      )
      (else)
    )

    (local.set $dirfd (i32.load (i32.const 0)))

    (call $__wasi_proc_exit (i32.const 0))
  )
  (func $getFirstGoodDirfd (type 4) (param $fd i32) (result i32)
    (local $dirfd i32)
    (local $errno i32)

    ;; Start with the lowest fd after stdin, stdout, and stderr.
    (local.set $dirfd (i32.const 3))

    (block ;; label = @1
      (block ;; label = @2
        (loop $loop ;; label = @3
          (call $__wasi_fd_prestat_get
            (local.get $dirfd)
            (i32.const 0)
          )

          ;; If errno is 0, we found a good dirfd. Break the loop.
          (br_if 2 (;@1;) (i32.eq (local.tee $errno) (i32.const 0)))

          ;; If errno is 8, we encountered `badf`. Return 8 indicating failure.
          (br_if 1 (;@2;) (i32.eq (local.get $errno) (i32.const 8)))

          ;; Increment dirfd.
          (local.set $dirfd (i32.add (local.get $dirfd) (i32.const 1)))

          (br $loop)
        )
      )

      (return (i32.const 8))
    )

    (i32.store (local.get $fd) (local.get $dirfd))
    i32.const 0
  )

  (memory (;0;) (export "memory") 1)

  (export "_start" (func $_start))
)
```

**Comment by MarkMcCaskey** [comment]
Yeah, we mount a virtual root directory that shows up as preopened I believe.  There are no files or directories in it by default but certain Wasmer flags like `--enable-experimental-io-devices` (if compiled with that feature) will add other virtual directories to the virtual root.  Additionally any preopened directories will appear in the virtual root.

This behavior is mostly for convenience and to  work around issues in some implementations of WASI, like AssemblyScript's.

Wasmer intends to follow the WASI standard but due to the lack of official spectests or specificity around some behavior, we made our own decisions that solved the problems we were seeing.  If this behavior is causing problems then we'll definitely revisit it and adjust it to make sense.

**Comment by yagehu** [comment]
Interesting. A little bit of context on why I'm even doing this: I'm trying to write short WASI programs in text format so I can programmatically verify basic WASI syscall support in various runtimes. For `prestat_get`, I was assuming the behavior that if no preopened directories were specified by the user, we should not find a preopened directory. Apparently I shouldn't assume so!

I'll close this issue for now. Just wanted to check my sanity.
