### ISSUE TITLE
Locating resources when targeting WASI

### ISSUE THREAD

**Issue by mejedi** [wasmerio/wasmer#1686]
### Summary

Some programs depend on resources (i.e. data files). Typically, you put them alongside the binary, so that resource path is easy to determine given the executable path. When targeting `emscripten` ABI, the path is available as `argv[0]`. But with `WASI`, only the filename is exposed.

How do I make it work with `WASI`?

### Additional details

```c
#include <stdio.h>
int main(int argc, char **argv) {
  return puts(argv[0]);
}
```

Compiled with emscripten `1.38.43` (`emcc -O2 test.c`):

```sh
$ wasmer run $(pwd)/a.out.wasm
/tmp/r/a.out.wasm
```

Compiled with emscripten `2.0.6`, targeting `WASI` (`emcc -O2 test.c -s STANDALONE_WASM=1`):

```sh
$ wasmer run $(pwd)/a.out.wasm
a.out.wasm
```

**Comment by MarkMcCaskey** [comment]
Generally you'd do it the same way you would with the Emscripten ABI but with a preopened directory.  As bundling files is not part of the WASI standard, there's no way to do this at the Wasm runtime level currently.

[Wapm](https://github.com/wasmerio/wapm-cli/), our package manager, supports bundling in files with the wapm package and when running with WASI, it will preopen the directory for you so everything should just work if run with wapm.

I believe the syntax is that in the wapm.toml, add a `[fs]` section and specify paths in it as
`"location/on/guest"="location/on/host"` relative to the wapm.toml file and then it will be included in the wapm package when uploaded to wapm. Then when downloaded and run, the file system will be made available through preopens.

wapm supports configuring which Wasm runtime it uses so this should be a fairly general solution but the logic in wapm for supporting other runtimes isn't that sophisticated yet and it assumes command line flags are identical.  If you run into any problems with your use case, please file an issue so we can fix it!

**Comment by mejedi** [comment]
@MarkMcCaskey Thank you for the prompt response!

My project is a CLI tool, therefore it is important to mimic the semantics of native tools irt the filesystem.

I've written a sample program to play with wapm options. The program lists pre-opens. With the following `wapm.toml` I am almost getting what I want:

```
[package]
...
wasmer-extra-flags = "--dir=."

...

[fs]
"/" = "/"
"/usr/share/eee/" = "resources"
```

The program is installed globally (`wapm install -g`). I get the following output:
```sh
$ wapm run eee
preopens:
[3] / (/.,//,//usr/share/eee/)
[4] . (.bazelrc,.clang-format,.clang-tidy,.clang_complete,.editorcon)
[5] /usr/share/eee/ (res1,res2)
[6] / (bin,boot,cdrom,dev,etc,home,initrd.img,initrd.img.old,lib,lib)
```
The program has access to the filesystem root via `#6`, current working directory via `#4` and resources via `#5`.

The only bit missing is figuring out the current working directory path. `wasi-libc` uses `PWD` environment variable. I've noticed that the host environment is not passed. Although `wasmer-extra-flags` could be used to configure environment variables, there's presumably no way to configure a dynamic value in `wapm.toml`.

Any suggestions?

**Comment by MarkMcCaskey** [comment]
> The only bit missing is figuring out the current working directory path. wasi-libc uses PWD environment variable. I've noticed that the host environment is not passed. Although wasmer-extra-flags could be used to configure environment variables, there's presumably no way to configure a dynamic value in wapm.toml.

That actually sounds like a great feature for wapm to have!  You should file an issue so we can pass env vars through.

That's interesting, I didn't know that the WASI libc used env vars but it makes sense.

Perhaps it's worth special casing some env vars in Wasmer itself for WASI.  I'll ping the team about it.
