### ISSUE TITLE
fd_datasync on stdout returns 0

### ISSUE THREAD

**Issue by yagehu** [wasmerio/wasmer#1703]
### Describe the bug

I wrote this super short WebAssembly text format program that simply performs `fd_datasync` on `stdout`. On other runtimes I've tested (Wasmtime, WAVM, SSVM) the return code is 76. But Wasmer returns 0 indicating success. I'm not sure if this is non-standard behaviour. Feel free to close if WASI does not define this behavior.

```sh
$ echo "`wasmer -V` | `rustc -V` | `uname -m`"
wasmer 0.17.1 | rustc 1.45.2 (d3fb005a3 2020-07-31) | x86_64
```

### Steps to reproduce

Run this `.wat` file with Wasmer (no flags).

```wat
(module
  (import "wasi_snapshot_preview1" "proc_exit"
    (func $__wasi_proc_exit (param i32))
  )
  (import "wasi_snapshot_preview1" "fd_datasync"
    (func $__wasi_fd_datasync (param i32) (result i32))
  )

  (func $_start (export "_start")
    (call $__wasi_fd_datasync
      (i32.const 1)
    )
    call $__wasi_proc_exit
  )

  (memory $memory (export "memory") 1)
)
```

### Expected behavior

Return 76 `notcapable`.

### Actual behavior

Returns 0 `success`.

**Comment by MarkMcCaskey** [comment]
This looks like the same thing as https://github.com/wasmerio/wasmer/issues/1702#issuecomment-707260672 ; we should review the capabilities in WASI libc and update wasmer-wasi accordingly

**Comment by Amanieu** [comment]
The latest versions of both wasmer and wasmtime return 0 for the example code.

In general I'm not sure that WASI actually specifies what capabilities are available on stdin/stdout/stderr.
