### ISSUE TITLE
probestack broken with engine-native and compiler-llvm

### ISSUE THREAD

**Issue by nlewycky** [wasmerio/wasmer#1722]
# Describe the bug

When building with --llvm and --native, `wast::llvm::spec::skip_stack_guard_page` fails with "out of bounds memory access" instead of the expected "call stack exhausted".

Let's take a quick look at one example:
```
(lldb) disassemble -s 0x7ffff77a0061
wasmer_nativexpTE17.so`wasmer_function__1:
    0x7ffff77a0061 <+1>:  pushq  %r15
    0x7ffff77a0063 <+3>:  pushq  %r14
    0x7ffff77a0065 <+5>:  pushq  %r13
    0x7ffff77a0067 <+7>:  pushq  %r12
    0x7ffff77a0069 <+9>:  pushq  %rbx
    0x7ffff77a006a <+10>: movl   $0x2098, %eax             ; imm = 0x2098 
    0x7ffff77a006f <+15>: callq  0x7ffff77a0020            ; symbol stub for: wasmer_probestack
    0x7ffff77a0074 <+20>: subq   %rax, %rsp
    0x7ffff77a0077 <+23>: movq   0x8(%rdi), %rbx
    0x7ffff77a007b <+27>: callq  0x7ffff77a0030            ; symbol stub for: wasmer_function__1
```

That wasmer_probestack stub is a PLT entry which looks like this:
```
(lldb) disassemble -s 0x7ffff77a0020
wasmer_nativexpTE17.so`wasmer_probestack:
    0x7ffff77a0020 <+0>:  jmpq   *0x9ffa(%rip)             ;  + 32
    0x7ffff77a0026 <+6>:  pushq  $0x1
    0x7ffff77a002b <+11>: jmp    0x7ffff77a0000
```
(you can ignore everything but the first instruction, __rust_probestack ends in a retq which will tail call return past this frame back to 0x7ffff77a006f)

That jmpq resolves to `0x000055555bde4148` which looks like bad code:
```
* thread #2, name = 'wast::llvm::spe', stop reason = instruction step into
    frame #0: 0x000055555bde4148
->  0x55555bde4148: jp     0x55555bde40df
    0x55555bde414a: movl   %ebx, 0x55(%rbx)
    0x55555bde414d: pushq  %rbp
    0x55555bde414e: addb   %al, (%rax)
```
but note that it is indeed the address of wasmer_probestack!
```
(lldb) p &wasmer_probestack
(void (**)()) $38 = 0x000055555bde4148
(lldb) p wasmer_probestack
(void (*)()) $39 = 0x000055555b89957a (compilers-95b529d63c259da9`__rust_probestack)
```
Somehow we jumped to the address of a global variable pointing to __rust_probestack instead of calling directly into __rust_probestack.

**Comment by nlewycky** [comment]
Lots of options, none of which stand out as particularly good.
* Just write our own stack probe function instead.
* Use unstable rust features to write a shim that calls the real stack probe function. #2082 
* When compiling for a given target, look up the name of the target stack probe function and use that instead of a function defined in wasmer's libcalls.rs.
* When building with native or object-file engines, include a one-line C program that adds the alias from one name to the other.
* Wait for https://internals.rust-lang.org/t/symbol-aliases/13297 to be resolved so that we can use that instead of a one-line C program. Unfortunately we'd need to use platform extensions instead of portable C.
* Add an interface to the compiler to ask the compiler to emit the symbol alias for us. LLVM can do that, singlepass can do that, cranelift presently doesn't have the ability to represent that in their IR.
* Disable stack probes for native and object-file engines.

**Comment by nlewycky** [comment]
> Just write our own stack probe function instead.

This requires unstable rust features anyways, so it's got the same problem as writing the shims.

**Comment by ptitSeb** [comment]
Still happening on Native engine only (with both llvm and cranelift compiler)
