### ISSUE TITLE
Port over Wasi stdout/etc capture example

### ISSUE THREAD

**Issue by MarkMcCaskey** [wasmerio/wasmer#1737]
We used to have an example showing how to capture stdout, etc. with WASI but that example didn't make the transition: here it is in old Wasmer https://github.com/wasmerio/wasmer/blob/0.x/examples/plugin.rs ; it should be mostly the same.

**Comment by Hywan** [comment]
Closed by https://github.com/wasmerio/wasmer/pull/1921.
