### ISSUE TITLE
Renaming a file unexpectedly places it outside of pre-opened directory

### ISSUE THREAD

**Issue by nr6000000** [wasmerio/wasmer#1759]
### Describe the bug
Whenever a file is renamed it's placed outside of pre-opened directory. It happens only if the file isn't in a subdirectory.

```sh
echo "`wasmer -V` | `rustc -V` | `uname -m`"
wasmer 1.0.0-alpha4 | rustc 1.47.0 (18bf6b4f0 2020-10-07) | x86_64
```

### Steps to reproduce
1. Download [uutils.wasm](https://registry-cdn.wapm.io/contents/_/coreutils/0.0.1/target/wasm32-wasi/release/uutils.wasm) from WAPM
2. Create directory dir with a sample file foo in it
3. Run `wasmer --dir=./dir uutils.wasm -- mv dir/foo dir/bar`

### Expected behavior
File ./dir/foo is renamed to ./dir/bar

### Actual behavior
File ./dir/foo is renamed to ./bar

### Additional context
`wasmer --dir=./dir uutils.wasm -- mv dir/dir2/foo dir/dir2/bar` works correctly

**Comment by MarkMcCaskey** [comment]
Thanks for the bug report!  That seems like a fairly important bug (breaking the filesystem sandbox), I'll make sure we stress test our sandboxing more
