### ISSUE TITLE
Add test for dynamic memory

### ISSUE THREAD

**Issue by MarkMcCaskey** [wasmerio/wasmer#1769]
#1687 fixes a bug that is most easily observable with dynamic memory.  Unfortunately the Wasmer API does not have a direct way to get access to a dynamic memory (it's likely possible by overriding tunables, however), we should add a test to ensure that the export bug fixed in #1687 stays fixed for memories.

Note, it should also be possible to observe this bug in the length of static memories with the wasm `memory.size` instruction

**Comment by heyjdp** [comment]
This issue needs test cases

**Comment by ptitSeb** [comment]
I propose this issue to be closed.
