### ISSUE TITLE
wasmer fails to execute qjs.wasm on windows 10

### ISSUE THREAD

**Issue by spullara** [wasmerio/wasmer#1788]
### Describe the bug

I installed wasmer on windows 10 via the powershell instructions. Then downloaded qjs.wasm. Running it then resulted in a panic.

### Steps to reproduce
iwr https://win.wasmer.io -useb | iex
wasmer .\Downloads\qjs.wasm

### Expected behavior

QuickJS to start up.

### Actual behavior
PS C:\Users\sam> wasmer .\Downloads\qjs.wasm
QuickJS - Type "\h" for help
qjs > thread 'main' panicked at 'not implemented: HostFile::poll in WasiFile is not implemented for non-Unix-like targets yet', lib\wasi\src\state\types.rs:402:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

thread 'main' has overflowed its stack
PS C:\Users\sam>

**Comment by MarkMcCaskey** [comment]
Thanks for the report! There are 2 platform specific parts of our WASI implementation: clocks and polling.  Last time I looked polling on Windows seemed to be non-trivial because of differences between posix and windows async APIs...

My advice for whoever picks this up in the future is to consider special casing the "sleep" use case from the async I/O use case, it might make things a lot simpler.

**Comment by wangbyby** [comment]
Hello, I have a similar bug.
# env+version
- win10 pre-build binary
- version:2.0.0-rc1.
- Download from https://github.com/wasmerio/wasmer/releases/download/2.0.0-rc1/wasmer-windows.exe
# Error
```bash
PS D:\wasmrust\wasm-code> wasmer --version
wasmer-cli
PS D:\wasmrust\wasm-code> wapm install quickjs
[INFO] Installing _/quickjs@0.0.3
Package installed successfully to wapm_packages!
thread 'main' panicked at 'Can't show wapm update notification: "Can\'t find the version of wasmer"', src\update_notifier.rs:175:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

# cmd has same error
D:\wasmrust\wasm-code> wapm install quickjs
No packages to install
thread 'main' panicked at 'Can't show wapm update notification: "Can\'t find the version of wasmer"', src\update_notifier.rs:175:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
# next
What should I do now?

Thanks!

**Comment by MarkMcCaskey** [comment]
@wangbyby Thanks for the update, the panic you're seeing is actually due to a bug in the `wasmer --version` command, but the wapm commands you've executed are actually succeeding. We'll be shipping a fix for this shortly

**Comment by syrusakbary** [comment]
@wangbyby we just published `wasmer-2.0.0rc2` which should solve your issue. You can try reinstalling wasmer and see if that fixes it!

**Comment by wangbyby** [comment]
thanks a lot！！！



---Original---
From: "Syrus ***@***.***&gt;
Date: Fri, Jun 4, 2021 03:28 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wasmerio/wasmer] wasmer fails to execute qjs.wasm on windows 10 (#1788)




 
@wangbyby we just published wasmer-2.0.0rc2 which should solve your issue. You can try reinstalling wasmer and see if that fixes it!

**Comment by olson-dan** [comment]
Just to be clear since there are two issues in this thread, the HostFile::poll issue is still open on 2.0.0.

**Comment by Hywan** [comment]
`wasi_poll_oneoff` issue for Windows is here, #570. Closing in favor of this issue.
