### ISSUE TITLE
The README file in this repo has a bad link - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [wasmerio/wasmer#1797]
The README file in this repo has a bad link - [404:NotFound]

Status code [404:NotFound] - Link: https://docs.wasmer.io/wasmer-js/wasmer-js

This was found by an new experimental hobby project that I have just created: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
If this has been in any way helpful then please consider giving the above Repo a Star.

**Comment by jubianchi** [comment]
Thanks for reporting that !

I submitted a PR to fix this issue.
