### ISSUE TITLE
`cargo publish` doesn't work on wasmer-c-api

### ISSUE THREAD

**Issue by nlewycky** [wasmerio/wasmer#1802]
### Describe the bug

`scripts/publish.py` runs `cargo publish` on every crate in Wasmer. This fails to publish the wasmer-c-api for two reasons:
1. wasmer-c-api doesn't build with the default features. `cargo publish --features=jit,native,object-file` builds though. 
2. the build.rs file changes the `wasmer_wasm.h` in the source directory. `cargo publish --no-verify` can proceed despite that.

**Comment by syrusakbary** [comment]
For 2, the only thing we need to do is assuring to build the library first, commit any files and the publish?

**Comment by nlewycky** [comment]
I really don't think we should be modifying the source directory as part of any build action of any kind, ever. Put another way, we should be able to make all of wasmer directories read-only except the `target/` directory and build test and publish should all work.

The reason we don't do this now is that we want to make sure we can review changes to that file and we don't have any way to review changes to it without putting it in the source directory. Last time this came up I didn't have any suggestions, but I just had an idea:
* we keep a copy of `wasmer_wasm.h` in the source tree under a different name like `wasmer_wasm.h-reference`
* add to `make test` a build of that file and verify that the generated `wasmer_wasm.h` matches our reference. If it doesn't, make test fails.
* when intentionally modifying the generator for `wasmer_wasm.h`, the developer can update the reference which will be included in the diff. We could even have a `make update-wasmer-wasm-h` rule to do it, but this rule would never be ordinarily run by our builds, our CI, or our packaging, only with a manual run.
* a tool like scripts/publish.py could run `make test-wasmer-wasm-h` before the rest of the publish to make sure it's up to date and fail before publishing some of the crates.

**Comment by jubianchi** [comment]
The `test-capi-*` targets actually build the `.h`. We could add something like `git diff --exit-code -- lib/c-api/wasmer_wasm.h` to the end of `test-capi` recipe and it will make the build fail if we forgot to generate and commit the `.h`.

Doing such thing we don't have to deal with a reference file (and thus, having to care about two files instead of only one today).

**Comment by Hywan** [comment]
I believe the problem has been solved with https://github.com/wasmerio/wasmer/pull/2076. Closing.
