### ISSUE TITLE
Possibility to unload a module

### ISSUE THREAD

**Issue by daubaris** [wasmerio/wasmer#1806]
### Summary

Because now `wasmer-1.0.0` has a concept of a `Store`, is it possible to remove objects from the store that are no longer referenced? If the feature is not present, are there any plans to implement it?

### Additional details

Relevant information related to this question was posted [here](https://github.com/bytecodealliance/wasmtime/issues/2210).

**Comment by Hywan** [comment]
Hello @daubaris,

For the moment, the `Store` aims at holding the engine and the “tunables”:

https://github.com/wasmerio/wasmer/blob/90fe6c3aefc488632521600bba5f5ed60577f695/lib/api/src/store.rs#L9-L23

We don't use it to store referenced objects or other things.

**Comment by syrusakbary** [comment]
Right now the Store only holds the Engine and Tunables, as Ivan commented.

It's true that once a module is being created, the Engine owns it's Artifact (the compiled version of the module). Perhaps we can add some way to unload the artifact directly?

Would that solve the issue @daubaris ?

**Comment by daubaris** [comment]
Wouldn't "unloading directly" cause some serious issues? I mean, there must be some mechanism ensuring that an "artifact" is no longer referenced in order for it to be unloaded, right? For example the runtime would need to trap on trying to use a reference that is invalid or the references should be automatically removed by the runtime. Otherwise, the embedder must be able to somehow detect all references and remove them. I think anything suits us fine as long as references can be handled and we can unload things.

I think the description of a store in Wasmer documentation is a bit ambiguous as it uses a sentence from the specification describing that it "consists of the runtime representation of all instances of functions, tables, memories, and globals that have been allocated during the life time of the abstract machine", although as @Hywan  mentioned "the Store aims at holding the engine and the 'tunables':". Maybe it should be removed? It is also unclear how and where does Wasmer store its runtime representation (e.g., functions)?

@syrusakbary, to answer the question if it would solve the issue - potentially. However, the main issues about invalid references are still relevant. How would the unloading mechanism actually work with having the issues described above in mind?

**Comment by Hywan** [comment]
I don't understand what problem you're trying to solve. What objects are we talking about? Why would you want to remove them? Let's start by answering those questions, because I'm sure we have an answer for you :-).

**Comment by daubaris** [comment]
At least from the official specification objects of a store are functions, tables, memories and globals, right?

Well, if I can load a module, I would also like to unload it whenever it is no longer used. Why waste memory? However, I can't unload a module without ensuring that all of its instance components are no longer referenced. 

The problem that I want to solve is to unload a module completely, which means removing all of the references to its components.

**Comment by Hywan** [comment]
In Wasmer, if you can drop a value, you're sure things will continue to work. We take care of everything behind the scene. Once a module is instantiated, the `Instance` holds everything it needs to work. Again, if you can drop it, it means it's OK.

It's even OK to drop an `Instance` and still get working exported `Function`s for example. Behind the scene, an `Instance` holds an `vm::InstanceHandle`, which holds a `vm::InstanceRef`, which is a safe reference to a low-level `vm::Instance`. The same `vm::InstanceRef` is held by `vm::ExportFunction`, which is held by `Function` itself. We've designed Wasmer in such a way that it works like a “garbage-collected API”, based on Atomic Reference Counting.

So once again, if Rust allows you to unload the module, it means everything is OK :-). We still can have bugs of course, in this case, please feel free to open an issue!

**Comment by Hywan** [comment]
Did I answer your question?

**Comment by daubaris** [comment]
Conceptually, yes. From the given example it seems that you are talking about a scenario where there is an independent instance and a host. However, what if there are two modules linked together which share memory, table and functions? Is it possible to drop only one of these modules that are linked together?

Also, in order to use this functionality, would one just use `Instance::drop` method?

**Comment by Hywan** [comment]
Usually Rust drops the value by itself, you don't need to do anything (and it's better like this!).

For cross-modules API, it is the same. You can drop the `Module` or the `Instance`: the underlying objects should store references to them. I didn't try that myself though.

**Comment by daubaris** [comment]
Alright, I guess this answers my questions. I'd maybe suggest adding an example and maybe some documentation regarding this (maybe even a graph?). However, other than that, the issue can be closed.

**Comment by Hywan** [comment]
Good! I'm closing the issue, but I keep the wish for another example in my todo list. Feel free to re-open if you need further information.
