### ISSUE TITLE
wasmer nightly source is the source to the github workflow

### ISSUE THREAD

**Issue by nlewycky** [wasmerio/wasmer#1808]
### Describe the bug

Go to https://github.com/wasmerio/wasmer-nightly/releases, download `wasmer-nightly-wasmer-nightly-2020-11-08.tar.gz`. It's only 3043 bytes:
```
wasmer-nightly-wasmer-nightly-2020-11-08/
wasmer-nightly-wasmer-nightly-2020-11-08/.github/
wasmer-nightly-wasmer-nightly-2020-11-08/.github/workflows/
wasmer-nightly-wasmer-nightly-2020-11-08/.github/workflows/main.yaml
wasmer-nightly-wasmer-nightly-2020-11-08/README.md
```

**Comment by syrusakbary** [comment]
Oh, that's fine. The source download links are being generated by Github, not us.
It basically includes a snapshot of the wasmer-nightly repo at the time of the release

**Comment by syrusakbary** [comment]
In case it was not clear for future readers: we can’t do anything to solve it, the "download source" as zip/tar files it’s a “feature” of Github automatically done for each release.

**Comment by MarkMcCaskey** [comment]
We could package the source we used to build and upload it to github, but I think that's probably not necessary... we should however include the git hash that we used to build it in the release notes and ideally in `wasmer --version`... but that's lower priority, I'd say we should make a way to easily install the nightly release first

**Comment by jubianchi** [comment]
https://github.com/wasmerio/wasmer-nightly/issues/4
