### ISSUE TITLE
Document ChainedResolver more clearly

### ISSUE THREAD

**Issue by MarkMcCaskey** [wasmerio/wasmer#1818]
If users want to create extended import objects, they'll have to chain resolvers together.

We should:

- [ ] create an example showing this
- [ ] document the traits better
- [ ] document / have an example in the rustdoc for `ImportObject` itself

**Comment by ngockhanhlam** [comment]
Need example

**Comment by epilys** [comment]
`ChainedResolver` has been removed in https://github.com/wasmerio/wasmer/pull/2846
