### ISSUE TITLE
Reload Artifact

### ISSUE THREAD

**Issue by deuszex** [wasmerio/wasmer#1823]
Hey!

I came across the `.cache(&self)` function on `wasmer_runtime::Module`, and found that while I gives me an `Artifact` I cannot find any convenient way to get a Module out of it. Then I happened to see the 0.18 yanked version that does have a convenient `.module(&self)` function for the exact case.

What is the case with the yanked version, and/or what do you think I could do to get a `Module` back from an `Artifact` in a simpler way, like in the yanked version? Is my only option to go with the recompilation way (`wasmer_runtime_core::load_cache_with`)?

**Comment by syrusakbary** [comment]
Hi @deuszex, the 0.x versions are no longer maintained, as we are putting our whole focus on Wasmer 1.0.

Have you tried it? I believe the `wasmer-cache` will probably fit your needs :)

**Comment by deuszex** [comment]
Hey @syrusakbary, Thank you for the answer!
I did not know that a version 1.0 is on the way, great news, good job.
Unfortunately we mainly used the wasmer_runtime crate, which as I see you are deprecating in the next version. So for the further, we will have to see what and how we'll rewrite.
Are the 1.0 alphas release candidates or just the usual versioning? In case they are RC-s which one do you see most likely to proceed as the final version?

**Comment by syrusakbary** [comment]
Sorry, forgot to reply here!
A rc version should be coming soon
