### ISSUE TITLE
Protect `WasiState` with a reentrant mutex

### ISSUE THREAD

**Issue by MarkMcCaskey** [wasmerio/wasmer#1825]
Context  #1810

it's a useful pattern to be able to acquire a mutex, call into Wasm, and have that Wasm call back into the host which then does something with WASI state.  Because #1810 will make the `Mutex` part of our public API, if this is something we want to do, we should do it before we go to 1.0

**Comment by syrusakbary** [comment]
WASI doesn’t support multi threaded environments. So I don’t think we need at the moment

**Comment by MarkMcCaskey** [comment]
See https://github.com/wasmerio/wasmer/pull/1810#issuecomment-732420685 for explanation about why we won't be using a reentrant mutex for now
