### ISSUE TITLE
Simplify Wasm C API implementation

### ISSUE THREAD

**Issue by MarkMcCaskey** [wasmerio/wasmer#1860]
As the Wasmer Rust API’s ownership becomes more like the C API, we can start simplifying some of the code in our C API implementation. For example currently we pass around lots of `Arc<Instance>` in order to keep things like functions working after the instance has been dropped at the C API level.  With the recent changes, that kind of explicit thing at the C API level shouldn’t be necessary anymore

**Comment by syrusakbary** [comment]
C-API is based on https://github.com/WebAssembly/wasm-c-api so we should respect that while changing the internals

**Comment by syrusakbary** [comment]
We might need to merge `Context` and `Store` together to be able to not do any breaking change on the official Wasm C API

**Comment by syrusakbary** [comment]
This is fixed by #2973

**Comment by syrusakbary** [comment]
This was refactored and fixed in #3013. Closing the issue
