### ISSUE TITLE
Naming conflict Tunables between wasmer/wasmer_engine

### ISSUE THREAD

**Issue by webmaster128** [wasmerio/wasmer#1872]
### Describe the bug

According to Syrus' statement (https://github.com/CosmWasm/cosmwasm/commit/950f63183a266d9114f80085b66d679b7a6c33ca#r44799222), all symbols from the crate `wasmer-engine` should be available in `wasmer`. When I tried that, I ran into the naming conflict `Tunables`, which is the trait in `wasmer-engine` and the reference implementation in `wasmer`.

In my project, I resolved the conflict as follows:

```rust
use wasmer::{Bytes, Engine, Pages, Singlepass, Store, Target, Tunables as ReferenceTunables, JIT};
use wasmer_engine::Tunables;
```

because I don't think `Tunables` is not a great name for one specific `Tunables` implementation. Maybe we adopt this here? Or resolve the conflict differently.

### Steps to reproduce

NA

### Expected behavior

All symbols from `wasmer_engine` are re-exported in `wasmer`

### Actual behavior

`wasmer_engine::Tunables` and `wasmer::Tunables` are different things.

**Comment by webmaster128** [comment]
I can work on this, but need a 👍/👎 if you would be happy with `Tunables` for the trait and `ReferenceTunables` (or `BaseTunables`) for the implementation.

**Comment by Hywan** [comment]
I'm OK to try something. Ping me on your PR so that I can review it :-).
