### ISSUE TITLE
Reference Types (externref) support

### ISSUE THREAD

**Issue by bkolobara** [wasmerio/wasmer#1875]
One feature I started relaying on lately in [lunatic's](https://github.com/lunatic-lang/lunatic) host functions are [externrefs](https://github.com/WebAssembly/reference-types). I currently use [Wasmtime's implementation](https://fitzgeraldnick.com/2020/08/27/reference-types-in-wasmtime.html), but would love if I could switch to Wasmer and also keep the externref aware host functions.

Wasmtime uses [deferred reference counting](https://www.researchgate.net/publication/200040321_An_Efficient_Incremental_Automatic_Garbage_Collector) to keep track of externref's lifetimes. In my experience this doesn't seem to provide a big benefit instead of just using regular reference counters on `local.get` and `local.set`. In most languages (C, Rust, ...) you can't express currently a reference type and most tools working with externrefs will immediately store them in a wasm table and return an index. Stores to a table or globals are either way not deferred. I think this would make the implementation somewhat easier without paying any extra cost in most languages right now.

Using atomic reference counts and marking externrefs `Sync` and `Send` would allow us to share them between instances on different threads and simplifying our current implementation in many cases.

This is something I **really** would love to see supported.

**Comment by Hywan** [comment]
Closed by https://github.com/wasmerio/wasmer/pull/2092.
