### ISSUE TITLE
`emscripten unexpected dynamic_base 0` when trying to run a wasm file.

### ISSUE THREAD

**Issue by krasi-georgiev** [wasmerio/wasmer#1898]
Files to reproduce are attached.

```sh
wasmer 1.0.0-beta1  | x86_64
```

### Steps to reproduce
```
wasmer edge-impulse-standalone.wasm

error: failed to run `edge-impulse-standalone.wasm`
╰─> 1: emscripten unexpected dynamic_base 0
```

Expected to provide some more descriptive error or to just run the web assembly.

Running the same with `node` works as expected
you can try it with `./wasm-node.sh ` from the attached archive.
[files.zip](https://github.com/wasmerio/wasmer/files/5655767/files.zip)

**Comment by krasi-georgiev** [comment]
I am pretty sure I am not calling the command correctly so some pointers where to look for a solution would be appreciated.

**Comment by syrusakbary** [comment]
I think the Wasmer emscripten integration is outdated in respect to the generated emscripten wasm file.

Probably a fix will be in the [wasmer emscripten](https://github.com/wasmerio/wasmer/tree/master/lib/emscripten) integration itself. Have you tried compiling your project with WASI?

**Comment by krasi-georgiev** [comment]
Thanks for the prompt suggestion. I was given this file by a third party so don't have access to the source but will pass along the details.

Can you give an example command to run to compile it to a format that Wasmer will understand?

I looked at the link from your comment, but can't quite understand how to actually run the compile command.

And also what is WASI?

**Comment by krasi-georgiev** [comment]
did you mean to try and convert `wasm` to `wat` by using this?
https://nodejs.org/api/wasi.html

**Comment by syrusakbary** [comment]
Not exactly. I meant generating the final wasm file with the WASI toolchain instead of the emscripten one.

**Comment by krasi-georgiev** [comment]
Unfortunately, I don't have the source `wat` file but will pass along the details and see what the team that provided the wasm file can do about it.

**Comment by ioanfesteu** [comment]
I have encountered the same error. The file `edge-impulse-standalone.wasm` is generated by a web application which can be found at www.edgeimpulse.com. Same file name, different project. I provided a similar wasm and also the source code may be this helps until @krasi-georgiev can provide his source code.
[audio-classifier-wasm.zip](https://github.com/wasmerio/wasmer/files/5794380/audio-classifier-wasm.zip)
[audio-classifier-cpp.zip](https://github.com/wasmerio/wasmer/files/5794381/audio-classifier-cpp.zip)

**Comment by LordMZTE** [comment]
I am getting this issue following the steps on [the rust cli app example](https://github.com/wasmerio/rust-cli-app-example)

**Comment by jcaesar** [comment]
Could this issue be reopened? It still very much exists.

To reproduce, I just tried to compile https://github.com/wasmerio/rust-cli-app-example with Rust 1.47 and emscripten 1.39.20 (Finding a working combination is black magic), running it with wasmer 2.0.0.

Result:
```
$ wasmer run wasm-target/wasm32-unknown-emscripten/release/rust_cli_app_example.wasm
error: failed to run `wasm-target/wasm32-unknown-emscripten/release/rust_cli_app_example.wasm`
╰─> 1: emscripten unexpected dynamic_base 0
```

Quick docker example of the environment setup I use: [waskid.sh](https://github.com/wasmerio/wasmer/files/6823659/waskid.sh.txt)

**Comment by zackangelo** [comment]
The problem appears to be that Emscripten removed this metadata from its output, so any WASM artifacts compiled after this change was made will not work (see https://github.com/emscripten-core/emscripten/pull/12057).
