### ISSUE TITLE
macOS + singlepass skip trap information

### ISSUE THREAD

**Issue by syrusakbary** [wasmerio/wasmer#1899]
### Describe the bug

Following from #1856, we identified that in macOS the traps are not mapped properly when using the singlepass compiler.

```
➜  wasmer git:(master) ✗ cargo run  --manifest-path lib/cli/Cargo.toml --features singlepass -- run --singlepass ~/x.wat
    Finished dev [unoptimized + debuginfo] target(s) in 0.47s
     Running `target/debug/wasmer run --singlepass /Users/syrusakbary/x.wat`
error: failed to run `/Users/syrusakbary/x.wat`
│   1: RuntimeError: unreachable
╰─> 2: unreachable
```

It seems that, for some reason the program counters are not accurate, or we are not retrieving them properly.

This is mainly caused because when calling `lookup_frame_info`, the function returns early

```rust
    pub fn lookup_frame_info(&self, pc: usize) -> Option<FrameInfo> {
        let module = self.module_info(pc)?;  // <---- Returns here, as doesn't find any module with that pc
        let func = module.function_info(pc)?;
```

**Comment by syrusakbary** [comment]
I believe this was solved by https://github.com/wasmerio/wasmer/pull/2836 ? @ptitSeb could you give more insight to see if this is already solved?

**Comment by heyjdp** [comment]
@ptitSeb Please make a test case for this issue so that we can close it

**Comment by ptitSeb** [comment]
@syrusakbary I need context, what is this `x.wat` file?
Trap handling is enable and working on Singlepass, on mac or elsewhere, with some limitation for now on aarch64 mac for the "backtrace", that is not consistant with the other platforms.
I'm unsure what this ticket is about

**Comment by syrusakbary** [comment]
We need to test that a start function that triggers a divide by zero triggers a DivideByZero (or similar error) from Wasmer, but not an `unreachable`
