### ISSUE TITLE
Allow users to handle metering errors

### ISSUE THREAD

**Issue by webmaster128** [wasmerio/wasmer#1931]
### Motivation

It would be good to be able to differentiate _out of gas_ `Metering` errors from other runtime errors. Right now you get

```
RuntimeError { source: Trap(UnreachableCodeReached), wasm_trace: [FrameInfo { module_name: "<module>", func_index: 0, function_name: Some("add_one_f"), func_start: SourceLoc(37), instr: SourceLoc(44) }], native_trace:    0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
 }
```

when adding this error debugger to the metering example:

```diff
diff --git a/examples/metering.rs b/examples/metering.rs
index ed588dda3..ea6a9e556 100644
--- a/examples/metering.rs
+++ b/examples/metering.rs
@@ -131,8 +131,11 @@ fn main() -> anyhow::Result<()> {
                 result
             );
         }
-        Err(_) => {
-            println!("Calling `add_one` failed: not enough gas points remaining.");
+        Err(err) => {
+            println!(
+                "Calling `add_one` failed: not enough gas points remaining: {:?}",
+                err
+            );
         }
     }
```

So it does not seems to be possible to differentiate point depletion from other traps and panics.

### Proposed solution

Unfortunately I don't know how to implement.

### Alternatives

?

### Additional context

I'm trying to re-enable metering after upgrading from Wasmer 0.17 to master.

**Comment by nlewycky** [comment]
The middleware can only do what normal wasm can do, which includes the same kinds of trap that non-metering wasm could contain. Can you tell it's a out-of-gas by querying `Metering::get_remaining_points()`? Is that good enough?

**Comment by webmaster128** [comment]
> Can you tell it's a out-of-gas by querying `Metering::get_remaining_points()`? Is that good enough?

Maybe, can try. For this to work all remaining points must be set to 0 in case of a gas depletion (which is probably desired anyways since you don't want guests to double spend their points). The [current behaviour is different](https://github.com/wasmerio/wasmer/blob/22c7bc8e19de54090f3f0a2197ad62c4a5b72c95/examples/metering.rs#L139-L142).

If runtime error + zero points left is interpreted as _out of gas_, you cannot differentiate traps that fully consume all available gas and not more.

**Comment by webmaster128** [comment]
> If runtime error + zero points left is interpreted as _out of gas_, you cannot differentiate traps that fully consume all available gas and not more.

This was better in 0.17 where gas used could exceed the limit. Then you could differentiate between all used or exceeded. Maybe we can change those points to signed 64 bit numbers and allow running into the negative?

**Comment by webmaster128** [comment]
If the metering middleware can write the remainign limit to a host-only global, can't we do the same for an error code in the code that stops the execution?

```rust
                if self.accumulated_cost > 0 {
                    state.extend(&[
                        // if unsigned(globals[remaining_points_index]) < unsigned(self.accumulated_cost) { throw(); }
                        Operator::GlobalGet { global_index: self.remaining_points_index.as_u32() },
                        Operator::I64Const { value: self.accumulated_cost as i64 },
                        Operator::I64LtU,
                        Operator::If { ty: WpTypeOrFuncType::Type(WpType::EmptyBlockType) },
                        Operator::Unreachable, // FIXME: Signal the error properly.
                        Operator::End,
```

**Comment by jubianchi** [comment]
@webmaster128 I think this is something we can explore.

After talking with @nlewycky I tried to figure out how to make Metering errors clear. I'll try to propose something around what you suggested.

**Comment by webmaster128** [comment]
Done in https://github.com/wasmerio/wasmer/pull/1951. When calling into Wasm, you can not use `wasmer_middlewares::metering::get_remaining_points` on a `RuntimeError` to detect if execution was terminated due to exhausted points.

https://github.com/CosmWasm/cosmwasm/pull/676/commits/752a3efec25de949df017588e79d6fd64cc1d2c7#diff-4f1a2ed5fb41c5926988ad2983d537e181b0a2fbb38c1a3252987809bbb23e1cR149-R152 shows how we do this.
