### ISSUE TITLE
How to objdump to get the assembly code

### ISSUE THREAD

**Issue by ZW007** [wasmerio/wasmer#1940]
### Can I get the assembly code generated from wasmer?

What I found is  **wasmer compile a.wasm -o a.wjit** command, but I dont know how to objdump such a wjit file. I like to get the assembly code. 

Also, It would be nicer if there are any convenient ways to locate a specific assembly snippet of my target function. 

Thank you for your help!

**Comment by nlewycky** [comment]
The `.wjit` files are serde formatted `SerializableModule` objects in https://docs.rs/wasmer-engine-jit/1.0.0-beta1/wasmer_engine_jit/struct.JITArtifact.html . No other tools besides wasmer knows how to read them.

You can always get `objdump` to dump something by attempting to decode all bytes. For example:
```
tail -c +12 a.wjit > a.raw
objdump -b binary -m i386:x86-64 -D a.raw
```
will dump tons of junk like
```
 198:   2f                      (bad)  
 199:   68 6f 6d 65 2f          pushq  $0x2f656d6f
 19e:   6e                      outsb  %ds:(%rsi),(%dx)
 19f:   69 63 68 6f 6c 61 73    imul   $0x73616c6f,0x68(%rbx),%esp
 1a6:   2f                      (bad)  
```
but also some real instructions like:
```
  d7:   48 89 e5                mov    %rsp,%rbp
  da:   40 ff d6                rex callq *%rsi
  dd:   40 5d                   rex pop %rbp
  df:   c3                      retq   
```
which you'll have to identify by eye.

The other option is to not go through `.wjit` files in the first place. If you can use another engine such as `--native` then you can get a `.o` or `.so` file that your native system `objdump` can handle:
```
$ wasmer compile --native a.wasm -o a.so
Engine: native
Compiler: cranelift
Target: x86_64-unknown-linux-gnu
✔ File compiled successfully to `a.so`.
```
This is the preferred method unless you're actively looking into differences in assembly between engine-jit and engine-native.

**Comment by ZW007** [comment]
@nlewycky Thank you so much! 

I would like to get the exact assembly code when I run **wasmer run a.wasm**. I think the wasmer run generates the assembly code in a JIT way, so I should use compile --jit to get the same assembly code right?

You said the .wjit file is actually a wasm module, SerializableModule, so when I run wasmer run a.wasm, the wasm is first being compiled to SerializableModule, then the module will be instantiated, right? The instantiation process won't change the assembly code already generate (modify, add, delete) , right?

**Comment by nlewycky** [comment]
Instantiation with engine-jit does change the assembly! A `.wjit` contains [relocations](https://docs.rs/wasmer-compiler/1.0.0-beta1/wasmer_compiler/struct.Relocation.html) similar to an object file. To load a `.wjit`, engine-jit fills in the addresses of functions and global variables by writing the addresses into the instruction stream as instructed to by those relocations. This is similar to what a [native program linker does when linking](https://www.airs.com/blog/archives/43). The result will be a slightly different instruction stream each time as ASLR causes the addresses to be different. The only way to get an exact dump of the contents would be to modify wasmer to dump the raw binary from CodeMemory or use a debugger to view the instruction memory.

But it's not different in interesting ways. Similarly with using engine-jit vs. engine-native, they both send the same code through the same compilers, the difference is that engine-native enables position independent code (like `-fPIC` to clang or gcc) while engine-jit doesn't. Because singlepass doesn't support PIC we don't support --singlepass and --native together, and that's the case you'd need to pull the assembly out of a `.wjit` file, otherwise you can rely on engine-native here.

**Comment by ZW007** [comment]
Thanks a lot!!~ @nlewycky  Could I ask more?

What I want to dump is a single wasm file that does matrix multiplication, no library or shared object needed: just want to look how cranelift JITs assembly code in terms of this matrix multiplication function. So maybe I can believe --native? but does not --native generates garbage code? 

Reading assembly is not pleaseant (   but I think I only need to look the  `objdump -d --section=.text mulWasmerNative.so ` then locate my multiplication function inside it, right? 

Your` objdump -m i386:x86-64` is a bit confused to me, I am using Linux on x86-64, so do I have to add `-m i386:x86-64`?

Use ` objdump -h mulWasmerNative.so  ` I got many sections other than .data and .text, such as .note.gnu.build-id, .gnu.hash, .dynsym. Do I need to care about then :(
 
I am trying to make a comparison between the assembly generated by wasmer, wasmtime, lucet, and maybe wavm. In wasmtime, I can use `wasmtime wasm2obj mul.wasm mulWasmtime.o`, then I can dump mulWasmtime.o. In lucet, since it is AOT, there is .so generated by lucetc, so I can directly dump. In wavm, I can directly get assembly by ` wavm compile --format=assembly mul.wasm mulWavm.asm`, but not sure if should use `--format=assembly` or `--format=object ` Using object seems to be more reasonable because it mimics the way how wavm executes my wasm file? https://github.com/WAVM/WAVM/issues/299

Do you think the way I am doing this comparison is correct? do they generate garbage code as well?

**Comment by nlewycky** [comment]
> So maybe I can believe --native? but does not --native generates garbage code?

Both `--native` and `--jit` simply ask the compiler to generate the code. The differences are that native sets ["enable_pic"](https://docs.wasmtime.dev/api/src/cranelift_codegen_meta/shared/settings.rs.html#63-70) which will change function calls a bit, and native emits a `.so` on disk for `dlopen` to load later, while JIT applies all the relocations itself to run the program in memory.

Cranelift isn't really intended for max performance code but for fast compile times, I wouldn't expect it to output high performance code for matrix multiply. Using `--llvm` with wasmer should generate much faster code!

> Your objdump -m i386:x86-64 is a bit confused to me, I am using Linux on x86-64, so do I have to add -m i386:x86-64?

An ELF binary header specifies what machine the binary is for. If you give objdump a `.wjit` file there's no way for it to know, so you must tell it. `objdump` won't assume the assembly is for your native system.

> Use objdump -h mulWasmerNative.so I got many sections other than .data and .text, such as .note.gnu.build-id, .gnu.hash, .dynsym. Do I need to care about then :(

Nope! You'll find those same sections on nearly any binary such as `/bin/ls` or `/lib/x86_64-linux-gnu/libc.so.6`. They don't contain instructions, `.gnu.hash` is a hashtable for fast symbol lookup (name to address), `.note.gnu.build-id` is part of a system for storing DWARF debug in separate files, etc. Focus on `.text` or sections whose names start with `.text`.

> Do you think the way I am doing this comparison is correct? do they generate garbage code as well?

That sounds fine to me. The only reason we got junk from `.wjit` files is that they contain all sorts of not-assembly data in it, because they are `serde` serialization format. The command-line I gave told objdump to read every single byte as if it was x86-64 instructions, but not all of them are.

If other tools emit assembly directly that should be fine, or if they emit ELF that objdump can read, that should be fine too.

**Comment by ZW007** [comment]
Thank you again! Now my concern is, for example in  https://github.com/WAVM/WAVM/issues/299  Using `--format=assembly` I directly get assembly code which has less lines than using `--format=object` and then dumping .text section. I don't know which should I trust. 

Meanwhile, in wasmtime, I can use `wasmtime wasm2obj mul.wasm mulWasmtime.o`, then I can dump` mulWasmtime.o`. In lucet, since it is AOT, there is .so generated by lucetc, so I can directly dump .so. This is similar to wasmer --native .so file I guess.  

It looks like I am comparing .so(wasmer, lucet), .o(wasmtime) and .assembly/.o file (wavm), so I am not sure if such a comparison is fair and truly reflects how those runtimes execute a wasm file?  A .so file does not use direct address like .o, so maybe .so could generate more lines of assembly?

**Comment by ZW007** [comment]
@nlewycky Hello! Sorry for bothering you again. May I ask if there is a way to get the compiling time when I run, `wasmer run a.wasm`. (1) I think I can use the timestamp at the beginning and end of my C code, but if wasmer compiling my wasm file in a JIT way, that is compiling is done during the execution stage, then the timestamp isn't a correct solution. (2) If it is JITed, I think I can still solve a system linear equation by executing the same code twice in a for loop(  Tc + Te = a, Tc + 2Te = b;  Solve it and get Tc.

**Comment by nlewycky** [comment]
The "engine-jit" in Wasmer doesn't yet do compilation during execution, for now it compiles the whole wasm module into code first and then starts execution second. We reserve the right to change that in the future (it is named "JIT" after all!) but so far you should be able to look at the compilation time either by timing the library call to Module::compile or with the CLI by checking when wasmer started and looking at when the cached .wjit file was created. Happy new year!

**Comment by ZW007** [comment]
@nlewycky  I see. Would you please give me some link where I can refer to the methods (Module::compile or with the CLI) you mentioned?  And do you know if wasmtime and wavm also do compilation before execution?

**Comment by nlewycky** [comment]
Module::compile: https://docs.rs/wasmer/1.0.0-rc1/wasmer/trait.Engine.html#tymethod.compile

I know wavm does compilation ahead of time. I'm confident but not quite as certain that wasmtime does the same.

**Comment by ZW007** [comment]
@nlewycky Hi Sir! I don't even know your name. May I ask what do you think the wasmer based serverless would look like? I want to measure that though I don't plan to build a serverless prototype. I can use multi-threads according to the user requests number and those threads share the same wasm module instantiation. Do you think is this reasonable? Wasmer can be embedded into C and I know a little about multithreading. 

Also, I am measuring the memory consumption of wasmer, but using CLI in terminal to execute a standalone wasmer module, I found the memory consumption does not change much over the scientific functions I tested (matrix etc), all around 0.9 MB. I think most of the consumption is the inherent overhead of a wasmer CLI process rather than my function. What do you think could be a better idea of testing memory.

**Comment by nlewycky** [comment]
Hi! Sorry, I was out on vacation!

> May I ask what do you think the wasmer based serverless would look like?

That's a big question! I'm not sure which part to focus on, so I'll try to cover two different issues briefly and you can ask more specific questions if you like. Shopify chose to use Wasm to run customer provided Wasm as part of store rendering, and I expect that's a pattern we'll see repeated elsewhere: https://shopify.engineering/shopify-webassembly .

Building a "runs your WebAssembly" service out of Wasmer doesn't seem like it would be too hard from a Wasmer API point of view. You have to solve where you run Wasmer and what your accounting looks like, how you receive the code that your service run, what APIs are available to that running code, what additional services you provide (caching of wasm executions? distributed filesystem between multiple nodes?), etc. But assuming you solve those issues, compiling and running wasm using Wasmer as a library is demoed in examples/hello_world.rs.

> I can use multi-threads according to the user requests number and those threads share the same wasm module instantiation.

Instances are not inherently thread-safe, they may contain global state such as the linear memory and global variables if those were specified in the wasm. It may be safe to run two functions on the same instance in a multiple threads if the functions are thread-safe, but if they aren't then you get race conditions.

Wasmer has an internal concept called an Artifact which is part of the engine. We build one artifact per module which contains the read-only state like function bodies, and instances hold a reference to one shared artifact. With that, multiple instantiations don't require recompiling.

> Also, I am measuring the memory consumption of wasmer, but using CLI in terminal to execute a standalone wasmer module, I found the memory consumption does not change much over the scientific functions I tested (matrix etc), all around 0.9 MB.

Possibly! I haven't done any memory profiling of wasmer myself. I would recommend using wasmer as a library and see what takes up memory, starting with the examples in the examples directory.

**Comment by ZW007** [comment]
@nlewycky Thank you! (1)So to build a wasmer based FaaS,  `You have to solve where you run Wasmer and what your accounting looks like` You mean choosing a host such as rust or cpp right? I would like to dive into the wasm, but it looks like I will have to learn rust before that (

(2) I have been very confused about wasm safety mechanism, according to what you said, multi wasm threads still share variable so it may cause race condition and thus unsafe. but I heard many times about wasm's sandbox safety, but how is it safety in this regard. I already asked in stackoverflow, but no one answered yet [https://stackoverflow.com/questions/64763007/why-is-webassembly-safe-and-what-is-linear-memory-model](url)

(3) `We build one artifact per module which contains the read-only state like function bodies, and instances hold a reference to one shared artifact. With that, multiple instantiations don't require recompiling.`

Do you mean one artifact is like a compiled wasm module, but not instantiated, just like in JS environment, compile and instantiate are two consecutive steps [https://developer.mozilla.org/en-US/docs/WebAssembly/Loading_and_running](url) 

but If yes, how do multiple instantiations exist in the host, are they separate process because multithreading is not safe?

**Comment by nlewycky** [comment]
You're welcome! I hope you continue to find the discussion helpful!

(1) I was thinking more about setting up a cloud provider to run on, a system for having your users create accounts and maybe set up billing to pay you for running their Wasm, a mechanism to handle abuse, and so on. Running a service requires all that sort of operations work.

I hope you don't mind, but I'm going to decline to design an entire FaaS cloud system in a github issue. :smile:

(2) I replied on StackOverflow.

Let's suppose you have some data that has a range of only 0..100 are valid numbers. What if you run some untrusted WebAssembly code that writes 234 instead? To be secure, the host code has to be prepared to handle reading this invalid value. If the Wasm code can trick the host into doing something like writing off the end of the buffer, it could break the security of your program without ever breaking the security of WebAssembly sandbox itself.

The situation is the same for racy memory access. If you want to run hostile WebAssembly code, that code may be doing arbitrary writes to its linear memory, either using atomic or non-atomic operations. You can safely read the memory after the WebAssembly execution on that thread is stopped. If you're writing in a programming language where a racy read is undefined behaviour, then this is one way a Wasm program can trick the host program to break security without breaking the Wasm sandbox. You could wait for the execution of the Wasm code to finish before accessing the memory.

(3) Yes, just like that. We don't use separate processes. Each Instance is more or less just a struct containing enough memory to store the globals and memory and tables for that particular instance, plus a pointer to the Artifact holding copies of the shared readonly parts (such as the compiled function bodies).

**Comment by ZW007** [comment]
@nlewycky Thanks for the clarification! That makes sense but I am still a bit confused, I know my questions may not be reasonable, sorry 

(1) In JS host, wasm is provided with a linear memory that I know can be used for the interaction between the js host and wasm (passing value back and forth), is this also the case for other hosts such as C or Rust? 

(2) it looks like wasm can do more than that with the linear memory. `WebAssembly offers load and store instructions to manipulate bytes in this array`, so I wonder when could such a load/store be generated? I use clang to get the wasm code which does contain many loads/stores, but which types of C/C++ code could generate corresponding load/store?

(3) Wasm is stack code (use no register) but it will finally be compiled into machine code (register operation) during the execution. `There is no instruction pointer you can move (there are no registers at all in WebAssembly). You can never have a pointer to the stack` Say I have C code which uses pointers to manipulate the program memory area, when the C code compiled into wasm, I still don't get how does it eliminate instruction pointer move. Is this what you mean by `WebAssembly does not protect against problems inside the sandbox. ` ? Back to the linear memory confusion, when my wasm code gets executed, where is my wasm program stack? Is this program stack the same stack with my host code program stack or are they separated? I don't think the wasm program stack locates in the above-mentioned linear memory because a simple wasm module does not require us to import a linear memory before execution. 

(4) `We don't use separate processes. Each Instance is more or less just a struct containing enough memory to store the globals and memory and tables for that particular instance, plus a pointer to the Artifact holding copies of the shared read only parts (such as the compiled function bodies).` Can I say you will use multi-threads to execute multi instances? but since those instances have separate memory, race conditions can be avoided. 

(5) `Each Instance is more or less just a struct containing enough memory to store the globals and memory and tables for that particular instance` Here again is the memory confusion(, is this memory the linear memory of wasm? I found the wasm design doc says `In the MVP, linear memory cannot be shared between threads of execution.` Here it means multi-thread wasm code itself rather than executing multi instances within multi host threads, right? According to my search, multi-threading is not supported in the current wasm.

I apologize for the lengthy questions.
