### ISSUE TITLE
Reusing an Artifact (JIT) in multiple instances leads to crashes

### ISSUE THREAD

**Issue by webmaster128** [wasmerio/wasmer#1943]
### Summary

For caching purposes, I'd like to store and reuse artifact for multiple instances. An artifact from cache is combined with a new `Store` to make a `Module` which is then instantiated. This works fine if I cache serialized versions of the artifact. However, it would be very nice to avoid this serialization/deserialization for in-memory artifact caching.

With the help of [this API adjustment](https://github.com/wasmerio/wasmer/compare/master...webmaster128:module-from-artifact), I implemented a cache for `Arc<dyn Artifact>`: https://github.com/CosmWasm/cosmwasm/pull/666. This works fine until the test `use_multiple_cached_instances_of_same_contract` somes in, which creates and executes multiple instances of the same artifact. Then it crashes with a `(signal: 11, SIGSEGV: invalid memory reference)` on Linux (CI and locally) and errors with `RuntimeError: out of bounds memory access` on a the Mac.

Now the real question: is instantiating an Artifact multiple times supported? Is this a bug or am I missing something here?

### Additional details

–

**Comment by syrusakbary** [comment]
> Now the real question: is instantiating an Artifact multiple times supported? Is this a bug or am I missing something here?

It should be theoretically possible to instantiate an artifact multiple times. However, the `Artifact` struct is only intended to be used by the engines.
Your API might have uncovered other bug, we'll take a look into it. Thanks for reporting it!

**Comment by webmaster128** [comment]
> However, the `Artifact` struct is only intended to be used by the engines.

I only operated on `Arc<dyn Artifact>`s, i.e. the trait. The only two methods I used are `module.artifact()` and `Module::from_artifact`, so I did not try to do anything super-internal.

**Comment by webmaster128** [comment]
I dug into this a little bit more. After refining the tests on my side, it turned out the issue also comes up with a single instance after caching. It happens **when a module is instantiated from an artifact after the original store dropped**. In https://github.com/wasmerio/wasmer/pull/1974 a minimal test case is shown to reproduce the issue. As far as I can tell the behaviour is the same for JIT and Native.

**Comment by Hywan** [comment]
I've dug into this.

A `Module` compiles a `dyn Artifact`. The artifact concept belongs to the engine. For example, for the JIT engine, we have `JITArtifact`.

An artifact is responsible to construct an `Instance`. Thus, it is possible to build several `Instance`s from the same `dyn Artifact`.

However, it is _not_ possible to build several `Module`s from the same `dyn Artifact`. Rephrasing it with the JIT engine: It is _not_ possible to build back a `Module` from `JITArtifact`.

I think the confusion comes from the fact that we have `Module::from_artifact`, which is misleading. I agree that `Module::from_artifact` doesn't have enough protection, but it's an internal method (also, I don't see how it would be possible to add more protections… that's complex).

The only way to build a `Module` back from an `Artifact` is by using the serialization API.

So to conclude, I believe it's not a bug. It's just incorrect to build a `Module` back from a `dyn Artifact` directly. It's something that is impossible and you should not try to :-).

The bug spotted by https://github.com/wasmerio/wasmer/pull/1974 is not about the `Store` being dropped: It's about the `Engine` being dropped.

If you change the test by the following one:

```rs
    #[test]
    fn from_artifact_works_when_original_store_drops() {
        // Create artifact
        let engine = JIT::new(Cranelift::default()).engine();
        let artifact: Arc<dyn Artifact> = {
            // Compile module
            let compile_time_store = Store::new(&engine);
            let original_module = Module::new(&compile_time_store, INCREMENTER_WAT).unwrap();

            // Ensure original module can be executed
            {
                let instance = Instance::new(&original_module, &ImportObject::new()).unwrap();
                let add_one = instance.exports.get_function("add_one").unwrap();
                let result = add_one.call(&[42.into()]).unwrap();
                assert_eq!(result[0].unwrap_i32(), 43);
            }

            Arc::clone(original_module.artifact())
        };

        let run_time_store = Store::new(&JIT::headless().engine());
        let restored = Module::from_artifact(&run_time_store, artifact);

        // Ensure restored module can be executed
        {
            let instance = Instance::new(&restored, &ImportObject::new()).unwrap();
            let add_one = instance.exports.get_function("add_one").unwrap();
            let result = add_one.call(&[42.into()]).unwrap();
            assert_eq!(result[0].unwrap_i32(), 43);
        }
    }
```

It will work. That's not related to the `Store`, but the `Engine`. Here, the `Engine` lives long enough. ⚠️ Also, this is an incorrect usage of the internal API! `Module::from_artifact` must not be used to build back a `Module` from an `Artifact`.

At best, we can say that it should not be possible to drop `Engine`, or dropping `Engine` should not lead to a bug, I agree on that. But using `Module::from_artifact` with a different `Store` than the original one used to create the `Artifact` is wrong/incorrect. I'll try to come with a PR to solve that.

In your first comment, you said:

> An artifact from cache is combined with a new Store to make a Module which is then instantiated. This works fine if I cache serialized versions of the artifact. However, it would be very nice to avoid this serialization/deserialization for in-memory artifact caching.

The only way to cache an artifact is by serializing it. The only way to re-use an artifact with a different store is by serializing it too :-).

**Comment by Hywan** [comment]
Sequel of my comment above. The “bug” appears because of 2 things:

1. Calling `Module.artifact()`, which allows to extract the `Artifact`, disconnecting it from its `Module`,
2. Calling `Module::from_artifact`, which is private.

`Module.artifact()` is `pub` only as a hack for the `wasmer-engine-object-file` feature. `Module::from_artifact` is private.

If you respect the API and don't hack it, the bug isn't possible to reproduce. I'll try to come with a PR to avoid doing such things.

**Comment by webmaster128** [comment]
Thank you for looking into this and the detailed explanation. This all makes sense.

This came up from the idea that _Module = Artifact + Store_ and it could potentially be possible to re-use one Artifact with a different store. See also https://github.com/wasmerio/wasmer/issues/1933 for the API discussion and motivation.

> But using `Module::from_artifact` with a different `Store` than the original one used to create the `Artifact` is wrong/incorrect. I'll try to come with a PR to solve that.

Alright. No need for changes here as `from_artifact` is private and I had to make it public in oder to produce the behaviour.

I'm closing this ticket since this is the wrong direction, as you pointed out. What remains open to me is #1933 and the question of how to create an in-memory module cache that avoids the costy serialization/deserialization.

Thanks again
