### ISSUE TITLE
Memory leaks in LLVM compiler

### ISSUE THREAD

**Issue by MarkMcCaskey** [wasmerio/wasmer#1945]
Run
```
RUSTFLAGS="-Z sanitizer=leak" cargo +nightly test --features "cranelift singlepass" --features "test-cranelift test-jit" -- --test-threads=1
```

to get a report of memory leaks.

**Comment by Hywan** [comment]
Note that a majority (if not all) leaks are fixed by https://github.com/TheDan64/inkwell/pull/225/. We are waiting on a release, or we can use our own fork.

**Comment by MarkMcCaskey** [comment]
This seems to be resolved now
