### ISSUE TITLE
Error type of FunctionMiddleware::feed is private

### ISSUE THREAD

**Issue by webmaster128** [wasmerio/wasmer#1950]
### Describe the bug

The error type of the `FunctionMiddleware::feed` is `BinaryReaderError`:

```rust
use wasmparser::{BinaryReader, Operator, Result as WpResult, Type};

// …

/// A function middleware specialized for a single function.
pub trait FunctionMiddleware: Debug {
    /// Processes the given operator.
    fn feed<'a>(
        &mut self,
        operator: Operator<'a>,
        state: &mut MiddlewareReaderState<'a>,
    ) -> WpResult<()> {
        state.push_operator(operator);
        Ok(())
    }
}
```

and

```rust
pub type Result<T, E = BinaryReaderError> = result::Result<T, E>;
```

However, `BinaryReaderError` is a type in the `wasmparser` crate with no public constructor. So if I understand correctly, a user of Wasmer cannot implement a `FunctionMiddleware` that errors.

### Steps to reproduce

–

### Expected behavior

The error type is either constructible or can be defined by the user ([as in Wasmer 0.17](https://github.com/wasmerio/wasmer/blob/0.17.1/lib/runtime-core/src/codegen.rs#L430-L431)). 

### Actual behavior

The error type is fixed to `wasmparser::BinaryReaderError`, which is not constructible.

### Additional context

I'm trying rewrite a the `Deterministic` middleware, orginally created here: https://github.com/spacemeshos/svm/blob/5df80288c8b9a5ab3665297251c283cb614ebb81/crates/svm-compiler/src/middleware/validation.rs.

**Comment by syrusakbary** [comment]
We should improve that, so middlewares can report errors!

Would you like to work on a PR for it @webmaster128 ?

**Comment by webmaster128** [comment]
I'm happy to help where I can. However, in this case I'm a bit clueless what a desired API would look like. I tried the associated error type from Wasmer 0.17, but this leads to all kind of new generic in the code that uses the middleware. So if I don't a brilliant idea magically, it would be cool if someone from the team could look into it.

**Comment by webmaster128** [comment]
Okay, I got some ideas now that I realized everthing is converted to WasmError at the end of the day.
