### ISSUE TITLE
`wasmer-c-api`'s documentation is broken on docs.rs

### ISSUE THREAD

**Issue by Hywan** [wasmerio/wasmer#1954]
The `wasmer-c-api`'s documentation can not be generated on docs.rs because of this:

https://docs.rs/crate/wasmer-c-api/1.0.0-beta2/builds/325937

```
[INFO] [stderr] error: failed to run custom build command for `wasmer-c-api v1.0.0-beta2 (/opt/rustwide/workdir)`
[INFO] [stderr] 
[INFO] [stderr] Caused by:
[INFO] [stderr]   process didn't exit successfully: `/opt/rustwide/target/debug/build/wasmer-c-api-e213afef7dae2643/build-script-build` (exit code: 101)
[INFO] [stderr]   --- stderr
[INFO] [stderr]   thread 'main' panicked at 'Unable to copy the generated C bindings: Os { code: 30, kind: Other, message: "Read-only file system" }', build.rs:124:14
[INFO] [stderr]   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It would be great to see how we could solve this.

**Comment by MarkMcCaskey** [comment]
This has been a long running issue for as long as we've generated header files with `build.rs` I believe...

Maybe we can do a diff in build.rs before ever writing to the file system?  That should at least fix it in this case.  Alternatively, we may want to avoid writing outside of the TARGET/BUILD directory at all in `build.rs` (it also breaks `cargo publish`...)
