### ISSUE TITLE
WasiState Should be a Valid WasiEnv

### ISSUE THREAD

**Issue by TheLostLambda** [wasmerio/wasmer#1973]
EDIT: Yikes, I was being silly! Please see the comment below!

Sorry this is a bit brief, if you need more information, please ask. I drafted a longer version of this issue that got deleted, so this is my second swing at things.

### Describe the bug

After PR #1810, I was able to pass the `WasiState` of the VM into host functions as an environment. This allowed me to write host functions that could read the stdout of the WASM module and pass data back and forth that way. Since the introduction of `WasmerEnv` in a subsequent PR, this use-case has been broken! I'm really struggling to find a work-around at the moment, as the stdout needs to be read when the host function is called, and references are proving challenging due to the mutex locking problem also outlined in #1810.

### Steps to reproduce

Attempt to pass `Arc<Mutex<WasiState>>` (from `wasi_env.state` in PR #1810) into `Function::new_native_with_env()` as the environment.

### Expected behavior

Host functions should be able to read the `WasiState` safely, as was possible before.

### Actual behavior

Code doesn't compile, as `WasmerEnv` is not implemented for `WasiState`.

### Additional context

[This code was previously functional in the alpha versions](https://github.com/mosaic-org/wasm-module-experiments/blob/4dda825458ed34ef2c515d827843edc6d91404f9/loader/src/main.rs#L48)

**Comment by TheLostLambda** [comment]
Yikes, okay, clearly I've just been a little silly! You've done me one better and made `WasiEnv` an implementer of `WasmerEnv`! After being a bit less silly, I've got something clean and functional (just cloning `WasiEnv` and passing that to the host function) – thank you for the thoughtful implementation of this!

The only reason I'm leaving this issue open is because we could now essentially revert #1810 if we wanted to. I'm now just using the `.state()` method instead of accessing the field, since I can pass the whole `WasiEnv` and don't need another Arc-Mutex wrapper.

I wish I could remove the "Bug" tag, as this really isn't a regression anymore, but I reckon if we want to make the `state` field private again, we should do that now (before stable 1.0). I don't mind leaving it public, but I certainly don't need it public anymore either :)

**Comment by Hywan** [comment]
I think the code is fine as is :-).
