### ISSUE TITLE
Makefile checks for LLVM 10, but documentation recommends LLVM 11.

### ISSUE THREAD

**Issue by TylerNowicki** [wasmerio/wasmer#1981]
The makefile performs this check at line 22

  ifneq (, $(findstring 10,$(LLVM_VERSION)))

But if we use LLVM 11 this will fail. Yet, documentation recommends LLVM 11

https://docs.wasmer.io/ecosystem/wasmer/building-from-source#llvm-compiler

The correct way to do this is to parse the major and minor versions and compare them separately.

See: https://stackoverflow.com/questions/3728372/version-number-comparison-inside-makefile

**Comment by syrusakbary** [comment]
Your comment is completely on point, @TylerNowicki!

We did the comparison that way because we initially only supported one version of LLVM.
Would you like to help us with a PR improving the Makefile?

**Comment by Hywan** [comment]
Actually, `wasmer-compiler-llvm` needs LLVM 10. We don't support LLVM 11 for the moment. It seems to be an error from the documentation, can you confirm @jubianchi @nlewycky please?

**Comment by TylerNowicki** [comment]
I noticed in the docs here
> https://github.com/wasmerio/wasmer/tree/master/lib/compiler-llvm
under Requirements "It currently requires LLVM 10."
