### ISSUE TITLE
LLVM 11.0.x isn't compatible？

### ISSUE THREAD

**Issue by ynliu-egoist** [wasmerio/wasmer#1984]
when executing  'make build-wasmer' to build runtime , only can find Available compilers include cranelift and singlepass.
i'm sure that LLVM 11.0.0 and environment variables are already in place，is there anything wrong with 11.0.0?

**Comment by Hywan** [comment]
We don't support LLVM 11 for the moment :-). We strictly require LLVM 10 for the moment.
