### ISSUE TITLE
Outdated Cargo.lock file?

### ISSUE THREAD

**Issue by carlocab** [wasmerio/wasmer#1986]
### Summary

wasmer is currently failing to build for Homebrew with Rust 1.49 on Apple Silicon: https://github.com/Homebrew/homebrew-core/pull/68089, https://github.com/Homebrew/homebrew-core/pull/68341, [CI logs](https://github.com/Homebrew/homebrew-core/pull/68341/checks?check_run_id=1651217079)

It appears this is due to a stale lock file, causing `cargo install --locked` to pull in dependencies that do not work for wasmer on Apple Silicon. Is it possible for the `Cargo.lock` file to be updated? If this could be done with a new release, that would be especially helpful.

### Additional details

Related: https://github.com/Homebrew/homebrew-core/issues/68301

**Comment by MarkMcCaskey** [comment]
Reopening because I don't know if this was actually fixed, we attempted to build Wasmer on aarch64-apple-darwin with Rust 1.49 and had no problems doing so locally. Additionally it worked in CI, is there something we're missing to be able to reproduce this issue?

**Comment by carlocab** [comment]
Yes, it does look like we're missing something... See in particular this comment: https://github.com/Homebrew/homebrew-core/pull/68341#issuecomment-755025861

And perhaps this one, though I really only say things I've said before in slightly different words. However, it may still clarify some things: https://github.com/Homebrew/homebrew-core/pull/68341#issuecomment-755030988

**Comment by ezfe** [comment]
Hey - When I run `cargo install --path .` on version 1.0.0 I get this error:

```
➜  wasmer git:(aa03cab26) cargo install --path .
error: specified package `wasmer-workspace v1.0.0 (/Users/ezekielelin/temp_dev/wasmer)` has no binaries
```

**Comment by carlocab** [comment]
But, I guess, to explain more fully here so you don't have to keep chasing links I share:

The reason I assumed it was a stale lock file was that wasmer builds (consistently) fail on our ARM runners. Our build script does nothing out of the ordinary, it just (essentially) runs

    cargo install --locked --root $PREFIX --path .

However, we discovered that if, instead, we ran

    cargo install --root $PREFIX --path .

then the build no longer fails.

Could something else cause this pattern of observations? That said, I don't know how to reconcile this with @ezfe's experience above.

**Comment by syrusakbary** [comment]
Oh, I think the command we have to run is in the wasmer-cli, not the workspace per se (I think this changed from `0.x` to `1.0`).

The command to run should be:

```bash
cargo install --path lib/cli
```

**Comment by ezfe** [comment]
That command does start the install process for me

```sh
error[E0432]: unresolved import `syn::export`
  --> /Users/ezekielelin/.cargo/registry/src/github.com-1ecc6299db9ec823/enumset_derive-0.5.0/src/lib.rs:10:10
   |
10 | use syn::export::Span;
   |          ^^^^^^ could not find `export` in `syn`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `enumset_derive`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `wasmer-cli v1.0.0 (/Users/ezekielelin/temp_dev/wasmer/lib/cli)`, intermediate artifacts can be found at `/Users/ezekielelin/temp_dev/wasmer/target`

Caused by:
  build failed
```

**Comment by syrusakbary** [comment]
Just saw the same error, it was caused because 5 hours ago when `syn` crate was updated to `1.0.58` (in semver it should be just a patch). However the API changed (breaking change), making private the access to some exports.

Since `enumset_derive` imports `Span` via `syn::export::Span`, now `enumset_derive` can't be built. Hence the error:

```
   Compiling enumset_derive v0.5.0error[E0432]: unresolved import `syn::export`
  --> /Users/syrus/.cargo/registry/src/github.com-1ecc6299db9ec823/enumset_derive-0.5.0/src/lib.rs:10:10
   |
10 | use syn::export::Span;
   |          ^^^^^^ could not find `export` in `syn`

error: aborting due to previous error
```

This is a major issue (since `syn` version should have been updated to `1.1.0` instead of `1.0.58`). However, this issue is unrelated to wasmer.
I was unable to open an issue in the syn repo. So I'll try to tag here @dtolnay with hopes he'll be able to see the issue.

Tagging also @Lymia as she is the owner of the `enumset` and she might be able to fix it on her library directly.

Right now all packages that depend on the `enumset` crate will break :(

**Comment by MarkMcCaskey** [comment]
Following up on this, what's the justification for homebrew updating locked deps? My understanding was that the intention of lockfiles was to provide a known, good set of dependency versions to allow binaries to continue to build and function as expected. It seems a bit strange to bypass the idea of the lockfile here.

Thanks for looking into this @syrusakbary! That's useful information. As a side, if you've run `cargo update` and want to get `syn` into a version that compiles, you can run `cargo update -p syn --precise 1.0.57`.  That'll keep all the updated dependencies except put `syn` one version back.

But updating outside of the wasmer tree means that those dependency versions in wasmer have not necessarily gone through our CI / testing process. So I wouldn't recommend, in general, updating locked dependencies before building and shipping binaries.

**Comment by carlocab** [comment]
Sorry, you must've misunderstood me (or perhaps I was unclear). We _don't_ update locked dependencies: our standard `cargo` builds pass the `--locked` flag to `cargo` to make sure the dependencies are pinned as in the lock file. This, however, only works if the lock file is correctly specified, and we've found a number of cases where they are not.

**Comment by MarkMcCaskey** [comment]
Oh okay! Sorry about the misunderstanding! I just assumed that's what was going on because of how I was able to reproduce it.

So I'm actually not familiar with the `--locked` flag, I've always assumed it would use the lockfile by default. Looking at the help text for `--locked`, raises further questions:
`--locked                    Require Cargo.lock is up to date`

I'm not completely clear on what that means, but that naively sounds like the opposite of what I would expect that flag to do.

**Comment by carlocab** [comment]
Yea, the docs here are a bit unclear too... but my understanding, based on lots of `cargo install`s (and also the experience of other Homebrew maintainers), is that passing the `--locked` flag to `cargo install` pins the dependencies according to `Cargo.lock`.

If you don't pass the `--locked` flag, then `cargo` uses the newest version available of each dependency. See these two threads for more discussion of this: https://github.com/Homebrew/homebrew-core/issues/46025, https://github.com/Homebrew/homebrew-core/pull/45839

**Comment by carlocab** [comment]
From `man cargo-install`:

```
By default, the Cargo.lock file that is included with the package will be ignored. This means that Cargo will
recompute which versions of dependencies to use, possibly using newer versions that have been released since
the package was published. The --locked flag can be used to force Cargo to use the packaged Cargo.lock file if
it is available. This may be useful for ensuring reproducible builds, to use the exact same set of
dependencies that were available when the package was published.
```

**Comment by MarkMcCaskey** [comment]
Fascinating, that sounds like there's no way to use lockfiles like I expected with `cargo install`. I suppose that's not an issue if no one ever breaks semver or uses undefined behavior but in practice it seems like things would break a lot...

Feels like I must be missing some important information about how to use lockfiles correctly, I'll look into it some more -- thanks!

**Comment by richiksc** [comment]
> Since `enumset_derive` imports `Span` via `syn::export::Span`, now `enumset_derive` can't be built. Hence the error:
> 
> ```
>    Compiling enumset_derive v0.5.0error[E0432]: unresolved import `syn::export`
>   --> /Users/syrus/.cargo/registry/src/github.com-1ecc6299db9ec823/enumset_derive-0.5.0/src/lib.rs:10:10
>    |
> 10 | use syn::export::Span;
>    |          ^^^^^^ could not find `export` in `syn`
> 
> error: aborting due to previous error
> ```
> 
> This is a major issue (since `syn` version should have been updated to `1.1.0` instead of `1.0.58`). However, this issue is unrelated to wasmer.

@syrusakbary @carlocab Regarding the `syn` issue, there is an open PR in the `enumset` repo, Lymia/enumset#18, that fixes this issue. There hasn't been any response from the maintainer, @Lymia, and there hasn't been any activity on the repo since August, but the author of the PR, @ocboogie, has a temporary patch fix you can add to `Cargo.toml`.

```
[patch.crates-io.enumset_derive]
git = "https://github.com/ocboogie/enumset"
branch = "span-fix" 
```

**Comment by MarkMcCaskey** [comment]
Unfortunately we won't be able to publish a new release with a git dependency (crates.io does not allow it last I checked, because git repos aren't guaranteed to stay online, etc.), so I don't think that solves the `cargo install` problem.

**Comment by richiksc** [comment]
Homebrew CI tests are failing not only on Big Sur ARM but also on 10.14 and 10.15 x86_64 macOS (x86_64 11.0 is pending), after sucessfully building with `cargo install --locked --path lib/cli`.

The failure output is this:

```
% wasmer run sum.wasm --invoke sum 1 2
error: failed to run `sum.wasm` (no compilers enabled)
│   1: module instantiation failed (engine: jit, compiler: headless)
╰─> 2: Validation error: The JITEngine is not compiled with compiler support, which is required for validating
```

On my local M1 MacBook, I tried generating a `sum.wasm` file by running a quick Ruby script with the `[...].pack('H*')` from the `test` block in the Homebrew formula and wrote it to a file. The version I built locally from `cargo install --locked --path lib/cli` came up with the same error:

```
% cargo install --locked --path lib/cli
[build succesful]
% wasmer run sum.wasm --invoke sum 1 2
error: failed to run `sum.wasm` (no compilers enabled)
│   1: module instantiation failed (engine: jit, compiler: headless)
╰─> 2: Validation error: The JITEngine is not compiled with compiler support, which is required for validating
```

I was thinking, maybe we are only building the CLI, and the Wasmer engine needs to be built separately as of 1.0.0.. The documentation for Wasmer says that to build wasmer from source you need to run `make build-wasmer`: https://docs.wasmer.io/ecosystem/wasmer/building-from-source#building-the-wasmer-runtime.

I tried compiling with that on my machine, and nope, same error.
```
% make build-wasmer
% wasmer run sum.wasm --invoke sum 1 2
error: failed to run `sum.wasm` (no compilers enabled)
│   1: module instantiation failed (engine: jit, compiler: headless)
╰─> 2: Validation error: The JITEngine is not compiled with compiler support, which is required for validating
```

I wanted to check one more thing to see if my generated `sum.wasm` was malformed, so I created a dead simple Rust program:

```rust
pub fn main() {}

#[no_mangle]
pub extern fn sum(a: i32, b: i32) -> i32 {
    a + b
}
```

and compiled it using `rustc --target wasm32-unknown-unknown`:

```
% rustup target add wasm32-unknown-unknown
% rustc --target wasm32-unknown-unknown -O sum.rs
% wasmer run sum.wasm --invoke sum 1 2
error: failed to run `sum.wasm` (no compilers enabled)
│   1: module instantiation failed (engine: jit, compiler: headless)
╰─> 2: Validation error: The JITEngine is not compiled with compiler support, which is required for validating
```

Same error.

**Comment by richiksc** [comment]
After looking through the `Makefile`, I was able to get it to build and run on my M1 local machine with this:

```
% cargo install --locked --path lib/cli --features "cranelift"
% wasmer run sum.wasm --invoke sum 1 2
3
```

🎉🎉🎉

Looks like as of Wasmer 1.0, you have to specify which compiler it should use. The default compiler, which is compatible with arm64 as well as being the one provided in their CI releases, is `cranelift`.

**Comment by carlocab** [comment]
Thanks to @richiksc for sorting out a working build of wasmer.

Though, now we need to work out what the correct options to use for the `--features` flag. Do you happen to have a recommended set, @MarkMcCaskey?

**Comment by richiksc** [comment]
We now have an official build and bottle of wasmer 1.0.0 on Homebrew. However, we still are building with just `--features "cranelift"`. If there's a recommended set of features we should use, we can add that, or instead, we can add a `install` task to the Makefile that uses the auto-detection logic to create the features list that it can then pass to `cargo install --locked`.

That's probably out of scope of this issue however, and given that the current Cargo.lock file builds succesfully with `locked` and we have a working build, including `arm64`, means that this issue should probably be closed.

**Comment by carlocab** [comment]
>this issue should probably be closed

I agree. Thanks for the help everyone!

**Comment by MarkMcCaskey** [comment]
> Thanks to @richiksc for sorting out a working build of wasmer.
> 
> Though, now we need to work out what the correct options to use for the `--features` flag. Do you happen to have a recommended set, @MarkMcCaskey?

Sorry about the delay, we detect features in the Makefile, so `make build-wasmer` should show what features should be enabled on a given platform: our releases ship with `cranelift`, `singlepass`, and `llvm` enabled on x86_64 macos and linux.
