### ISSUE TITLE
self-update in 1.0.0-beta1 thinks 1.0.0 is a lower version

### ISSUE THREAD

**Issue by SamuraiCrow** [wasmerio/wasmer#1987]
### Describe the bug

Typing "wasmer self-update" in the BASH prompt fails due to the Beta version thinking it's newer than the mainline release.  The "Are you sure?" prompt returns immediately to the command prompt without accepting input.

```sh
echo "`wasmer -V` | `rustc -V` | `uname -m`"
```

[samuraicrow@manjaro-pc ~]$ echo `wasmer -V`
wasmer 1.0.0-beta1
[samuraicrow@manjaro-pc ~]$ echo `rustc -V`
rustc 1.49.0 (e1884a8e3 2020-12-29)
[samuraicrow@manjaro-pc ~]$ echo `uname -m`
x86_64

### Steps to reproduce

type "wasmer self-update" at prompt

### Expected behavior

Update proceeds on wasmer.

### Actual behavior

Update asks "Current version is a higher version.  Are you sure you want to update?" and immediately exits to the BASH prompt without accepting any input.

### Additional context

Running latest Manjaro on x86_64 Intel with 16 GiB of RAM from an SSD.

**Comment by MarkMcCaskey** [comment]
Thanks for the heads up, we'll get a fix out soon

**Comment by SamuraiCrow** [comment]
Thanks!

**Comment by syrusakbary** [comment]
Meanwhile if you want to fix it manually you can run:

```bash
rm $(which wasmer)
curl https://get.wasmer.io -sSfL | sh
```

**Comment by MarkMcCaskey** [comment]
Actually, I'm not able to answer the y/n prompt when doing it via curl | sh 🤔 , either way, the fix was merged

**Comment by MarkMcCaskey** [comment]
Alright, it should be fixed now!
