### ISSUE TITLE
WAPM is missing in installer for Windows

### ISSUE THREAD

**Issue by reregaga** [wasmerio/wasmer#1988]
### Describe the bug
Written in the title.

`wasmer 1.0.0`
`rustc 1.48.0 (7eac88abb 2020-11-16)`

### Steps to reproduce
1. Read https://docs.wasmer.io/ecosystem/wapm/getting-started, see `WAPM comes bundled with Wasmer`
1. Go to https://github.com/wasmerio/wasmer/releases/tag/1.0.0
2. Download exe and install wasmer, or install wasmer with PowerShell `iwr https://win.wasmer.io -useb | iex`
2. Open cmd.exe, run `wasmer -V`, result: `wasmer 1.0.0`
3. Run `wapm`, see `'wapm' is not recognized as an internal or external command, operable program or batch file.` or in PowerShell `wapm : The term 'wapm' is not recognized as the name of a cmdlet, function, script file, or operable program.`
4. ...
5. Goto wapm repo https://github.com/wasmerio/wapm-cli and compile it from sources :(.
### Expected behavior
Wapm install with wasmer from wasmer.exe
### Additional context
Windows 10 Pro.

**Comment by qumeta** [comment]
can't find WAPM

**Comment by HUMORCE** [comment]
different from the docs, no **wapm** inside the package. 😂

**Comment by SamuraiCrow** [comment]
There are Windows installation insteuctions at [https://wapm.io/](https://wapm.io/) but it doesn't come bundled any more afaik.  There might be a documentation bug, however.
