### ISSUE TITLE
The `Cflags` emitted by `wasmer config --pkg-config` are wrong

### ISSUE THREAD

**Issue by helje5** [wasmerio/wasmer#1989]
### Describe the bug

When running `wasmer config`, the `-I` in the cflags are incorrect. The include path (`-I`) adds an additional `wasmer` to the end.

This is on BS macOS ARM, but I suppose it doesn't matter.

```sh
helge@M1ni ~ $ wasmer config --pkg-config
prefix=/Users/helge/.wasmer
exec_prefix=/Users/helge/.wasmer/bin
includedir=/Users/helge/.wasmer/include
libdir=/Users/helge/.wasmer/lib

Name: wasmer
Description: The Wasmer library for running WebAssembly
Version: 1.0.0
Cflags: -I/Users/helge/.wasmer/include/wasmer
Libs: -L/Users/helge/.wasmer/lib -lwasmer
```

### Steps to reproduce

1. run `wasmer config --pkg-config`

### Expected behavior

The cflags should be:
```
Cflags: -I/Users/helge/.wasmer/include
```

### Actual behavior

The cflags are:
```
Cflags: -I/Users/helge/.wasmer/include/wasmer
```

This directory does not exist.

**Comment by helje5** [comment]
Also: the libs miss the `-lffi`, which breaks static compiles. Should look like this:
```
Libs: -L/Users/helge/.wasmer/lib -lwasmer -lffi
```

**Comment by MarkMcCaskey** [comment]
I believe `-lffi` is only required if the `libwasmer` was built without statically linking `libffi`. I believe the default and the one we ship should not need `-lffi`. Are you using the `libwasmer` in the release or built with custom features?

**Comment by helje5** [comment]
`-lffi` is only required with the static lib, correct. It doesn't hurt though in the dynamic variant either.

This is the standard release, I didn't build anything on my own.

There is another issue here w/ M1 Macs, their libffi doesn't have `ffi_type_longdouble` function, but the static lib is referring them.
