### ISSUE TITLE
Wasmer hangs when running tools w/o arguments

### ISSUE THREAD

**Issue by helje5** [wasmerio/wasmer#1994]
### Describe the bug

Wasmer itself (and its C API) just hangs when invoking tools like `cowsay` or `fortune` w/o any arguments.

Example:
```sh
helge@M1ni ~ $ wapm install cowsay
[INFO] Installing _/cowsay@0.2.0
Package installed successfully to wapm_packages!
helge@M1ni ~ $ wapm run cowsay
^C
```
Hangs seemingly forever.

When passing arguments, it works:
```sh
helge@M1ni ~ $ wapm run cowsay h
 ___
< h >
 ---
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
               ||----w |
                ||     ||
```

This is not restricted to `cowsay`, e.g. the `fortune` example seems to have the same issue.

### Steps to reproduce

1. `wapm install cowsay`
2. `wapm run cowsay`

### Expected behavior

Cowsay prints something, maybe a help if an arg is required, or at least exists.

### Actual behavior

Instance hangs.

### Additional context

This is on macOS BS, both on Intel or M1.

**Comment by jubianchi** [comment]
Hello @helje5!

This is the expected behavior: when you don't provide any argument to `cowsay` it expects something on `STDIN`.

Two choices here:

```bash
echo Hello Wasmer | wapm run cowsay
```

or

```
wapm run cowsay
Hello Wasmer
^D
```

_`^D` means <kbd>CTRL</kbd>+<kbd>D</kbd>_

**Comment by helje5** [comment]
Uh, sorry. That works!

**Comment by Devonta55** [comment]
Sorry for what

**Comment by helje5** [comment]
Sorry for spamming the bug tracker with nonsense :-)

**Comment by Devonta55** [comment]
Lol you got joke you need to mind your business fr.
