### ISSUE TITLE
FFI (dlopen / dlsym)

### ISSUE THREAD

**Issue by brandonros** [wasmerio/wasmer#1995]
### Summary

https://github.com/WebAssembly/WASI/issues/84

If this can't be tackled at the WASI layer, could we add it as a non-standard feature of this runtime?

### Additional details

I think WebAssembly would get a lot more useful if it could call into existing .so / .dylib / .dll files. I know WebAssembly is big on security/sandboxing/permission, so this would obviously need to be behind some kind of "off by default" permission flag.

**Comment by brandonros** [comment]
A really common FFI usecase that I run into frequently is J2534.

> SAE J2534 is a standard for communications between a computer and a vehicle.

I have many J2534 .DLL files that describe how a USB device (like a vehicle communication interface) communicates. If I could call into the functions they expose with wasmer, it would open a whole new world of features.

Example: https://github.com/joeyoravec/j2534-logger/blob/master/ptshim32/j2534_v0404.h#L452-L465

**Comment by syrusakbary** [comment]
I personally think it should be easy to achieve, specially we restrict the "dll" to be other wasm files. Would that make sense for your use case @brandonros ?

**Comment by brandonros** [comment]
@syrusakbary 


```
typedef long (J2534_API* PTOPEN)(void *pName, unsigned long *pDeviceID)
PTOPEN PassThruOpen;
HINSTANCE hDLL;
hDLL = LoadLibrary(DllLibraryPath);
PassThruOpen = (PTOPEN)(GetProcAddress(hDLL, "PassThruOpen"));
```

That is how J2534 is commonly used in C. Could you see that working in wasmer one way or another?

**Comment by MarkMcCaskey** [comment]
I don't think we can support Wasm loading arbitrary native code in general without that being some sort of opt-in thing. The reason being that it completely breaks the sandbox and reduces portability.

A related, but not quite the same thing, would be doing dlopen at the wasmer / VM level itself. Allowing users to expose native functionality to any Wasm program by creating an import object that has functions that would call into the functions in a dll. That seems like a nice way to make wasmer extensible to any kind of ABI by allowing ABIs to be written as plugins.

**Comment by brandonros** [comment]
> cross-platform

Windows / Mac / Linux all have dlsym/dlopen or equivalent.

**Comment by hanwenlei** [comment]
Any conclusions from this discussion? FFI is supported by many languages, such as JNI of Java. I wonder why WebAssembly doesn't support loading arbitrary native code.
