### ISSUE TITLE
Adding C/C++ example for exposing host (imported) function, pls

### ISSUE THREAD

**Issue by diceangel20** [wasmerio/wasmer#2022]
Hi,

Congrats on your new 1.0 version.

Could you please add up an example for exposing host (imported) function in C/C++?
https://docs.wasmer.io/integrations/examples/host-functions

Thanks in advance.
A supporter.

**Comment by diceangel20** [comment]
And, same request for this one:
https://docs.wasmer.io/integrations/examples/memory-pointers

**Comment by Hywan** [comment]
Thanks for the request. Sure we can do that. Until we do that, you have examples here: https://github.com/wasmerio/wasmer/blob/c48fddeff612457bfc7c9e30d812560fc601eada/lib/c-api/examples/imports-exports.c and https://github.com/wasmerio/wasmer/blob/c48fddeff612457bfc7c9e30d812560fc601eada/lib/c-api/examples/memory.c. Hope it helps!

**Comment by diceangel20** [comment]
Any timing for this update? Or you need some help? if so, drop us some links/documents for knowledge.

**Comment by c0diq** [comment]
Could you show the code that would be used to generate the wat? I have not been able to make a C function and compile it with either emcc or wasicc that would work with the samples.

**Comment by Hywan** [comment]
We write the `.wat` by hand, we don't bother explaining how clang, Rust, Zig, AssemblyScript, Swift, and so on, work :-). But it's definitely something that should exist somewhere.

Quickly, in C, see this issue, https://github.com/wasmerio/wasmer/issues/2322.
