### ISSUE TITLE
Abstraction over signal handling and Thread Local Storage for traps

### ISSUE THREAD

**Issue by bkolobara** [wasmerio/wasmer#2024]
I'm opening this issue to continue the discussion started in #1127.

### Issue

Just to give a bit of context, here is a short overview of how traps currently work in Wasmer.

Every time a Wasm function is invoked, the execution of this function is wrapped in a [CallThreadState::with()](https://github.com/wasmerio/wasmer/blob/master/lib/vm/src/trap/traphandlers.rs#L598) call. This call will set a [thread local variable](https://github.com/wasmerio/wasmer/blob/master/lib/vm/src/trap/traphandlers.rs#L745) with some data about how to handle traps if they occur.

All of this is necessary because once a trap is triggered the signal handler is going to be invoked on a separate stack, and can only get information about the execution environment through this well known thread local variable. I'm not aware of any other way this could be solved. Generally, this is a pretty good approach.

The only issue is that the runtime assumes that once a Wasm function is invoked until it finishes it will be running on the same thread and the thread local reference is going to be valid. For a [project](https://github.com/lunatic-lang/lunatic) I'm working on this is not true though. I'm executing the Wasm functions on a separate stack and I can pause the instance and move to another thread, while invalidating the thread local reference.

My current workaround is to use a fork of Wasmer where I expose the thread local variable as public and carefully move it with the instance from thread to thread. Of course, using a fork is not ideal and I would love to solve this upstream.

### Proposal

One way of solving this I came up with would be to introduce a trait `TrapHandler` that requires functions like [`wasmer_call_trampoline`](https://github.com/wasmerio/wasmer/blob/master/lib/vm/src/trap/traphandlers.rs#L497) and [`setup_unix_sigaltstack`](https://github.com/wasmerio/wasmer/blob/master/lib/vm/src/trap/traphandlers.rs#L782) to be implemented. Wasmer would than provide a default implementation that just wraps the current implementation, but you would also be able to provide your own (and pass it to the engine?).

That way I could provide my own implementation without having access to Wasmer's internals.

### Benefits

One nice side-effects of this would be that if you wanted to use Wasmer in an (embedded) environment without thread local storage you could provide your own implementation.

### Drawbacks

I'm not sure how much of the internals of `wasmer-vm` need to be made public and re-exported through the `wasmer` crate for you to actually be able to provide your own implementation of a signal handler.

If the Wasmer team thinks this direction is feasible I would love to start working on a PR and see how far I get. Any suggestions and tips are welcome!

**Comment by bkolobara** [comment]
Wasmtime now provides a really nice way to move the thread local storage with you from thread to thread: https://docs.rs/wasmtime-runtime/0.26.0/wasmtime_runtime/struct.TlsRestore.html

I would love to see a similar API in Wasmer.

**Comment by MarkMcCaskey** [comment]
Interesting idea, thanks for the link!
