### ISSUE TITLE
CLI: --env should allow variables that contain `=`

### ISSUE THREAD

**Issue by artlogic** [wasmerio/wasmer#2028]
### Describe the bug

When passing environment variables into `wasmer run` via the `--env` flag, the program will fail if the environment variable contains an `=`. It's sometimes useful or necessary to include an `=` in an environment variable. I believe this should be allowed.

Versions: `wasmer 1.0.0 |  | x86_64`

### Steps to reproduce

* Run: `wasmer run --env=MYVAR=1+2=3 test.wasm`
* Output: `error: Invalid value for '--env <KEY=VALUE>...': Env vars must be of the form <var_name>=<value>. Found MYVAR=1+2=3`

### Expected behavior

The value should be allowed and parsed correctly.

### Actual behavior

An error message is displayed and the program stops.

**Comment by MarkMcCaskey** [comment]
Thanks for the report!  I thought we had this issue and the past and fixed it... I'll look into it later, just to clarify the expected behavior here is that the variable is parsed as:

name = `MYVAR`
value = `1+2=3`

is that correct?

**Comment by artlogic** [comment]
That's perfect @MarkMcCaskey!

**Comment by Hywan** [comment]
@MarkMcCaskey Are you refering to https://github.com/wasmerio/wasmer/pull/1762?

**Comment by MarkMcCaskey** [comment]
> @MarkMcCaskey Are you refering to #1762?

Yeah, I think so. I knew someone worked on this in the past, unsure if it's since been broken (and we're not testing it?) or if something else happened.

**Comment by Hywan** [comment]
This error comes from the `cli` crate itself. I'm fixing it.
