### ISSUE TITLE
Docs issue: diagrams not readable in dark theme

### ISSUE THREAD

**Issue by Spoonbender** [wasmerio/wasmer#2029]
The diagrams found [here](https://github.com/wasmerio/wasmer/blob/master/examples/README.md) are not readable when viewing GitHub using the dark theme.

**Steps to reproduce:**
1. Set your [GitHub appearance preferences](https://github.com/settings/appearance) to use dark mode
2. Browse to the wasmer examples readme.md at https://github.com/wasmerio/wasmer/blob/master/examples/README.md
3. Attempt to read the text inside the diagram blocks (see screenshot below)

**Expected behavior:**
Reading succeeds and the information is conveyed.

**Actual behavior:**
Reading fails and the Wasmer main workflows remain a mystery.

**Possible workarounds:**
1. Configure light theme on your GitHub appearance preferences, or
2. Browse the docs in Incognito mode

![image](https://user-images.githubusercontent.com/6010433/104891069-1f8a3c00-5979-11eb-8697-334861e99aeb.png)

**Comment by syrusakbary** [comment]
Thanks for the ping! The new diagrams have white backgrounds so it's easier to read in Github with the dark theme!
