### ISSUE TITLE
Export from wasm module and import into a second wasm module using wasmer CLI

### ISSUE THREAD

**Issue by TimSC** [wasmerio/wasmer#2031]
I am relatively new to wasm. Is it possible to run two wasm source files using wasmer CLI, with one module importing functions from a second wasm module (which exports the relevant functions)?

As far as I can tell, it seems like another language (Rust, C, C++, etc) are necessary to glue things together, is that correct?

**Comment by MarkMcCaskey** [comment]
Hi @TimSC, that does sound like a useful feature! We don't currently support that with the wasmer CLI but it sounds pretty straight-forward to add -- unless there are subtleties to it that I'm not aware of!
