### ISSUE TITLE
Making VMOffsets accessible from the InstanceHandle

### ISSUE THREAD

**Issue by Geal** [wasmerio/wasmer#2032]
Hello! In my project, I have to rewrite parts of the VM context, and for that I use the `wasm_vm::VMOffsets` structure.
Right now, to access it, I write:

```rust
// with handle a &wasmer_vm::InstanceHandle
let module = handle.module_ref();
let vmoffsets = VMOffsets::new(std::mem::size_of::<*mut u8>() as u8, module);
```

Would it be possible to add a method to `InstanceHandle` so that it can directly return a `VMOffsets` that makes sense for it? Making sure that it has the same pointer size, etc.

**Comment by Hywan** [comment]
Sure, I think it's perfectly fine to add such feature. `InstanceAllocator` already has this API (which is private), so I guess it's fine to expose it publicly through `InstanceHandle` or even `InstanceRef`.

**Comment by Hywan** [comment]
Would #2040 solve your issue @Geal?

**Comment by Geal** [comment]
yes, thanks
