### ISSUE TITLE
Getting started example fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by darkoverlordofdata** [wasmerio/wasmer#2046]
### Describe the bug

```sh
echo "`wasmer -V` | `rustc -V` | `uname -m`"
```
wasmer 1.0.1 | rustc 1.49.0 (e1884a8e3 2020-12-29) | x86_64

### Steps to reproduce

1. curl https://get.wasmer.io -sSfL | sh
2. wapm install -g quickjs
3. wasmer qjs.wasm

### Expected behavior

I expected the prompts shown at https://docs.wasmer.io/ecosystem/wasmer/getting-started
### Actual behavior
error: failed to run `qjs.wasm`
╰─> 1: No such file or directory (os error 2)

**Comment by MarkMcCaskey** [comment]
Hi! I'll take a closer look at the example text later, but the way you'd run something installed from wapm is with `wapm run qjs`!

It looks like that example expected just the Wasm module to be downloaded

**Comment by darkoverlordofdata** [comment]
That works! Looks like a misprint in the docs, and I'm too new to autmaticall do the right thing. 
btw - same page, I also noticed another misprint -  the version #'s listed 
```
GLIBC: >= 3.4.21
GLIBCXX: >= 2.27
``` 
are the opposite of what I show on my desktop libc is 2.27, and libcxx is 3.4.25

**Comment by jubianchi** [comment]
@darkoverlordofdata thanks for the heads up on this: there is indeed an error there. I will fix that.
