### ISSUE TITLE
Make `Module::deserialize_from_file` and `Module::serialize_to_file` return (serialized) module size

### ISSUE THREAD

**Issue by maurolacy** [wasmerio/wasmer#2055]
### Motivation

It's useful to have an estimate of a `Module` size, by example for using it in caches that have a weight/size based replacement policy.

We've have [found out](https://github.com/CosmWasm/cosmwasm/blob/main/packages/vm/examples/module_size.sh) that the serialized module size is a good proxy for the actual in-memory module size.
Moreover: the serialized module size is straightforward to obtain, whereas the module size is difficult, as a module consists of many nested structs, many of which are pointers / references, and computing their total memory footprint is non-trivial.

So, when serializing / deserializing, particularly to / from file, it would be convenient to return the module size, given that it's already available.

### Proposed solution

Return the serialized module size "in passing" from both `serialize_to_file` and `deserialize_from_file`.

Consider doing the same from the other `deserialize` / `serialize` methods, if it's straightforward / relatively non-breaking.
 
### Alternatives

A fs-stored module size can always be obtained with relative ease from the associated file. This is just an optimization, given that the module size is already available, and it's easy / non-breaking to return it.

### Additional context

In the context of [cosmwasm-vm](https://github.com/CosmWasm/cosmwasm/tree/main/packages/vm), we're currently planning on using the module size for a (size-limited) modules in-memory cache.

**Comment by Hywan** [comment]
Hello,

Thanks for the proposal. I'm not sure I've understood it correctly. Do you want to know the size of a serialized module, or the size of `Module` once fully loaded in memory (i.e. after `Module::new` or `Module::desrialize` has been called)?

The size of a serialized is its number of bytes. Basically `module.serialize()?.len()`.

The size of an in-memory `Module` is more difficult to compute (it depends on the engine and the compiler + the system itself). But I don't understand in which context it can be useful.

Can you elaborate please?

**Comment by maurolacy** [comment]
> I wonder if that is necessarily the case. When you look at https://github.com/wasmerio/wasmer/blob/1.0.1/lib/engine-native/src/artifact.rs#L493-L555 you see a file path loaded into [libloading::Library](https://docs.rs/libloading/0.6.7/libloading/struct.Library.html) which does not seem to provide the information. So additional metadata calls to the filesystem would be needed in some cases.

Yeah, there seem to be a number of places where these (similar / related) functions are implemented.

I was thinking more of here: [deserialize_from_file](https://github.com/wasmerio/wasmer/blob/fa0938ca96399368e6eac8f1d8c2230cdd3b333c/lib/engine/src/engine.rs#L51)
and here: [serialize_to_file](https://github.com/wasmerio/wasmer/blob/fa0938ca96399368e6eac8f1d8c2230cdd3b333c/lib/engine/src/artifact.rs#L73)

**Comment by maurolacy** [comment]
> Hello,
> 
> Thanks for the proposal. I'm not sure I've understood it correctly. Do you want to know the size of a serialized module, or the size of `Module` once fully loaded in memory (i.e. after `Module::new` or `Module::desrialize` has been called)?
> 
> The size of a serialized is its number of bytes. Basically `module.serialize()?.len()`.
> 
> The size of an in-memory `Module` is more difficult to compute (it depends on the engine and the compiler + the system itself). But I don't understand in which context it can be useful.
> 
> Can you elaborate please?

Hello,

We want the size of the serialized / deserialized module. Having the size of the Module in memory would be great, but it is our understanding that it's non-trivial to compute. We have found that the size of the serialized module closely matches the size of the module in memory.

That's why I propose returning these sizes from the serialization / deserialization from file functions. Given that the vector or slice is present at some point in these functions, it's trivial to obtain their size. This is a minor optimization, by the way, in that obtaining this information from the file directly is also cheap. This is just cheaper, in-passing, and also mostly non-breaking of the current API/

**Comment by maurolacy** [comment]
To answer why we want that, it's just to better control the size of an in-memory cache for these modules. If we have the module size (or a good proxy for it), we can make sure that our cache doesn't exceed a given size.

**Comment by syrusakbary** [comment]
I'm not sure if I see the value added vs having a function that gets the length in bytes of a file / byte stream.

In general, the more functional (in the pure sense) our API is, the better.
That means, that if for retrieving two things we can have two functions instead of one that would be preferred as it increases maintainability.

That means, that if we want to have the size of a module and the contents of the module we would have:
* function to serialize a module (get the contents)
* function to get the length of a serialized module.

For the last bullet, I believe rust `fs` can be used. So I'm unsure if we really to need that in Wasmer.

Perhaps might be interesting to have a "module size estimator" for a given compiler/settings but I believe that would not be trivial to do (without computing the serialized value).

Am I missing something here?

**Comment by maurolacy** [comment]
> Am I missing something here?

No, not really.

I wouldn't add a function to get the module size, except if it reports the exact in-memory module size.

**Comment by Hywan** [comment]
If you're able to compile and serialize the module ahead-of-time, then you will be able to allocate the exact space in memory to store the serialized module. Since we support cross-compilation and ahead-of-time compilation, it's not a problem… if and only if you can fetch the modules ahead-of-time obviously.

**Comment by maurolacy** [comment]
Our use case is for caching, that is, when you already have the compiled (and deserialized) module, and want to cache it in memory (and control / limit the cache's size).

Anyway, I'll close this, as it will not be implemented.
