### ISSUE TITLE
CLI: add an option to adopt all the host's environment variables

### ISSUE THREAD

**Issue by artlogic** [wasmerio/wasmer#2078]
### Motivation

I've been using wasienv and wasmer to cross compile 3rd party projects to wasm. Many of these projects contain automated tests that set environment variables to configure the tests. Currently I've had to write a wrapper script to set each variable manually. I would like some way to pass all the set variables automatically.

### Proposed solution

I propose adding a flag to the CLI - something like `--hostenv` that sets up the WASI environment variables to match the host environment variables.

I'd be happy to help with a PR if this is a feature that would be useful to others. It certainly would be useful to me!

**Comment by MarkMcCaskey** [comment]
Thanks for the suggestion! I agree that this is a useful feature to have as long as it's opt-in!

I'm not sure about the flag name `--hostenv`, maybe something more explicit like `--inherit-host-env` would be better -- not sure yet!

**Comment by artlogic** [comment]
@MarkMcCaskey I'm willing to defer to your judgement on the flag name - whatever you think is best!

**Comment by MarkMcCaskey** [comment]
I'll get feedback from the Wasmer team on the name of the flag but it should be trivial to change so if you'd like to make a PR adding this, I'd be happy to review / help get it shipped! We can always change the name of the flag after that PR lands too.

My thoughts are that this can either be done at the `wasmer-cli` level where we just call [`WasiStateBuilder::env`](https://docs.rs/wasmer-wasi/1.0.1/wasmer_wasi/struct.WasiStateBuilder.html#method.env) in a loop, or we can have another method on [`WasiStateBuilder`](https://docs.rs/wasmer-wasi/1.0.1/wasmer_wasi/struct.WasiStateBuilder.html) for inheriting host envs. The benefit of doing it at the `WasmStateBuilder` level is that this feature becomes available to users of the API too and we could easily add it to the C API as well. The downside though is that it might encourage deveolpers to inherit the host env in too many cases and that could be problematic for fingerprinting / sandboxing in general. Not doing it in `WasmStateBuilder` means using inconvenience of the API as a feature, which I have mixed feelings about.

I suppose I'm fine with either of these solutions for now!

Thanks!

**Comment by artlogic** [comment]
I saw this was marked as stale - I'd still like to pursue this - just haven't had time. I think it's an important addition.
