### ISSUE TITLE
C API: HostRef Integration

### ISSUE THREAD

**Issue by chances** [wasmerio/wasmer#2080]
### Summary

I'm trying to use functions related to `wasm-c-api/example/hostref`.

> The `wasmer_last_error_length` function is now part of the deprecated API.
> 
> We are moving toward the standard wasm-c-api.
> You can find an example of how to use traps with it here:
> https://github.com/wasmerio/wasmer/blob/master/lib/c-api/tests/wasm-c-api/example/trap.c
> 
> > Turns out the test file that the wasm functions i referred to is not being run when testing:
> > ```
> > wasm-c-api/example/finalize			wasm-c-api/example/hostref
> > ```
> 
> You are right! There are some parts of the wasm-c-api that are not yet fully integrated, but they will be soon!
> 
> Let us know if you have any more questions!

_Originally posted by @syrusakbary in https://github.com/wasmerio/wasmer/issues/1952#issuecomment-748508494_

I'm opening this issue to track progress of HostRef integration.

**Comment by MarkMcCaskey** [comment]
Thanks for sharing your interest in this feature with us! We're actively working on adding reference types to Wasmer and as part of that we will of course support significantly more of the Wasm C API. I believe all of the Wasm C API examples that we don't support currently are blocked (at least partially) on reference types, so it'll be a big step forward for our Wasm C API support as well.
