### ISSUE TITLE
Add support for Android NDK

### ISSUE THREAD

**Issue by leeveel** [wasmerio/wasmer#2099]
### Describe the bug

device:  x86_64-linux
os: centos7.7
wasmer version: 1.0.1,1.0.2, master
cmd: make build-capi 
build tool: https://github.com/bbqsrc/cargo-ndk
I got these errors for aarch64-linux-android on all wamser version:

```
   Compiling wasmer-c-api v1.0.2 (/data/wasmer-master/lib/c-api)
error: unsupported platform
   --> lib/vm/src/trap/traphandlers.rs:275:21
    |
275 |                     compile_error!("unsupported platform");
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no method named `si_addr` found for struct `siginfo_t` in the current scope
   --> lib/vm/src/trap/traphandlers.rs:119:43
    |
119 |                     let addr = (*siginfo).si_addr() as usize;
    |                                           ^^^^^^^ method not found in `siginfo_t`

error[E0308]: mismatched types
   --> lib/vm/src/trap/traphandlers.rs:197:52
    |
197 |         unsafe fn get_pc(cx: *mut libc::c_void) -> *const u8 {
    |                   ------                           ^^^^^^^^^ expected *-ptr, found `()`
    |                   |
    |                   implicitly returns `()` as its body has no tail or `return` expression
    |
    = note: expected raw pointer `*const u8`
                 found unit type `()`

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0308, E0599.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `wasmer-vm`
```

**Comment by Hywan** [comment]
Hello,

As the error says, the targeted platform isn't supported yet by the runtime.

**Comment by leeveel** [comment]
@Hywan Thanks for your replay. I want to use wasmer for embedded-use in unity3d game.

**Comment by Hywan** [comment]
And this game runs on an Android platform, is that correct?

**Comment by leeveel** [comment]
Yes, It's just like lua. my main purpose is do some think like hot reload scripts to fix game bugs.

**Comment by Hywan** [comment]
Let me see if we can push this idea further. cc @syrusakbary

**Comment by theduke** [comment]
I would also really love to see Android support.

There are many use cases.
The main benefit is that it would make using C or Rust code in Android apps much, much easier, because you wouldn't need to deal with the hassle of setting up native compilation.

This would especially be true if https://github.com/wasmerio/wasmer-java had pre-built JARs for the various Android architectures.

Please also note that Android has multiple ABIs. (See https://developer.android.com/ndk/guides/abis )

By far the most important one is `armeabi-v7a`, followed by `arm64-v8a`.

**Comment by Hywan** [comment]
Thank you for your comment.

**Comment by dead10ck** [comment]
This would also support building Rust libs / apps that depend on wasmer on Termux. e.g. zellij uses wasm plugins

**Comment by caiiiycuk** [comment]
+1

**Comment by xJonathanLEI** [comment]
Looks like the Termux guys actually got it to compile on Android?

https://github.com/termux/termux-packages/pull/7982

Is it possible we bring their patch here to make things work? I would like to give it a try this weekend.

cc. @truboxl (PR author)

**Comment by cbrzn** [comment]
Hey I just built my library (which uses wasmer) to all android targets using [`cargo-ndk`](https://github.com/bbqsrc/cargo-ndk). So just to confirm, this issue can be closed :smile:

**Comment by syrusakbary** [comment]
Awesome, closing the issue

**Comment by tsangint** [comment]
Are android and ios officially supported now? I haven't seen relevant documents

**Comment by xJonathanLEI** [comment]
I think it's supported in the sense that "it works now", not in that the team would put in work on bug fixes etc.
