### ISSUE TITLE
Android build support

### ISSUE THREAD

**Issue by dodola** [wasmerio/wasmer#21]
I try to build wasmer with carto and Android NDK have some problems，Is the project planned to run on Android?

**Comment by syrusakbary** [comment]
In the short term we are trying to focus on x86 and x86_64 environments to reach faster the MVP, but we would like to support arm as well in a near future.

If you would like to contribute into the project adding support for arm we would happily review & merge :)

**Comment by dodola** [comment]
@syrusakbary thanks for reply
