### ISSUE TITLE
Merge two import objects?

### ISSUE THREAD

**Issue by caelunshun** [wasmerio/wasmer#2100]
### Motivation

With the current API, it doesn't seem possible to combine two `ImportObject`s. This limitation makes it difficult to use `wasmer-wasi` and custom imports simultaneously. 

### Proposed solution

#258 added an `extend` method to `ImportObject`, but it seems this method no longer exists. Adding it back would be an adequate solution.

**Comment by caelunshun** [comment]
Looks like this functionality already exists in [the `ChainableNamedResolver` trait](https://docs.rs/wasmer/1.0.2/wasmer/trait.ChainableNamedResolver.html).

**Comment by MarkMcCaskey** [comment]
Yep, it should work but we have #1818 to make it more clear, I'll try to prioritize that soon
