### ISSUE TITLE
Actionscript 2/3

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [wasmerio/wasmer#2132]
Thanks for proposing a new feature!

### Motivation

since Flash EOF a lot of good project that cannot be converted in JS for various reason are in a prematured death. let developers and designer to continue to program in Actionscript will open door to the last web standards and keeping their preferred language

### Proposed solution

compile SWF directly in WASM

**Comment by Hywan** [comment]
Hello,

We aren't editing compilers from languages X to Wasm. We are editing a Wasm runtime (with compilers, engines etc.), and embeddings.

What you're looking for already exist though, it's https://ruffle.rs/:

> ruffle is a Flash Player emulator built in the Rust programming language. 

Ruffle, the Flash Player emulator, can compile to Wasm, and thus can run in a browser for example. See https://ruffle.rs/#usage to learn more.

It's open source, and you can freely contribute to it if you wish, https://github.com/ruffle-rs/ruffle.

I'm closing the issue as the discussion it's not related to Wasmer :-).
