### ISSUE TITLE
How to load a complicated guest module when does integration with wasmer?

### ISSUE THREAD

**Issue by diceangel20** [wasmerio/wasmer#2136]
### Summary
"How to load a complicated guest module when does integration with wasmer?"

You have many C examples for guest modules to be loaded inside wasmer when doing integrations. Almost those examples are short code examples. We tried with more complicated source code when had include many libraries and also ran with main() function.

It worked great if we use wasmer cli to run .wasm file. But when we try to load this module with one of your example, for example: https://github.com/wasmerio/wasmer/blob/master/lib/c-api/examples/imports-exports.c

It was stopped with message "> Error instantiating module!", this section:

```c
wasm_instance_t* instance = wasm_instance_new(store, module, &import_object, NULL);
if (!instance) {
 printf("> Error instantiating module!\n");
 return 1;
}
```

### Additional details

For example, here are what we included:

```c
#include <iostream>
#include <stdio.h>
#include <fstream>
#include <cstdlib>
#include <math.h>
#include "self_defined_lib.h"

int main (int argc, char **argv){
....
return 0;
}
```

**Comment by MarkMcCaskey** [comment]
Hello! Try running `wasmer inspect file.wasm` to learn more about what's inside the Wasm module that you're trying to run. You didn't include it in the example above but the contents of the `import_object` are very important and likely the issue here.

My guess is that you haven't supplied the required imports. Perhaps you're dealing with a WASI module and need to supply the WASI imports.

Feel free to check out the entire file, but definitely copy this error reporting function and put it in all your failuer branches: https://github.com/wasmerio/wasmer/blob/master/lib/c-api/tests/test-wasi.c#L12-L19

That'll give you an actual error message about what went wrong!

**Comment by diceangel20** [comment]
Hello!

We tested following your recommendations and saw some interesting things:
1. Here is what we got from running: wasmer inspect foo.wasm

`Type: wasm
Size: 725.3 KB
Imports:
  Functions:
    "wasi_unstable"."fd_prestat_get": [I32, I32] -> [I32]
    "wasi_unstable"."fd_prestat_dir_name": [I32, I32, I32] -> [I32]
    "wasi_unstable"."clock_time_get": [I32, I64, I32] -> [I32]
    "wasi_unstable"."proc_exit": [I32] -> []
    "wasi_unstable"."fd_fdstat_get": [I32, I32] -> [I32]
    "wasi_unstable"."fd_close": [I32] -> [I32]
    "wasi_unstable"."args_sizes_get": [I32, I32] -> [I32]
    "wasi_unstable"."args_get": [I32, I32] -> [I32]
    "wasi_unstable"."fd_seek": [I32, I64, I32, I32] -> [I32]
    "wasi_unstable"."fd_read": [I32, I32, I32, I32] -> [I32]
    "wasi_unstable"."fd_write": [I32, I32, I32, I32] -> [I32]
    "wasi_unstable"."environ_sizes_get": [I32, I32] -> [I32]
    "wasi_unstable"."environ_get": [I32, I32] -> [I32]
  Memories:
  Tables:
  Globals:
Exports:
  Functions:
    "_start": [] -> []
  Memories:
    "memory": not shared (2 pages..)
  Tables:
  Globals:
`
2. We were able to instantiated and implemented our WASI module with: ./test-wasi
but at the end, we got this memory issue: "Segmentation fault"

3. Went further to run ./test-wasi with "./assets/qjs.wasm" , it returned the same issue after implemented WASI module, something like this:

`Initializing...
Loading binary...
Compiling module...
Setting up WASI...
Instantiating module...
Extracting export...
found 2 exports
Calling export...
Evaluating "function greet(name) { return JSON.stringify('Hello, ' + name); }; print(greet('World'));"
"Hello, World"
Segmentation fault
`

4. In file test-wasi.c, we were unable to compile it because of this function: "wasi_config_capture_stdout(config);"
the compiler returned this error log: 
test-wasi.c:(.text.startup+0x16d): undefined reference to `wasi_config_capture_stdout'
collect2: error: ld returned 1 exit status

To compile successfully, we had to comment this function: //wasi_config_capture_stdout(config);
All tests #1,2,3 were implemented without the above function.

Hopefully, you can give us some advices.

**Comment by Hywan** [comment]
If I understand correctly, you're saying WASI segfaults on your system? I'm not able to reproduce your error locally with our tests.

Can you provide me a script and a Wasm module to reproduce, and your system (platform and architecture) please?

About the item number 5, please do not mix questions in the same thread. We will come back to that later, or in another issue maybe?

**Comment by diceangel20** [comment]
Please use our Wasm module, basically this module work well when we use wasmer cli to run it without segfault.
But, with test-wasi.c, we faced that segfault issue.
[foo.zip](https://github.com/wasmerio/wasmer/files/6041501/foo.zip)

The good thing is test-wasi allowed us to implement this module which we tried to do.

"About the item number 5, please do not mix questions in the same thread. We will come back to that later, or in another issue maybe?" - Sure. We are trying to port our system which use many libs to Wasmer.

**Comment by MarkMcCaskey** [comment]
Unfortunately the nature of C and C APIs is that they're prone to memory errors if the API is used even slightly incorrectly. Can you please post the full C source code to reproduce this issue here? The internals of Wasmer should generally never segfault (if they do, that's a major bug that we'll want to fix as soon as we can). So the only thing that should be segfaulting is the C API either caused by a bug in our C API or a misuse of the API.

**Comment by diceangel20** [comment]
You can pull it from here: https://github.com/xtblock/dai-gomoku
Let us know if you need anything else.

**Comment by diceangel20** [comment]
This issue is about wasmer versioning, it works with wasmer 1.02 that you updated 3 weeks ago but we had used 1.0 to run it.

Should we create a new ticket to suggest adding version in all examples? Everyone will need to notice it firstly.

Something like:

//wasmer version ^1.02

**Comment by Hywan** [comment]
The examples are expected to run with the code they live with, since they act as tests too. We don't keep examples for old Wasmer versions. If you want such old examples, all you need is to navigate in the Git history :-).

**Comment by diceangel20** [comment]
Nevermind, thanks for your help.
