### ISSUE TITLE
Memory64 proposal support

### ISSUE THREAD

**Issue by psoni2628** [wasmerio/wasmer#2137]
### Motivation

Memory64 exists as an experimental feature in wasmer, but there is not any code for implementation of the feature. I thought it would be a good idea to have a public place for discussion about the feature. 

### Proposed solution

@MarkMcCaskey mentioned to me that it should not be too hard to get memory64 to work. We need to use dynamic memory which ensures that we always have bounds checks (we can optimize these out for 32bit memories).

> For some more background, the technical reason we can avoid bounds checks with 32bit memories is due to being able to mmap 4gb of virtual memory, allowing us to guarantee that a 32bit pointer will always be in bounds. We can’t do that for 64bit memory. At least not directly, so we want to use dynamic memory.

> Dynamic memory doesn’t do the virtual memory trick and because of that it requires bounds-checks on memory access. I think just some slight tweaking to dynamic memory is all we’ll need to make this work.

**Comment by ptitSeb** [comment]
...unstale...

**Comment by kylegranger** [comment]
I see the `memory64` feature is exposed.  But it is not yet implemented?  
In a Rust application, when I enable it (using wasmer 4.1.0), and use a wasm64-unknown-unknown WASM file (which works with a similarly enabled `wasmtime` runtime for Rust), I get this:
```
'not implemented: 64bit memory not implemented yet'
```

**Comment by WireWhiz** [comment]
Same error for me, any updates on this? It's something I would be interested in contributing too if I could help. Still relatively new to rust so I don't know if I would be that much help, but I have some experience with llvm and whatnot.

**Comment by theduke** [comment]
Yes, there was some initial work on plumbing for 64bit support, but it is not implemented and does not work at the moment.
