### ISSUE TITLE
Configure SIMD with Wasmer C API

### ISSUE THREAD

**Issue by chorusg** [wasmerio/wasmer#2142]
### Summary

Hello,

We use many algebraic calculations in our WASI module. Could you let us know how to turn SIMD on with wasmer when does integration?

### Additional details

We are porting some neural networks to wasmer.

**Comment by syrusakbary** [comment]
Have you tried using the `-msimd128` to the compile flags when compiling to WASI? I think that will probably work!

You can find a more complete example here:
https://github.com/wasmerio/c-wasm-simd128-example

Let me know if that worked!

**Comment by chorusg** [comment]
Hello,

This setting is for WASI module, we have learnt to use it when ran the WASI module with wasmer cli.

Our question is when we do integrating libwasmer, how do we configure SIMD128? Just like how you make wasmer implement WASI module with SIMD128 when we type the flag: --enable-simd

**Comment by syrusakbary** [comment]
Ohhh, I believe you need to setup a compiler flag.
In rust we enable it via the engine features:

https://github.com/wasmerio/wasmer/blob/master/lib/engine-jit/src/builder.rs#L40-L44

Adding @MarkMcCaskey and @Hywan to see if there is an API to do it in C. @chorusg are you using libwasmer from c or from any of the wasmer language integrations?

**Comment by diceangel20** [comment]
@syrusakbary Yes, we are using C libwasmer.

**Comment by Hywan** [comment]
I can work on that :-). When do you need this feature?

**Comment by diceangel20** [comment]
Hi @Hywan,

We would need it asap if possible.

**Comment by Hywan** [comment]
Such API wasn't a priority for us right now, so I rushed it, https://github.com/wasmerio/wasmer/pull/2153. I will greatly appreciate if you could review and test for your usecase :-).

**Comment by chorusg** [comment]
Hi @Hywan,

Because we are running v1.02 already, how do we update lib to test this new feature?

We pulled wasmer_wasm.h, and what else do we have to do to test it now?

We saw your have 2 prefixes: wasm_ and wasmer_ , could you explain their purpose?

**Comment by Hywan** [comment]
Yeah, you need to do this:

```sh
$ git clone https://github.com/wasmerio/wasmer
$ cd wasmer
$ make build-capi
$ make pacakge
$ cd package
```

inside the `package/` directory, you will find `include/` and `lib/` as we provide them already. Get `wasm.h` (the C header from the Wasm C API working group, i.e. the standard API), `wasmer_wasm.h`, which is your entry point (it includes `wasm.h` and it adds the Wasmer-specific API, like `wasmer_features_t`!), get your lib in `lib/libwasmer.*`.

Note that you should build against the branch used in https://github.com/wasmerio/wasmer/pull/2153. Edit `.git/config`, and add:

```
[remote "github-pr"]
        url = git@github.com:wasmerio/wasmer.git
        fetch = +refs/pull/*/head:refs/remotes/github-pr/pr/*
```

then `git fetch github-pr`, finally `git checkout -b pr/2153 github-pr/pr/2153` (and now, `make build-capi` etc.).

Alternatively, you can wait one or two days and you would be able to build from the `master` branch as https://github.com/wasmerio/wasmer/pull/2153 is about to be merged really soon.
