### ISSUE TITLE
Enable LLVM backend on windows

### ISSUE THREAD

**Issue by hanabi1224** [wasmerio/wasmer#2148]
### Motivation

It will be awesome to have LLVM backend enabled on windows

### Proposed solution

I managed a produce a LLVM-enabled binary for windows from [github action CI](https://github.com/hanabi1224/ci-playground/actions/runs/606744252) (wasmer.exe in artifact).  I made two minor changes tho
1. change LLVM [build script](https://github.com/hanabi1224/ci-playground/blob/main/.github/workflows/main.yml) (based on [this](https://github.com/wasmerio/llvm-custom-builds/blob/master/build.ps1)) to remove ```-DLLVM_ENABLE_PROJECTS="clang;lld" ``` and ```-DLLVM_TARGETS_TO_BUILD="X86;AArch64"```   My working archive can be downloaded [here](https://github.com/hanabi1224/ci-playground/releases/download/llvm-windows-0.1-pre1/llvm-11.1.0-windows.zip)
2. Add ```build.rs``` to compiler-llvm for windows to link ```msvcrt.lib``` or ```msvcrtd.lib```
```rust
### build.rs ###

fn main() {
    configure_dylib_windows();
}

#[cfg(windows)]
fn configure_dylib_windows() {
    #[cfg(debug_assertions)]
    let lib = "msvcrtd";
    #[cfg(not(debug_assertions))]
    let lib = "msvcrt";
    println!("cargo:rustc-link-lib=dylib={}", lib);
}
```

It seems not hard to enable llvm on windows unless there're some extra context I'm not aware of. Please let me know your concerns and I'm willing to help submit PR.

**Comment by Hywan** [comment]
Hello,

Thanks for your proposal! I've few questions though:

* Why removing`-DLLVM_ENABLE_PROJECTS` and `-DLLVM_TARGETS_TO_BUILD` solve any particular problem? Also, we need to compute `clang` and `lld`for projects like `wasmer-python`, we must be very careful on that side.
* I see you've added the `-DLLVM_STATIC_LINK_CXX_STDLIB=ON` argument, maybe it's what makes the difference here?
* The `build.rs` for `wasmer-compiler-llvm` looks good to me as far as I can judge.

cc @nlewycky @wasmerio/langint

**Comment by hanabi1224** [comment]
@Hywan My answers are inline
>  Why removing-DLLVM_ENABLE_PROJECTS

 ```-DLLVM_ENABLE_PROJECTS```, I only removed it for speeding up, should be ok to add back. 
> and -DLLVM_TARGETS_TO_BUILD

```-DLLVM_TARGETS_TO_BUILD```, it complains about missing symbols of all excluded targets during linking on windows.

> -DLLVM_STATIC_LINK_CXX_STDLIB=ON

The build worked for me was without this.  I added this later to see if I can remove build.rs(which tells cargo to link msvcrt.lib) but haven't got a chance to check yet 

> The build.rs for wasmer-compiler-llvm looks good to me as far as I can judge.

I can submit a PR for this change.

**Comment by hanabi1224** [comment]
@Hywan  update on```-DLLVM_STATIC_LINK_CXX_STDLIB=ON```
It produces an extra ```LLVM-C.lib``` but still does not work without ```println!("cargo:rustc-link-lib=msvcrt")```. So it can be optional since it makes no difference.

**Comment by Hywan** [comment]
>  can submit a PR for this change.

@hanabi1224 Please yeah, open a PR at https://github.com/wasmerio/llvm-custom-builds please, so that we can check with the CI there. Thanks!

**Comment by hanabi1224** [comment]
@Hywan PR created.

**Comment by Hywan** [comment]
Thanks!

**Comment by Hywan** [comment]
Will fix https://github.com/wasmerio/wasmer/issues/1513.

**Comment by ptitSeb** [comment]
LLVM is enable and works on Windows. Closing the issue.
