### ISSUE TITLE
PIC support on Singlepass

### ISSUE THREAD

**Issue by ailisp** [wasmerio/wasmer#2179]
### Describe the bug
NativeEngine + Singlepass failed when use together with Function::new_native_with_env. Call such a function would raise `Trap(HeapAccessOutOfBounds)`

```
Latest master wasmer  | rustc 1.49.0 (e1884a8e3 2020-12-29) | x86_64
```

### Steps to reproduce

To reproduce, clone this branch of our fork (which modify engine and backend used in `imported-function-env` example): https://github.com/near/wasmer/tree/native-engine-singlepass-imports-fail. Then run:
```
cargo run --example imported-function-env --release --features "singlepass"
```
Output:
```
   Compiling wasmer-workspace v1.0.2 (/Users/bo/workspace/near-wasmer)
    Finished release [optimized] target(s) in 1.26s
     Running `target/release/examples/imported-function-env`
Compiling module...
Instantiating module...
Initial ounter value: 0
Calling `increment_counter_loop` function...
Error: RuntimeError { source: Trap(HeapAccessOutOfBounds), wasm_trace: [], native_trace:    0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
 }
```

### Expected behavior

This test should pass as JIT+Singlepass does.

### Actual behavior

```
Trap(HeapAccessOutOfBounds)
```

### Additional context

We're using this method to import host function to blockchain runtime. Previously we use JIT+Singlepass and that worked (You can try in the same example by replace Native with JIT, JIT+Cranelift and Native+Cranelift all work too, just Native+Singlepass combination doesn't; Also, basic test Native+Singlepass works, see example engine_native. so precisely speaking, this bug happen when Native+SinglePass+call a function import with `Function::new_native_with_env`

**Comment by syrusakbary** [comment]
Yeah, we currently don't fully support Singlepass + Native (we don't test it either, since is not yet fully supported), but should be doable to support.
Is Singlepass + native needed for your use case or is more a research thing?

**Comment by ailisp** [comment]
Thanks! I see, we're discussing about feasibility of cranelift + native. The major cons of cranelift is compilation speed. 
How much work is needed to bring Singlepass + Native similar to Singlepass + JIT?

Also I see native engine claimed:
> The Native Engine and JIT engine mainly differ on how the Modules are loaded/stored. Using the same compilers, both will have the same runtime speed.

But doesn't JIT engine take additional time to compile before execution, makes executing a JITArtifact slower than same NativeArtifact?

**Comment by ailisp** [comment]
Looks like not only this fail, in current master (6916e531be7ba7b6312da6199035cf2f69822fe6)
```
$ cargo test --features singlepass,test-singlepass,test-native
...
test result: FAILED. 68 passed; 89 failed; 182 ignored; 0 measured; 0 filtered out

$ cargo test --features singlepass,test-singlepass,test-jit
...
test result: ok. 157 passed; 0 failed; 182 ignored; 0 measured; 0 filtered out

$ cargo test --features cranelift,test-cranelift,test-native
...
test result: ok. 254 passed; 0 failed; 85 ignored; 0 measured; 0 filtered out
```

Tests seem to have a good coverage in general, so fix to make all tests pass on singlepass+native might mean it works okay.

**Comment by Hywan** [comment]
For the record: `NativeEngine` has been renamed to `DylibEngine`.

**Comment by ptitSeb** [comment]
Do you still reproduce the issue? I tried and everything seems to works fine on my end, with current master.

**Comment by ailisp** [comment]
@ptitSeb with current master, above example seems to require cranelift backend, so I can't tell whether it works with  singlepass:
```
wasmer (master) cargo run --example imported-function-env --release --features "singlepass"
...
error: target `imported-function-env` in package `wasmer-workspace` requires the features: `cranelift`
Consider enabling them by passing, e.g., `--features="cranelift"`
```

Then I test (dylib engine + singlepass):

```
cargo test --features singlepass,test-singlepass,test-dylib
...
test result: ok. 212 passed; 0 failed; 426 ignored; 0 measured; 0 filtered out; finished in 3.55s
```

It passed, but a lot of `::singlepass::dylib` tests are ignored. Compare to test with cranelift: `cargo test --features cranelift,test-cranelift,test-dylib`:
```
test result: ok. 539 passed; 0 failed; 99 ignored; 0 measured; 0 filtered out; finished in 617.81s
```
The number of tests are significantly less. So I suspect it isn't fixed, but test ignored.

**Comment by ptitSeb** [comment]
> @ptitSeb with current master, above example seems to require cranelift backend, so I can't tell whether it works with singlepass:
> 
> ```
> wasmer (master) cargo run --example imported-function-env --release --features "singlepass"
> ...
> error: target `imported-function-env` in package `wasmer-workspace` requires the features: `cranelift`
> Consider enabling them by passing, e.g., `--features="cranelift"`
> ```
Well, I modified the code as  per the fork mentionned in the initial post and I got it running fine

> 
> Then I test (dylib engine + singlepass):
> 
> ```
> cargo test --features singlepass,test-singlepass,test-dylib
> ...
> test result: ok. 212 passed; 0 failed; 426 ignored; 0 measured; 0 filtered out; finished in 3.55s
> ```
> 
> It passed, but a lot of `::singlepass::dylib` tests are ignored. Compare to test with cranelift: `cargo test --features cranelift,test-cranelift,test-dylib`:
> 
> ```
> test result: ok. 539 passed; 0 failed; 99 ignored; 0 measured; 0 filtered out; finished in 617.81s
> ```
> 
> The number of tests are significantly less. So I suspect it isn't fixed, but test ignored.
Yes, singlepass-dylib are ignore for now. I will remove that soon. My current testing shows  that it works fine on Linux/x86_64 and need a bit of work on Linux/Arm64 and more work on macOS/Arm64.
