### ISSUE TITLE
It looks that the link of rust doc becomes invalid at [Language Integrations]

### ISSUE THREAD

**Issue by Dengjianping** [wasmerio/wasmer#2212]
### Summary
Readme:
The link of rust doc goes [invalid](https://wasmerio.github.io/wasmer/crates/wasmer_runtime)

### Additional details
N/A

**Comment by syrusakbary** [comment]
Oh no. Thanks for the ping!
The proper link should be https://wasmerio.github.io/wasmer/crates/wasmer/
