### ISSUE TITLE
Does the LLVM Compiler Support bulk_memory?

### ISSUE THREAD

**Issue by jozanza** [wasmerio/wasmer#2252]
### Summary

I'm using the llvm compiler along with the native engine, and bulk_memory instructions like `memory.copy` seem to cause panics.

### Additional details

It looks like certain wasm bulk memory operators, such as `MemoryCopy`, are not implemented by `compiler-llvm`. In cases when certain instructions are run (`memory.copy`, `memory.fill`, etc), the wasm execution will crash, hitting [this default case](https://github.com/wasmerio/wasmer/blob/master/lib/compiler-llvm/src/translator/code.rs#L9598-L9603).

My `wasmer` dependency in `Cargo.toml` looks like this:
```toml
wasmer = { version = "1.0.2", default-features = false, features = ["wat", "default-native", "default-llvm" ] }
```

**Comment by VictorBulba** [comment]
+1

My error messages: 
`Codegen("Operator MemoryCopy { src: 0, dst: 0 } unimplemented")`
`Codegen("Operator MemoryFill { mem: 0 } unimplemented")`

**Comment by nlewycky** [comment]
We support TableCopy, TableInit and ElemDrop because those are used by the reference types proposal (as well as TableFill and TableGrow which aren't in the bulk memory proposal) but not the other operators.

**Comment by jozanza** [comment]
Thanks for the clarification @nlewycky! Is there any plan to add those extra couple memory ops? It looks like bulk_memory is a [finished proposal](https://github.com/WebAssembly/proposals/blob/master/finished-proposals.md) at this point and is making its way into browsers, so it'd be really nice for compatibility.
