### ISSUE TITLE
Working Example of Copying Data to Host Memory

### ISSUE THREAD

**Issue by dbcfd** [wasmerio/wasmer#2255]
### Summary

I'm looking for a working example of a Rust wasm plugin copying data to a Rust application running Wasmer.

### Additional details

Here is what I've tried so far
- Return a CString from Rust as u32, recreate in host
- Copy a length into environment memory using an import call and environment, return u32 pointer, read length from memory, copy data in host
- Return a pointer to environment memory via import call. Copy wasm memory into this pointer.
- Pass a pointer and length to host memory via import call. Copy into environment memory.

In most cases, there's a mismatch in address between host and module (64bit vs 32bit), so when possible I've also split the address into two u32. The most common outcome is an invalid memory access and a `Trap(HeapAccessOutOfBounds)`.

**Comment by MarkMcCaskey** [comment]
Hello, thanks for the issue! WebAssembly cannot access host memory at all as it's sandboxed. So all memory transfer must be done in the Wasm linear memory.

You can use something like [`WasmPtr`](https://docs.rs/wasmer/1.0.2/wasmer/struct.WasmPtr.html) on the host to read and write memory.

The fundamental idea is:

- get an offset (32bit) from the Wasm program
- add offset to linear memory base (64bit pointer on the host) to get a pointer to that memory
- read and write to the computed address.

`WasmPtr` is a nice abstraction to help you do that.

I'll follow up early next week if you have any questions about this

**Comment by dbcfd** [comment]
So I was able to get memory out of wasm. Main thing is using `instance.exports.get_memory("memory")` and then treating that as the base address in wasm. Then had to realize WasmPtr isn't really a pointer, but an offset in that linear memory. I was then able to use memory from the store/host via a host call, using the same offset approach.

Code here https://github.com/dbcfd/wasmer-test

Thanks for the help.

**Comment by dbcfd** [comment]
I was wrong, I wasn't actually able to get use the host memory that I created with `Memory::new(&store`. Was hoping to use that as a way to share data amongst multiple modules, but not sure why that isn't working. Copying data to the module memory works though.

**Comment by dbcfd** [comment]
Same issue, tried to use ptr, instead of WasmPtr with a defined offset. All working now.

**Comment by MarkMcCaskey** [comment]
> I wasn't actually able to get use the host memory that I created with Memory::new(&store. Was hoping to use that as a way to share data amongst multiple modules, but not sure why that isn't working

The issue is likely that by default programs compiled to the WASI ABI export memories, not import them. So if you're making your own memory, the Wasm module likely isn't using it. You can run `wasmer inspect file.wasm` on a file to see its exports
