### ISSUE TITLE
Question About Memory Docs

### ISSUE THREAD

**Issue by dbcfd** [wasmerio/wasmer#2273]
### Summary
From https://docs.rs/wasmer/1.0.2/wasmer/struct.Memory.html

```
A memory created by the host or in WebAssembly code will be accessible and mutable from both host and WebAssembly.
```

Can you explain what it means for a memory created by the host to be accessible by WebAssembly? Is

```rust
let m = Memory::new(&store, MemoryType::new(1, None, false)).unwrap();
```

the memory created by the host? If so, how is that then exposed to WebAssembly?

**Comment by syrusakbary** [comment]
> the memory created by the host?
Yeah, that's right.

You will need to expose that memory `m` to WebAssembly via an import.

Such as:
```rust
    let import_object = imports! {
        "env" => {
            "memory" => m // or whatever is the imported name for that memory
        }
    };
    let instance = Instance::new(&module, &import_object)?;
```
