### ISSUE TITLE
Provide an option to load AoT binary files

### ISSUE THREAD

**Issue by c0diq** [wasmerio/wasmer#2278]
Wasmer command line allows running AoT file compiled with Wasmer.
```
> wasmer compile foo.wasm -o foo.dylib --native
> Wasmer run foo.dylib
```

However there is no C-API equivalent to instantiate a AoT file from what I can tell. The `serialized` version seems to be for loading a JIT binary serialized to disk.

**Comment by syrusakbary** [comment]
Sorry for the delay, I just realized of this issue by looking individually at repos.
It would be a great idea to add a new `deserialize_from_file` API to the Wasmer C API.

Would you like to contribute with a PR adding this feature? :)

**Comment by Hywan** [comment]
Hello @c0diq,

Once a `wasm_module_t` is built with `wasm_module_new`, the Wasm module is already compiled. You can serialize it with the non-standard function [`wasm_module_serialize`](https://docs.rs/wasmer-c-api/2.0.0/wasmer_c_api/wasm_c_api/module/fn.wasm_module_serialize.html), and deserialize with the non-standard function [`wasm_module_deserialize`](https://docs.rs/wasmer-c-api/2.0.0/wasmer_c_api/wasm_c_api/module/fn.wasm_module_deserialize.html) (this later contains a fully working example).

You can define your compiler with [`wasm_config_set_compiler`](https://docs.rs/wasmer-c-api/2.0.0/wasmer_c_api/wasm_c_api/engine/fn.wasm_config_set_compiler.html) and your engine with [`wasm_config_set_engine`](https://docs.rs/wasmer-c-api/2.0.0/wasmer_c_api/wasm_c_api/engine/fn.wasm_config_set_engine.html). All the functions have attached examples.

Hope this helps. I'm closing the issue as I believe I've answered the question.
