### ISSUE TITLE
Wasmer can't run non-wasi files (master)

### ISSUE THREAD

**Issue by syrusakbary** [wasmerio/wasmer#2282]
### Describe the bug

I think due to latest changes in WASI. detection wasmer is no longer able to run simple files:

```bash
➜ ./target/release/wasmer tests/examples/fac.wat
error: failed to run `tests/examples/fac.wat`
│   1: WASI execution failed
╰─> 2: The WASI version could not be determined
```

**Comment by MarkMcCaskey** [comment]
Good catch, we should definitely have an integration test for this

**Comment by MarkMcCaskey** [comment]
Oh! This edge case is far more subtle, the bug is specifically WASI ABIs that don't have any WASI imports, we fail to detect anything so say that it "isn't WASI", I suppose we should default to the latest ABI in that case
