### ISSUE TITLE
error: unable to rename temporary

### ISSUE THREAD

**Issue by vshymanskyy** [wasmerio/wasmer#2297]
### Describe the bug

Ubuntu 21.04
wasmer 1.0.2 | x86_64

Trying to run `clang.wasm`, getting `error: unable to rename temporary 'source/hello/hello-1df6f5ea.o.tmp' to output file 'source/hello/hello.o': 'I/O error'`.
It seemed to work when the source/destination were in the root, but fails in subfolders.

https://github.com/wasm3/wasm3-self-compiling/blob/7a251d9483cdd4f559e7cf4af36a6468af100ea4/Makefile#L21-L26

### Steps to reproduce

```sh
git clone https://github.com/wasm3/wasm3-self-compiling.git

cd wasm3-self-compiling

wasmer run --mapdir=/:. --mapdir=./:. ./wasm/clang.wasm -- -cc1 -triple wasm32-unknown-wasi -isysroot /sys -internal-isystem /sys/include -emit-obj -o source/hello/hello.o source/hello/hello.c -O3
```

### Expected behavior

Compilation succeeds.

### Actual behavior

`error: unable to rename temporary 'source/hello/hello-1df6f5ea.o.tmp' to output file 'source/hello/hello.o': 'I/O error'`

**Comment by chenyukang** [comment]
I'm fixing this...
