### ISSUE TITLE
How to define the export/import name of a C function?

### ISSUE THREAD

**Issue by kan-fumihito** [wasmerio/wasmer#2322]
### Summary

 I want to name exported function, so that i can use host function in wasm in C++.
In Rust, this is what i want to do,
```Rust
fn func_one(a :i32) -> i32{
  a + 1
}
fn func_two(b :i32) -> i32{
  b + 2
}
fn main(){
   // ...
   imports! {
           "env" => {
               "func_one" => func_one,
               "func_two" => func_two,
           },
       }
}
```
and wasm,
```WebAssembly
(module
   (type $func_t (func (param i32) (result i32)))
   (import "env" "func_one" (func $func_one (type $funt_t)))
   (import "env" "func_two" (func $func_two (type $funt_t)))
   ;; ...
)
```

I cannot find document relative this usecase in C/C++.

### Additional details
I don't know why exported function name will be 'host_function' by default, and global too.
I wanna know this.

**Comment by Hywan** [comment]
Hello,

Thanks for asking this.

There is a small confusion in the namings:
* An exported function is a function that is exported from the Wasm module, so it lives on the Wasm side.
* An imported function is a function that is imported from the host to the Wasm module, so it lives on the host side.

Knowing that, in Rust it's really to define the exported function name like this:

```
#[no_mangle]
pub fn sum(x: i32, y: i32) -> i32 { x + y }
```

The `#[no_mangle]` attribute tells the compiler to not rename (_mangle_) the function.

And to define an imported function, you have to do this:

```
#[link(wasm_import_module = "math")]
extern "C" {
    fn sum(x: i32, y: i32) -> i32;
}
```

will is equivalent to `(import "math" "sum" (func …))`.

For C/C++ though, it's a little bit trickier. Check https://aransentin.github.io/cwasm/ to learn more.

To define an exported function, you have to pass the `-fvisibility hidden` argument to the C compiler to hide all symbols, except the one that are marked with `__attribute__(visibility("default"))`:

```c
#define export __attribute__((visibility( "default")) 

export uint32_t sum(uint32_t x, uint32_t y) {
    return x + y;
}
```

To define an imported function, using an `extern "C" { … }` block should fulfill your need. However, I don't know how to pass the module name.

**Comment by Rochet2** [comment]
> However, I don't know how to pass the module name.

You can use various attributes to set the names in C/C++ for clang. See https://clang.llvm.org/docs/AttributeReference.html
Couldn't get online compilers to use the attributes though, but they should work with clang (emscripten, wasi-sdk).
You can use one or more attributes, so you can just define the module or just the name.

```
__attribute__((import_module("module_name")))
__attribute__((import_name("function_name")))

__attribute__((export_name("function_name")))
```

For example
```cpp
__attribute__((import_module("env")))
__attribute__((import_name("func_one")))
int example_function(int);
```

**Comment by Hywan** [comment]
Thanks @Rochet2 for the answer!
