### ISSUE TITLE
c-api: missing symbols declared in wasm.h

### ISSUE THREAD

**Issue by kubkon** [wasmerio/wasmer#2344]
### Describe the bug

While splitting up common implementation of `wasm.h` shared by the runtimes (here, Wasmer and Wasmtime), I've stumbled upon a few missing symbols.

### Steps to reproduce

Head over to [wasmer-zig](https://github.com/kubkon/wasmer-zig), and follow the instructions to run the default example:

```sh
$ gyro build run -Dexample=instance
```

### Expected behavior

The missing symbols should be successfully resolved by `lld.ld`.

### Actual behavior

Note that there might be more missing symbols, but these are the ones you'll get when trying to run a Zig version of [instance.c](https://github.com/wasmerio/wasmer/blob/master/lib/c-api/examples/instance.c):

```sh
ld.lld: error: undefined symbol: wasm_func_copy
>>> referenced by main.zig:157 (/home/kubkon/dev/wasmer-zig/.gyro/wasm-zig-kubkon-9c42564835bd97ec0e8edf3f93411a1a52b49cc9/pkg/src/main.zig:157)
>>>               /home/kubkon/dev/wasmer-zig/zig-cache/o/06f5c0423f3306307f3110e3ed1105a8/instance.o:(.wasmer.wasm.Func.copy)

ld.lld: error: undefined symbol: wasm_instance_type
>>> referenced by main.zig:319 (/home/kubkon/dev/wasmer-zig/.gyro/wasm-zig-kubkon-9c42564835bd97ec0e8edf3f93411a1a52b49cc9/pkg/src/main.zig:319)
>>>               /home/kubkon/dev/wasmer-zig/zig-cache/o/06f5c0423f3306307f3110e3ed1105a8/instance.o:(.wasmer.wasm.Instance.getType)

ld.lld: error: undefined symbol: wasm_instancetype_exports
>>> referenced by main.zig:538 (/home/kubkon/dev/wasmer-zig/.gyro/wasm-zig-kubkon-9c42564835bd97ec0e8edf3f93411a1a52b49cc9/pkg/src/main.zig:538)
>>>               /home/kubkon/dev/wasmer-zig/zig-cache/o/06f5c0423f3306307f3110e3ed1105a8/instance.o:(.wasmer.wasm.InstanceType.exports)

ld.lld: error: undefined symbol: wasm_instancetype_delete
>>> referenced by main.zig:532 (/home/kubkon/dev/wasmer-zig/.gyro/wasm-zig-kubkon-9c42564835bd97ec0e8edf3f93411a1a52b49cc9/pkg/src/main.zig:532)
>>>               /home/kubkon/dev/wasmer-zig/zig-cache/o/06f5c0423f3306307f3110e3ed1105a8/instance.o:(.wasmer.wasm.InstanceType.deinit)
error: LLDReportedFailure
```

### Additional context

If we list symbols provided by latest `libwasmer.so` and grep for `wasm_func_copy`, it is indeed missing:

```sh
$ nm $(wasmer config --libdir)/libwasmer.so | grep wasm_func_copy

```

The same symbol is provided by `libwasmtime.so` for comparison:

```sh
$ nm libwasmtime.so | grep wasm_func_copy
0000000000115770 T wasm_func_copy
```

**Comment by MarkMcCaskey** [comment]
Thanks for the report, I've added `wasm_func_copy` support locally, however I don't believe any of those `instancetype` symbols are part of the Wasm C API. They're not declared in `wasm.h`, so I would assume that's a wasmtime specific extension to the Wasm C API (if they're in libwasmtime). I'll push up a PR with `wasm_func_copy` though!

**Comment by kubkon** [comment]
> Thanks for the report, I've added `wasm_func_copy` support locally, however I don't believe any of those `instancetype` symbols are part of the Wasm C API. They're not declared in `wasm.h`, so I would assume that's a wasmtime specific extension to the Wasm C API (if they're in libwasmtime). I'll push up a PR with `wasm_func_copy` though!

Oh oops, that may very well be. I’ll double check then. Thanks for the quick turnaround @MarkMcCaskey!
