### ISSUE TITLE
Proposal: Deny missing documentations

### ISSUE THREAD

**Issue by Hywan** [wasmerio/wasmer#235]
Hello fellow wasmerians,

I would like to propose to forbid missing documentations, with `#[deny(missing_docs)]`. I think it's important to provide a strong documentation and a strong code quality. This attribute is a first step in that direction. It will also ease contributions.

If everyone agrees, I think it would be great to create one issue per crate so that it's easier to track the progression.

Thoughts?

**Comment by bjfish** [comment]
👍

**Comment by syrusakbary** [comment]
I like this idea!

**Comment by MarkMcCaskey** [comment]
I think we generally have this in Wasmer now and it's been great!  So I'm going to close this issue
