### ISSUE TITLE
feat: Deny warnings

### ISSUE THREAD

**Issue by Hywan** [wasmerio/wasmer#236]
Hello fellow wasmerians,

In order to continue our quest to quality, I propose to deny warnings. I think it's the first baby step to code quality.

Thus, I'm proposing to add `#![deny(warnings)]` into all crates.

Thoughts?

Progression:

 * [ ] `clif-backend`,
 * [ ] `dynasm-backend`,
 * [ ] `emscripten`,
 * [ ] `llvm-backend`,
 * [ ] `runtime`,
 * [ ] `runtime-abi`,
 * [ ] `runtime-c-api`,
 * [ ] `runtime-core`,
 * [ ] `spectests`,
 * [ ] `win-exception-handler`.

**Comment by bjfish** [comment]
👍

**Comment by CryZe** [comment]
I forgot if this affects dependent crates as well, but if it does I'd highly recommend not using this. However if it doesn't then it might be fine, although personally I've noticed that it's really bad for actually refactoring the code (as nothing compiles anymore, so how do you verify any intermediate steps?). So ultimately I'd recommend denying warnings on CI only.

**Comment by bjfish** [comment]
I think if I was working on a refactoring or big feature branch I’d probably comment this out temporarily.  Or I think there is also a rust or cargo flag to allow warnings.

**Comment by CryZe** [comment]
Denying warnings on CI and just warning locally (for both normal warnings and missing docs) would still be a lot more ergonomic for devs. Also rustc is adding all kinds of warnings all the time, so denying in general is also questionable, as old versions just straight up fail building then, breaking semver completely (not sure if deny applies to dependencies though, but at least binaries of wasmer wouldn't compile anymore).

**Comment by Hywan** [comment]
It only affects the current crate, not the dependencies.

**Comment by MarkMcCaskey** [comment]
I believe we also have this in Wasmer.  I think we're not doing `deny(warnings)` directly but are linting for the most common in CI
