### ISSUE TITLE
Failed to run wasm module produced from emscripten

### ISSUE THREAD

**Issue by oeway** [wasmerio/wasmer#2385]
### Describe the bug
I am trying to compile and run my own wasm module compiled with emscripten(with `-s STANDALONE_WASM`, `emsdk version: 2.0.23`), it works in my browser but when I run it with wasmer, it failed. 

I used the latest wasmer-cli, x86_64 on ubuntu.

### Steps to reproduce

Download my wasm module [here](https://github.com/imjoy-team/imjoy-potree-converter/releases/download/v0.1.0/PotreeConverter.wasm), and use wasmer to run it.

### Expected behavior

It should print the command help strings.

### Actual behavior
```bash
$ wasmer run ./PotreeConverter.wasm 
error: failed to run `./PotreeConverter.wasm`
╰─> 1: Error while importing "env"."__cxa_rethrow": unknown import. Expected Function(FunctionType { params: [], results: [] })
```

### Additional context

I also tried to compile my module with `emsdk 1.38.43`, here is the error:
```bash
$ wasmer run ./PotreeConverter.wasm 
error: failed to run `./PotreeConverter.wasm`
│   1: This module has both Emscripten and WASI imports. Wasmer does not currently support Emscripten modules using WASI imports.
╰─> 2: Error while importing "env"."___cxa_uncaught_exceptions": unknown import. Expected Function(FunctionType { params: [], results: [I32] })
```

**Comment by chenyukang** [comment]
This seems a known issue: 

Refer to #2308 
```
Emscripten and WASI are really different ABI, and that's why Wasmer doesn't support both at the same time. Wasmer support Emscripten, or WASI, but separately.
```

**Comment by oeway** [comment]
Thanks! Do you know how to fix this issue? Please note that when I use emsdk 2, it does not show the error message about "This module has both Emscripten and WASI imports.".

I am very new to wamser, wondering if I want to just compile my c++ command line project to run with wasmer, is there a specific guideline I can follow to make it work?

**Comment by Hywan** [comment]
Supporting WASI and Emscripten at the same time is unlikely to happen soon.

Also, Emscripten doesn't define any official specification for their ABI. Our Emscripten support is then outdated as far as I know since emscripten version 2.0. @MarkMcCaskey may confirm that :-).

You can try to compile your C project with wasienv or clang to target wasm32-wasi only.
