### ISSUE TITLE
Compilation failing with invalid field

### ISSUE THREAD

**Issue by MidasLamb** [wasmerio/wasmer#2389]
### Describe the bug

When trying to run the embedded rust example in the doc, following error is shown:
```sh
error[E0609]: no field `Rip` on type `CONTEXT`
   --> C:\Users\Midas\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmer-vm-1.0.2\src\trap\traphandlers.rs:330:56
    |
330 |                     (*(*exception_info).ContextRecord).Rip as *const u8,
    |                                                        ^^^ help: a field with a similar name exists: `Eip`

error: aborting due to previous error
```

### Steps to reproduce

1. Copy paste the example from https://docs.rs/wasmer/1.0.2/wasmer/
2. Compile with target i686-pc-windows-msvc (not sure if this is required)
3. Run `cargo b`
4. See error during compilation of rust.

### Expected behavior
Compilation succeeds

### Actual behavior
Compilation failed

**Comment by syrusakbary** [comment]
This issue seems to appear when compiling Wasmer in 32-bit Windows environments. In 64-bit ones it works properly

**Comment by MidasLamb** [comment]
> This issue seems to appear when compiling Wasmer in 32-bit Windows environments. In 64-bit ones it works properly

In the PR that I made, it seems that it's just targeting windows, without any dependency on whether it's 32 or 64 bit (unless that's decided somewhere higher up the tree): 
``` rust
} else if #[cfg(target_os = "windows")] {
```
