### ISSUE TITLE
WASMER_INSTALL_PREFIX will cause confusion in install

### ISSUE THREAD

**Issue by chenyukang** [wasmerio/wasmer#2413]
### Summary

As a normal case in building from source on Linux/Unix. I will use 
```
make 
sudo make install
```
to build and install from source code.

But follow these steps, there will be an error like this by default: 
```
target/release/wasmer config --pkg-config | install -Dm644 /dev/stdin "/usr/local"/lib/pkgconfig/wasmer.pc
unset WASMER_DIR # Make sure WASMER_INSTALL_PREFIX is set during build
error: failed to retrieve the wasmer config
│   1: failed to retrieve the WASMER_DIR environment variables
╰─> 2: environment variable not found
```

Then, I need to find the document, and the document is not clear about this,  https://github.com/wasmerio/wasmer/blob/master/PACKAGING.md.
Actually, we need to add `WASMER_INSTALL_PREFIX` in the `make` stage, not `make install` stage.

By default, `makefile` use `DISTDIR` as the target directory. 
https://github.com/wasmerio/wasmer/blob/144300e0bc51d01290680a46cd30a6ca76ed0359/Makefile#L632

I saw the `WASMER_INSTALL_PREFIX` is introduced by this commit: https://github.com/wasmerio/wasmer/commit/80ec06ffab9d7af017a5a5490d153a2230f9374a

I don't get the point for this variable, and I think it makes some confusion.  

If we want to configure the path, we need to add two environment variables, `WASMER_INSTALL_PREFIX` to recompile the whole project.

**Comment by jcaesar** [comment]
> I don't get the point for this variable, and I think it makes some confusion.

I might have wanted to document that more. (In my defence, you're picking an undocumented installation route, [I think](https://github.com/wasmerio/wasmer-install).)

The intention behind having `DESTDIR` and  `WASMER_INSTALL_PREFIX` is that many distros stage installation in some `/tmp/foo/bar/usr` path before building a package, and then install that to `/usr`. Problem is: When wasmer is being `make install`ed to `DESTDIR=/tmp/foo/bar/usr`, how would it know that it's supposed to include its headers from `/usr/include`? So, `WASMER_INSTALL_PREFIX` must be compiled in.


> If we want to configure the path, we need to add two environment variables, WASMER_INSTALL_PREFIX to recompile the whole project.

I'm not sure what you mean by this. Is this a change that needs to be contributed to wasmer's source, or something that a user needs to do to install/use wasmer?

> Then, I need to find the document, and the document is not clear about this, https://github.com/wasmerio/wasmer/blob/master/PACKAGING.md.

That's the *distro packaging* manual, and unrelated to your case. Can I somehow make that clearer? (You're not packaging for a distro, are you?)
