### ISSUE TITLE
2.0.0-rc2 not published to crates.io

### ISSUE THREAD

**Issue by webmaster128** [wasmerio/wasmer#2421]
### Summary

It looks like version 2.0.0-rc2 was not published to crates.io. Could this be done? rc1 is there: https://crates.io/crates/wasmer/versions

### Additional details

We'd like to test it in CosmWasm (https://github.com/CosmWasm/cosmwasm/pull/955)

**Comment by webmaster128** [comment]
[wasmer-types was updated to rc2](https://crates.io/crates/wasmer-types/versions)

**Comment by MarkMcCaskey** [comment]
Oops, looks like the publish process may have been interrupted. 2.0.0-rc2 contains no changes to the crates (other than wasmer-cli) so there's no real reason to update, but I'll look into this and fix it today

**Comment by MarkMcCaskey** [comment]
Alright, I just reran the publishing script to push all the 2.0.0-rc2 crates up to crates.io . The code should be identical to 2.0.0-rc1 so if it worked with that, it'll work with this too
