### ISSUE TITLE
wasmer 2.0.0: Invalid syntax in `wax`

### ISSUE THREAD

**Issue by KSXGitHub** [wasmerio/wasmer#2425]
The `wax` file is not a valid shell file.

## Steps to reproduce

1. Go to the release page of 2.0.0 and download [wasmer-linux-amd64.tar.gz](https://github.com/wasmerio/wasmer/releases/download/2.0.0/wasmer-linux-amd64.tar.gz).
2. Extract the archive.
3. Open `bin/wax` in a text editor.

## Expected behavior

`wax` is a valid shell file:

```sh
#! /bin/bash
exec wapm execute "$@"
```

## Actual behavior

`wax`'s shebang is messed up:

```
#!/bin/bash\nwapm execute "$@"
```

**Comment by Hywan** [comment]
Thank you for the bug report.

It's a difference between `echo` and `echo -e` in macOS and Linux. Let's fix that!

**Comment by KSXGitHub** [comment]
> It's a difference between `echo` and `echo -e` in macOS and Linux. Let's fix that!

You can just call `echo` twice.

**Comment by KSXGitHub** [comment]
> Also yes, or just do this:
> 
> ```shell
> echo "hello
> world"
> ```

Because of indentation, it would actually be:

```sh
    # ...
    echo "hello
world"
    # ...
```
