### ISSUE TITLE
LLVM 13 support

### ISSUE THREAD

**Issue by 12101111** [wasmerio/wasmer#2433]
Thanks for proposing a new feature!

### Motivation

The inkwell fork https://github.com/wasmerio/inkwell/ is outdated and don't support LLVM 12.

### Proposed solution

Uptream already support LLVM 12: https://github.com/TheDan64/inkwell/pull/253

**Comment by Hywan** [comment]
Hello,

First step is to support LLVM 12 in our build toolchain. I've opened https://github.com/wasmerio/llvm-custom-builds/pull/17 to address that.

Then we would need to update our fork of inkwell. After that, we will update `wasmer-compiler-llvm` along with our CI to support LLVM 12 (in the `Makefile` and so on).

**Comment by Hywan** [comment]
As expected, the second step is to update our fork of inkwell, https://github.com/wasmerio/inkwell/pull/1.

**Comment by syrusakbary** [comment]
This is now fixed (#2645 has just been merged)
