### ISSUE TITLE
build failed with LLVM11 on WSL

### ISSUE THREAD

**Issue by chenyukang** [wasmerio/wasmer#2435]
### Summary

Seems we just moved to LLVM11 recently.
I'm trying to build with llvm, and stuck at this error.

`make build-wasmer` will report this error: 

```
error: could not find native static library `Polly`, perhaps an -L flag is missing?

error: aborting due to previous error

error: could not compile `llvm-sys`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [Makefile:341: build-wasmer] Error 101
```

### Additional details

There is only dynamic library in llvm-11/lib:

```
~/wasmer$ ls -l /usr/lib/llvm-11/lib | grep Polly
-rw-r--r-- 1 root root  3783072 Oct 30  2020 LLVMPolly.so
```

I use this command to install llvm11 on WSL:

```bash
sudo apt-get install llvm-11*
```

**Comment by chenyukang** [comment]
@jubianchi  Do you know how to resolve this?

**Comment by chenyukang** [comment]
It seems an issue for `llvm-sys`. 
Rollback to llvm10 will be OK: 

```
--- a/lib/compiler-llvm/Cargo.toml
+++ b/lib/compiler-llvm/Cargo.toml
@@ -28,7 +28,7 @@ loupe = "0.1"
 package = "wasmer_inkwell"
 version = "0.2.0-alpha.2"
 default-features = false
-features = ["llvm11-0", "target-x86", "target-aarch64"]
+features = ["llvm10-0", "target-x86", "target-aarch64"]
```

**Comment by Hywan** [comment]
Please open an issue for [`llvm-sys`](https://gitlab.com/taricorp/llvm-sys.rs/) or [`inkweel`](https://github.com/TheDan64/inkwell). I've never tried to install LLVM through WSL, I don't know what to expect in that situation.

**Comment by Hywan** [comment]
@chenyukang Did you open an issue on `inkwell` or `llvm-sys`?

**Comment by chenyukang** [comment]
> @chenyukang Did you open an issue on `inkwell` or `llvm-sys`?

I haven't, a little busy recently, I may need more investigation about it.

**Comment by chenyukang** [comment]
I opened an issue for llvm-sys.rs： 
https://gitlab.com/taricorp/llvm-sys.rs/-/issues/16

**Comment by chenyukang** [comment]
It turns out there is a bug for Ubuntu distribution: ,
as a workaround, we could use this command to fix it:

```bash
sudo apt-get install libclang-common-11-dev
```

**Comment by Hywan** [comment]
It would be good to document that somewhere. Maybe in the `lib/compiler-llvm/README.md` file? What do you think?

**Comment by Hywan** [comment]
And thank you for your investigation!

**Comment by chenyukang** [comment]
> It would be good to document that somewhere. Maybe in the `lib/compiler-llvm/README.md` file? What do you think?

Good idea, let me open a PR.

**Comment by Hywan** [comment]
@chenyukang can we close the issue now :-)?

**Comment by chenyukang** [comment]
I think this may take a long time. https://bugs.launchpad.net/ubuntu/+source/llvm-toolchain-11/+bug/1934927
And our document had added:
```
wget https://apt.llvm.org/llvm.sh -O /tmp/llvm.sh
sudo bash /tmp/llvm.sh 11
```


 https://apt.llvm.org/llvm.sh is the right way to install LLVM related packages, don't have this issue.

**Comment by Hywan** [comment]
I understand this is a yes, we can close the issue :-).
