### ISSUE TITLE
Trap messages get an extra null terminator

### ISSUE THREAD

**Issue by liamappelbe** [wasmerio/wasmer#2439]
### Describe the bug
Trap messages get an extra null terminator, even if they're already null terminated.

I'm using wasmer-c-api version 1.0.2 on Windows.

### Steps to reproduce
As a work around to #2438, I'm trying to set the trap message to a unique string to use as a key in a map. I create a trap using `wasm_trap_new`, and pass it a `wasm_byte_vec_t` like `[100, 97, 114, 116, 58, 99, 49, 119, 109, 119, 97]`. This trap is returned from 
a function created using `wasm_func_new_with_env`. When I catch the trap returned by `wasm_func_call`, the `wasm_byte_vec_t` is `[100, 97, 114, 116, 58, 99, 49, 119, 109, 119, 97, 0]`.

I also tried explicitly null terminating the `wasm_byte_vec_t`, and then the returned vector is `[100, 97, 114, 116, 58, 99, 49, 119, 109, 119, 97, 0, 0]`.

This means that the returned message doesn't match the one I'm using as a key in my map. I'll work around it for now by just dropping any null terminators before using it as a map key.

### Expected behavior
The `wasm_byte_vec_t` message on the trap returned by `wasm_func_call` should be the same as the one returned by the callback function.

### Actual behavior
The `wasm_byte_vec_t` gets an extra 0 at the end.

**Comment by syrusakbary** [comment]
Thanks for the great analysis @liamappelbe, we'll take a look at it soon!

**Comment by Hywan** [comment]
The null byte is added here:

https://github.com/wasmerio/wasmer/blob/6773109fe0cf2fea78376939e084c097d37a9629/lib/c-api/src/wasm_c_api/trap.rs#L34-L47

**Comment by Hywan** [comment]
It comes from the standard `wasm.h` file:

https://github.com/WebAssembly/wasm-c-api/blob/c9d31284651b975f05ac27cee0bab1377560b87e/include/wasm.h#L378

which we use and is up-to-date:

https://github.com/wasmerio/wasmer/blob/6773109fe0cf2fea78376939e084c097d37a9629/lib/c-api/tests/wasm-c-api/include/wasm.h#L378-L384

The Trap API uses `wasm_message_t`, which is like `wasm_name_t` but the message is null terminated.

**Comment by Hywan** [comment]
Classical way to create a trap message is the following:

```c
  own wasm_message_t trap_message;
  wasm_name_new_from_string_nt(&trap_message, "trapping from a host import");
  own wasm_trap_t *trap = wasm_trap_new(store, &trap_message);
  wasm_name_delete(&trap_message);
```

It uses the `wasm_name_new_from_string_nt` function from `wasm.h`, which includes the null byte at the end of the string.

**Comment by Hywan** [comment]
The bug I see is that we always add a null byte at the end, whatever the message contains. We must add a test here. I'm fixing it.

**Comment by Hywan** [comment]
The bug is fixed. It's under review.
