### ISSUE TITLE
Simple emscripten wasm causes error

### ISSUE THREAD

**Issue by richardanaya** [wasmerio/wasmer#244]
```
(module
  (type $t0 (func (result i32)))
  (type $t1 (func (param i32 i32 i32) (result i32)))
  (import "env" "_emscripten_memcpy_big" (func $env._emscripten_memcpy_big (type $t1)))
  (func $main (export "main") (type $t0) (result i32)
    i32.const 0)
  (memory $memory (export "memory") 2 10)
  (global $g0 i32 (i32.const 0))
  (global $g1 (mut i32) (i32.const 0)))
```

**Comment by richardanaya** [comment]
```
wasmer run wasmer.wasm
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/circleci/project/lib/runtime-core/src/structures/slice.rs:58:10
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Makefile:2: recipe for target 'run' failed
make: *** [run] Error 101
```

**Comment by xmclark** [comment]
hello @richardanaya, and thanks for reporting the crash! That example seems like it should just work 🙃 

Can you tell us what version of wasmer (from source, or installer) you're using, and what OS you're on? Thanks!

**Comment by richardanaya** [comment]
2.1 on Linux, I think right now there are some strong assumptions in code
that I import table and memory

**Comment by richardanaya** [comment]
I also was able to repro on source

**Comment by xmclark** [comment]
Did you generate this module from source code (e.g. with emscripten or cargo) or did you write it by hand? It seems odd that it is exporting a memory. This is not a judgement, just an observation.

**Comment by richardanaya** [comment]
I have a simple programming language for web assembly that exposes its
memory by default so that browser host can send memory into the wasm module.

**Comment by xmclark** [comment]
Wow very cool! I am actually super curious to hear about how you're doing that and how it's going 😻 

There may be some edge case we are not accounting for. Emscripten is a funny thing. Regardless, Wasmer should *not* crash here. We should at least get an elegant failure. I am taking a look into this soonish.

**Comment by richardanaya** [comment]
This project is extremely alpha

https://github.com/wasplang/wasp

here's the code I generated the wasm from:

https://github.com/wasplang/wasp/blob/master/examples/wasmer/main.w

**Comment by syrusakbary** [comment]
Emscripten requires at least one imported table. We are pushing a change to throw an exception when that's not the case.
