### ISSUE TITLE
HostFile::poll in WasiFile is not implemented for non-Unix-like targets yet?

### ISSUE THREAD

**Issue by coolxv** [wasmerio/wasmer#2440]
### Summary
Windows 10  wasmer 2.0

PS E:\work-wasm\wasmer\bin> .\wasmer.exe .\qjs.wasm
QuickJS - Type "\h" for help
qjs > thread 'main' panicked at 'not implemented: HostFile::poll in WasiFile is not implemented for non-Unix-like targets yet', lib\wasi\src\state\types.rs:403:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by Hywan** [comment]
Closing as it is a duplication of #570.
