### ISSUE TITLE
pthread_attr_setdetachstate is not implemented

### ISSUE THREAD

**Issue by hatf0** [wasmerio/wasmer#2441]
### Describe the bug
The pthread function "pthread_attr_setdetachstate" is not implemented (or stubbed out?), resulting in code which uses this routine to fail to run. 
```
wasmer run (wasm file which imports pthread_attr_setdetachstate)
error: failed to run `(file which imports pthread_attr_setdetachstate).wasm`
│   1: This module has both Emscripten and WASI imports. Wasmer does not currently support Emscripten modules using WASI imports.
╰─> 2: Error while importing "env"."_pthread_attr_setdetachstate": unknown import. Expected Function(FunctionType { params: [I32, I32], results: [I32] })
```

The first error message seems to be erroneous -- `wasmer inspect` does not show that the module imports any functions within the WASI namespace, please ignore.

```sh
wasmer 2.0.0 | rustc 1.49.0 (e1884a8e3 2020-12-29) | x86_64
```

### Steps to reproduce
* Run a wasm file that imports pthread_attr_setdetachstate

### Expected behavior

* No error regarding pthread_attr_setdetachstate

### Actual behavior
* Error regarding pthread_attr_setdetachstate

### Additional context
Can attach the file that I'm working on which imports it, if necessary.

**Comment by Hywan** [comment]
Hello,

Thank you for the bug report. WebAssembly doesn't support thread yet. [The Thread proposal](https://github.com/WebAssembly/threads/) is still at [phase 2](https://github.com/WebAssembly/proposals#phase-2---proposed-spec-text-available-cg--wg) at the time of writing.

I'm closing the issue as it's basically not supported by WebAssembly right now :-).

Feel free to reopen if you feel the need or if you disagree :-). Thanks!
