### ISSUE TITLE
Wasmer fails to validate WASM file built with rustc 1.53.0

### ISSUE THREAD

**Issue by 4LT** [wasmerio/wasmer#2443]
[qmpp_hello_plugin.zip](https://github.com/wasmerio/wasmer/files/6712694/qmpp_hello_plugin.zip)
Not sure if this is a wasmer bug or a rustc bug!

Module::from_file returns an Err when my module is built with `--release` (does not occur on debug builds)

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Compile(Validate("Unexpected EOF (at offset 1540335)"))', src/main.rs:52:70
```

Relevant source:
```rs
let module = Module::from_file(&store, "qmpp_hello_plugin.wasm").unwrap();
```

wasmer 2.0.0
rustc 1.53.0
Linux 5.12

### Expected behavior
Module is loaded from file.

### Actual behavior
An `Err` is returned.

Module source:
```rs
use std::ffi::CString;

#[allow(non_snake_case)]
#[no_mangle]
pub extern "C" fn QMPP_Hook_init() {
    let name = CString::new(&b"Hello"[..]).unwrap();
    unsafe {
        QMPP_register(name.as_ptr());
    }
    drop(name);
}

#[allow(non_snake_case)]
extern "C" {
    pub fn QMPP_register(name: *const i8);
}
```

Module compiled with `cargo build --target wasm32-unknown-unknown --release`

Cargo.toml contains
```toml
[lib]
crate-type = ["cdylib"]
```

**Comment by syrusakbary** [comment]
Can you attach the `qmpp_hello_plugin.wasm` file?

**Comment by 4LT** [comment]
I've updated the issue description with the attachment

**Comment by syrusakbary** [comment]
I checked with the official `wabt` validator (`wasm-validate`) apart from the `wasmer` validator, both fail to validate it.
It seems the file is not a valid Wasm file @4LT, so I think it's more a rustc bug!

**Comment by 4LT** [comment]
Got it! I'll submit a pull request in rust-lang then

**Comment by 4LT** [comment]
ahh, nevermind, it's fixed in nightly
