### ISSUE TITLE
Failed to run a program with lib function: Error while importing "wasi_snapshot_preview1"."proc_exit": unknown import. 

### ISSUE THREAD

**Issue by Fvoiretryzig** [wasmerio/wasmer#2461]
### I want to use Wasmer run a wasm file compiled from C using Clang but this error message appears,
```shell
error: failed to run `matrix.wasm`
╰─> 1: Error while importing "wasi_snapshot_preview1"."proc_exit": unknown import. Expected Function(FunctionType { params: [I32], results: [] })
``` 
I use Wasmer run command with `--invoke` option.

And my environment are as follows,
```shell
wasmer 2.0.0 | rustc 1.52.1 (9bc8c42bb 2021-05-09) | x86_64
```
And my Clang version is 11.0.0.

### Steps to reproduce

1. I use Clang to compile this C file,
```c
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
int length(char* s) {
	return strlen(s);
}
int matrix(int row, int col) {
	printf("this is matrix\n");
	int a[row][col];
	int b[col][row];
	int r[row][row];
	for(int i = 0; i<row; i++) {
		for(int j = 0; j<col; j++) {
			a[i][j] = rand()%1000+1;
			b[j][i] = rand()%1000+1;
		}
	}
	for(int i = 0; i<row; i++) {
		for(int j = 0; j<row; j++) {
			r[i][j] = 0;
			for(int k = 0; k<col; k++) {
				r[i][j] += a[i][k] * b[k][j];
			}
		}
	}
	
	return r[row-1][row-1];
}
int main(){
	int a = matrix(10, 12);
	printf("a: %d\n", a);
	printf("length: %d\n", length("abcd"));
	return 0;
}
```
2. The command used to compile this file is,
```sh
clang --sysroot home/user/wasi-sdk-12.0/share/wasi-sysroot/ \
-Wl,--export-all \
-o matrix.wasm matrix.c
```
And I use wasm2wat to translate wasm file into wat format. The file content the following import,
```
  (import "wasi_snapshot_preview1" "proc_exit" (func $__wasi_proc_exit (type 2))) 
  (import "wasi_snapshot_preview1" "fd_seek" (func $__wasi_fd_seek (type 3)))
  (import "wasi_snapshot_preview1" "fd_write" (func $__wasi_fd_write (type 4)))
  (import "wasi_snapshot_preview1" "fd_close" (func $__wasi_fd_close (type 5))) 
  (import "wasi_snapshot_preview1" "fd_fdstat_get" (func $__wasi_fd_fdstat_get (type 6)))
```
3. I run the wasm file with command,
```shell
wasmer run matrix.wasm -i matrix 10 12
```
4. The error message appears,
```shell
error: failed to run `matrix.wasm`
╰─> 1: Error while importing "wasi_snapshot_preview1"."proc_exit": unknown import. Expected Function(FunctionType { params: [I32], results: [] })
```
However when I run this wasm file directly,
```shell
wasmer run matrix.wasm
```
Everything goes on well. 
### Expected behavior
I want when I run the command,
```shell
wasmer run matrix.wasm -i matrix 10 12
```
It can return the correct result. I want to know how to import this wasi module correctly.
### Actual behavior
When I run the command,
```shell
wasmer run matrix.wasm -i matrix 10 12
```
it just shows the error message,
```shell
error: failed to run `matrix.wasm`
╰─> 1: Error while importing "wasi_snapshot_preview1"."proc_exit": unknown import. Expected Function(FunctionType { params: [I32], results: [] })
```

### Additional context

I delete these import lines and other lines related to them in the wat file and run it with,
```shell
wasmer run matrix.wat -i matrix 10 12
```
it returns the value but it does not print anything. I suppose that because I delete the lines related to the 'fd_write', it cannot print anything. I guess it maybe when I invoke a specific function, these wasi modules are not loaded yet? How I can import them  successfully?

**Comment by chenyukang** [comment]
If we invoke with a function, we won't work with WASI env.
Have a look at this line： https://github.com/wasmerio/wasmer/blob/master/lib/cli/src/commands/run.rs#L96

I made a branch that can also run invoke a function with WASI(only for demo): 
https://github.com/wasmerio/wasmer/pull/2484/files

@Hywan What is the reason wasmer won't run a invoke function with WASI?
