### ISSUE TITLE
Set memory limits (tunables) via C API?

### ISSUE THREAD

**Issue by tudor** [wasmerio/wasmer#2470]
### Summary

Is there a way to set an upper bound on the size of a WASM memory from the C API? The Rust API has "Tunables", can that be exported through the C API as well?

**Comment by syrusakbary** [comment]
The C-API doesn't have yet a way to set an upper bound, but it would be great to have it as well as other tunable aspects.

Would you like to contribute with a PR? We can also help guiding and so!

**Comment by ptitSeb** [comment]
...unstale...
