### ISSUE TITLE
C API: wasm_extern_delete, wasm_externtype_delete, etc not implemented

### ISSUE THREAD

**Issue by tudor** [wasmerio/wasmer#2471]
Their bodies are `{}`, which may be the cause of memory leaks.

It's likely that this is the cause of #2469

**Comment by tudor** [comment]
oops, I should have read `DEVELOPMENT.md` first :)

**Comment by Hywan** [comment]
Yeah, https://github.com/wasmerio/wasmer/blob/c7f4bd28109ee1eaa18c5979c5abe6ada5beb67c/lib/c-api/src/wasm_c_api/DEVELOPMENT.md#destructors explains how the destructors work :-)!
