### ISSUE TITLE
RFE: Add error-handling example for C API’s wasm_instance_new()

### ISSUE THREAD

**Issue by FGasper** [wasmerio/wasmer#2472]
### Motivation

When wasm_instance_new() fails, how should I consume `traps` if it’s non-NULL? Nothing seems to indicate how I can discover how many traps there are.

### Proposed solution

Add examples that show how to report all of the available information about the failure when `wasm_instance_new()` fails.

**Comment by FGasper** [comment]
UPDATE: Per the Rust code it looks like the variable can only ever expose a single trap … so should it be renamed?

**Comment by Hywan** [comment]
Hello,

The naming follows the Wasm standard C API. However, you might be interested by https://github.com/wasmerio/wasmer/issues/1744 and https://github.com/wasmerio/wasmer/pull/1761. I agree that the documentation should contain more information about it.

Do you want to open a PR?

**Comment by FGasper** [comment]
> Hello,
> 
> The naming follows the Wasm standard C API. However, you might be interested by #1744 and #1761. I agree that the documentation should contain more information about it.
> 
> Do you want to open a PR?

I’ll comment on the naming in the C API repo, as that seems to be the source of the “naming bug”.

I can look at creating a PR to provide error handling in the C API examples, sure.

Thank you!

**Comment by FGasper** [comment]
> The naming follows the Wasm standard C API.

I don’t see anything in https://github.com/WebAssembly/wasm-c-api/blob/master/include/wasm.h that uses the word “traps” … ?

**Comment by syrusakbary** [comment]
https://github.com/WebAssembly/wasm-c-api/blob/master/include/wasm.h#L376-L387

I may be confused... but there can be only one trap at a time.

> UPDATE: Per the Rust code it looks like the variable can only ever expose a single trap … so should it be renamed?

This might be a good idea. What do you think will be good to rename?

**Comment by FGasper** [comment]
> What do you think will be good to rename?

I’m working on a PR just to rename them “trap”.

**Comment by FGasper** [comment]
@syrusakbary @Hywan One of the challenges I’ve found is determining how best to convert a trap’s contents into a string. Extracting the message is straightforward enough, but it would be great to be able to extract names from the stack trace as well.

Do you have any insight into how to do this?

**Comment by Hywan** [comment]
See https://github.com/wasmerio/wasmer/pull/2444 which has fixed a bug, and more importantly has added more documentation.

**Comment by Hywan** [comment]
Everything is documented here, https://wasmerio.github.io/wasmer/crates/doc/wasmer_c_api/wasm_c_api/trap/index.html

**Comment by FGasper** [comment]
> Everything is documented here

```
// Do something with the trap.
```
^^ @Hywan Are there any examples of this? I don’t see any.

It’s straightforward enough to get the error message itself, but what is to be done with the origin and trace?

**Comment by Hywan** [comment]
This part is not documented yet. `wasm_trap_origin` returns a `wasm_frame_t`, and `wasm_trap_trace` returns a fills out a `wasm_frame_vec_t`. Please open an issue for that specifically :-).
