### ISSUE TITLE
Request: arm64 Linux

### ISSUE THREAD

**Issue by simonSlamka** [wasmerio/wasmer#2473]
Thanks for proposing a new feature!

### Motivation
I am using the new Apple SIlicon processor and would like to run Wasmer on it.

### Proposed solution

Include support for arm64. The installer is reporting that the arch is not yet supported, which is why I'm opening this issue.

### Alternatives

None. I need a native arm64 build.

### Additional context

Have you considered building for arm64?

Thanks

**Comment by Hywan** [comment]
Hello,

The title of the issue says “arm64 **Linux**” but the description of the issue says: “Apple Silicon”, which is arm64 Darwin.

We are supporting arm64 for both Linux and Darwin. Our aarch64 linux is under rework, but it should be up soon. You can still build it yourself:

```sh
$ git clone https://github.com/wasmerio/wasmer
$ cd wasmer
$ make build-wasmer
```

then, depending on what you need, you can also run `make package`.

**Comment by simonSlamka** [comment]
> The title of the issue says “arm64 **Linux**” but the description of the issue says: “Apple Silicon”, which is arm64 Darwin.

Hey. I assure you, this is correct. I am running VMs using Parallels. So yes, arm64 **Linux**.
By saying *Apple Silicon*, I just specified the exact CPU family I have.

Thanks

**Comment by Hywan** [comment]
OK, then it doesn't change my words. Our aarch64 linux pipeline is under rework, so you need to build it yourself, with the instructions I've shared with you :-). Does it work?

**Comment by simonSlamka** [comment]
Yeah, sorry.

Sure, it works.

**Comment by Hywan** [comment]
Happy it works :-).
