### ISSUE TITLE
wasmer tool can successfully produce compiled binaries that do not pass validation checks

### ISSUE THREAD

**Issue by lucianoiam** [wasmerio/wasmer#2477]
wasmer 2.0.0
rustc 1.53.0 (53cb7b09b 2021-06-17)
x86_64

### Steps to reproduce

- Download and uncompress attachment
- wasmer compile test.wat  -o test.wasmu
- wasmer validate test.wasmu

### Expected behavior

wasmer validate succeeds

### Actual behavior

wasmer validate fails

```
error: failed to validate `./test.wasmu`
╰─> 1: Validation error: Bad magic number (at offset 0)
```

### Additional context

This online compiler can produce a binary from the same .wat file that passes validation checks and runs fine on libwasmer https://webassembly.github.io/wabt/demo/wat2wasm/

[test.wat.zip](https://github.com/wasmerio/wasmer/files/6834632/test.wat.zip)

**Comment by syrusakbary** [comment]
Wasmer compile generates artifacts that are not WebAssembly files, but more like artifacts (think of dlls in Windows, dylibs in macOS or so in linux).

wasmer validate validates WebAssembly files, not compilation ones. At least at the moment.
It might be a good idea to add support for this, but I do believe it might be good to do as a separate command?

**Comment by lucianoiam** [comment]
Oops pardon my ignorance then, that explains .wasmu vs .wasm perhaps?. So if I correctly understand `compile` and `validate` work on different formats?
I just joined WebAssembly programming so the answer is rather a generic one, surely it would be good to have support for more operations. Or at least a more detailed error message from wasmer.
Thanks for the prompt reply.
