### ISSUE TITLE
Binary distribution for MinGW

### ISSUE THREAD

**Issue by lucianoiam** [wasmerio/wasmer#2483]
*Thanks for proposing a new feature!*

Motivation: be more FOSS friendly

*A clear and concise description of what the motivation for the new feature is, and what problem it is solving.*

The current Windows libwasmer requires MSVC. Having a MinGW compatible libwasmer might lower the entry point for developers without a Rust background. Currently linking a C project targeting MinGW requires dealing with Cargo, Rust, etc. only to build a library. Not rocket science just a bit inconvenient especially when a newcomer is researching which Wasm library to pick.

*A clear and concise description of the feature you would like to add, and how it solves the motivating problem.*

Add a .tar.gz to GitHub releases like [this one](https://github.com/lucianoiam/apices/files/6795372/wasmer-mingw-amd64.tar.gz) (some files are missing but you get the idea)

*A clear and concise description of any alternative solutions or features you've considered, and why you're proposed solution is better.*

Moving to a library with less dependencies / easier to build / MinGW friendly. Not worth now I rolled my own binary but it could have been easier.

*Add any other context or screenshots about the feature request here.*

**Comment by Hywan** [comment]
Hello,

Thank you for the detailed issue.
I agree with this. I've started to work on that with @jubianchi but nothing released yet.
