### ISSUE TITLE
DOCS: wasm_limits_t members should be documented

### ISSUE THREAD

**Issue by FGasper** [wasmerio/wasmer#2485]
### Describe the bug

The code examples like https://github.com/wasmerio/wasmer/blob/master/lib/c-api/examples/memory2.c all initialize `wasm_limits_t` directly, i.e., by assigning to the struct members.

Wasmer’s docs for that struct, though, seem to say that the members are private:
https://docs.rs/wasmer-c-api/2.0.0/wasmer_c_api/wasm_c_api/types/struct.wasm_limits_t.html

Thus, it _looks_ like he documentation is wrong, and `min` and `max` should be publicly documented.

(wasm.h also documents these members.)

**Comment by Hywan** [comment]
Hello,

Thank you for the close look.
You're correct. Can you please open a PR to fix that?

**Comment by Hywan** [comment]
Closed by @2493.
