### ISSUE TITLE
Supper for text input?

### ISSUE THREAD

**Issue by richardanaya** [wasmerio/wasmer#249]
I was thinking about what it would take to support text input for emacripten based apps. Does this work with wasmer?

Basically I’m interested in writing a roguelike on wasmer. 

Also could be useful for apps that have command line input after execution.

**Comment by xmclark** [comment]
Yeah this is an excellent use case for Wasmer and one we have been exploring. We can use Emscripten to achieve some of this. There is [another repo](https://github.com/wasmerio/rust-cli-app-example) where we experiment with some of these ideas. It's a bit buggy at the moment, but should be totally possible. 

In the future we may have a better POSIX interface in Wasmer (not emscripten) that allows us to do this more securely and reliably.

I just tried making a super basic program in C that I compile with Emscripten:
```c
#include <stdio.h>
int main( ) {
    int c;
    printf( "Enter a value :");
    c = getchar( );
    printf( "\nYou entered: ");
    putchar( c );
    return 0;
}
```
compilation:
```
# activate emcc  first
> emcc main.c -o main.wasm
```

and running  it:
```
> wasmer run ./main.wasm
```

I was trying this out on my windows box...safe to say the result was not as expected. The prints and the readlines are out of order. It may be a bug with how we are doing `putchar` in wasmer or an issue with generated emscritpen wasm. Theoretically this should work 🙃.

**Comment by syrusakbary** [comment]
Reading from stdin with Wasmer is possible with both `Emscripten` and `WASI` ABIs.

Closing the issue :)
