### ISSUE TITLE
Documentation mentions that multi-value proposal isn't standardized

### ISSUE THREAD

**Issue by protheory8** [wasmerio/wasmer#2496]
### Describe the bug

Multi-value proposals has been standardized for quite a while now, but the documentation at https://docs.rs/wasmer/2.0.0/wasmer/struct.Features.html#method.multi_value says that it is not.

### Steps to reproduce

N/A

### Expected behavior

Should say `The WebAssembly multi-value proposal is now fully standardized.`

### Actual behavior

Says `The WebAssembly multi-value proposal is not currently fully standardized.`

### Additional context

N/A

**Comment by protheory8** [comment]
I could contribute to fix that line and enable the multi value proposal by default. Is implementation up-to-date?

**Comment by Hywan** [comment]
Yes, please, do so :-). If you need any guidance, please ping me.

**Comment by protheory8** [comment]
@Hywan Not completely sure where to enable to the multi-value proposal. I checked out [this](https://docs.rs/wasmer-types/2.0.0/src/wasmer_types/features.rs.html#52) file, but it seems like it's already enabled by default. Do I just need to fix the documentation comment or do I also need to enable it elsewhere?

**Comment by Hywan** [comment]
You can check that all compilers have this features turn on by default too (`wasmer-compiler-singlepass`, `wasmer-compiler-cranelift` and `wasmer-compiler-llvm`).

But apart from that, yes, the documentation you've pointed in the description of this issue must be updated for sure.

**Comment by protheory8** [comment]
> You can check that all compilers have this features turn on by default too (`wasmer-compiler-singlepass`, `wasmer-compiler-cranelift` and `wasmer-compiler-llvm`).

@Hywan I didn't find any mentions of multi-value in those crates, except
```rust
if compile_info.features.multi_value {
    return Err(CompileError::UnsupportedFeature("multivalue".to_string()));
}
```
in `wasmer-compiler-singlepass`.

**Comment by Hywan** [comment]
OK, so you can just update the documentation as mentionned in your first message :-).
