### ISSUE TITLE
iOS: wasmer attempts to allocate too much memory

### ISSUE THREAD

**Issue by Absolucy** [wasmerio/wasmer#2500]
### Describe the bug

`wasmer 2.0.0 |  | iPhone12,1`

When running the wasmer CLI on iOS, it attempts to allocate *too much* memory, leading to:

```
Lucys-iPhone:~ mobile% wasmer qjs.wasm
error: failed to run `qjs.wasm`
│   1: WASI execution failed
╰─> 2: Insufficient resources: Failed to create memory: Error when allocating memory: Cannot allocate memory (os error 12)
```
This also occurs with a simple Rust "hello world" WASM binary.

The iPhone has around ~1GB of RAM free, so that is not the issue. It seems that wasmer is attempting to mmap around 8 GiB of memory.

### Steps to reproduce

1. Have iOS device with terminal device
2. Compile wasmer for it (you will need to find&replace all instances of `target_os = "macos"` with `target_vendor = "apple"`
3. Run any WASM binary using the wasmer cli on iOS
4. It won't work

### Expected behavior

WASM running

### Actual behavior

![image](https://user-images.githubusercontent.com/65794972/127787962-08a8185a-553a-4915-99b1-945757cd79b2.png)

**Comment by NathHorrigan** [comment]
@Absolucy What build steps are you following?

**Comment by Absolucy** [comment]
`cargo build --release --target aarch64-apple-ios`?

**Comment by Hywan** [comment]
Hello,

Thank you for the bug report! Can you please give me the steps to reproduce the bug? I'm not familiar with iOS.

**Comment by Absolucy** [comment]
wait i just realized it probably wouldn't work in a sandboxed iOS app in the first place, and unsandboxed iOS is probably too niche and hard to reproduce, sorry!!

**Comment by Hywan** [comment]
But, eh, I still want to reproduce the error :-p.

**Comment by Hywan** [comment]
Is there a simple way to do that from a shell for example?
