### ISSUE TITLE
lib/c-api documentation broken lnk

### ISSUE THREAD

**Issue by JamesDunne** [wasmerio/wasmer#2504]
https://github.com/wasmerio/wasmer/tree/master/lib/c-api#readme

The following link is broken:

> The full C API documentation can be found here: https://wasmerio.github.io/wasmer/crates/wasmer_c_api/index.html

**Comment by Hywan** [comment]
Closed by https://github.com/wasmerio/wasmer/commit/7e914488383e2c0f3086b1b3aa60f277d60f5095. Thank you for taking the time to open the issue!
