### ISSUE TITLE
[c-api] `wasm_instance_new` is slow

### ISSUE THREAD

**Issue by lei-april** [wasmerio/wasmer#2506]
First of all, thank you for the awesome work on this cool project :)

### Summary

I'm trying to integrate wasmer into our blockchain service as a smart contract executor, using it's c-api. I've done a few simple  tests and notice that `wasm_instance_new` takes ~1ms, while `wasm_func_call` usually takes less than 1ms. So the overhead of `wasm_instance_new` more than doubles the total execution time of our smart contract.

Is it possible to make `wasm_instance_new` faster?

### Additional details

- wasmer 2.0.0 is used.
- The wasm module tested is ~200KB in size.
- Tests are done on a x86-64 Linux machine.

**Comment by Hywan** [comment]
We can try to make it faster yes :-). Are you willing to try with some PR also?

**Comment by lei-april** [comment]
> We can try to make it faster yes :-). Are you willing to try with some PR also?

Sure. But I just glimpsed the implementation of `wasm_instance_new`, no idea what it's actually doing. Any hint where I should start?

**Comment by Hywan** [comment]
The code lands here, https://docs.rs/wasmer-c-api/2.0.0/src/wasmer_c_api/wasm_c_api/instance.rs.html#40-84. I think it's a good start. You can time some portions of the code, but most of the work happens in `Instance::new` https://github.com/wasmerio/wasmer/blob/7e914488383e2c0f3086b1b3aa60f277d60f5095/lib/api/src/sys/instance.rs#L115.

**Comment by Hywan** [comment]
I've opened #2521 as a low hanging fruit. We can parallelized the creation of `OrderedResolver`.

**Comment by jcaesar** [comment]
(Are you using multiple threads to create instances? If so, you might be running into #2563.)
