### ISSUE TITLE
[c-api] wasm_func_call leaks memory

### ISSUE THREAD

**Issue by JamesDunne** [wasmerio/wasmer#2508]
### Describe the bug
Using the wasm.h C API, calling `wasm_func_call` in a tight loop leaks memory fairly quickly. The called wasm function executes successfully with no traps.

```sh
echo "`wasmer -V` | `rustc -V` | `uname -m`"
```
wasmer 2.0.0 | rustc 1.52.1 (9bc8c42bb 2021-05-09) | x86_64

### Steps to reproduce
On MacOS, use Instruments.app to monitor a test app calling `wasm_func_call()` in a tight loop and observe allocations growing and not being freed.

### Expected behavior
Memory should not leak.

### Actual behavior
Using Instruments.app in "Leaks" mode, we find the following:

Many `Malloc 128 Bytes` category allocations are made with the "Responsible Caller" recorded as `alloc::raw_vec::RawVec$LT$T$C$A$GT$::shrink_to_fit::had584de680efdcdd`

After selecting one of the leaky allocations, this is the stack trace starting from `wasm_func_call`, found by drilling down in the disassembly view and clicking through the highlighted `callq` instructions:
```
"wasmer::externals::function::Function::call::hd2cef88294d6d070"
"wasmer_vm::trap::traphandlers::wasmer_call_trampoline::ha7c3ffd07d0a997f"
"wasmer_register_setjmp"
```

A snippet of disassembly for `wasmer_register_setjmp`:
```
...
+0x33	callq               "DYLD-STUB$$setjmp"
+0x38	movl                %eax, %ecx
+0x3a	xorl                %eax, %eax
+0x3c	testl               %ecx, %ecx
+0x3e	jne                 "wasmer_register_setjmp+0x4e"
+0x40	movq                %r12, (%rbx)
+0x43	movq                %r14, %rdi
+0x46	callq               *%r15
+0x49	movl                $1, %eax
+0x4e	movq                1399851(%rip), %rcx
+0x55	movq                (%rcx), %rcx
+0x58	cmpq                -40(%rbp), %rcx
+0x5c	jne                 "wasmer_register_setjmp+0x6e"
...
+0x6d	retq
```

The instruction `+0x46	callq               *%r15` is highlighted by Instruments.app as being responsible for the high number of allocations.

That instruction corresponds to line 30 in this C code:
https://github.com/wasmerio/wasmer/blob/2.0.0/lib/vm/src/trap/handlers.c#L30

Of course, that code is just a generic dynamic dispatch to a function pointer (`body(payload)`), so we have to traverse back up the stack a bit to find the culprit:
https://github.com/wasmerio/wasmer/blob/2.0.0/lib/vm/src/trap/traphandlers.rs#L562 

I'm unfamiliar with Rust so this is where my analysis ends. Hopefully someone on the team can investigate the issue and determine what is leaking memory.

**Comment by Hywan** [comment]
Hello,

Thank you for the bug report. Can you please share with us the C code that triggers this leak you're noticing please?

**Comment by JamesDunne** [comment]
https://github.com/JamesDunne/wasmer-memory-leak/blob/main/main.cpp

The memory leak is triggered by wasm calling back to the host. I took a trivial callback example from wasm-c-api and added a loop around the wasm call so that the process memory can be monitored.
