### ISSUE TITLE
feat(dependabot) Set up Dependabot

### ISSUE THREAD

**Issue by Hywan** [wasmerio/wasmer#251]
### Motivation

Keeping all dependencies up-to-date is time consuming. We want to automate that.

### Proposed solution

https://github.com/marketplace/dependabot/ is a bot (used by rustwasm for instance) to delegate that job. PR example: https://github.com/rustwasm/wasm-snip/pull/23.

**Comment by syrusakbary** [comment]
Love it!

**Comment by syrusakbary** [comment]
I just installed it. Closing the issue :)
