### ISSUE TITLE
Add deprecation notice to the crate `wasmer-runtime`

### ISSUE THREAD

**Issue by marioortizmanero** [wasmerio/wasmer#2539]
I was confused at first about the differences between `wasmer` and `wasmer-runtime`. I'm guessing the latter was just the previous name you used before moving on to `wasmer`, but it'd be very useful to have a clear warning in the docs (docs.rs) or description (crates.io). Some tutorials like [this one](https://freemasen.com/blog/wasmer-plugin-pt-1/) use `wasmer-runtime` and it's easy to mistake them (the compiler emits no warnings regarding v0.18 being yanked).

Something like:

> WARNING: this crate has been deprecated in favor of `wasmer`. Refer to that instead.

would be enough.

**Comment by epilys** [comment]
Thank you for bringing this to our attention, now `wasmer-runtime` has a deprecation notice in `crates.io`, in its `README.md` and also the only unyanked version throws a compile error telling you it's deprecated.

https://crates.io/crates/wasmer-runtime
