### ISSUE TITLE
`make install-capi-lib` and `make install-pkgconfig` fail unless wasmer binary is built.

### ISSUE THREAD

**Issue by FGasper** [wasmerio/wasmer#2541]
### Describe the bug

Using Rust 1.54 on CloudLinux 6 and a checked-out version of wasmer’s git repo:

- `make build-capi` works fine
- `make install-capi-headers` works

… but that’s where success stops:
```
# make install-capi-lib
-----------
INFORMATION
-----------

/bin/bash: rustup: command not found
Host Target: ``.
Enabled Compilers: cranelift, singlepass.
Testing the following compilers & engines:
* API: cranelift-universal cranelift-dylib singlepass-universal
* C-API: cranelift-universal cranelift-dylib
Cargo features:
* Compilers: `--features cranelift,singlepass`.


--------------
RULE EXECUTION
--------------


pkgver=$(target/release/wasmer --version | cut -d\  -f2) && \
	shortver="${pkgver%.*}" && \
	majorver="${shortver%.*}" && \
	install -Dm755 target/release/libwasmer.so "/usr/local/lib/libwasmer.so.$pkgver" && \
	ln -sf "libwasmer.so.$pkgver" "/usr/local/lib/libwasmer.so.$shortver" && \
	ln -sf "libwasmer.so.$pkgver" "/usr/local/lib/libwasmer.so.$majorver" && \
	ln -sf "libwasmer.so.$pkgver" "/usr/local/lib/libwasmer.so"
/bin/bash: target/release/wasmer: No such file or directory
install: accessing `/usr/local/lib/libwasmer.so.': Too many levels of symbolic links
make: *** [install-capi-lib] Error 1
```
… and:
```
# make install-pkgconfig
-----------
INFORMATION
-----------

/bin/bash: rustup: command not found
Host Target: ``.
Enabled Compilers: cranelift, singlepass.
Testing the following compilers & engines:
* API: cranelift-universal cranelift-dylib singlepass-universal
* C-API: cranelift-universal cranelift-dylib
Cargo features:
* Compilers: `--features cranelift,singlepass`.


--------------
RULE EXECUTION
--------------


# Make sure WASMER_INSTALL_PREFIX is set during build
unset WASMER_DIR; \
	if pc="$(target/release/wasmer config --pkg-config 1>/dev/null 2>/dev/null)"; then \
		echo "$pc" | install -Dm644 /dev/stdin "/usr/local"/lib/pkgconfig/wasmer.pc; \
	else \
		echo 1>&2 "WASMER_INSTALL_PREFIX was not set during build, not installing wasmer.pc"; \
	fi
WASMER_INSTALL_PREFIX was not set during build, not installing wasmer.pc
```

### Steps to reproduce

See above.

### Expected behavior

Since the Makefile exposes the library-only build targets, the library-only installation targets should work in isolation; currently they require the binary to be built.

### Actual behavior

Failure as shown above.

### Additional context

CloudLinux 6’s gcc is too old to build the binary; there’s a dependency that expects `-std=c11` to work, but it doesn’t in this older gcc. The library builds, though, without issue.

**Comment by jcaesar** [comment]
> CloudLinux 6

I added those Makefile install targets. But I have absolutely no interest on supporting software outdated to that ridiculous level. Sorry. (Can you really not acquire a newer gcc?  I mean, you're trying to acquire wasmer, which is newer than what your distro could possibly give you. Other than that... Just install the files without using the Makefile?)

**Comment by FGasper** [comment]
@jcaesar That was just context; the issue presents on any OS where you try to build & install the libraries independent of the binary.
