### ISSUE TITLE
How to utilize networking within wasm

### ISSUE THREAD

**Issue by diclophis** [wasmerio/wasmer#2555]
### Summary

What support exists in wasmer (specifically the wasmer-ruby wrapper) to provide TCP/HTTP networking facilities to wasm modules?

I am intrigued with the notion of utilizing wasm as part of a user-definable ETL pipeline, however I have not identified the best way to "capture" the result of any compute performed inside of a wasm module.... My initial thought is, have the module read in a file, and write out a file (given there is some file system support), and then do the networking at the "host" layer before and after the module is invoked (pre-fetching the file for input, and sending the output file onward to subsequent systems in the pipeline)

**Comment by jcaesar** [comment]
Directly doing networking from inside wasm? Wasmer doesn't provide any functionality to do that, as far as I know. (WASI [has](https://github.com/wasmerio/wasmer/blob/2a4ac7a135c77c5018de17b8ef289dd045e9767e/lib/wasi/src/lib.rs#L265-L267) some related function calls but wasmer leaves them [unimplemented](https://github.com/wasmerio/wasmer/blob/650352ddeca4e130fcfe45312f4a9ccdd1cea841/lib/wasi/src/syscalls/mod.rs#L2569).) You can of course provide your own `imports!` that allow for that. (But I would question if it's appropriate for a user-defined step in an ETL pipeline to do user-defined network IO.)

> the best way to "capture" the result of any compute performed inside of a wasm module....

Probably the most lightweight way is to have your wasmer functions return a pointer to the wasmer memory, which you then read from your ruby code. (I hope this is possible from ruby. For a Rust example, see [here](https://github.com/wasmerio/wasmer/blob/e5a784a00633615f43c5169745e2902c4b614309/examples/exports_memory.rs#L75-L89).)

> have the module read in a file, and write out a file

That sounds heavy. But it's of course possible.

**Comment by diclophis** [comment]
@jcaesar ok thanks, your points seem reasonable.

**Comment by jcaesar** [comment]
(PS: Ruby also had the "return pointer from memory"-[example](https://github.com/wasmerio/wasmer-ruby/blob/master/examples/exports_memory.rb#L70).)
