### ISSUE TITLE
Rust crate reports RuntimeError User(Exit(0)), but wasmer cli does not give an error

### ISSUE THREAD

**Issue by folkertdev** [wasmerio/wasmer#2566]
### Describe the bug

[gist containing my code](https://gist.github.com/folkertdev/51a2937bcc4814ed7baa55e0dc84fc45)

The contained `host.wat` file runs fine with the wasmer cli (and `wasmtime` too)

```shell
folkertdev@folkertdev ~/r/wasmer-bug (master)> wasmer host.wat
[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2]
runtime: 0.578ms
```

However, running the same file with the rust bindings  causes an error

```
folkertdev@folkertdev ~/r/wasmer-bug (master)> cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/debug/wasmer-bug`
[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2]
runtime: 0.304ms
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RuntimeError { source: User(Exit(0)), wasm_trace: [], native_trace:    0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
 }', src/main.rs:27:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```sh
$ echo "`wasmer -V` | `rustc -V` | `uname -m`"
wasmer 2.0.0 | rustc 1.55.0 (c8dfcfe04 2021-09-06) | x86_64
```

### Steps to reproduce

1.  go to [gist containing my code](https://gist.github.com/folkertdev/51a2937bcc4814ed7baa55e0dc84fc45)
2. start a fresh rust project, copy `main.rs`, `Cargo.toml` into the usual places
3. put `host.wat` at the top level (so "beside" `Cargo.toml` and the `src` folder
4. `cargo run`

### Expected behavior

If the wasmer cli exits without any errors, then loading/running the same file with the rust api should also not cause any errors

### Actual behavior

The rust api throws an error

**Comment by jcaesar** [comment]
See https://github.com/wasmerio/wasmer/blob/6382d99ac7e5d761eac5c2341e40783eaba4fed3/lib/cli/src/commands/run/wasi.rs#L79-L88 on how to handle wasi user exits.

**Comment by folkertdev** [comment]
hmm, looks like the `Error` in `WasiError` confused me then? it's more like `WasiMessage`, something for the (in this case rust) host to respond to what happened during evaluation.

**Comment by jcaesar** [comment]
I guess so. It's certainly not the best API design, but internally there doesn't seem to be a way of aborting WASM execution except with an error. 
And well, `Exit(1)` should probably actually be treated as an error (just not in the engine, but in the executed module).
