### ISSUE TITLE
Support for s390x/systemz for wasmer

### ISSUE THREAD

**Issue by udai05** [wasmerio/wasmer#2572]
Looking for timeline to support systemz/s390x.  

I'm trying to dig around this for couple of days. 
I'm able to compile the 'build-capi' and 'build-wasmer' now. 

1. Need your help in understanding what else is required to test the build.
2. And how do I integrate this with wasmvm.

Thanks.

**Comment by vmorris** [comment]
@US-05 I am interested in s390x support in wasmvm as well. Do you have a fork with the requisite changes that we can view to get wasmer to build?

**Comment by epilys** [comment]
Unfortunately we don't have the resources to handle such a feature right now. We're open to collaborating with someone from the community if someone is open on working on it. If the feature is for a corporate project consider becoming a [sponsor](https://wasmer.io/wasmer-open-source-program) in order for us to prioritize your requests.
