### ISSUE TITLE
When calling `Instance::new`, it prompts an exception `Error: Link(Import("__wbindgen_placeholder__ ...`

### ISSUE THREAD

**Issue by ZhaoJieMin** [wasmerio/wasmer#2578]
I just changed the parameter in `wat2wasm` in the sample code to read wasm binary and that's it.

Did I understand it wrong? Can't it be changed like this?

result

```shell
Compiling module...
Instantiating module...
Error: Link(Import("__wbindgen_placeholder__", "__wbindgen_describe", UnknownImport(Function(FunctionType { params: [I32], results: [] }))))

```

Complete code

```rust
use wasmer::{imports, wat2wasm, Instance, Module, Store};
use wasmer_compiler_cranelift::Cranelift;
use wasmer_engine_universal::Universal;
use std::path::Path;
use std::path::PathBuf;

fn main() -> Result<(), Box<dyn std::error::Error>> {
//     let wasm_bytes = wat2wasm(
//         br#"
// (module
//   (type $add_one_t (func (param i32) (result i32)))
//   (func $add_one_f (type $add_one_t) (param $value i32) (result i32)
//     local.get $value
//     i32.const 1
//     i32.add)
//   (export "add_one" (func $add_one_f)))
// "#,
//     )?;

    let file = Path::new("./hello_wasm.wasm");
    let wasm_bytes = std::fs::read(file)?;
    let wasm_bytes = wat2wasm(
        &*wasm_bytes
    )?;

    let store = Store::new(&Universal::new(Cranelift::default()).engine());

    println!("Compiling module...");
    // Let's compile the Wasm module.
    let module = Module::new(&store, wasm_bytes)?;

    // Create an empty import object.
    let import_object = imports! {};

    println!("Instantiating module...");
    // Let's instantiate the Wasm module.
    let instance = Instance::new(&module, &import_object)?;

    let add_one = instance
        .exports
        .get_function("fibonacci")?
        .native::<i32, i32>()?;

    println!("Calling `fibonacci` function...");
    let result = add_one.call(1)?;

    println!("Results of `fibonacci`: {:?}", result);
    assert_eq!(result, 2);

    Ok(())
}
```

The file `hello_wasm.wasm` is compiled by `wasm-pack build --scope mynpmusername`.

```rust
extern crate wasm_bindgen;
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub fn fibonacci(num: i32) -> i32 {
    if num <= 1 {
        return 1;
    }
    return fibonacci(num - 1) + fibonacci(num - 2);
}
```

**Comment by jcaesar** [comment]
Correct me if I'm wrong, but the wasm-bindgen crate is for using WebAssembly from JavaScript. It needs some extra code that is written in JS and used by the compiled wasm modules to interact with the JS "outside" world. If you want to use Wasmer, that JS code won't be there. Hence, you can't use webpack with wasmer.

If you want to export a function without webpack, you need to declare it as `#[no_mangle] pub extern "system" fn fibonacci` (Though I'm [not sure](https://github.com/wasmerio/wasmer/blob/8f855cf9ccce1d0c0587f9a34c8e912331643e26/tests/wasi-wast/wasi/tests/fd_read.rs#L80) whether the extern declaration is really necessary.)

**Comment by ZhaoJieMin** [comment]
> Correct me if I'm wrong, but the wasm-bindgen crate is for using WebAssembly from JavaScript. It needs some extra code that is written in JS and used by the compiled wasm modules to interact with the JS "outside" world. If you want to use Wasmer, that JS code won't be there. Hence, you can't use webpack with wasmer.
> 
> If you want to export a function without webpack, you need to declare it as `#[no_mangle] pub extern "system" fn fibonacci` (Though I'm [not sure](https://github.com/wasmerio/wasmer/blob/8f855cf9ccce1d0c0587f9a34c8e912331643e26/tests/wasi-wast/wasi/tests/fd_read.rs#L80) whether the extern declaration is really necessary.)

Change it to the following code to solve it

```rust
#[no_mangle]
pub extern "C" fn fibonacci(num: i64) -> i64 {
    if num <= 1 {
        return 1;
    }
    return fibonacci(num - 1) + fibonacci(num - 2);
}
```
