### ISSUE TITLE
LLVM-Universal doesn't work properly on M1

### ISSUE THREAD

**Issue by ptitSeb** [wasmerio/wasmer#2586]
Once enable, the the `make test-llvm-universal` tests don't run correctly when built and run on a mac M1 (doesn't work on Linux/aarch64 either)

**Comment by jcaesar** [comment]
Rel/dupe? #2553

**Comment by ptitSeb** [comment]
No, the #2553 is too general on M1.
Also, I'll rename this, as it concern also linux/aarch64
