### ISSUE TITLE
Staticlib engine causes rust panic when creating a wasm instance

### ISSUE THREAD

**Issue by HeliosPanoptes** [wasmerio/wasmer#2590]
### Describe the bug

`wasmer 2.0.0 | rustc 1.54.0-nightly (3e99439f4 2021-05-17) | x86_64`

When making a wasm module instance with the `staticlib` engine, wasmer panics:
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /Users/GW/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-vm-2.0.0/src/instance/mod.rs:1079:29
```

Here is a test project.
[wasmer-bug.zip](https://github.com/wasmerio/wasmer/files/7255691/wasmer-bug.zip)

When digging in to the stack trace, at `lookup_by_declaration wasmer-vm-2.0.0/src/instance/mod.rs:1079`, 
`instance-ref.functions.elems.length` is 0. When instantiating a module with `universal` or `dylib`, the length instead shows up as 2.

### Steps to reproduce

For example,
1. Open the test project: [wasmer-bug.zip](https://github.com/wasmerio/wasmer/files/7255691/wasmer-bug.zip)
2. Run with `cargo run -- --engine universal test.wasm`
3. See an output value
4. Run with `cargo run -- --engine staticlib test.wasm`
5. See the panic dump

### Expected behavior

That wasmer does not panic when using staticlib

### Actual behavior
That wasmer panics when using staticlib

### Additional context

None that I can think of.

**Comment by Zhangyx24** [comment]
I found this problem occurred again, in macOS with wasmer2.3.0.
![WechatIMG1244](https://user-images.githubusercontent.com/28601300/179482964-78e9b950-f182-41ff-b31c-6994b0ed2da5.jpeg)

**Comment by epilys** [comment]
@Zhangyx24 your screenshot says the verson is 2.0.0. Can you retry with 2.3.0?
