### ISSUE TITLE
Polling not implemented for clocks yet

### ISSUE THREAD

**Issue by dpogorzelski** [wasmerio/wasmer#2601]
### Describe the bug

```sh
thread 'main' panicked at 'not implemented: Polling not implemented for clocks yet', lib/wasi/src/syscalls/mod.rs:2375:21
```

### Steps to reproduce

```rust
use std::{thread, time};

fn main() {
  let delay = time::Duration::from_secs(3);
  loop {
    println!("sleeping for 3  sec ");
    thread::sleep(delay);
  }
}
```
`cargo build --target wasm32-wasi`
`wasmer hello.wasm`

### Additional context

the platform is darwin(intel)

**Comment by dpogorzelski** [comment]
Seems like this issue/missing feature is also present on linux(amd64) ?

**Comment by XX** [comment]
> Seems like this issue/missing feature is also present on linux(amd64) ?

Yes, this issue is present on linux (amd64) also. :(

**Comment by haike0513** [comment]
Is there any plan to fix it

**Comment by syrusakbary** [comment]
Yes, we did work on it as part of this PR #2689 but we will merge it as part of Wasmer 3.0 :)
