### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by YunSuk-Yeo** [wasmerio/wasmer#2606]
### Describe the bug

Hi, I'm from Terra which are using CosmWasm as our contract layer. 

I'm here to report some memory leak problems. I'm not that familiar with c code, so it might not exact problem point. 
After upgrading Terra to use `CosmWasm@v0.16.x` and `Wasmer@2.0.x`, we are undergoing OOM errors. 

I did some memory leak tracking using [bcc tool](https://github.com/iovisor/bcc/blob/master/tools/memleak.py)

with following command
```shell
# use interval of 30 seconds and prune any allocations newer than 600,000ms = 10min
sudo /usr/share/bcc/tools/memleak --pid 336984 -o 600000 30
```

EDIT: seems this was due to CosmWasm cache.

> The snapshot of output is here
> ```shell
> [00:36:11] Top 10 stacks with outstanding allocations:
>         149736 bytes in 29 allocations from stack
>                 rkyv::core_impl::_$LT$impl$u20$rkyv..DeserializeUnsized$LT$$u5b$U$u5d$$C$D$GT$$u20$for$u20$$u5b$T$u5d$$GT$::deserialize_unsized::habe723ffcc689668+0xc3 [libwasmvm.so]
>                 [unknown]
>         153657 bytes in 41 allocations from stack
>                 rkyv::core_impl::_$LT$impl$u20$rkyv..DeserializeUnsized$LT$$u5b$U$u5d$$C$D$GT$$u20$for$u20$$u5b$T$u5d$$GT$::deserialize_unsized::habe723ffcc689668+0xc3 [libwasmvm.so]
>                 [unknown]
>         172872 bytes in 5 allocations from stack
>                 rkyv::core_impl::_$LT$impl$u20$rkyv..DeserializeUnsized$LT$$u5b$U$u5d$$C$D$GT$$u20$for$u20$$u5b$T$u5d$$GT$::deserialize_unsized::habe723ffcc689668+0x3c [libwasmvm.so]
>         182736 bytes in 4 allocations from stack
>                 rkyv::core_impl::_$LT$impl$u20$rkyv..DeserializeUnsized$LT$$u5b$U$u5d$$C$D$GT$$u20$for$u20$$u5b$T$u5d$$GT$::deserialize_unsized::h572cd1a8756a59ce+0x3c [libwasmvm.so]
>         4214016 bytes in 2538 allocations from stack
>                 _$LT$alloc..vec..Vec$LT$T$C$A$GT$$u20$as$u20$core..clone..Clone$GT$::clone::hcb0611247faf2647+0x236 [libwasmvm.so]
>         6532440 bytes in 2538 allocations from stack
>                 rkyv::core_impl::_$LT$impl$u20$rkyv..DeserializeUnsized$LT$$u5b$U$u5d$$C$D$GT$$u20$for$u20$$u5b$T$u5d$$GT$::deserialize_unsized::h572cd1a8756a59ce+0x10d [libwasmvm.so]
>         6532440 bytes in 2538 allocations from stack
>                 _$LT$alloc..vec..Vec$LT$T$C$A$GT$$u20$as$u20$core..clone..Clone$GT$::clone::hcb0611247faf2647+0x1ac [libwasmvm.so]
>         9885317 bytes in 2154 allocations from stack
>                 rkyv::core_impl::_$LT$impl$u20$rkyv..DeserializeUnsized$LT$$u5b$U$u5d$$C$D$GT$$u20$for$u20$$u5b$T$u5d$$GT$::deserialize_unsized::habe723ffcc689668+0xc3 [libwasmvm.so]
>         21008040 bytes in 875335 allocations from stack
>                 wasmer_vm::func_data_registry::FuncDataRegistry::register::h36b55fc820caae7b+0x1ab [libwasmvm.so]
>         134224000 bytes in 9 allocations from stack
>                 _ZN5alloc7raw_vec11finish_grow17h8116a46933501429E.llvm.10265175094725309632+0x30 [libwasmvm.so]
> ```
> 
> I'm my interpretation, wasmer is making memory leak bigger than 150MB during 10 minutes. This leak leads our machine(>64GB memory) to OOM error. 

We are using official CosmWasm shared library [libwasmvm.so](https://raw.githubusercontent.com/CosmWasm/wasmvm/v0.16.1/api/libwasmvm.so).

As defined [here](https://github.com/CosmWasm/cosmwasm/blob/93ea53e56b152f552df73db7104dfeef3f1fe904/packages/vm/Cargo.toml#L48)
`CosmWasm@v0.16.x` is using `wasmer@2.0.0`

### Steps to reproduce

1. Sync Terra Mainnet
2. Track memory leak with bcc tools

### Expected behavior
Should not leak memory

### Actual behavior

Huge Memory Leak lead OOM

**Comment by webmaster128** [comment]
When I run the entire CosmWasm test suite on a local checkout of wasmer 2.0.0 with this diff:

```diff
diff --git a/lib/vm/src/func_data_registry.rs b/lib/vm/src/func_data_registry.rs
index 7fc9fc24d..cdbf102ad 100644
--- a/lib/vm/src/func_data_registry.rs
+++ b/lib/vm/src/func_data_registry.rs
@@ -105,6 +105,7 @@ impl FuncDataRegistry {
     pub fn register(&self, anyfunc: VMCallerCheckedAnyfunc) -> VMFuncRef {
         let mut inner = self.inner.lock().unwrap();
         if let Some(&idx) = inner.anyfunc_to_index.get(&anyfunc) {
+            println!("Found at index {}", idx);
             let data: &Box<_> = &inner.func_data[idx];
             let inner_ptr: &VMCallerCheckedAnyfunc = &*data;
             VMFuncRef(inner_ptr)
@@ -112,6 +113,7 @@ impl FuncDataRegistry {
             let idx = inner.func_data.len();
             inner.func_data.push(Box::new(anyfunc.clone()));
             inner.anyfunc_to_index.insert(anyfunc, idx);
+            println!("Inserted at index {}", idx);
 
             let data: &Box<_> = &inner.func_data[idx];
             let inner_ptr: &VMCallerCheckedAnyfunc = &*data;
```

I get a single "Found at" entry vs. 53k "Inserted at" entries. This does not feel like a reasonable ratio for such code (that I am completely unfamiliar of). Is there something wrong with the Hash or Eq implementation of `VMCallerCheckedAnyfunc`?

**Comment by webmaster128** [comment]
The same test in `SignatureRegistry::register` shows 0 "Found"s and 33k insertions:

```diff
--- a/lib/vm/src/sig_registry.rs
+++ b/lib/vm/src/sig_registry.rs
@@ -45,7 +45,10 @@ impl SignatureRegistry {
         let mut inner = self.inner.write().unwrap();
         let len = inner.signature2index.len();
         match inner.signature2index.entry(sig.clone()) {
-            hash_map::Entry::Occupied(entry) => *entry.get(),
+            hash_map::Entry::Occupied(entry) => {
+                println!("Found signature");
+                *entry.get()
+            }
             hash_map::Entry::Vacant(entry) => {
                 // Keep `signature_hash` len under 2**32 -- VMSharedSignatureIndex::new(std::u32::MAX)
                 // is reserved for VMSharedSignatureIndex::default().
@@ -55,6 +58,7 @@ impl SignatureRegistry {
                     "Invariant check: signature_hash.len() < std::u32::MAX"
                 );
                 let sig_id = VMSharedSignatureIndex::new(u32::try_from(len).unwrap());
+                println!("Inserted signature {:?}", sig_id);
                 entry.insert(sig_id);
                 inner.index2signature.insert(sig_id, sig.clone());
                 sig_id
```

**Comment by YunSuk-Yeo** [comment]
I will close this, until finding clear problems

**Comment by syrusakbary** [comment]
Hey @YunSuk-Yeo is this issue completely solved by not using the cache? Could it be possible to have a way for us to reproduce it? Thanks!
