### ISSUE TITLE
officially language integration with lua is not there. Please implement it

### ISSUE THREAD

**Issue by zaxebo1** [wasmerio/wasmer#2612]
### Motivation

Lua is extremely popular language in game industry as embedded programming language. 
Many also use it for standalone scripting too,

[https://github.com/wasmerio/wasmer/#-language-integrations](https://github.com/wasmerio/wasmer/#-language-integrations) does not lists lua.

Can the Wasmer runtime can be implemented to be used as a library embedded in lua, so that we can use WebAssembly in standalone lua interpreter??

**Comment by Marak** [comment]
re: https://github.com/ysugimoto/webassembly-lua

**Comment by JustKira** [comment]
Will this be revisited in near future
