### ISSUE TITLE
Memory leak through FuncDataRegistry when repeatedly instantiating module

### ISSUE THREAD

**Issue by matklad** [wasmerio/wasmer#2638]
### Describe the bug

The following code: 

```rust
let module = wasmer::Module::new(&store, &wasm).unwrap();
loop {
  let imports = ...;
  let instance = wasmer::Instance::new(&module, &imports).unwrap();
}
```

uses unbounded amount of memory

### Steps to reproduce

Full repro is here: https://github.com/matklad/repros/blob/9f98e5cda5a54a7242ba2b3c39b1a36bee5d4404/wasmer-leak/src/main.rs

### Expected behavior

Bounded memory usage

### Actual behavior

Memory usage increases without bound

### Additional context

Reproduces this with both wasmer2 and current master. The culprit is this data structure: 

https://github.com/wasmerio/wasmer/blob/e389ad02c43dd24050d391e6dd17adf27ff30b3a/lib/engine-universal/src/artifact.rs#L42

This is a hashmap keyed by *addresses* of all imported functions. It is a part of `Store`, so it is shared across all `Instance`s we create. The hashmap is append only and never shrinks, so it accumulates imports from long-dead instances.

**Comment by syrusakbary** [comment]
Thanks to #2699 we now don't leak the function references by default to the store.

This means that if the Wasm is not using reference types, the functions are not stored in the store, and therefore not leaked anywhere.
However, if the funcrefs are used this will be registered in the store until the store drops.
