### ISSUE TITLE
missing crystal language  

### ISSUE THREAD

**Issue by cekongnet** [wasmerio/wasmer#2644]
Crystal language is a ruby-like language (crystal-lang.org) that I'm currently developing in, hoping Wasmer will be embedded in it. thank you!

**Comment by syrusakbary** [comment]
That would be great! We don't have crystal experience internally so if you could help us creating the embedding that would be awesome

**Comment by naqvis** [comment]
Published wasmer binding to crystal on [wasmr-crystal](https://github.com/naqvis/wasmer-crystal)

**Comment by syrusakbary** [comment]
Great work @naqvis. I've just linked to the package in the README docs :)
