### ISSUE TITLE
Add an imported function environment

### ISSUE THREAD

**Issue by Hywan** [wasmerio/wasmer#267]
### Summary

An instance has a context (`vm::Ctx`), which is passed as the first argument of any imported function.

In order to integrate the runtime into dynamic languages, we need to add a _context per function_. So far, to declare an imported function, one must pass a function pointer. Thus, it is not possible to pass a function pointer with an environment/context, which is required in many cases. Think of a closed scope to the function pointer.

### Additional details

I need this for wasmerio/php-ext-wasm and other integrations. In dynamic languages, a function declared in the language land (for instance in the PHP land) has no function pointer. It is a pair of 2 structures. Thus, the strategy to implement imported functions that live in the PHP land is: Register a “dispatcher function” per imported functions, that, given its _function context_, will look for the appropriated 2 structures, and use them to call the PHP functions.

With a C++-ish pseudocode, it looks like:

```cpp
int32_t my_imported_dispatcher_function(
    const wasmer_instance_context_t *instance_context, /* already here */
    const wasmer_function_context_t *function_context, /* NEW! */
    int32_t x,
    int32_t y
) {
    my_structure *function_data = (my_structure *) wasmer_function_context_data_get(function_context);
    bool result = php_function_call(function_data->struct1, function_data->struct2);
    // …
}

// when registering our imported function, it's classic:
const wasmer_import_func_t *imported_function = wasmer_import_func_new(
    (void (*)(void *, void *)) my_imported_dispatcher_function,
    inputs_signature,
    inputs_signature_length,
    outputs_signature,
    outputs_signature_length
);

// then, register a specific context for this function:
wasmer_function_context_data_set(
    wasmer_function_get_context(imported_function),
    my_structure { … }
);
```

**Comment by MarkMcCaskey** [comment]
I think this has been resolved now
