### ISSUE TITLE
Windows release does not contain a import library for the dll

### ISSUE THREAD

**Issue by madebr** [wasmerio/wasmer#2680]
### Describe the bug

The [2.0.0 Binary Windows release](https://github.com/wasmerio/wasmer/releases/download/2.0.0/wasmer-windows-amd64.tar.gz) of wasmer does not contain an import library for linking with the dll.

Currently, the archive looks like:
```
└── wasmer-windows-amd64
    ├── ATTRIBUTIONS
    ├── bin
    │   ├── wapm.exe
    │   ├── wasmer.exe
    │   └── wasmer-headless.exe
    ├── lib
    │   ├── wasmer.dll
    │   └── wasmer.lib
    ├── include
   ...
```

It is missing: `wasmer.dll.lib`.
Additionally, `wasmer.dll` should be put in the `bin` folder.

The tree should thus become:
```
└── wasmer-windows-amd64
    ├── ATTRIBUTIONS
    ├── bin
    │   ├── wapm.exe
    │   ├── wasmer.dll
    │   ├── wasmer.exe
    │   └── wasmer-headless.exe
    ├── lib
    │   └── wasmer.dll.lib
    │   └── wasmer.lib
    ├── include
   ...
```

### Steps to reproduce

1. Download the windows binary release.
2. Write a mini wasmer user
3. I cannot link to `wasmer.dll` because no import library is available.

### Expected behavior

`lib/wasmer.dll.lib` is available.

### Actual behavior

`lib/wasmer.dll.lib` is not available.

### Additional context

Theoretically, it is possible for users to generate an import library using `dumpbin` or `pexports`.
But it should be part of the SDK because using the tools above might pick up internal symbols of wasmer.

**Comment by aadarshadhakalg** [comment]
Hey, @Amanieu any updates on this issue?

**Comment by madebr** [comment]
Recent releases ship `.dll.lib` import libraries, so this issue got resolved.
Thanks!
