### ISSUE TITLE
No --enable-experimental-io-devices switch in Wasmer 2.0.0 on Windows

### ISSUE THREAD

**Issue by niutech** [wasmerio/wasmer#2695]
I have downloaded the latest version of Wasmer 2.0.0 on Windows 10 x64 and wanted to use the I/O devices, so I typed:
```
wasmer.exe run --enable-experimental-io-devices wasmerboy.wasm
```
but I got this output:
```
error: Found argument '--enable-experimental-io-devices' which wasn't expected, or isn't valid in this context
        Did you mean --enable-simd?
```

Please include I/O devices in Windows build so that I could run `wasmerboy.wasm` as a standalone GUI app.

**Comment by Amanieu** [comment]
Does this still happen in the latest version of wasmer?

**Comment by niutech** [comment]
Yes, in Wasmer 2.2.0-rc1 I still get `error: Found argument '--enable-experimental-io-devices' which wasn't expected, or isn't valid in this context`

**Comment by Amanieu** [comment]
@syrusakbary Is there any reason not to enable the `experimental-io-devices` Cargo feature by default so it is included in the release builds?

**Comment by syrusakbary** [comment]
I think enabling `experimental-io-devices` required fixing some dependencies (if I recall properly we disabled it because one depdency was failing on unix), so that's why it was not enabled. But once we do update the depdenencies I think it should be good to go
