### ISSUE TITLE
Use in browser environment

### ISSUE THREAD

**Issue by corwin-of-amber** [wasmerio/wasmer#2697]
From browsing the codebase, it seems like a lot of work has already gone towards supporting a browser target with its native WebAssembly VM, providing a respective imports object for running WASI-compiled binaries.

I have build `lib/wasi` with the `js-default` feature but could not figure out how it is supposed to be used from a main.js.
Can we get some pointers for how to build it for this purpose and use it in the browser? Regrettably, all searches across the web lead back to the old version of wasmerio/wasmer-js, so disseminating the new approach is going to take some patience ☺️

**Comment by syrusakbary** [comment]
Hi @corwin-of-amber, we are very close to releasing the new version of wasmer-js.

You can check the codebase here:
https://github.com/wasmerio/wasmer-js/tree/refactor

Let me know if you have any questions!

**Comment by corwin-of-amber** [comment]
Awesome update! I will check it out.
