### ISSUE TITLE
Modules compiled with "universal" wasmer are not universal

### ISSUE THREAD

**Issue by liamappelbe** [wasmerio/wasmer#2707]
### Describe the bug

I'm trying to [update Dart's package:wasm from version 2.0.0 to 2.1.0](https://github.com/dart-lang/wasm/pull/68), but I'm getting an error in one of my tests. The test tries to instantiate a module that was serialized to a file using `wasm_module_serialize`. I serialized the file on Linux, and the test fails on Mac with this error:

```
missing requires CPU features: "EnumSet(BMI1 | BMI2 | AVX2 | LZCNT)"
```

The cargo.toml that pulls in wasmer looks like this:

```
[package]
name = "wasmer"
version = "2.1.0"

[lib]
name = "wasmer"
crate-type = ["staticlib"]
path = "wasmer.rs"

[dependencies.wasmer-c-api]
version = "2.1.0"
default-features = false
features = ["jit", "cranelift", "wasi", "universal"]
```

My understanding is that if I put "universal" in the feature list, I should be able to compile and serialize a module on one machine, and deserialize it on a different machine with a totally different OS and architecture. This test worked in version 2.0.0.

### Steps to reproduce

Compile and serialize a module on Linux (using `wasm_module_serialize`), and try to deserialize and instantiate it on Mac (using `wasm_module_deserialize`).

### Expected behavior

If wasmer was built with the "universal" feature, the module should be able to run, even though it was compiled on a different architecture.

### Actual behavior

Instantiation may fail, depending on the destination architecture.

**Comment by Amanieu** [comment]
`universal` is just the new name for the `jit` engine, it has nothing to do with making serialized modules portable.

In fact serialized modules are inherently non-portable. What you can do however is cross-compile a module by setting up the target using `Universal::set_target`. This allows you to select the target OS, CPU, etc. Make sure that the CPU features selected are a subset of the ones actually available on the target machine.

**Comment by liamappelbe** [comment]
Hmmm. That's not what I was told on #2595. @syrusakbary

If I wanted to make the serialized modules cross platform, could I just specify an empty set of CPU features? How much slower would the running code be if I do this?

Also, what's new in 2.1.0 that causes this breakage? It definitely worked in 2.0.0.

**Comment by Amanieu** [comment]
> If I wanted to make the serialized modules cross platform, could I just specify an empty set of CPU features? How much slower would the running code be if I do this?

On x86 you need to specify SSE2 at minimum for the cranelift compiler, and AVX for the singlepass compiler.

> Also, what's new in 2.1.0 that causes this breakage? It definitely worked in 2.0.0.

2.1.0 actually verifies that the CPU supports the required features before instantiating a module.
