### ISSUE TITLE
Remove libtinfo.so dependency in Wasmer 4.0+ (with LLVM)

### ISSUE THREAD

**Issue by omarabid** [wasmerio/wasmer#2716]
I've installed wasmer in Archlinux using the terminal command provided in the landing page

```
curl https://get.wasmer.io -sSfL | sh
```

However, some libraries seems to be missing. Wasmer doesn't run and throws the following error

```
./wasmer: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
```

This can be fixed by installing ncurses5-compat-libs from the community repo

```
yay -S ncurses5-compat-libs
```

**Comment by jcaesar** [comment]
(Interestingly, installing wasmer with `pacman -S wasmer` on archlinux yields binaries that don't depend on `libtinfo`… oO)

**Comment by SamuraiCrow** [comment]
`pacman -S wasmer` does work on Manjaro as well but doesn't install WAPM.  I tried installing the WAPM package from AUR and it failed.  The plot thickens.

**Comment by Amanieu** [comment]
This happened because Wasmer 2.1 switched to using the official LLVM libraries releases. Previously, it used custom LLVM builds which specifically disabled terminfo support in LLVM (which we don't actually need and is causing this issue). For now the workaround of installing `ncurses5-compat-libs` should be enough but in the future we might want to start using custom LLVM builds again.

**Comment by ryanoneill** [comment]
FYI, I encountered this on a fairly standard Linux Mint 20.3 (Una) install. Installing `libncurses5` via apt resolved the issue. Thanks!

**Comment by kenorb** [comment]
Same on Ubuntu 21.10.

**Comment by jcaesar** [comment]
@jonaprieto 
```none
# dnf repoquery -l ncurses-compat-libs.x86_64 | grep libtinfo
/usr/lib64/libtinfo.so.5
```
Did you maybe accidentally install the `i686` variant? [This](https://github.com/wasmerio/wasmer/issues/2822#issuecomment-1109442782) for some reason does that…

**Comment by jonaprieto** [comment]
Yes. Indeed.

**Comment by brainwo** [comment]
Got the same issue on Arch Linux, installed via pacman. Running the latest 2.3.0 version.

**Comment by syrusakbary** [comment]
Wasmer needs to stop depending on `libtinfo` for next releases. Thanks for the ping everyone

**Comment by ptitSeb** [comment]
This is fixed on current version. A custom build of llvm is used and wasmer binary have no dependcies with ncurses.
 I checked with latest 4.2.0:
```bash
$ ldd ~/.wasmer/bin/wasmer
        linux-vdso.so.1 (0x00007ffc14fda000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f73ffa4c000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f73ffa47000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f73ff968000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f73ff74e000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f73ff56d000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f7404442000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f73ff54b000)
```

Closing the ticket. Feel free to re-open if it happens again (but it should not).
