### ISSUE TITLE
Cache files should be version-dependent

### ISSUE THREAD

**Issue by jedisct1** [wasmerio/wasmer#272]
Keys used for cache files only depend on the original wasm file data.

When wasmer is updated or compiled differently, the old cache files keep being silently used forever.

Ideally, a UID generated at compile-time should be used as the BLAKE2B key or salt in order to have a cache directory seamlessly shared by multiple wasmer versions.

**Comment by lachlansneff** [comment]
So, you're saying that we should version our wasm files somehow, suggesting that it be done by generating a unique salt per wasmer version?

**Comment by jedisct1** [comment]
Exactly.

**Comment by lachlansneff** [comment]
I think this is a good idea and will look into implementing it.
