### ISSUE TITLE
Use of supertrait bounds makes it tedious to implement some traits

### ISSUE THREAD

**Issue by nagisa** [wasmerio/wasmer#2731]
### Describe the bug

This issue is not limited to, but perhaps best exemplified by the `Tunables` trait. This trait seems like something that one might want to implement (there's even an example to do so!), but in order to implement this trait it is also necessary to implement the external trait `loupe::MemoryUsage`. Since `loupe::MemoryUsage` itself is not re-exported by `wasmer`, implementing `Tunables` suddenly requires importing an entirely unrelated third party crate.

If the user does not utilize the `MemoryUsage` functionality themselves, then the motivation for implementing this trait disappears entirely (other than the fact that it gatekeeps the developer from implementing the trait of interest itself).

### Steps to reproduce

Try to implement `Tunables` for your own type.

### Expected behavior

`Tunables` and other similar traits should be implementable without requiring the developer to implement traits/functionality irrelevant to them.

I think one of the straightforward options here would be to have a 

```rust
impl MemoryUsage for dyn Tunables + Send + Sync {
    fn size_of_val(&self, tracker: &mut dyn MemoryUsageTracker) -> usize
        ...
    }
}
```

or somesuch which then delegates to some method of the `Tunables` trait.

**Comment by syrusakbary** [comment]
It makes a lot of sense. I was thinking that perhaps would be a good idea to make `loupe::MemoryUsage` dependency optional across all crates. Thoughts?

**Comment by nagisa** [comment]
Hm, if `MemoryUsage` was made optional, then perhaps simply re-exporting `MemoryUsage` from something like `wasmer-types` could be good enough for people who actively utilize that functionality, and for the rest of us it would no longer be a concern at all.

**Comment by syrusakbary** [comment]
Adding the 2.x milestone and @Amanieu so we can move this things forward as part of the next release

**Comment by Amanieu** [comment]
We don't use `MemoryUsage` internally, it's purely available as a way for users to estimate the memory usage of their Wasm instances. I think the best solution here would be to just re-export the `loupe` crate as `wasmer::loupe`. This allows users to just import `wasmer::loupe::MemoryUsage` and then `#[derive(MemoryUsage)]` to satisfy the supertrait requirement.

> Adding the 2.x milestone and @Amanieu so we can move this things forward as part of the next release

The timing is rather unfortunate since the 2.1.1 release just went out an hour ago.

**Comment by syrusakbary** [comment]
#2744 is the follow-up for this issue
