### ISSUE TITLE
wasmer_emscripten example?

### ISSUE THREAD

**Issue by rygo6** [wasmerio/wasmer#2738]
I got a new Rust project compiling with:
```
wasmer = "2.0"
wasmer-emscripten = "2.1.1"
```

I got wasmer instancing a wasm module and running it. But I am trying now to get an emscriptem wasm module loaded and have fiddled with the calls trying to guess what do, but am wondering, is there an example anywhere of how to use wasmer-emscripten? The docs here don't give a lot of info of what exactly to call and when: https://docs.rs/wasmer-emscripten/2.1.1/wasmer_emscripten/

**Comment by Amanieu** [comment]
You can refer to [this code](https://github.com/wasmerio/wasmer/blob/a66226594f5035c6a4816ad338c257f2ce5c5c86/lib/cli/src/commands/run.rs#L100) in the wasmer command-line interface which runs an emscripten module.

**Comment by jcaesar** [comment]
I'm curious, how did you create your emscripten wasm module? (I've [tried](https://github.com/wasmerio/wasmer/issues/2498#issuecomment-932257354), and never managed to compile rust in a way that wasmer-emscripten is compatible with…)
