### ISSUE TITLE
Maybe a bug: integerDivideByZero

### ISSUE THREAD

**Issue by ERICXUCHI** [wasmerio/wasmer#2739]
### Describe the bug

Hello, I wanna tell an inconsistency between two similar testcases:

```c
// test1.c
#include <stdio.h>

int main(){
    int a = 9;
    int b = 0;
    int c = a / b;
    printf("%d", c);

    return 0;
}
```

```c
// test2.c
#include <stdio.h>

int main()
{
    int a = 9 / 0;
    
    printf("%d", a);

    return 0;

}

```

compile by emscripten:

`emcc test1.c -s STANDALONE_WASM=1 -o test1.js` 

 `emcc test2.c -s STANDALONE_WASM=1 -o test2.js`

then run:

`wasmer test1.wasm`

`wasmer test2.wasm`

test2.wasm generates 0

```sh
echo "`wasmer -V` | `rustc -V` | `uname -m`"
```

` wasmer 2.0.0 | rustc 1.51.0 (2fd73fabe 2021-03-23) | x86_64 `

### Steps to reproduce

compile by emscripten:

`emcc test1.c -s STANDALONE_WASM=1 -o test1.js` 

 `emcc test2.c -s STANDALONE_WASM=1 -o test2.js`

then run:

`wasmer test1.wasm`

`wasmer test2.wasm`

here is the result:

for test1.wasm:

```
error: failed to run `test1.wasm`
│   1: WASI execution failed
│   2: failed to run WASI `_start` function
│   3: RuntimeError: integer divide by zero
           at <unnamed> (test1.wasm[5]:0x2cd)
           at <unnamed> (test1.wasm[6]:0x314)
╰─> 4: int_divz
```

for test2.wasm:

0

### Expected behavior

for test2.wasm:

should be error

### Actual behavior
 
0

### Additional context

![image](https://user-images.githubusercontent.com/57583292/147824301-3ca9b15a-3fc0-4972-aa0d-07a883b60c2e.png)

**Comment by Amanieu** [comment]
Division by 0 is undefined behavior in C, so emcc is free to compile it to anything it wants. This is not a problem with wasmer.
