### ISSUE TITLE
wasmer 2.1.1 build issues

### ISSUE THREAD

**Issue by williamh** [wasmerio/wasmer#2740]
I attempted to write a Gentoo ebuild for wasmer-2.1.1 based on the information in PACKAGING.md and found a couple of issues.

- wasmer does not honor WASMER_INSTALL_PREFIX.
- The wasmer.pc file that is installed is empty.

I attempted to run the make commands manually and saw the same issues.

Here are the steps I ran manually. If this is fixed it should solve the packaging issue.

```
$ export WASMER_INSTALL_PREFIX=/usr
$ make
$ DESTDIR=/tmp/test make install
```

After you run these steps, you will see that the installation is in /tmp/test instead of /tmp/test/usr. Also, you will see that the wasmer.pc file is empty.

Thanks for your time,

William

**Comment by Amanieu** [comment]
- You are expected to include WASMER_INSTALL_PREFIX in DESTDIR.
- The wasmer.pc file is fixed by #2743

**Comment by williamh** [comment]
@Amanieu  Thanks for responding.
If I didn't miss it, You might want to document your expectation about WASMER_INSTALL_PREFIX being included in destdir somewhere. Most of the time this behavior is not the case.
[DESTDIR](https://www.gnu.org/prep/standards/html_node/DESTDIR.html) is usually pre-pended to installation paths.

**Comment by Amanieu** [comment]
I've updated the README to clarify the behavior of DESTDIR.
