### ISSUE TITLE
Add str type to wasmer-runtime

### ISSUE THREAD

**Issue by Haski-server** [wasmerio/wasmer#275]
Please add type str for imported functions.

**Comment by lachlansneff** [comment]
Wasm doesn't have a string type and different language implement strings different, so it's not really possible for us to have a universal str type. You can implement one for your use case by using the primitive types given however.

**Comment by Haski-server** [comment]
In the example, https://github.com/wasmerio/wasmer-rust-example is copying a string from the VM memory. But in the documentation for the library, I did not find a copy of something in the VM memory.

**Comment by lachlansneff** [comment]
I'm not entirely sure what you mean. The wasmer-rust-example copies a string (that is the memory representing a string) from the wasm memory to a `Vec` and then reinterprets it as a `&str`.

**Comment by Hywan** [comment]
@Haski-server WebAssembly only supports `u32`, `u64`, `f32` and `f64`. If you want to copy a string, let's say from JS to Wasm, you need to encode it as a sequence of bytes, then copy each byte into the Wasm memory, something like that:

```js
function writeBuffer(Module, string) {
    const buffer = new TextEncoder().encode(string);
    const buffer_length = buffer.length;
    const pointer = Module.alloc(buffer_length);
    const memory = new Uint8Array(Module.memory.buffer);

    for (let i = 0; i < buffer_length; ++i) {
        memory[pointer + i] = buffer[i];
    }

    return pointer;
}
```

(see [`TextEncoder`](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder)).

And on the Wasm part, let's say if the original program is written in Rust, you have to reconstitute your string based on this sequence of bytes, like this:

```rust
#[no_mangle]
pub extern "C" fn readString(pointer: *mut u8, length: usize) -> … {
    let slice: &[u8] = unsafe { slice::from_raw_parts(pointer, length) };
    let string = str::from_utf8(slice)?;

    // …
}
```

(see [`str::from_utf8`](https://doc.rust-lang.org/std/str/fn.from_utf8.html)).

I don't want to push my own work, but I wrote a series on my blog, and this episode might interest you: https://mnt.io/2018/08/22/from-rust-to-beyond-the-webassembly-galaxy/. It shows every details to pass strings, structures etc. between JS to Rust through Wasm. I hope it helps!

**Comment by CryZe** [comment]
As a side note: In real code you probably don't want to use the raw for loop for memcpy'ing the memory over. JavaScript has built-in memcpy via [TypedArray::set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/set)

**Comment by Haski-server** [comment]
> @Haski-server WebAssembly only supports `u32`, `u64`, `f32` and `f64`. If you want to copy a string, let's say from JS to Wasm, you need to encode it as a sequence of bytes, then copy each byte into the Wasm memory, something like that:
> 
> ```js
> function writeBuffer(Module, string) {
>     const buffer = new TextEncoder().encode(string);
>     const buffer_length = buffer.length;
>     const pointer = Module.alloc(buffer_length);
>     const memory = new Uint8Array(Module.memory.buffer);
> 
>     for (let i = 0; i < buffer_length; ++i) {
>         memory[pointer + i] = buffer[i];
>     }
> 
>     return pointer;
> }
> ```
> 
> (see [`TextEncoder`](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder)).
> 
> And on the Wasm part, let's say if the original program is written in Rust, you have to reconstitute your string based on this sequence of bytes, like this:
> 
> ```rust
> #[no_mangle]
> pub extern "C" fn readString(pointer: *mut u8, length: usize) -> … {
>     let slice: &[u8] = unsafe { slice::from_raw_parts(pointer, length) };
>     let string = str::from_utf8(slice)?;
> 
>     // …
> }
> ```
> 
> (see [`str::from_utf8`](https://doc.rust-lang.org/std/str/fn.from_utf8.html)).
> 
> I don't want to push my own work, but I wrote a series on my blog, and this episode might interest you: https://mnt.io/2018/08/22/from-rust-to-beyond-the-webassembly-galaxy/. It shows every details to pass strings, structures etc. between JS to Rust through Wasm. I hope it helps!

Ctx.memory (0) is available for working with memory, but it does not allow writing to memory, only to read. How can I pass a string?
