### ISSUE TITLE
How to run demo in iOS

### ISSUE THREAD

**Issue by zhangjiuzhou** [wasmerio/wasmer#2751]
I tried to build IOS samples in Xcode, but the following compilation errors occurred. I don't know how to solve them

> Engine: dylib
> Compiler: cranelift
> Target: x86_64-apple-ios
> error: failed to compile `DylibExample/sum.wasm`
> ╰─▶ 1: Compilation error: Shared object file generator failed with:
>        stderr:Apple clang version 13.0.0 (clang-1300.0.29.30)
>        Target: x86_64-apple-ios
>        Thread model: posix
>        InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
>         "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -lto_library /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib -dynamic -dylib -arch x86_64 -platform_version ios-simulator 5.0.0 15.2 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -o /var/folders/vw/m5lcxmtn119fpb6txx3zhspr0000gp/T/wasmer_dylib_b3Y3nA.dylib /var/folders/vw/m5lcxmtn119fpb6txx3zhspr0000gp/T/wasmer_dylib_IdceF4.o -undefined dynamic_lookup
>        ld: warning: -undefined dynamic_lookup is deprecated on iOS Simulator
>        ld: dynamic main executables must link with libSystem.dylib for architecture x86_64
>        clang: error: linker command failed with exit code 1 (use -v to see invocation)
>        stdout:
> 
>

**Comment by zhangjiuzhou** [comment]
> 

I'm using DylibExample. The above error is caused when I run this example.

**Comment by DavidHy2021** [comment]
I tried to build IOS samples in Xcode, but the following compilation errors occurred. I don't know how to solve them
![截屏2023-02-14 16 33 15](https://user-images.githubusercontent.com/13817263/218681622-eb1d09ec-6fb7-40b1-9641-9f71c3fa196f.png)
