### ISSUE TITLE
ChainResolver and memory uninitialized

### ISSUE THREAD

**Issue by Defman** [wasmerio/wasmer#2752]
### Describe the bug
Using `ChainResolver` causes memory to not be initialize on `WasiEnv`.

### Steps to reproduce
Chain Was import object with any* other import object.

### Expected behavior

Memory to be initialized (not panic on `Memory should be set on `WasiEnv` first`)

### Actual behavior

Panic with the message `Memory should be set on `WasiEnv` first`.

**Comment by syrusakbary** [comment]
Hey @Defman can you create a repo or publish here a zip file with a way to reproduce the issue? Thanks!

**Comment by Defman** [comment]
Our own env depends on some wasi functions being exported by the instance which hence depends on wasi_env. Our evn should be initialized after wasi_env... have solved our own internal issue by removing the env initialization order.

**Comment by Defman** [comment]
I would like to reopen this issue and explain it a bit further.

Let `AEnv` be an environment which initialization depends on `BEnv` being initialized. How can we control the order of which environments are initialized?

In my use case I have an environment which depends on wasi allocate and is being called on environment initialization.

```rust
impl WasmerEnv for AEnv {
    fn init_with_instance(&mut self, instance: &Instance) -> Result<(), HostEnvInitError> {
        let _ = instance.exports.get_function("some_allocate_which_uses_wasi_allocate")?;
        Ok(())
    }
}

**Comment by kwonoj** [comment]
I hit the same message, only if I'm trying to use `wasmer::js` while same logic works with `wasmer::sys`.

It's little bit complex to repro, with this PR

https://github.com/swc-project/swc/pull/4151

- `cd tests/rust-plugins/swc_internal_plugin && cargo build --target wasm32-wasi`
- `cd creates/wasm && ./scripts/build.sh && node test.js`  

```
// test.js
const swc = require('./pkg');
const fs = require('fs');

const bytes = fs.readFileSync('../../tests/rust-plugins/swc_internal_plugin/target/wasm32-unknown-unknown/debug/swc_internal_plugin.wasm');

const resolver = { test: bytes };

let ret = swc.transformSync(`console.log('boo');`, {
  jsc: {
    experimental: {
      plugins: [['test', {}]]
    }
  }
}, resolver);
console.log(ret);
```

**Comment by syrusakbary** [comment]
Thanks for the the detail explanation @kwonoj, we'll take a look

I believe that might be caused by a bug in either the `init_envs` function in `wasmer::js::Instance` or when chaining imports (although I'm not 100% sure yet)

**Comment by epilys** [comment]
@kwonoj @Defman I was not able to reproduce this. Steps I took:

- load a wasi module
- chain its imports with functions with a different environment
- make an Instance and run its `_start` function
- run it with `wasm-pack`

If you still get this error, can you make a small example that reproduces it in the style of the test functions here: https://github.com/wasmerio/wasmer/blob/2.2.1/lib/wasi/tests/js.rs
