### ISSUE TITLE
docs.rs build has failed for 2.1.0 and 2.1.1

### ISSUE THREAD

**Issue by dsherret** [wasmerio/wasmer#2765]
I went to go check out the docs because I'm curious about the new "js" feature, but it seems they're not building for the latest versions.

https://docs.rs/crate/wasmer/2.1.1

* https://docs.rs/crate/wasmer/2.1.1/builds/480618
* https://docs.rs/crate/wasmer/2.1.0/builds/470439

**Comment by jcaesar** [comment]
Apologies, that was my bad. It [should](https://github.com/wasmerio/wasmer/pull/2734) work again in the next release.

**Comment by Amanieu** [comment]
Fixed in 2.2.0-rc1.
