### ISSUE TITLE
Support SSE legacy instructions for the SInglepass compiler

### ISSUE THREAD

**Issue by batconjurer** [wasmerio/wasmer#2767]
### Motivation

I am trying to run a block chain node on my home server and the chain uses wasmer for its smart contracts. My server uses the legacy SSE 4.2 instructions so when trying to compile the wasm code using the singlepass compiler, I get an error because only the newer AVX instructions are supported.

We should support these legacy instructions as many machines out there still use them and new computers are still being sold with chips that use them. 

### Proposed solution

I looked at `emitter_x64.rs` and I see that the AVX instructions used mostly have an SSE counterpart. Non-destructive instructions were introduced in AVX. For SSE, to achieve the same behavior, requires two instructions: A move and then the destructive instruction. 

Some ops such as blendvps only have support on SSE 4.1, so it will have to mimicked for older SSE versions if those are to be supported.

**Comment by syrusakbary** [comment]
It would be great to have a PR so we can take a look. We should emit the optimal AVX code when possible (if the CpuFeature::AVX is available on the host) and SSE 4.2 in case CpuFeature::SSE42 is present (and not AVX).

https://docs.rs/wasmer/2.0.0/wasmer/struct.Target.html#method.cpu_features
https://docs.rs/wasmer/2.0.0/wasmer/enum.CpuFeature.html

**Comment by syrusakbary** [comment]
Adding @ptitSeb to also confirm from our side that everything should be good with this strategy

**Comment by ptitSeb** [comment]
Sounds good to me (and requiring AVX is a bit overkill, so I'm good with an SSE only option)

**Comment by batconjurer** [comment]
I've hacked together a decent amount of the SSE code, so I will do a bit of clean up and can start a PR. If we go with SSE 4.2 only, this will be pretty easy I think. If we want to support older SSE, this will require more work and I haven't finished investigating how much.

**Comment by syrusakbary** [comment]
I think SSE 4.2 should be fine for now (we can always add more support for older SSE apart)

**Comment by hasselalcala** [comment]
Hello! 

I new learning near and sandbox and I have the next problem <img width="1051" alt="Captura de pantalla 2024-04-24 a la(s) 11 57 39 a m" src="https://github.com/wasmerio/wasmer/assets/83148363/5457b6ae-0559-4eaa-a606-09d694145044">

and I found this issue https://github.com/near/near-workspaces-rs/issues/110 

Im not sure how to proceed because I am having problems to test my contracts. 

Any idea? Thanks.
