### ISSUE TITLE
Failure to run Wasmer 2.2.0-rc1 on macOS x86_64

### ISSUE THREAD

**Issue by MaxDesiatov** [wasmerio/wasmer#2772]
### Describe the bug

Running this command
```sh
$ curl https://get.wasmer.io -sSfL | sh
```
produces this output:
```
downloading: wasmer-darwin-amd64
Latest release: 2.2.0-rc1
Downloading archive from https://github.com/wasmerio/wasmer/releases/download/2.2.0-rc1/wasmer-darwin-amd64.tar.gz

######################################################################## 100.0%

error: Your platform is not yet supported (darwin-amd64).
Please open an issue on the project if you would like to use wasmer in your project: https://github.com/wasmerio/wasmer
```

### Steps to reproduce

1. Runt the installation steps on macOS Big Sur (presumably reproducible on any macOS version) x86_64: `curl https://get.wasmer.io -sSfL | sh`

Here's a link to our failing CI run: https://github.com/swiftwasm/swift/runs/4979932239?check_suite_focus=true

### Expected behavior

Installation is completed successfully, as it did with Wasmer 2.1.1.

### Actual behavior

The error message is shown as above.

**Comment by Amanieu** [comment]
Can you try again? There was an issue with setting up the github release.

**Comment by MaxDesiatov** [comment]
That fixes it, thanks!
