### ISSUE TITLE
Use a more compact encoding for trap information

### ISSUE THREAD

**Issue by Amanieu** [wasmerio/wasmer#2773]
Current we store trap information for all possible trapping instructions as a `TrapInformation` struct which consists of a 32-bit code offset and a 32-bit trap code. This occupies 8 bytes per trap code.

Since traps are infrequent, we should optimize this information for size as much as possible. One potential encoding would be a byte stream consisting of alternating pairs of [ULEB128](https://en.wikipedia.org/wiki/LEB128)-encoded offsets and 1-byte trap codes. Each offset is encoded relative to the previous offset (the first offset is relative to the start of the function). This should reduce the overhead per trap to 2 bytes.

The end of the array of trap information is marked by a trap code byte with the high bit set.

**Comment by syrusakbary** [comment]
Side question: Do you know if this strategy is possible with cranelift @Amanieu ?

**Comment by Amanieu** [comment]
Yes it should work for both singlepass and cranelift.

**Comment by syrusakbary** [comment]
I assumed LLVM too?
Side question: does this strategy work in any chipset architecture? (arm, risc-v, ...)

**Comment by Amanieu** [comment]
LLVM doesn't seem to use the trap information, I'll need to look into it a bit more. And yes, this works on any arch.

**Comment by syrusakbary** [comment]
Oh, I think I got a bit confused. I thought this ticket was proposing to attach the trap info itself next to the `ud2` trap bytes (as that's what I thought @ptitSeb was mentioning the other day) but now I understand it's about the encoding format itself so it's faster to decode

**Comment by ptitSeb** [comment]
We discussed both subject, the trap info as a paiload to the undefined instruction, and the recodic of the trap info to be more efficient.
They are not exclusive, both can be done.

**Comment by ptitSeb** [comment]
So, singlepass now use a TrapCode embedded in the undefined opcode used. Other compiler have not been changed, as the gain in compacity for trap information is at the cost of a bigger complexity, especialy since trapinformation can be handle in an individual way.
I propose this ticket to be closed now @syrusakbary .
