### ISSUE TITLE
Singlepass v2 on ARM fails to compile

### ISSUE THREAD

**Issue by syrusakbary** [wasmerio/wasmer#2777]
The program `main.wasm` which is a Go database (TiDB) is able to run on other compilers but when run with singlepass it outputs the following:

Download the file here: https://registry-cdn.wapm.io/contents/lucklove/tidb/0.1.6/main.wasm

```
$ wasmer run main.wasm --singlepass
thread '<unnamed>' panicked at 'singlepass can't emit LDR S64, Memory(X29, -104), Memory(X8, 0)', lib/compiler-singlepass/src/emitter_arm64.rs:382:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'singlepass can't emit LDR S64, Memory(X29, -72), Memory(X8, 0)', lib/compiler-singlepass/src/emitter_arm64.rs:382:18
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ImpossibleRelocation(Dynamic(DynamicLabel(2)))', lib/compiler-singlepass/src/machine_arm64.rs:1891:35
```

**Comment by ptitSeb** [comment]
You need to be patient, it may take a long time for the other compiler to build this one.

I suggest you read this blog entry: https://wasmer.io/posts/wasmer-2.2 at the end, there are some compile benchmark.

**Comment by Zhangyx24** [comment]
Thanks a lot !
