### ISSUE TITLE
Serialized module stability

### ISSUE THREAD

**Issue by webmaster128** [wasmerio/wasmer#2781]
### Summary

In one of our use case we compile and serialize modules with Wasmer 2.0.0 and derialize and run it with Wasmer 2.1.1. This leads to crashes at runtime. As soon as the cache is cleared between the two versions, everything works smoothly.

I digged a bit in the code and have two questions:
1. Do I understand correctly that the commit https://github.com/wasmerio/wasmer/commit/a603c33def41cb3816aea89334cd53d2d43f82f0 is breaking the module format because `SerializableModule` changed?
2. Is there any kind of stability guarantee that Wasmer can give users? Would it be possible to expose a module serialization number to let callers know when the format changed?

### Additional details

- Using the Universal engine with Singlepass.
- We have a module serialization version already that we could use on our side if we know a breaking change happened (https://github.com/CosmWasm/cosmwasm/blob/66b987766423c154cb0e99a7e28157f7ab3d27cf/packages/vm/src/modules/file_system_cache.rs#L10-L17).

**Comment by Amanieu** [comment]
1. In #2747 we added version checking when loading serialized module, so incompatible modules simply fail to load with an error. This change is not included in 2.1.1 but is in 2.2.0-rc1.
2. As a general rule serialized modules are only compatible with the exact same version of Wasmer that created them.

**Comment by webmaster128** [comment]
Thank you for the quick response and update. This solves a large part of the problem: random crashes are converted into load time errors.

Now for the context of blockchain, it would be very unfortunate if we had to recompile all the program for every Wasmer bump. Especially when the caller of Wasmer is a library, not an application we can have users thet upgrade Wasmer without us knowing.

Would it be possible as an addition to #2747 to export the version as a compile time constant? This would allow me to do something like this:

```rust
// TODO: convert to compile time error once available in Rust
assert_eq!(MetadataHeader::CURRENT_VERSION, 1, "Wasmer module format changed. Please update the expected version accordingly and bump MODULE_SERIALIZATION_VERSION.");
```

**Comment by epilys** [comment]
This is tracked in #2916.
