### ISSUE TITLE
WasmerEnv should fallback to import object if not found in export

### ISSUE THREAD

**Issue by Defman** [wasmerio/wasmer#2794]
Thanks for proposing a new feature!

### Motivation

I'm trying to use wasi with imported memory instead of exported memory and I have run into the issue that the `wasmer-wasi` crate uses the `WasmerEnv` to get a reference to the memory. Which ofc's fails do to it being imported and not exported.

### Proposed solution

Make the export object fallback to imported objects, kinda like chain resolver.

### Alternatives

Is it possible to export an imported object?

**Comment by Amanieu** [comment]
Could you explain what your use case is for using an imported memory instead of one exported from the module?

**Comment by epilys** [comment]
`WasmerEnv` won't be present in 3.0, but there will be a way to manually manage the environments which would allow your usecase
