### ISSUE TITLE
Generating wat from Abstract Syntax Tree

### ISSUE THREAD

**Issue by fade2black** [wasmerio/wasmer#2813]
### Summary

I have written frontend part (parsing and generating AST) of a toy programming language written in Rust. It is a simple Kaleidoscope like language. Now I'd like to generate wat code from that AST. How could I go about it? For example in LLVM we have a C++ IRBuilder class that to create LLVM instructions.

**Comment by SamuraiCrow** [comment]
LLVM has an experimental WASM backend so using WASM2WAT from the WebAssembly Binary Toolkit (WABT) would probably be the best way to convert the WebAssembly binary to WebAssembly text.

**Comment by fade2black** [comment]
@SamuraiCrow I don't want to convert wasm into wat. I have a AST (Abstract Syntax Tree), say for expression. I want to generate wat from the that abstract syntax tree. The hardest way is to generate it manually looking at AST itself. But I'm curious whether or there is a crate/module that takes AST and builds wat as a target.

**Comment by SamuraiCrow** [comment]
An AST is typically custom made for the language so it is unlikely that a code generator is already available.
