### ISSUE TITLE
WAPM not included with Homebrew install

### ISSUE THREAD

**Issue by deecewan** [wasmerio/wasmer#2815]
### Describe the bug

Pretty much all the documentation I've seen implies that `wapm` (and by extension `wax`) _come with_ a `wasmer` install, however `brew install wasmer` doesn't seem to give any binaries other that `wasmer`.

See [here](https://docs.wasmer.io/ecosystem/wapm/getting-started#install-wapm) for the docs that say:

> WAPM comes bundled with Wasmer, so you just need to install Wasmer in your system to have the `wapm` CLI!

```sh
echo "`wasmer -V` | `rustc -V` | `uname -m`"

> "wasmer 2.2.0 | rustc 1.55.0 (c8dfcfe04 2021-09-06) | x86_64"
```

### Steps to reproduce

1. `brew install wasmer`

### Expected behavior

2. `wapm` is installed

### Actual behavior

`wapm` results in `command not found: wapm`

**Comment by SamuraiCrow** [comment]
The Arch Linux packager supplied WAPM as a separate package.  Did Homebrew do something similar on the Mac?

**Comment by deecewan** [comment]
🤔 yep looks like `wapm` is supplied separately on Homebrew, too. Interesting that the documentation doesn't reference that, tho

**Comment by SamuraiCrow** [comment]
Do you mean the documentation of Homebrew or of Wasmer?  Package maintainers are not affiliated with Wasmer.

**Comment by deecewan** [comment]
of Wasmer. They reference installing from Homebrew, but the homebrew package doesn't include either `wapm` or `wax`, both of which are "automatically available" when you install wasmer

**Comment by jcaesar** [comment]
So you would like for https://github.com/wasmerio/wasmer/blame/704d93530c11fbd2ee8ec772e98a635f8d9f481d/README.md#L65 to be updated?
