### ISSUE TITLE
Recommended pattern to setup workspace have multiple binary depends on different feature sets

### ISSUE THREAD

**Issue by kwonoj** [wasmerio/wasmer#2817]
### Summary

Hi, this time's question is regarding organizing workspaces. 

Here's simplified example https://github.com/kwonoj/wasmer-js-test/tree/workspace-features-resolution

```
//workspace
 - A (compiled to wasm)
   - runner_base
 - B (native binary)
   - runner_base
 - runner_base
   - [features = "js"]
      - wasmer/js
   - [features = "native"]
      - wasmer/sys
```

A and B are orthogonal, no direct overlaps except sharing some of common dependencies. Common dependency opt to in to specific feature of wasmer depends on build target. This makes build failures by cargo, with errors like 

```
    |
233 |                 crate::Function::get_self_from_extern(_extern)?.native().map_err(|_| crate::sys::exports::ExportError::IncompatibleType)
    |                        ^^^^^^^^ ambiguous name
    |
    = note: ambiguous because of multiple glob imports of a name in the same module
note: `Function` could refer to the struct imported here
   --> /home/ojkwon/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-2.2.0/src/lib.rs:467:9
    |
467 | pub use sys::*;
    |         ^^^^^^
    = help: consider adding an explicit import of `Function` to disambiguate
note: `Function` could also refer to the struct imported here
   --> /home/ojkwon/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-2.2.0/src/lib.rs:473:9
```

Which looks like cargo try to resolve wasmer for every feature for each build target somewhat sound similar to https://github.com/rust-lang/cargo/issues/4463, but cannot say for sure if this is the exact case or wasmer have some internal behavior raises this.

Is there a recommended pattern to workaround this in easy way?

Thanks.

### Additional details

Provide any additional details here.

**Comment by syrusakbary** [comment]
Hey @kwonoj, I'm unable to access the repo posted: https://github.com/kwonoj/wasmer-js-test/tree/workspace-features-resolution

So I'll reply a bit more blindly.
I think the issue might be that `runner_base` is depending on `wasmer` with the default features activated.
Perhaps using wasmer without any default feature and then the "native" feature will use `wasmer/sys` and "js" `wasmer/js` should just work?

It might be also doable to do it via target features.

To put an example in our repo, the wasmer-wasi integration can target both the native system and the JS (just depending on its features) and it works in the desired way when used as a dependency.

**Comment by kwonoj** [comment]
@syrusakbary sorry, I just made repo public. There is more contrived example at https://github.com/swc-project/swc we are trying to build, so far my attempt to set default-features=false with opt in specific feature somehow didn't work.

**Comment by syrusakbary** [comment]
No worries. How could I reproduce the issue on the provided repo?
(what are the commands that fail to run?)

**Comment by kwonoj** [comment]
mind try `cargo build`? also this PR's CI log shows the problem we want to solve. (https://github.com/swc-project/swc/pull/3876)

**Comment by syrusakbary** [comment]
Few findings:

1. I just realized that wasmer-cache depends on wasmer `sys` always (which shouldn't be the case): https://github.com/wasmerio/wasmer/blob/master/lib/cache/Cargo.toml#L14
2. Ideally you should use only one package and gate the native or wasm via features in that package (right now you have two different packages doing the same thing)

I also created the PR showcasing a fix: https://github.com/kwonoj/wasmer-js-test/pull/1

**Comment by kwonoj** [comment]
Thanks, I'll try to utilize suggestion into main repo to see if I can make things work. 

One quick q - https://github.com/kwonoj/wasmer-js-test/pull/1/files#diff-980f9468767d9444054506ddfa23bf39b71cafa00a6fe14d28339e2b85b98705R2 in here it selects specific pkg to build, will build whole (`cargo build`) works?

**Comment by syrusakbary** [comment]
No, the general `cargo build` doesn't work.

I think the best way to manage this is to have the wasmer dependency in one crate only and feature gate the js or native options as we do for example in wasmer-wasi: https://github.com/wasmerio/wasmer/blob/master/lib/wasi/Cargo.toml

In Wasmer, we had this same issue, and basically we are able to compile wasmer natively with `make build-wasmer` and also compile the wasmer-wasi version with `make test-js` all both being compatible in the same workspace.
https://github.com/wasmerio/wasmer/blob/master/Makefile#L526

So it's definitely doable

**Comment by kwonoj** [comment]
Sorry, please allow me to have one more question: the repo's example is simplified, the actual goal is a base package contains `wasmer` and selectively choose `js/sys` from host_native/wasm. 

(basically this again)

```
//workspace
 - A (compiled to wasm)
   - runner_base
 - B (native binary)
   - runner_base
 - runner_base
   - [features = "js"]
      - wasmer/js
   - [features = "native"]
      - wasmer/sys
   ```

This is essentially same as what you suggested

> the wasmer dependency in one crate only and feature gate the js or native options as we do for example in wasmer-wasi

if I understood correctly? 

> make build-wasmer and also compile the wasmer-wasi version with make test-js all both being compatible in the same workspace

This is actually something I wanted to avoid and curious if I could still use current practices (just running `cargo build`). Looks like I may need to introduce some way to selectively call build fn.

**Comment by syrusakbary** [comment]
> if I understood correctly?

Yup, that's it!

> This is actually something I wanted to avoid and curious if I could still use current practices (just running cargo build). Looks like I may need to introduce some way to selectively call build fn.

What we currently do in our codebase is: the native build builds normally with `make build-wasmer` (that executes `cargo build` under the hood, with the default features)
And in the case that we want to build for js, we actually use an extra feature provided to `wasm-pack` :) (`--no-default-features --feature ...`).

Hope this clarifies!

**Comment by kwonoj** [comment]
Thanks, that was helpful context. I'll try to dig bit further on our end.

**Comment by syrusakbary** [comment]
Hey @kwonoj, please let us know if we should keep the issue open (if something is not yet clarified or there are more changes to do in our side)

**Comment by kwonoj** [comment]
I saw you checked actual work https://github.com/swc-project/swc/pull/4012#discussion_r826363299 , indifferent to close issue or use it for further tracking.

**Comment by kwonoj** [comment]
It's not super elegant but at least seems I've reached `working` state, let me close this issue and create separate issue as needed. Thanks for the help!
