### ISSUE TITLE
How to use the staticlib engine in Rust

### ISSUE THREAD

**Issue by recmo** [wasmerio/wasmer#2827]
### Summary

I have a Rust library that calls a wasm library. Currently I `include_bytes!` the wasm bytecode. It is going to run on mobile devices, so reducing resources is important. I would like to statically compile and link the bytecode.

### Additional details

I tried

```rust
const WASM_STATICLIB: &[u8] = include_bytes!("wasm_staticlib.o");
let store = Store::new(&Staticlib::headless().engine());
let module = unsafe { Module::deserialize(&store, WASM_STATICLIB).unwrap() };
```

but this panics with

```
wasm should be valid: CorruptedBinary("misaligned metadata")
```

This happens no matter if the `.o` file is created using `Module::serialize` or the wasmer CLI:

```
wasmer compile path/to/wasm/file.wasm --llvm --staticlib -o my_wasm.o --header my_wasm.h
```

**Comment by heyjdp** [comment]
Thanks for the ticket. We have a Wasmer engine refactor planned, and we will incorporate this request into Wasmer 3.x

**Comment by ptitSeb** [comment]
This ticket seems outdated now. I close it. Feel free to re-open it if the issue is still present on curretn wasmer version.
