### ISSUE TITLE
Improve usabiliy of WasmerEnv trait

### ISSUE THREAD

**Issue by gterzian** [wasmerio/wasmer#2838]
### Motivation

[`init_with_instance`](https://github.com/wasmerio/wasmer/blob/baebb436e25f72657feb77fd059d1172ed2a011f/lib/api/src/sys/env.rs#L91) provides the host env with a `&Instance`, where `Instance` is `Clone`, making it very tempting for people to simply clone the instance and store it on the host env for later use, which seems to create a memory leak. 

### Proposed solution

`init_with_instance` could  take an argument that would enforce the implicit constraints of the method. 

For example a `&InitialiazedInstanceProxy`, which would not be `Clone`, and would have a method like `get_export_with_generics_weak`, wich would proxy internally to `instance.exports.get_with_generics_weak`.

### Alternative

Clarify this issue in the documentation. Good idea anyway, since people can still easily store an `Instance` on their host env outside of `init_with_instance`.

### Additional context

The temptation to store `Instance` on the host env is especially tempting in the light of using `wasmer_middlewares::metering`, since helper functions like [`get_remaining_points`](https://github.com/wasmerio/wasmer/blob/8f2e49d52823cb7704d93683ce798aa84b6928c8/lib/middlewares/src/metering.rs#L293) take an `&Instance` as argument, and it's not obvious how to get access to it from host functions unless stored on the env. 

Example of mistake made in the wild and fix: https://github.com/massalabs/massa-sc-runtime/pull/121

**Comment by heyjdp** [comment]
We are rethinking the API for Wasmer 3.0, this issue should be fixed by those changes. Thanks for the ticket!

**Comment by syrusakbary** [comment]
Closing this in favor of #2924
