### ISSUE TITLE
Is the stack check flag used?

### ISSUE THREAD

**Issue by gterzian** [wasmerio/wasmer#2844]
It appears to me the [`Singlepass.enable_stack_check`](https://docs.rs/wasmer-compiler-singlepass/latest/wasmer_compiler_singlepass/struct.Singlepass.html#method.enable_stack_check) flag is not actually used anywhere in the code. 

For example it seems to not be used at all in https://github.com/wasmerio/wasmer/blob/8f2e49d52823cb7704d93683ce798aa84b6928c8/lib/compiler-singlepass/src/codegen_x64.rs 

Perhaps the flag should be removed?

**Comment by Amanieu** [comment]
That's a good point, stack checks are always enabled. This flag should be removed.
