### ISSUE TITLE
Segmentation fault in Cranelift

### ISSUE THREAD

**Issue by francisco-perez-sorrosal** [wasmerio/wasmer#2849]
When running `rustpython.wasm` with Wasmer and cranelift, a segmentation bug occurs:
```bash
wasmer run rustpython.wasm --dir=. -- hello_wasmer.py
```

This succeeds with singlepass:

```
$ wasmer run rustpython.wasm --dir=. --singlepass --disable-cache -- hello_wasmer.py
a
```

But with Cranelift, it fails with a seg fault:

```
$ wasmer run rustpython.wasm --dir=. --cranelift --disable-cache -- src/hello_wasmer.py
[1]    87596 segmentation fault  wasmer run rustpython.wasm --dir=. --cranelift --disable-cache --
```
<img width="798" alt="Screen Shot 2022-04-17 at 18 31 19" src="https://user-images.githubusercontent.com/918006/163740817-cb94593b-da1c-4418-9dde-03f50495124b.png">

[segfault-cranelift.zip](https://github.com/wasmerio/wasmer/files/8502870/segfault-cranelift.zip)

**Comment by Amanieu** [comment]
I can't reproduce the crash on the latest master, it works fine for me. What version of wasmer are you using?

**Comment by syrusakbary** [comment]
It was using Wasmer 2.2.1 (latest release). This issue might be fixed by the stack refactor

**Comment by epilys** [comment]
@francisco-perez-sorrosal  I can't reproduce it either on 2.2.1 or 2.2.0 releases. You can check the version with `wasmer --version`. If you were indeed getting this segfault on the latest release, can you reopen this issue along with your CPU architecture? (x86_64 or arm64?)
