### ISSUE TITLE
linux-aarch64 platform is not yet supported wasmer2.2.1

### ISSUE THREAD

**Issue by zszs97** [wasmerio/wasmer#2860]
### Download the latest version of wasmer from Ubuntu 20 server installed on raspberry pie 4B
error：

```sh
downloading: wasmer-linux-aarch64
Latest release: 2.2.1
Downloading archive from https://github.com/wasmerio/wasmer/releases/download/2.2.1/wasmer-linux-aarch64.tar.gz
curl: (52) Empty reply from server    #     #     #                           

error: File download failed with code 000
downloading: wapm-cli-linux-aarch64
Latest release: 0.5.4
Downloading archive from https://github.com/wasmerio/wapm-cli/releases/download/v0.5.4/wapm-cli-linux-aarch64.tar.gz
######################################################################## 100.0%
error: Your platform is not yet supported (linux-aarch64).
Please open an issue on the project if you would like to use wasmer in your project: https://github.com/wasmerio/wasmer

```
architecture
```sh
root@ubuntu:~# uname -a
Linux ubuntu 5.4.0-1052-raspi #58-Ubuntu SMP PREEMPT Mon Feb 7 16:52:35 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```
I found wasmer2 Aarch64 is resupported in version 2. Why can't it be displayed in this architecture?
how to install wasmer correctly on raspberry pie (Linux aarch64)?
I will really appreciate if someone can answer my question. Thank you very much!

**Comment by epilys** [comment]
Hello, the `aarch64` build was just missing from the release process; we'll be adding it asap.

**Comment by epilys** [comment]
Hello again, an `aarch64` build has been added to the latest release, and will be part of every release onwards. Thank you for your report!
