### ISSUE TITLE
What are the limitation of wasimake versus standard make?

### ISSUE THREAD

**Issue by SugarRayLua** [wasmerio/wasmer#2888]
### Summary

Hello. I’m a novice programmer who recently has started to try using web assembly on my Mac (x64, OSX Monterey) in order to create some .wasm files that I can run on my iPad using the a-shell app which runs .wasm files. However, when I attempted to build the tcl language from source (tcl8.6.12) I could configure it with wasiconfigure fine but then then got the following error when I tried to use wasimake, I got the following fatal error:

### Additional details

“static declaration of ‘strlcpy’ follows non-static declaration
strlcpy(char *dst, const char *src, size_t, siz)

Provide any additional details here.

Yet, when compile tcl from source using standard make, a makefile is generated without any errors.

I appreciate any further information you might have as to the limitations of using wasimake versus standard make for web assembly.

Thanks!

**Comment by syrusakbary** [comment]
Thanks for opening the issue. If you could create the issue here that would be great:
https://github.com/wasienv/wasienv

**Comment by syrusakbary** [comment]
(closing it in the wasmer repo, since it's not related to the runtime)
