### ISSUE TITLE
Make Rayon optional on Cranelift compiler (like for Singlepass)

### ISSUE THREAD

**Issue by ptitSeb** [wasmerio/wasmer#2894]
Thanks for proposing a new feature!

### Motivation

The idea is to be able to build Cranelift is buildable on wasm-wasi target.

### Proposed solution

Make `rayon` optional on Cranelift compiler.

### Alternatives

Allow `rayon` to be build on `wasm-wasi` target and act as if no thread was asked on command line.

**Comment by syrusakbary** [comment]
This issue is fixed by #2898
