### ISSUE TITLE
-1 will be taken as an arguement

### ISSUE THREAD

**Issue by ERICXUCHI** [wasmerio/wasmer#2907]
### Describe the bug
when we execute `wasmer a.wasm -1` , -1 will be taken as an arguement.

<img width="510" alt="image" src="https://user-images.githubusercontent.com/57583292/171310936-e887ae98-244c-4bb4-b444-c9796c3f0e93.png">

### Steps to reproduce
just test the code in the screenshot, and the problem may reproduce.

### Expected behavior

the same as the first args.

### Actual behavior

cannot not recognize the negative number.

### Additional context

**a.wasm is compiled by emscripten with test.c**
`emcc test.c -s STANDALONE_WASM=1 -o a.wasm`

**Comment by igrep** [comment]
For a workaround, how about `wasmer -- a.wasm -1`?

**Comment by ERICXUCHI** [comment]
> For a workaround, how about `wasmer -- a.wasm -1`?

Yeah yeah, it works.

Thank you very much.
