### ISSUE TITLE
Update wit-bindgen to use the new Context API

### ISSUE THREAD

**Issue by epilys** [wasmerio/wasmer#2911]
Improve on #2892.

WIT Bindgen allows defining bindings through a DSL (WIT) into different programming languages.
Wasmer provides a way to allow the bindings to use Wasmer (Wasmer Rust, Wasmer Python, Wasmer Go, ...) under the hood.

We need to adapt https://github.com/wasmerio/wit-bindgen to use the new Context api of Wasmer and pass the tests

**Comment by syrusakbary** [comment]
This issue should be resolved in the `wasmer3`/`context_api` branch.
