### ISSUE TITLE
xxxx

### ISSUE THREAD

**Issue by epilys** [wasmerio/wasmer#2918]

**Comment by syrusakbary** [comment]
@epilys can you provide context here?

**Comment by syrusakbary** [comment]
@epilys can you provide context here?

**Comment by syrusakbary** [comment]
@Amanieu it was mentioned that this task was from the organization of previous work. Could you provide some context on what did you mean so we can take on this work and to see if it's still relevant? Thanks a lot!

**Comment by Amanieu** [comment]
The idea was to lazily initialize `VMCallerCheckedAnyfunc` in `get_vm_funcref` instead pre-building them in `build_funcrefs`. But I'm not sure the original motivation (performance) still applies since it no longer needs to lock the shared signature registry when resolving funcrefs.
