### ISSUE TITLE
Does Wasmer support interpreter mode?

### ISSUE THREAD

**Issue by Zhangyx24** [wasmerio/wasmer#2945]
Does Wasmer support interpreter mode or AoT only?

**Comment by epilys** [comment]
Thank you for your question! Unfortunately not at the moment but it's definitely in our goals. Currently we don't have the resources to support such a project but we're definitely open to the concept in the future.

**Comment by Zhangyx24** [comment]
Thanks for your answer! So wasmer currently only supports JIT and AOT?

**Comment by Zhangyx24** [comment]
@epilys Thanks for your answer! So wasmer currently only supports JIT and AOT?
