### ISSUE TITLE
Wasmer cache can throw panic if cache file has been corrupted

### ISSUE THREAD

**Issue by grishasobol** [wasmerio/wasmer#2955]
https://github.com/wasmerio/wasmer/blob/66c1c00df0704ba2ba59c250ac571586d5010c79/lib/engine-universal/src/artifact.rs#L85-L103

Hello guys, as I can see in code above, you work with `string slice` without any checks before. As a result this may cause problems  in some cases. For example: if we would corrupt file in compiled wasm cache, then this part of code may throw panic, which is not suitable behaviour. I think the best way is to return error in the case.

**Comment by epilys** [comment]
I meant a `validate: bool` argument. You might not want to revalidate an immutable bytes slice after a first validation. Would that satisfy your usecase?

**Comment by grishasobol** [comment]
> I meant a `validate: bool` argument. You might not want to revalidate an immutable bytes slice after a first validation. Would that satisfy your use case.

Yep, if you will use `validate = true` by default in wasmer functions which uses this method, or propagate validate argument up for all functions which uses this method.

**Comment by epilys** [comment]
Propagating the option makes sense to me. We're redesigning the API for the next major release, 3.0, at the moment. So we will take this into consideration, thanks for writing the ticket!

**Comment by silwol** [comment]
If we strive to follow the [API guidelines](https://rust-lang.github.io/api-guidelines/interoperability.html), I think it makes sense to rather expose a `deserialize_unchecked(…)` method that may panic, and a `deserialize(…)` method that does checking and returns a `Result<…>`. The latter may call the former of course, or both call an additional private function that has a `validate: bool` parameter - depending on what makes more sense for the implementation.

**Comment by epilys** [comment]
Actually keeping this open because it might get lost in #2925. But it depends on it.
