### ISSUE TITLE
What are the difference between Emscripten ABI and WASI?

### ISSUE THREAD

**Issue by Zhangyx24** [wasmerio/wasmer#2956]
What are the difference between Emscripten ABI and WASI?
Does wasmer support both Emscripten ABI and WASI?

**Comment by jcaesar** [comment]
WASI is [fully specified](https://github.com/WebAssembly/WASI/blob/main/phases/snapshot/docs.md) and doesn't have a main implementation. Whatever you're thinking of as "Emscripten" is the fleeting thing that is used between emscripten-compiled binaries and the JS code that is supposed to accompany them for execution on the web. It isn't standardized and changes all the time, even with compiler flags on the same version.  
WASI still lacks quite a few important features (network access, e.g.), but other than that, if you're using WASM outside of the web, it is most likely what you want.

WASI alone is definitely supported. Emscripten alone is maybe supported, but the last time I tried to compile a working binary I [had a bad time](https://github.com/wasmerio/wasmer/issues/2498#issuecomment-932257354=), and then ran into some deadlocks. I'd say it's supported, but badly.  
Having both at the same time, in the same binary, [is not supported](https://github.com/wasmerio/wasmer/issues/2308#issuecomment-842948786=). One reason you may think you have both is that more recent versions of Emscripten use part of the WASI but still mix in their own imports. (Ends up looking like [this](https://github.com/wasmerio/wasmer/issues/2589#issuecomment-931366432=).) So in fact you don't have both, you just have a newer version of Emscripten which is not supported by wasmer.

**Comment by Zhangyx24** [comment]
Thanks a lot!
