### ISSUE TITLE
panicked at 'singlepass can't emit SUB S64 GPR(X6) GPR(X6) Imm32(4)'

### ISSUE THREAD

**Issue by kvinwang** [wasmerio/wasmer#2959]
Wasmer panics while loading my module under an M1 MacBook.

```
thread '<unnamed>' panicked at 'singlepass can't emit SUB S64 GPR(X6) GPR(X6) Imm32(4)', /Users/soptq/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-2.3.0/src/emitter_arm64.rs:993:18
```

It seems like wasmer would panic if the given wasm byte codes were not well-formed or some instructions were not supported.
This should return `CompileError` rather than panic. Otherwise, the untrusted wasm code could DoS attack the host Application.

**Comment by ptitSeb** [comment]
That's a good point.
I'll add the missing emitter and will think on better error management for singlepass.

**Comment by ptitSeb** [comment]
So, wasmer should not panic anymore when something goes wrong with singlepass compiler, and also, the bug should be fixed.
Can you try again with latest master @kvinwang ?

**Comment by kvinwang** [comment]
> Can you try again with latest master @kvinwang ?

It works now. Thanks very much!
