### ISSUE TITLE
There may be a problem with the api of wasmer2.2.1

### ISSUE THREAD

**Issue by xuebingqing** [wasmerio/wasmer#2961]
## Description

We are testing the wasmer virtual machine. The current strategy is to generate random wasm files for wasmer to execute. We look for bugs by comparing the differences in the wasm execution results of wasmer.Unfortunately, we found some problems during the test. 

When using the API of wasmer2.1.1 to execute 003884.wasm first function it will time out.

But when using the API of wasmer2.2.1 to execute 003884.wasm second function it will pop up the following error:
```sh
Err(RuntimeError { source: Trap(StackOverflow), wasm_trace: [], native_trace:  })
Err(RuntimeError { source: Trap(StackOverflow), wasm_trace: [], native_trace:  })
```

Then we directly call wasmer2.2.1 through the command line, and found that the same timeout
```sh
wasmer 003884.wasm -i add0 1 1 1
```

To confirm, we use other wasm virtual machines to run 003884.wasm.The result is still timeout.
```sh
wasmtime bug/003884.wasm --invoke add0 1 1 1
```

We found that the results of running the wasm file in the wasmer2.2.1 api are different from the results of running the wasm file in other ways.

Therefore, I guess that there are some problems with the wasmer2.2.1 api, which caused the stackoverflow error to be thrown directly，instead of always timing out. Is it a bug in wasmer2.2.1 api?

## Steps to Reproduce
1. Execute 003884.wasm through the api of warmer2.1.1
```sh
wasmer2_1exec 003884.wasm
```
2. Execute 003884.wasm through the api of warmer2.2.1
```sh
wasmer2_2exec 003884.wasm
```
3. Execute wasmer2.2.1 from the command line
```sh
wasmer 003884.wasm -i add0 1 1 1
```

### Environment
- Cargo version: 1.59
- Rust version: 1.59
- Wasmer version: 2.2.1
- Operating system: Ubuntu20.04

Thank you very much for taking the time out of your busy schedule to reply.

Here is our program. 

[program.zip](https://github.com/wasmerio/wasmer/files/8940051/program.zip)
- The main.rs is the source code.

- The wasmer2_2exec compiled from main.rs which use the wasmer2.2.1 api.

- The wasmer2_1exec compiled from main.rs which use the wasmer2.1.1 api.

**Comment by syrusakbary** [comment]
Thanks for the bug report. We'll investigate!

**Comment by syrusakbary** [comment]
We checked and it's not fixed, we need to do further debug here

**Comment by ptitSeb** [comment]
I analyzed the .wasm file, and it start with this:
```wat
(module
  (type $t0 (func (param f32 i64 i32)))
  (type $t1 (func (param f32) (result i64)))
  (func $add0 (type $t0) (param $p0 f32) (param $p1 i64) (param $p2 i32)
    (local $l3 i64) (local $l4 f32)
    loop $L0 (result i32)
      local.get $p1
      f64.const -0x1.3a0e68f6d0a06p-575 (;=-9.92019e-174;)
      i32.trunc_sat_f64_u
      br $L0
```

The issue is: that `loop $L0` ... `br $L0` looks like an infinite loop to me, eventually dying with a saturated stack? I'm not sure what is the expected result here, but you do get an infinite loop... What seems to  be missing is, maybe, the growing stack. What is your thought @xuebingqing ?

**Comment by xuebingqing** [comment]
I think the expected result should be a timeout instead of stackoverflow

**Comment by ptitSeb** [comment]
Current result should be a timeout. I think the ticket can be closed.

**Comment by xuebingqing** [comment]
OK，thanks for your reply
