### ISSUE TITLE
New Swift runtime for WASM

### ISSUE THREAD

**Issue by thanhbinh01234** [wasmerio/wasmer#2964]
### Motivation

I see that there are many runtime for wasmer, but there is no updated runtime for Swift language. Is there a plan to support create a Swift extension as well?

### Alternatives

The recommend runtime lib for Swift is https://github.com/helje5/SwiftyWasmer, but it is archived and it uses deprecated C API.

**Comment by syrusakbary** [comment]
Thanks for opening the issue. We would love for the community to take on this effort, since we have no Swift experts in house for now.
For any future reader, any help there will be welcome!
