### ISSUE TITLE
Add WASI Interface to Wasmer

### ISSUE THREAD

**Issue by syrusakbary** [wasmerio/wasmer#297]
WASI is a WebAssembly System Interface.

Here's a detailed blogpost from Mozilla about it: https://hacks.mozilla.org/2019/03/standardizing-wasi-a-webassembly-system-interface/

Wasmer should support WASI, in a similar way we support emscripten.
So binaries/libraries can be executed with wasmer easily.

## Related issues

Rust is also trying to target `wasi` from rust libraries: https://github.com/rust-lang/rust/pull/59464

## Related docs

WASI API: https://github.com/CraneStation/wasmtime-wasi/blob/wasi/docs/WASI-api.md

**Comment by syrusakbary** [comment]
We just merged #299 which adds initial (and experimental) support for WASI 🎉

We will keep iterating on the WASI integration, so keeping this issue open until is feature complete

**Comment by jedisct1** [comment]
Wasmer's support for WASI is pretty decent already!

You should ask to be listed here https://wasi.dev

**Comment by syrusakbary** [comment]
Thanks for the ping!

We will need to submit PRs to the following repos:
* https://github.com/cranestation/wasi
* https://github.com/CraneStation/wasi.dev

@Hywan do you want to handle this? :)

**Comment by syrusakbary** [comment]
I've created the issue in the wasi.dev repo adding Wasmer: https://github.com/CraneStation/wasi.dev/pull/2

Closing the issue here since Wasmer WASI support is stable and mature now.

Thanks everyone for your support!
