### ISSUE TITLE
Problems using wasi

### ISSUE THREAD

**Issue by xuebingqing** [wasmerio/wasmer#2980]
## Description
We are testing the wasmer virtual machine. In the process of using the API of wasmer2.1，We may find a bug. 

Our wasm files are compiled from Rust. This wasm file uses wasi and simply outputs hello world. 

But when we call the _start function for the second time through the api of wasmer2.1.1, there is such a problem. 

```sh
Hello, world!
fatal runtime error: assertion failed: thread_info.is_none()
```

The first line is the first call to _start.
The second line is the result of the second call.

Then we test and execut many times and find that this error will always exist. Is this a bug?

## Steps to Reproduce
1. Execute hello.wasm through the api of wasmer2.1.1.
```sh
wasmer2_1exec hello.wasm
```
We execute the _start function twice in the program

## Environment
- Cargo version: 1.59
- Rust version: 1.59
- Wasmer version: 2.1

- Operating system: Ubuntu20.04

Thank you very much for taking the time out of your busy schedule to reply.

Here is our program.
[program.zip](https://github.com/wasmerio/wasmer/files/8997186/program.zip)

- The main.rs is the source code.
- The wasmer2_1exec compiled from main.rs which use the wasmer2.1.1 api.
- hello.wasm outputs hello world

**Comment by jcaesar** [comment]
I think that this is working as intended. The panic likely is inside the wasm binary itself and not wasmer. It seems that the wasm binary was compiled from Rust, and Rust's wasm runtime simply does not support the entrypoint being executed twice (and it shouldn't).
