### ISSUE TITLE
Fail to run cargo run --example compiler-llvm --release --features "llvm" in macOS and linux

### ISSUE THREAD

**Issue by Zhangyx24** [wasmerio/wasmer#2981]
### Summary

I tried to run the test /examples/compiler_llvm.rs through command `cargo run --example compiler-llvm --release --features "llvm"`，but it failed both on macOS and linux.

### Additional details
1. on macOS
rustc version is 1.59.0, cargo version is 1.59.0.
macOS version is macOS Catalina 10.15.7.

2. on linux
rustc version is 1.59.0, cargo version is 1.59.0.
linux version is Linux ubuntu 5.4.0-120-generic.

![WechatIMG1198](https://user-images.githubusercontent.com/28601300/176081104-0d26936f-52e5-49b0-8ee3-89735c22704a.jpeg)

**Comment by syrusakbary** [comment]
It seems that llvm was not automatically detected. Do you have LLVM installed in your system?

**Comment by Zhangyx24** [comment]
Yes, I installed lllvm through command "brew install llvm@12".

**Comment by epilys** [comment]
Is the `llvm-config` binary in your `PATH` environment variable? what is the output of the command:

```shell
llvm-config --prefix
```

**Comment by Zhangyx24** [comment]
Yes，but cargo run --example compiler-llvm --release --features "llvm" is not ok.
![WechatIMG1201](https://user-images.githubusercontent.com/28601300/176130206-460778d2-05e6-4a65-92e1-46b8199d96ba.jpeg)

**Comment by epilys** [comment]
try exporting the env var 

```shell
export LLVM_SYS_120_PREFIX=`llvm-config --prefix`
cargo run --example compiler-llvm --release --features "llvm"
```

and retrying. This is a problem with `llvm-sys` not detecting your installation, which is one of `wasmer`'s dependencies.

**Comment by Zhangyx24** [comment]
Thanks for your answer!
