### ISSUE TITLE
Limit number of stacks in the stack pool

### ISSUE THREAD

**Issue by kaimast** [wasmerio/wasmer#3002]
This is more of a suggestion than a feature request. When looking at the codebase, it seems to me that  a new stack is allocated whenever non is available right now. 
Stacks are never cleaned up though, they will always be pushed back into the stack pool.

See [here](https://github.com/wasmerio/wasmer/blob/14d8084c29f6c47e76a16fdee2083aa997d34482/lib/vm/src/trap/traphandlers.rs#L865).

This might not be problem in most cases but could potentially be an issue for applications that are very bursty. 
Additionally, when async support is eventually added, it is possible to have a large number of wasm functions yielded at the same time, each requiring their own stack.

A good solution imho would be to have the option to specify the maximum size of the stack pool or set it to some reasonable number (maybe a multiple of the number of CPU cores?).

A somewhat related question: it also seems that stacks are shared between instances and not cleaned up. Could that potentially leak information?

**Comment by syrusakbary** [comment]
Thanks for creating this issue @kaimast , once we start adding support for async calls in the runtime, we'll follow up with more discussion
