### ISSUE TITLE
How to specify AOT mode or JIT mode in Rust api?

### ISSUE THREAD

**Issue by Zhangyx24** [wasmerio/wasmer#3014]
### Summary

When using rust api to execute wasm in Rust, how to specify the mode is AOT or JIT?

### Additional details

Here is the Rust program:
use wasmer_compiler_singlepass::Singlepass;
use wasmer_engine_universal::Universal;

use std::fs::File;
use std::io::Read;

fn main() -> anyhow::Result<()> {

    let mut f = File::open("test.wat").unwrap();
    let mut buf = Vec::new();
    f.read_to_end(&mut buf).unwrap();
    let wasm_bytes = wat2wasm(buf.as_slice()).unwrap();

    let store = Store::new(&Universal::new(Singlepass::default()).engine());

    println!("Compiling module...");
    let module = Module::new(&store, wasm_bytes)?;

    println!("Instantiating module imports...");
    let import_object = {};
    let instance = Instance::new(&module, &import_object)?;

    println!("Call `func1` function...");
    let func1 = instance.exports.get_function("func1")?;
    func1.call(&[])?;

    println!("Call `func2` function...");
    let func2 = instance.exports.get_function("func2")?;
    func2.call(&[])?;

    Ok(())
}
#[test]
fn test() -> anyhow::Result<()> {
    main()
}

**Comment by jcaesar** [comment]
Wasmer only supports AOT compilation.

**Comment by Zhangyx24** [comment]
Do you mean that executing WASM using rust API only supports AOT mode?

**Comment by jcaesar** [comment]
I'm beginning to feel unsure that we're using the same terminology.

With Wasmer (no matter whether from Rust or elsewhere), you must compile the entire WASM module before you can run any of its functions. No further compilation or optimization is done once the first compilation is finished. That's AOT as far as I'm concerned.

You can do this compilation immediately before executing, or you can do the compilation, serialize the result, and de-serialize it later in a different process or on a different machine.

**Comment by Zhangyx24** [comment]
Through command line , we can use AOT through `wasmer compiler xxx.wasm -o xxx.wasmu` and `wasmer xxx.wasmu`.
And we can directly using JIT through `wasmer xxx.wasm`.
Can we say that there is no big difference between AOT and JIT in high-level language api to execute wasm ?

**Comment by jcaesar** [comment]
I have no confidence I can explain this to you in natural language. Probably best if you just had a look at the code for the wasmer command line.
* [`wasmer compile`](https://github.com/wasmerio/wasmer/blob/7bf5d9d1e329582d55705cc3bba1e5d3e0526150/lib/cli/src/commands/compile.rs#L74-L75)
* [`wasmer run foo.wasmu`](https://github.com/wasmerio/wasmer/blob/7bf5d9d1e329582d55705cc3bba1e5d3e0526150/lib/cli/src/commands/run.rs#L226-L231)
* [`wasmer run foo.wasm`](https://github.com/wasmerio/wasmer/blob/7bf5d9d1e329582d55705cc3bba1e5d3e0526150/lib/cli/src/commands/run.rs#L240). (I guess this is what you call JIT? The [typical definition of JIT](https://en.wikipedia.org/wiki/Just-in-time_compilation) is somewhat different though.)

The wasmer command doesn't use any private API or anything, you can do all the things it can do through the Rust API as well.

**Comment by Zhangyx24** [comment]
Thanks for your answer.

**Comment by hungryzzz** [comment]
> I have no confidence I can explain this to you in natural language. Probably best if you just had a look at the code for the wasmer command:
> 
> * [`wasmer compile`](https://github.com/wasmerio/wasmer/blob/7bf5d9d1e329582d55705cc3bba1e5d3e0526150/lib/cli/src/commands/compile.rs#L74-L75)
> * [`wasmer run foo.wasmu`](https://github.com/wasmerio/wasmer/blob/7bf5d9d1e329582d55705cc3bba1e5d3e0526150/lib/cli/src/commands/run.rs#L226-L231)
> * [`wasmer run foo.wasm`](https://github.com/wasmerio/wasmer/blob/7bf5d9d1e329582d55705cc3bba1e5d3e0526150/lib/cli/src/commands/run.rs#L240). (I guess this is what you call JIT? The [typical definition of JIT](https://en.wikipedia.org/wiki/Just-in-time_compilation) is somewhat different though.)
> 
> The wasmer command doesn't use any private API or anything, you can do all the things it can do through the Rust API as well.

Hi, does the `.wasmu` file contain a set of low-level bytecode instructions generated by wamser? And how does wamser execute the `.wasmu` file? Just to interprete the bytecode intruction one by one?

**Comment by ptitSeb** [comment]
Wasmer ise AOT all the time. There is no JIT.
You can use pre-compiled binary with the `.wasmu` or use the bytecode wenassembly .wasm, that will be compile before running (or use a cached version if you run it a second time).

**Comment by hungryzzz** [comment]
Thank you for your answer, so `.wasmu`  contains the compiled machine instructions which can run directly on CPU?

**Comment by ptitSeb** [comment]
yes, `.wasmu` contains the compiled code, but you cannot run it directly. You still need the wasmer runtime (all the WASI syscall for example) and do the linking process to actually run it.

**Comment by hungryzzz** [comment]
Okay, I got it! Thank you very much!

**Comment by ptitSeb** [comment]
Note that if you want directly executable stuff, you can use the `create-exe` command with wasmer, that will take the precompile `.wasmu` and link it with the runtime and the needed glue to give a autonomous executable file that can be run directly.
