### ISSUE TITLE
Does singlepass compiler support simd instructions?

### ISSUE THREAD

**Issue by Zhangyx24** [wasmerio/wasmer#3015]
Does singlepass compiler support simd instructions?

For example :
`(module
  (func (result v128)
    v128.const i32x4 0x00000000 0x00000000 0x00000000 0x00000007
    v128.const i32x4 0x00000000 0x00000000 0x00000000 0x00000009
    i32.const 0
    select)
  (export "func1" (func 0)))`

**Comment by ptitSeb** [comment]
No, it doesn't for now.

**Comment by Zhangyx24** [comment]
Thanks for your answer !
