### ISSUE TITLE
Error executing wasm with simd instructions ?

### ISSUE THREAD

**Issue by Zhangyx24** [wasmerio/wasmer#3016]
### Describe the bug

I tried to execute a wasm program with all the 3 compilers, however singlepass failed and the other two compilers got the wrong answer.
Both macOS and linux got the same result.
My wasmer version is 2.3.0.
MacOS is 10.15.7, linux is ubuntu 20.04.

![WechatIMG1233](https://user-images.githubusercontent.com/28601300/178099409-13864668-e8f2-41b0-a5c3-abfc73bc8738.jpeg)

```sh
wasmer test.wat -i func1 --llvm
wasmer test.wat -i func1 --cranelift
wasmer test.wat -i func1 --singlepass
```

### Expected behavior
The wat file is :
`(module
  (func (result v128)
    v128.const i32x4 0x00000000 0x00000000 0x00000000 0x00000007
    v128.const i32x4 0x00000000 0x00000000 0x00000000 0x00000009
    i32.const 0
    select)
  (export "func1" (func 0)))` 
<img width="637" alt="截屏2022-07-09 下午5 09 51" src="https://user-images.githubusercontent.com/28601300/178099473-d299e6da-e7fc-4dab-93f7-23819fea196b.png">

And the answer is expected to be 9.

**Comment by syrusakbary** [comment]
SIMD is not yet supported in singlepass, so that's why it's failing there.

What's the expected result that LLVM and Cranelift should output?

**Comment by Zhangyx24** [comment]
I think the expected output is 9.

**Comment by jcaesar** [comment]
Are you sure you sure the expected output isn't `0x9_00000000_00000000_00000000`? Because that's the current output, and it does make sense. (And wasmtime also outputs that.)

**Comment by Zhangyx24** [comment]
Yes, you are right. Probably, I misunderstood. Thanks for your answer!

**Comment by jcaesar** [comment]
(I tried reproducing this in JS just to be sure, but node doesn't seem to support v128, and FF does this:
```
WebAssembly.instantiate(Uint8Array.from(atob(
"AGFzbQEAAAABBQFgAAF7AwIBAAcJAQVmdW5jMQAACisBKQD9DAEAAAACAAAAAwAAAAcAAAD9DAQAAAAFAAAABgAAAAkAAABBABsL"
), c => c.charCodeAt(0)), {})
.then(w => console.log(w.instance.exports.func1()))
```
```
Uncaught (in promise) TypeError: cannot pass v128 to or from JS
```
)
