### ISSUE TITLE
Example for 'exports-memory' does not seem to work?

### ISSUE THREAD

**Issue by kmott** [wasmerio/wasmer#3036]
### Summary

Hello, I am working through the examples, and I noticed `exports-memory` does not seem to work if I create it as a standalone project.

```
  |
1 | use wasmer::{imports, wat2wasm, Instance, Module, Store, TypedFunction, WasmPtr};
  |                                                          ^^^^^^^^^^^^^ no `TypedFunction` in the root
```

If I check out the main `wasmer` repo and run the example with `cargo run --example exported-memory --release --features "cranelift"` it works just fine.

I wonder if when the `NativeFunc` -> `TypedFunction` [rename](https://github.com/wasmerio/wasmer/pull/2939) occurred, the examples got updated as well, but the 2.3.0 version of wasmer does not support the new `TypedFunction` yet (I think this may occur with a few other examples as well)?

### Repro & Logs

- Gist that contains a repro of the issue and logs from `cargo run`: https://gist.github.com/kmott/52eb2e3ba13431d8737e604f13d8fee0

**Comment by jcaesar** [comment]
> I wonder if when the NativeFunc -> TypedFunction https://github.com/wasmerio/wasmer/pull/2939 occurred, the examples got updated as well, but the 2.3.0 version of wasmer does not support the new TypedFunction yet (I think this may occur with a few other examples as well)?

Looking at the [list of changed files](https://github.com/wasmerio/wasmer/commit/a419ccdf52f1d259e4bd8db59f64bf61ad6bbacd#diff-6cbb9a50292e5a0e99eb51cecce2316142a6995162440f9bed51d993a8cbf855), I'd say it happened to nearly all the examples.

But is this a problem? Couldn't you just grab the example for wasmer 2.3.0?
https://github.com/wasmerio/wasmer/blob/2.3.0/examples/exports_memory.rs

**Comment by syrusakbary** [comment]
Thanks for repoting the issue. The current examples have changed from the 2.3.0 API so that's why you are encountering the issue.

If you use the file from the `2.3.0` tag things should work properly. Sorry for the confussion, as soon as we release the Wasmer 3.0 beta it should be solved.

Closing the issue
