### ISSUE TITLE
Add support for Zig cc when compiling with `create-exe`

### ISSUE THREAD

**Issue by syrusakbary** [wasmerio/wasmer#3042]
We should add support for `zig cc` when compiling (if zig is available) instead of using clang, as it's better for cross-compilation.

**Comment by jcaesar** [comment]
Are you going to compile zig to wasm for this?

**Comment by syrusakbary** [comment]
@jcaesar we wanted to use Zig compiled to wasm for this, but it seems for that Zig needs to have full support on the self-hosted version for the different chipset backends.

They only have behavioral tests passing when using LLVM, which is not available yet when compiling Zig to Wasm. So we need for Zig to have better support on the x86, arm backends
