### ISSUE TITLE
Add support for filesystem in the Wasmer C API

### ISSUE THREAD

**Issue by syrusakbary** [wasmerio/wasmer#3043]
Right now, `create-exe` works great when compiling an standalone wasm file to an executable.
The python package consists of:
* `python.wasm` (the Python wasm module)
* Filesystem (the `lib/asyncio.py`, `lib/...`, ...).

However, when doing it with wapm packages such as Python (which had a filesystem), we also need to embed the filesystem (as binary) in the compiled executable, so we can cross-compile the wapm python package to a self-working `python.exe` (just one file) that has the wasm file contents compiled statically, and also the filesystem binary contents.

**Comment by syrusakbary** [comment]
Outcome:

Wasmer should support creating executables from pirita files (that are self-contained)

```
wasmer create-exe python.pirita
```

**Comment by syrusakbary** [comment]
State of the art:
* https://github.com/facebookincubator/xar

**Comment by fschutt** [comment]
Technically this can be closed now, we shipped this as part of the pirita changes in `wasmer-private/create-obj-pirita` in the `wasmer.h`.
