### ISSUE TITLE
`wasmer create-exe` failed becauase "wasmer.h" not found

### ISSUE THREAD

**Issue by NobodyXu** [wasmerio/wasmer#3053]
### Describe the bug

I installed `wasmer` using:

```sh
cargo install wasmer-cli --features singlepass,cranelift,llvm
```

And then `wasmer create-exe` failed.

### Steps to reproduce

For example,
1. `cargo install wasmer-cli --features singlepass,cranelift,llvm`
2. `cargo new hello-world`
3. `rustup target install wasm32-wasi`
4. `cd hello-world && cargo build --release --target wasm32-wasi`
5. `wasmer create-exe hello-world/target/wasm32-wasi/release/hello-world.wasm -o hello-world`

### Actual behavior

```
error: Failed to compile C source code
╰─▶ 1: C code compile failed with: stdout: 
       
       stderr: wasmer_main.c:1:10: fatal error: wasmer.h: No such file or directory
           1 | #include "wasmer.h"
             |          ^~~~~~~~~~
       compilation terminated.
       
```

## System information

```
wasmer 2.3.0
```

```
Linux 5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by epilys** [comment]
I don't know if/where it exists in the documentation, but environment variable `WASMER_DIR` must point to your `wasmer` installation. Since you installed it with cargo, it's not going to be there. You can download the tarball from the releases and take the files from there and put it in any directory (for example `/home/user/.local/share/wasmer/`) then `export WASMER_DIR=/home/user/.local/share/wasmer/`

**Comment by epilys** [comment]
`create-exe` should show an error if `WASMER_DIR` is not set correctly.

**Comment by NobodyXu** [comment]
> I don't know if/where it exists in the documentation, but environment variable `WASMER_DIR` must point to your `wasmer` installation. Since you installed it with cargo, it's not going to be there. You can download the tarball from the releases and take the files from there and put it in any directory (for example `/home/user/.local/share/wasmer/`) then `export WASMER_DIR=/home/user/.local/share/wasmer/`

Can we have that documented in `wasm create-exe --help`?

Also, does that mean we need to have a c compiler, linker and `ar`?

**Comment by epilys** [comment]
I think you need a `cc` (clang or gcc) and `ld`, yeah. We're working on a new create-exe interface for 3.0.0 which will have all these things sorted out and documented!

**Comment by NobodyXu** [comment]
Thanks!

I'm looking forward to the 3.0.0 release!

**Comment by NobodyXu** [comment]
I just saw the [new blog post](https://wasmer.io/posts/wasm-as-universal-binary-format-part-1-native-executables) and it's good to see wasmer moving forward.

Though after checking the doc again, I still was not able to find the documentation for exactly what is needed for `wasmer create-exe`.

@epilys Is it feasible to improve a new API like `wasmer create-exe --self-test` that returns `0` if the env required for `create-exe` is set-up and ready-to-go, otherwise return a non-zero code?

I was thinking about fetching wasi and compile it to native executable in `cargo-binstall` https://github.com/cargo-bins/cargo-binstall/issues/246 but I need some way to reliable determine if `wasmer create-exe` would work or not.

Using `wasmer create-exe` to compile a sample hello-world program would definitely work, but I afraid that would waste a lot of resource for nothing and it is better for `wasmer` itself to support for a efficient `--self-test` so that `cargo-binstall` and other tools can reliably use it to determine if that `create-exe` is usable.

If `--self-test` is possible, I'd also like a `--quiet` flag to disable stderr/stdout.

**Comment by epilys** [comment]
@NobodyXu hello, thanks for the update!

In the beta, we added some documentation on the `wasmer create-exe --help` output:

```shell
% ./package/bin/wasmer create-exe --help
wasmer-create-exe    
Compile a WebAssembly binary into a native executable
                                         
To use, you need to set the `WASMER_DIR` environment variable
to the location of your Wasmer installation. This will probably be `~/.wasmer`. It
should include a `lib`, `include` and `bin` subdirectories. To create an executable 
you will need `libwasmer`, so by setting `WASMER_DIR` the CLI knows where to look for
header files and libraries.                                                        
                                         
Example usage:
                                                                                   
                
$ # in two lines:        
$ export WASMER_DIR=/home/user/.wasmer/
$ wasmer create-exe qjs.wasm -o qjs.exe # or in one line:
$ WASMER_DIR=/home/user/.wasmer/ wasmer create-exe qjs.wasm -o qjs.exe
$ file qjs.exe
qjs.exe: ELF 64-bit LSB pie executable, x86-64 ...
```

A `--self-test` flag sounds incredibly useful since there are lots of possibilities in how this can go wrong. You can make a new feature request issue or we will do it ourselves.

**Comment by NobodyXu** [comment]
@epilys I've submit a new feature request #3092.
