### ISSUE TITLE
How to import both wasi and host functions in rust api ?

### ISSUE THREAD

**Issue by Zhangyx24** [wasmerio/wasmer#3080]
### Summary
[test-wat.txt](https://github.com/wasmerio/wasmer/files/9276834/test-wat.txt)
How to import both WASI and host function `foo` ?
Now I get the code, but is wrong:
[test-rs.txt](https://github.com/wasmerio/wasmer/files/9276836/test-rs.txt)

wasmer 2.3.0

**Comment by jcaesar** [comment]
You can combine two import objects with the [`chain_back`](https://docs.rs/wasmer/latest/wasmer/trait.ChainableNamedResolver.html#provided-methods) method.

Should look something like this:
```rusted
use wasmer::ChainableNamedResolver;
let import_object = imports! {
    "foo" => {
        "foo" => Function::new_native(&store, foo_host),
    },
}.chain_back(wasi_env.import_object(&module));
let instance = Instance::new(&module, &import_object)?;
```

**Comment by syrusakbary** [comment]
Small update: we removed the `chain_back` method. Now you can use `imports1.extend(imports2)`

**Comment by Zhangyx24** [comment]
Do you mean :

    let import_object = imports! {
    "foo" => {
        "foo" => Function::new_native(&store, foo_host),
    },
    }.extend(wasi_env.import_object(&module));

**Comment by epilys** [comment]
@Zhangyx24 yes but with an important difference, the [std::iter::Extend](https://doc.rust-lang.org/std/iter/trait.Extend.html) trait takes a `&mut self` as argument, so the code should be:

```rust
let mut imports: Imports = imports! {
  "foo" => {
      "foo" => Function::new_typed(&mut store, foo_host),
  }
};

imports.extend(/* import iterator here */);
```

There's an example in the [migration document to version 3.0.0 here](https://github.com/wasmerio/wasmer/blob/a6ddf4e23ddbba827673e4068e8ae1b2fed4609e/docs/migration_to_3.0.0.md#chainablenamedresolver-is-removed).

**Comment by Zhangyx24** [comment]
Is this available in wasmer2.3.0 ?

**Comment by syrusakbary** [comment]
You can use the `chain_back` API as @jcaesar commented if you want to use it in Wasmer 2.3.0:

https://docs.rs/wasmer/2.3.0/wasmer/trait.ChainableNamedResolver.html#provided-methods

Closing the issue!

**Comment by Zhangyx24** [comment]
Thanks a lot !
