### ISSUE TITLE
__WASI_ENOENT when renaming a file

### ISSUE THREAD

**Issue by dicej** [wasmerio/wasmer#3084]
### Describe the bug

While working on https://github.com/konsoletyper/teavm/pull/610, I noticed that renaming a file in a preopened directory doesn't seem to work in Wasmer.  I originally noticed this when testing a Java program, but was able to reproduce it in Rust.

```sh
echo "`wasmer -V` | `rustc -V` | `uname -m`"
```
Wasmer complains that it doesn't understand the `-V` flag, but I'm using wasmer-cli built from commit 22c37368e714d4bc7f76c369b58eac6a50d32276, which was master as of yesterday.

```
 | rustc 1.62.0 (a8314ef7d 2022-06-27) | x86_64
```

### Steps to reproduce

1. Build the following Rust program using `cargo build --target wasm32-wasi`:
```rust
fn main() -> Result<(), Box<dyn std::error::Error>> {
    std::fs::rename("foo/bar.txt", "foo/um.txt")?;
    Ok(())
}
```
2. Create the directory and add the file to it:
```
mkdir foo
touch foo/bar.txt
```
3. Run the program:
```
wasmer --dir foo target/wasm32-wasi/debug/wasi-file-test.wasm
```

### Expected behavior

The `foo/bar.txt` file would be renamed to `foo/um.txt`.  This is the behavior when running the module using Wasmtime.

### Actual behavior

`Error: Os { code: 44, kind: NotFound, message: "No such file or directory" }`

**Comment by ptitSeb** [comment]
I reproduce the issue with current master. I'll check what's going on.
