### ISSUE TITLE
wit-bindgen fork doesn't work with master branch

### ISSUE THREAD

**Issue by canewsin** [wasmerio/wasmer#3091]
I was using wit-bindgen fork to gen wasmer bindings with *.wit files

https://github.com/wasmerio/wit-bindgen.git

Fork is gen older code which is incompatible with latest beta 3.0.0 beta as well as master

**Comment by syrusakbary** [comment]
Hey @canewsin, please use the `wasmer` branch, as it's up to date with `3.0.0-beta`

https://github.com/wasmerio/wit-bindgen/tree/wasmer/

**Comment by canewsin** [comment]
I was using wasmer branch indeed

**Comment by canewsin** [comment]
@syrusakbary 
replace these lines While gen import bindings
```rust
let slice = unsafe {
    memory
        .data_unchecked(store)
        .get(base as usize..)
        .and_then(|s| s.get(..size as usize))
        .ok_or_else(|| RuntimeError::new("out of bounds read"))?
};
```

with
```rust
let slice = {
    let mut buf = vec![];
    memory.view(&store).read(base as u64, &mut buf)?;
    buf.resize(size as usize, 0);
    buf
};
```

But while importing macro gen previous api

**Comment by canewsin** [comment]
@syrusakbary https://github.com/wasmerio/wit-bindgen/pull/6
Successfully tested and can confirm Issue resolved with this PR, You can close this issue PR merge.
