### ISSUE TITLE
Shipped wasmer-headless binary doesn't seem to work

### ISSUE THREAD

**Issue by epilys** [wasmerio/wasmer#3121]
This is supposed to be the correct workflow for using wasmer-headless, correct? Compile with regular `wasmer` binary, and then you can run it with `wasmer-headless`.

```shell
manos ~ % ~/Desktop/wasmer/bin/wasmer compile qjs.wasm -o compiled.wasmu
Compiler: cranelift
Target: aarch64-apple-darwin
✔ File compiled successfully to `compiled.wasmu`.
manos ~ % ~/Desktop/wasmer/bin/wasmer-headless run compiled.wasmu       
zsh: floating point exception  ~/Desktop/wasmer/bin/wasmer-headless run compiled.wasmu
manos ~ % ~/Desktop/wasmer/bin/wasmer-headless run compiled.wasmu
zsh: segmentation fault  ~/Desktop/wasmer/bin/wasmer-headless run compiled.wasmu
```

_Originally posted by @epilys in https://github.com/wasmerio/wasmer/issues/3086#issuecomment-1220516798_

**Comment by syrusakbary** [comment]
Confirming that the bash code posted should work

**Comment by epilys** [comment]
I can't reproduce this in `master` after initially getting these failures. Cosmic rays? In either case unless someone else reproduced this I'm closing it as not a bug.
