### ISSUE TITLE
Help with trampoline instructions (adding BPF llvm target)

### ISSUE THREAD

**Issue by coffeemug** [wasmerio/wasmer#3143]
I'm experimenting with patching Wasmer llvm compiler to support the BPF target. This is useful because Solana runtime expects contracts compiled to BPF, and getting this target working in Wasmer would open up the possibility to write contracts in AssemblyScript. To do this I'm trying to understand the trampoline code: https://github.com/wasmerio/wasmer/blob/43b6e0c26226ef5f89ba37f4e895ee2edd1f420c/lib/compiler/src/artifact_builders/trampoline.rs#L12

It looks like on ARM the trampoline instructions simply jump 8 bytes ahead, and on X86 they jump 2 bytes ahead. On both targets this is followed by eight zeroed bytes:

```
// ARM: jump to program counter + 8 bytes followed by 8 zeroed bytes?
LDR x17, [PC, #8]
BR x17
JMPADDR            00 00 00 00 00 00 00 00

// X86: jump to program counter + 2 bytes followed by 8 zeroed bytes?
JMP [RIP + 2]   FF 25 02 00 00 00 [00 00]
64-bit ADDR     00 00 00 00 00 00 00 00
```

Am I parsing this correctly? (my assembly is very rusty). Why jump 8 bytes forward on ARM and 2 bytes forward on X86? And why have a padding of eight zeroed bytes after? Wouldn't the code be jumping into the zero buffer?

A different way to phrase this question: how would you recommend going about getting trampolines working on the BPF target?

**Comment by coffeemug** [comment]
Ah, I haven't touched assembly in ages and misread everything, these are indirect jumps 🤦 I'll look into decoding this after a good night's sleep, but would still appreciate an explanation.

**Comment by ptitSeb** [comment]
it's a direct jump, but the 64bits ADDR is initially 0 here and then changed with a relocation to the actual jump address.

**Comment by syrusakbary** [comment]
@coffeemug do you need some extra information from our side apart from what was provided?
We are not experts on the BPF target so it will be a bit tricky to get a full response from us there

**Comment by coffeemug** [comment]
Thanks, I'm good now (I temporarily switched to wasm2c and ported that). Going to close, feel free to reopen if it makes sense 🙏
