### ISSUE TITLE
c-api: is there a way to get function by name from wasm module

### ISSUE THREAD

**Issue by lykhouzov** [wasmerio/wasmer#3147]
### Summary

I was searching in examples but haven't found the answer, nor in API
I see it exists in rust API, but I need it in C++ project, so I have to use C-API.

examples of c-api shows only how to get a func from exports, but in the example
1. it expects a func to be xported fiest, so if I do a wasm module with rust compiled in wasm - it does not work
2. even if I do for loop and check a type of export and see a func, how can I separate them if I do not know their names?

**Comment by syrusakbary** [comment]
You are right, we need to add a new function in the C-API that is able to get the function name given a function index (it should get it from the function names section in the Wasm module, present mainly when compiling Wasm in debug mode)
