### ISSUE TITLE
Create Wasmer getting started doc

### ISSUE THREAD

**Issue by syrusakbary** [wasmerio/wasmer#3149]
Currently Wasmer has the docs: https://docs.wasmer.io/ecosystem/wasmer

We need to revisit those and revamp it to make it easy to use

**Comment by fschutt** [comment]
Basically we don't need to "fix" anything, we just need to make the menu structure more accessible.

**Comment by fschutt** [comment]
Discussion moved to PR https://github.com/wasmerio/docs.wasmer.io/pull/154
