### ISSUE TITLE
Standardize js and sys tests

### ISSUE THREAD

**Issue by syrusakbary** [wasmerio/wasmer#3152]
In the Wasmer API, we have two kind of tests: `js` and `sys` ones depending on the feature used.

However, both are testing the Wasmer API (which should be resilient across the js or sys feature).
In general, we should unify the `crates/api/tests` for both js and sys (and using the `test` or `wasm_bindgen` macro depending on the target/feature).
That way we test our that our public API is resilient

**Comment by fschutt** [comment]
Ideally this should be done after https://github.com/wasmerio/wasmer/pull/3129 is merged, but I can start working on it

**Comment by syrusakbary** [comment]
Closing
