### ISSUE TITLE
Weird behavior for atomic load

### ISSUE THREAD

**Issue by zzjas** [wasmerio/wasmer#3167]
### Describe the bug

`i32.atomic.load` won't give a runtime error for out-of-bounds access.

### Steps to reproduce

```
(module
    (memory 1)
    (func (export "_start")
        i32.const 0xffff_fff0
        i32.atomic.load offset=16
        drop
    )
)
```
Run with `wasmer --enable-all atomic.wat`

### Expected behavior

We think this should be a runtime OOB error but wasmer will return normally.

If the `0xffff_fff0` is changed to `0xfff0`, wasmer will then give OOB error. Or if the `i32.atomic.load` is changed to `i32.load`, wasmer will also give the error.

Please excuse us if this behavior is intended. Also, the test is collected from https://github.com/bytecodealliance/wasmtime/issues/3132 in case the discussion there might be useful.

Thanks.

**Comment by zzjas** [comment]
Sorry forgot to add this. It was tested using
wasmer version: 2.3.0
OS: macOS 12.5.1 (M1 Chip)

**Comment by ptitSeb** [comment]
What compiler are you using? Cranelift (the default one) or Singlepass?

**Comment by zzjas** [comment]
Cranelift

**Comment by ptitSeb** [comment]
Ok, thanks. I'll have a look at it. It seems there is the same "warp around" issue as with wasmtime.

**Comment by ptitSeb** [comment]
Merged
