### ISSUE TITLE
Has anyone tried compiling the Wasmer Rust library itself to WebAssembly?

### ISSUE THREAD

**Issue by danaugrs** [wasmerio/wasmer#3169]
Has anyone tried compiling the Wasmer Rust library itself to WebAssembly?

**Comment by ptitSeb** [comment]
The Compiler can be build as WebAssembly yes. But the runtime cannot.

**Comment by danaugrs** [comment]
Cool! Why not the runtime?

**Comment by ptitSeb** [comment]
The runtime use stuff not easily run in wasm, like Signals, MMAP, and creating executable code in memory. Wasm inside Wasm would be more suitable with an interpretor.

**Comment by danaugrs** [comment]
Thanks!
