### ISSUE TITLE
Comparison to Lucet

### ISSUE THREAD

**Issue by nhynes** [wasmerio/wasmer#317]
There are too many Wasm JITs that seek to provide the same high-level goal! The newest entrant into the foray is [Lucet](https://github.com/fastly/lucet). How would you say that Lucet compares to Wasmer?

Especially with the addition of the dynasm backend to Wasmer and the future addition of Wasi, it looks like this project strives to do everything.

**Comment by nhynes** [comment]
Found a HN post that offers a comparison: https://news.ycombinator.com/item?id=19515806

**Comment by lachlansneff** [comment]
That comment covers things pretty well. Wasmer aims, as part of its vision, to be a general-purpose webassembly runtime. Currently, we have three backends and are working on tiering runtime as well that combines the fast startup time of the dynasm backend with the high-performance of the llvm backend.

**Comment by luover** [comment]
Does wasmer support(or will) AOT ?

**Comment by zmlzm** [comment]
Does wasmer support(or will) support AOT ?

**Comment by Hywan** [comment]
Yes. With module caching, it compiles the module to executable code, and save it into a file. See `wasmer cache …`.

**Comment by syrusakbary** [comment]
Closing the issue as it seems is clear :)

**Comment by ydmitry** [comment]
What about isolation / sandboxing / security ? Does wasmer OK to run untrusted code?
