### ISSUE TITLE
Docs say Wasmer supports threads but no(?) docs mention how to enable it

### ISSUE THREAD

**Issue by sgbeal** [wasmerio/wasmer#3172]
### Summary

[The Wasmer feature docs](https://docs.wasmer.io/ecosystem/wasmer/wasmer-features) say that the wasm threading proposal is implemented, but trying to run any wasm built with threads/-lpthread results in:

```
Validation error: threads support is not enabled (at offset 131312)
```

Scouring the docs reveals no mention of _how_ to enable the threads support.

How do we enable threads support with wasmer?

It's certainly possible that i'm misunderstanding the scope of the threading support and am climbing down the wrong rabbit hole here. (My goal is to run an emscripten-compiled wasm file which uses pthreads from the CLI.)

**Comment by ptitSeb** [comment]
you need to use `--enable-threads` or `--enable-all` in the `wasmer run` command line.

Note that thread support will be improve in future version 3.1. You can check a WIP of this there: https://github.com/wasmerio/wasmer/pull/3153

**Comment by sgbeal** [comment]
Thank you, @ptitSeb, that got me past that hurdle and leveled up my wasmer use. IMO it warrants a mention in the docs. Perhaps under the feature chart linked above, even if it's just something like "see `wasmer help run` for the flags needed to enable various features."

**Comment by ptitSeb** [comment]
Threads are enabled by default now, closing this ticket.
