### ISSUE TITLE
Easier insertion / extraction API for Python / JS with wit-bindgen

### ISSUE THREAD

**Issue by fschutt** [wasmerio/wasmer#3173]
In a lot of embedding cases (where I want to let wasmer run some code in a sandbox), I need to insert custom Rust types into JS / Python, then extract them back to Rust again after the script has finished / returned, so that I can use Wasmer as a drop-in replacement for PyO3. I.e.:

```rust
let module = Module::new("python.wasm");
let instance = module.instance();
instance.add_python_class::<MyClass>()?; // python code can use MyClass functions
instance.run("_start");
let result = instance.extract::<MyResult>()?;
println!("python returned: {:?}", result);
```

**Comment by syrusakbary** [comment]
We need to think a bit further on perhaps how to do this with wit-bindgen
