### ISSUE TITLE
There is error when I am tryin to run converted raylib game from wasm to apple M1  

### ISSUE THREAD

**Issue by lvdpower** [wasmerio/wasmer#3180]
### Describe the bug
There is error when I am tryin to run converted raylib game from wasm to apple M1  
(I have compiled to webassembly this game and it run via browser good)

https://github.com/zf3/raylib-games-wasm/blob/main/README.md

But I am trying to convert it to native and I have this error.

timur@Mac-mini-timur arkanoid % ./wasmer create-exe arkanoid.wasm -o ./program                                                  
Compiler: cranelift
Target: aarch64-apple-darwin
Format: Symbols
Using libwasmer file: /Users/timur/.wasmer/lib/libwasmer.a
Using path `/Users/timur/.wasmer/lib/libwasmer.a` as libwasmer path.
✔ Native executable compiled successfully to `./program`.

timur@Mac-mini-timur arkanoid % ./program
Error getting WASI imports!
Error len: `44`
Failed to resolve import "env" "glViewport"

```sh
echo "`wasmer -V` | `rustc -V` | `uname -m`"
```

**Comment by syrusakbary** [comment]
`wasmer create-exe` only works with Wasm WASI executables, we need to improve the error when compiling so `create-exe` fails with an error early on (it seems the Wasm file was generated with emscripten)
