### ISSUE TITLE
Double open the same file, close one fd, weird offset issue

### ISSUE THREAD

**Issue by zzjas** [wasmerio/wasmer#3188]
This is in `double_open.c`
```
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>

int main() {
  int fd0 = open("hello.txt", O_RDWR);
  int fd1 = open("hello.txt", O_RDWR);

  char buf1[5];
  read(fd1, buf1, 4);
  buf1[4] = '\0';
  printf("read from fd1: %s\n", buf1);

  close(fd0);

  read(fd1, buf1, 4);
  buf1[4] = '\0';
  printf("read from fd1: %s\n", buf1);
}
```

This is in `hello.txt`
```
123456789ABCDEFG
```

### Steps to reproduce
Using
wasmer 2.3.0 (wasmer-darwin-arm64)
wasi-sdk-16.0
macOS 12.5.1 (M1)

```
./wasi-sdk-16.0/bin/clang --sysroot=./wasi-sdk-16.0/share/wasi-sysroot double_open_read.c -o double_open_read.wasm
wasmer --dir=. double_open_read.wasm
```

### Expected behavior
```
read from fd1: 1234
read from fd1: 5678
```

### Actual behavior
```
read from fd1: 1234
read from fd1: 1234
```

### Additional context
If we change `read` to `write`, we would expect the two writes to be both successful but the second one will return -1 instead.

**Comment by syrusakbary** [comment]
Indeed. This seems like a bug! Thanks for reporting the issue

**Comment by zzjas** [comment]
Hi, we realized that this is actually not an offset issue. The `read(fd1, ...)` will simply fail and return -1 after `close(fd0)`.
