### ISSUE TITLE
wasmer --version does not work when trying from releases.

### ISSUE THREAD

**Issue by iulian-birlica** [wasmerio/wasmer#3195]
### Describe the bug

`wasmer --version` (or `wasmer -V`) do not work when invoked using the releases binaries, but it works if I build `wasmer` from scratch.

### Steps to reproduce
Download the binary from the github releases (I tried linux-aarch64, darwin-arm64 and linux-amd64).
Try to run `wasmer --version`
Example output:

```
wasmer --version
error: Found argument '--version' which wasn't expected, or isn't valid in this context

	If you tried to supply `--version` as a value rather than a flag, use `-- --version`

USAGE:
    wasmer [OPTIONS] <FILE> [ARGS]...

For more information try --help
```

The `--version` argument is also missing in `wasmer --help`.

```
wasmer --help
wasmer
Wasmer Engineering Team <engineering@wasmer.io>
WebAssembly standalone runtime.

USAGE:
    wasmer <SUBCOMMAND>

OPTIONS:
    -h, --help    Print help information

SUBCOMMANDS:
    binfmt         Unregister and/or register wasmer as binfmt interpreter
    cache          Wasmer cache
    compile        Compile a WebAssembly binary
    config         Get various configuration information needed to compile programs which use
                       Wasmer
    create-exe     Compile a WebAssembly binary into a native executable
    create-obj     Compile a WebAssembly binary into an object file
    help           Print this message or the help of the given subcommand(s)
    inspect        Inspect a WebAssembly file
    run            Run a WebAssembly file. Formats accepted: wasm, wat
    self-update    Update wasmer to the latest version
    validate       Validate a WebAssembly binary
    wast           Run spec testsuite
```

### Expected behavior
I expected for the binary to output the version

### Actual behavior
The command errors.
### Additional context
I tried this on darwin-arm64, linux-aarch64 and linux-amd64. Every other version worked, apart from 3.0.0-beta (latest as of now). Building the project also works.

**Comment by syrusakbary** [comment]
This issue was solved by #3090, and released in wasmer `3.0.0-beta.2`. Please let us know if you have any issues with it.

(you may need to do `rm ~/.wasmer/bin/wasmer` if `wasmer self-update` doesn't work at first try)
