### ISSUE TITLE
Incompatible import type for resized table

### ISSUE THREAD

**Issue by benozol** [wasmerio/wasmer#3197]
### Describe the bug

A WASM module that imports a table with a minimum size can only be instantiated with an imported table that was created with a compatible table type. Importing a table that was created with a lower minimum size and resized using `Table::grow` to a compatible size results in an error `incompatible import type`.

Observed using Wasmer 2.3.0 and 3.0.0-beta.

### Steps to reproduce

Using Wasmer 3.0.0-beta:

```rust
use wasmer::{imports, Instance, Module, Store, Table, TableType, Type, Value};

const WAT:&str = r#"(module (table (import "env" "table") 100 funcref))"#;

fn wasmer3() -> anyhow::Result<()> {
    let mut store = Store::default();
    let module = Module::new(&store, WAT)?;
    let ty = TableType::new(Type::FuncRef, 0, None);
    let table = Table::new(&mut store, ty, Value::FuncRef(None))?;
    table.grow(&mut store, 100, Value::FuncRef(None))?;
    let imports = imports! {"env" => {"table" => table}};
    let _instance = Instance::new(&mut store, &module, &imports)?;
    Ok(())
}
```

### Expected behavior

After calling `table.grow` the size of `table` is compatible with the WASM import declaration, and the instance is created.

### Actual behavior

Error while importing `"env"."table"`: incompatible import type. Expected `Table(TableType { ty: FuncRef, minimum: 100, maximum: None })` but received `Table(TableType { ty: FuncRef, minimum: 0, maximum: None })`.

### Additional context

The WASM specification states that the limits of the table limits must match (https://www.w3.org/TR/wasm-core-2/valid/types.html#tables), and the minimum limit is updated when growing a table (https://www.w3.org/TR/wasm-core-2/exec/modules.html#grow-table).

In `wasmtime` and Javascript in Firefox/Chrome/V8 the instantiation is successful in the corresponding code:

#### Javascript (works)

```js
const module = await WebAssembly.compileStreaming(fetch('test1.wasm'));
const table = new WebAssembly.Table({ initial: 0, element: "anyfunc" });
table.grow(100);
const instance = await WebAssembly.instantiate(module, {env: {table: table}});
console.log(instance);
```

#### Wasmtime 1.0.0 (works)

```rust
use wasmtime::{Engine, Instance, Module, Store, Table, TableType, Val, ValType};

fn wasmtime() -> anyhow::Result<()> {
    let engine = Engine::default();
    let mut store = Store::new(&engine, ());
    let module = Module::new(&engine, WAT)?;
    let ty = TableType::new(ValType::FuncRef, 0, None);
    let table = Table::new(&mut store, ty, Val::FuncRef(None))?;
    table.grow(&mut store, 100, Val::FuncRef(None))?;
    let _instance = Instance::new(&mut store, &module, &[table.into()])?;
    Ok(())
}
```

#### Wasmer 2.3.0 (fails)

```rust
use wasmer::{Store, Module, Instance, Table, TableType, Type, Value, imports};

fn wasmer2() -> anyhow::Result<()> {
    let store = Store::default();
    let module = Module::new(&store, WAT)?;
    let ty = TableType::new(Type::FuncRef, 0, None);
    let table = Table::new(&store, ty, Value::FuncRef(None))?;
    table.grow(100, Value::FuncRef(None))?;
    let imports = imports!{"env" => {"table" => table}};
    let _instance = Instance::new(&module, &imports)?;
    Ok(())
}
```

**Comment by syrusakbary** [comment]
Thanks for the report!

**Comment by syrusakbary** [comment]
The issue is that Wasmer currently changes the minimum when calling `table.grow` (it shouldn't be the case) (if we do `table.grow(10)` the minimum goes from `x` to `x+10` at the moment).

Once we solve that, the issue shall be solved.

Thanks again for the report!
