### ISSUE TITLE
Is being able to open and stat a directory intended?

### ISSUE THREAD

**Issue by zzjas** [wasmerio/wasmer#3203]
### Describe the bug
Wasmer is able to `open` and `stat` a directory when the flag is `O_RDWR`.

```
#include <stdio.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <unistd.h>

int main(int argc, char * argv[]) {
	int fd0 = open("test_dir", O_RDWR);
	printf("fd is %d\n", fd0);
	struct stat stat;
        stat.st_size = 0;
	fstat(fd0, &stat);
	printf("stat dir size %d\n", stat.st_size);
}
```

### Steps to reproduce
Store the above into a file `dir.c`.
Compile with `wasi-sdk-16.0` and run with wasmer.

```
mkdir -p test_dir
$WASI_SDK_PATH/bin/clang --sysroot=$WASI_SDK_PATH/share/wasi-sysroot dir.c -o dir.wasm
wasmer dir.wasm --dir=.
```

To compare:
```
wasmtime dir.wasm --dir=.
clang dir.c -o dir.out
./dir.out
```

### Expected behavior
The `open` returns `-1`.

### Actual behavior
`open` returns a file descriptor and it can be used to `stat`.

**Comment by fschutt** [comment]
I think this is a duplicate of #3125, which is currently being worked on in #3201.

**Comment by zzjas** [comment]
Hi, thanks for checking out the issue. I'm not sure if they are the same. #3125 was about rights for an existing file descriptor. However, here a valid file descriptor should not be returned by `open` in the first place.

e.g.
Here is the output from wasmer
```
fd is 5
stat dir size 128
```
and here is the output from wasmtime and native libc
```
fd is -1
stat dir size 0
```

I built wasmer on branch`wasi-fs-rights` commit `00ad13810869d9e07466209f4bdd686409e631a2` from #3201 with `make build-wasmer`. The behavior of `open` is still the same as described above.
