### ISSUE TITLE
Update to latest (non-patch-specific) version of rkyv

### ISSUE THREAD

**Issue by syrusakbary** [wasmerio/wasmer#3207]
We should be using the latest version of rkyv (`0.7.x`)

**Comment by syrusakbary** [comment]
And not pin a specific patch version, but an open one (two digits):

In `types/Cargo.toml`:

```
rkyv = { version = "0.7", features = ["indexmap"] }
```

**Comment by syrusakbary** [comment]
From offline sync `version = "0.7.38"` should be equivalent to `version = "0.7.(any number higher)"`

**Comment by Michael-F-Bryan** [comment]
From [the cargo docs](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#caret-requirements):

> Caret requirements are an alternative syntax for the default strategy, `^1.2.3` is **exactly equivalent** to `1.2.3`.

(emphasis mine)
