### ISSUE TITLE
Upstream wasi-types-generator-extra into wit-bindgen

### ISSUE THREAD

**Issue by fschutt** [wasmerio/wasmer#3209]
We need to remove [lib/wasi-types/wasi-types-generator-extra/src/main.rs](https://github.com/wasmerio/wasmer/issues/new?assignees=&labels=%F0%9F%90%9E+bug&template=---bug-report.md&title=#diff-8747a217eb303dd2584bcdc0796a5c82cb097ac73eb7655c8c49ecfe765fa45b) and upstream the functionality (bitflags support for repr(u16)) into wit-bindgen.

**Comment by fschutt** [comment]
Currently blocked because #3177 is not yet merged.

**Comment by syrusakbary** [comment]
Context: we would like to remove this code: https://github.com/wasmerio/wasmer/pull/3177/files#diff-8747a217eb303dd2584bcdc0796a5c82cb097ac73eb7655c8c49ecfe765fa45bR28-R51

And wit-bindgen doesn't seem to want to support the older repr: https://github.com/bytecodealliance/wit-bindgen/issues/323
