### ISSUE TITLE
popcnt stuck in a loop on M1 and singlepass compiler

### ISSUE THREAD

**Issue by grishasobol** [wasmerio/wasmer#3210]
### Describe the bug
Using M1 + singlepass compiler causes stucking in loop for that code for example:
```wat
(module
  (func $popcnt (export "popcnt") (param i32) (result i32)
      local.get 0
      i32.popcnt
  )
)
```
If param == 1, then function `popcnt` call execution lasts forever.

### Environment
Use wasmer in Cargo.toml like this:
```
wasmer = { version = "2.3.0", default-features = false, features = ["default-singlepass", "default-universal", "wat", "sys"] }
```

```sh
$ rustc -V
rustc 1.65.0-nightly (17cbdfd07 2022-09-13)

$ uname -a
... MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0 ... RELEASE_ARM64_T6000 arm64
```

### Steps to reproduce
1. Clone repo https://github.com/grishasobol/wasmer-fail .
2. Make `cargo test` on machine with M1 processor (see Environment above).
3. Tests must stuck in a loop.

### Additional context
This happen because this assembler execution on M1 result conflicts with Aarch64 documentation:
```asm
mov w1, 32
mov w2, 1
lsl w3, w2, w1
```
There will be `1` in `w3`, but due documentation must be `0`. (The same for 64 registers)

You can reproduce this:
1. take file [arm.s.zip](https://github.com/wasmerio/wasmer/files/9685436/arm.s.zip)
2. build it
```sh
$ as -o arm.o arm.s && ld -o arm arm.o -lSystem -syslibroot `xcrun -sdk macosx --show-sdk-path` -e _start -arch arm64
```
3. run it and print return code
```sh
$ ./arm ; echo $?
1
```

**Comment by syrusakbary** [comment]
This should be fixed by #3211
