### ISSUE TITLE
What would cause a `UnknownImport` error?

### ISSUE THREAD

**Issue by ra0x3** [wasmerio/wasmer#3213]
### Summary

- I am working on a quite complex project, that has been using wasmer fine until a few days ago.
- Due to the project's complexity, I won't be able to post a minimum reproducible example I'm afraid.
- Recently, after upgrading some of the project's dependencies (not related to wasmer), I'm experiencing a very spooky wasmer runtime error
- The code in question compiles to wasm with no issues (via `cargo build --release` with a `wasm32-unknown-unknown` target)
- However...when I try starting my service, I get a runtime error from wasmer (error output below)

### Additional details

Error output
```bash
4 vmctx, i32, i32, i32) -> i32 system_v)
Oct 01 20:07:25.080  INFO wasmer_compiler_cranelift::translator::func_translator: translate(14 bytes, u0:743(i64 vmctx, i32, i32, i32) -> i32 system_v)
Oct 01 20:07:25.082  INFO wasmer_compiler_cranelift::translator::func_translator: translate(3299 bytes, u0:729(i64 vmctx, i32, i32) system_v)
Oct 01 20:07:25.082  INFO wasmer_compiler_cranelift::translator::func_translator: translate(87 bytes, u0:730(i64 vmctx, i32) system_v)
Oct 01 20:07:25.085  INFO wasmer_compiler_cranelift::translator::func_translator: translate(38 bytes, u0:211(i64 vmctx) system_v)
Oct 01 20:07:25.086  INFO wasmer_compiler_cranelift::translator::func_translator: translate(385 bytes, u0:74(i64 vmctx, i32, i32) -> i32 system_v)
Oct 01 20:07:25.088  INFO wasmer_compiler_cranelift::translator::func_translator: translate(7846 bytes, u0:736(i64 vmctx, i32, i32, i32) system_v)
Oct 01 20:07:25.088  INFO wasmer_compiler_cranelift::translator::func_translator: translate(46 bytes, u0:212(i64 vmctx) system_v)
Oct 01 20:07:25.088  INFO wasmer_compiler_cranelift::translator::func_translator: translate(1838 bytes, u0:731(i64 vmctx, i32, i32, i32) system_v)
Oct 01 20:07:25.089  INFO wasmer_compiler_cranelift::translator::func_translator: translate(1341 bytes, u0:737(i64 vmctx, i32, i32) system_v)
Oct 01 20:07:25.090  INFO wasmer_compiler_cranelift::translator::func_translator: translate(370 bytes, u0:68(i64 vmctx, i32) system_v)
Error: Error instantiating wasm interpreter: Link(
    Import(
        "__wbindgen_placeholder__",
        "__wbindgen_describe",
        UnknownImport(
            Function(
                FunctionType {
                    params: [
                        I32,
                    ],
                    results: [],
                },
            ),
        ),
    ),
)

Caused by:
    Error while importing "__wbindgen_placeholder__"."__wbindgen_describe": unknown import. Expected Function(FunctionType { params: [I32], results: [] })
```

Provide any additional details here.

The code that I'm using the create my WASM instance is roughly. I have narrowed the issue/error down to this specific line `let instance = Instance::new(&module, &import_object)?;`

```rust
        let store = Store::new(&Universal::new(compiler()).engine());
        let module = Module::new(&store, &wasm_bytes)?; // the `wasm bytes` is the compiled wasm from cargo build --release with a wasm32-unknown-unknown target

        let mut import_object = imports! {};

        let mut env = IndexEnv::new(db_conn).await?;
        let exports = ffi::get_exports(&env, &store);
        import_object.register("env", exports);

        let instance = Instance::new(&module, &import_object)?;
        env.init_with_instance(&instance)?;
        env.db.lock().await.load_schema_wasm(&instance).await?;

        if !instance
            .exports
            .contains(ffi::MODULE_ENTRYPOINT.to_string())
        {
            return Err(IndexerError::MissingHandler);
        }
```

Even more additional context

- Not sure if this would help, but here is a file diff of my old code that worked (left) and the new code (right) that compiles fine, but throws the aforementioned runtime error. https://www.diffchecker.com/wNi0wReX
- Again, not sure if this would even help, but trying to provide all the context/info I can 
- I realize this is a real shot in the dark, but I'm just having a hard time seeing how this error could have mysteriously appeared 🤔 
- I'm hoping to get some hint/tip on _anything_ that could possibly be the error - which is why I opened this issue as a `Question`. I'm not expecting to solve this issue in these comments
- Any/all help would be extremely appreciated

**Comment by syrusakbary** [comment]
Were you able to resolve it @ra0x3 ?

**Comment by ra0x3** [comment]
@syrusakbary No I just figured this issue might be unproductive since it's so vague
