### ISSUE TITLE
Port wasmer-os to wasmer

### ISSUE THREAD

**Issue by john-sharratt** [wasmerio/wasmer#3217]
The following tasks are needed to follow port over `wasmer-os` to `wasmer`

1. Push the slim branch into master for ATE

https://github.com/wasmerio/ate/tree/slim

2. Publish the following WASIX binaries under the wasmer WAPM namespace

- coreutils
- bash
- dash
- kibi

e.g. wasmer/coreutils

3. Create a new project within wasmer repo named `wasmer-os` under /lib/os

4. Port over the embedded files into a wasmer-os  that reside in these repos:

https://github.com/wasmerio/ate/tree/slim/wasmer-os/static
(redirect the binary aliases to the wasmer namespace on WAPM)

5. Implement a build step in the project so that it detects changes to the static files

https://github.com/wasmerio/ate/blob/slim/wasmer-os/build.rs

6. Port over the console API's and refactor them to meet the coding style of wasmer.

https://github.com/wasmerio/ate/blob/slim/wasmer-os/src/api/abi.rs

7. Port over the UnionFS and other file system implementations

https://github.com/wasmerio/ate/tree/slim/wasmer-os/src/fs

8. Port over the BUS and rename it to RPC

https://github.com/wasmerio/ate/tree/slim/wasmer-os/src/bus
(there is left over code here that is no longer needed)

9. Port over the WebC fetching logic

https://github.com/wasmerio/ate/blob/slim/wasmer-os/src/wapm/mod.rs

10. Refactor the FD implementation and move into either wasmer-os or wasmer-vfs

https://github.com/wasmerio/ate/blob/slim/wasmer-os/src/fd.rs

11. Port over the binary factory and strip out excess bloat

https://github.com/wasmerio/ate/blob/slim/wasmer-os/src/bin_factory.rs

12. Port over Job management

https://github.com/wasmerio/ate/blob/slim/wasmer-os/src/job.rs
https://github.com/wasmerio/ate/blob/slim/wasmer-os/src/reactor.rs

13. Port the pipes over to WasiPipe

https://github.com/wasmerio/ate/blob/slim/wasmer-os/src/pipe.rs

14. Port the FD polling logic over to wasmer

https://github.com/wasmerio/ate/blob/slim/wasmer-os/src/poll.rs

15.  Implement the main execution function again and simplify it

https://github.com/wasmerio/ate/blob/slim/wasmer-os/src/eval/exec.rs

16. Port over the main Console control plane.

https://github.com/wasmerio/ate/blob/slim/wasmer-os/src/console.rs

17. Modify the Wasmer CLI so that if it detects WASIX that it will run the Console (OS) instead of just invoking the binary.

https://github.com/john-sharratt/wasmer/blob/master/lib/cli/src/commands/run.rs

**Comment by john-sharratt** [comment]
`   Compiling wasmer-cli v3.0.0-beta (/prog/wasmer/lib/cli)
    Finished dev [unoptimized + debuginfo] target(s) in 47.23s
     Running `/prog/wasmer/target/debug/wasmer --use sharrattj/coreutils /prog/ate/wasmer-web/public/bin/dash.wasm`
# ls
bin
dev
etc
tmp
usr
# cd bin
# ls -C
arch      cp         factor    link     nproc     relpath  sum       uname
base32    csplit     false     ln       numfmt    rm       sync      unexpand
base64    cut        fmt       logname  od        rmdir    tac       uniq
baseenc   date       fold      ls       paste     runcon   tail      unlink
basename  dd         groups    mkdir    pathchk   seq      tee       uptime
cat       df         hashsum   mkfifo   pinky     sh       test      users
chcon     dircolors  head      mknod    pr        shred    timeout   wasmer
chgrp     dirname    hostid    mktemp   printenv  shuf     touch     wc
chmod     du         hostname  more     printf    sleep    tr        who
chown     echo       id        mv       ptx       sort     true      whoami
chroot    env        install   nice     pwd       split    truncate  yes
cksum     expand     join      nl       readlink  stat     tsort
comm      expr       kill      nohup    realpath  stdbuf   tty
# cd /
# wasmer syrusakbary/python
Python 3.6.7 (default, Feb 14 2020, 03:17:48)
[Wasm WASI vClang 9.0.0 (https://github.com/llvm/llvm-project 0399d5a9682b3cef7 on generic
Type "help", "copyright", "credits" or "license" for more information.
>>> 1 + 2
3
>>> ^C
john@AlienWorld:/prog/wasmer/lib/cli$ cargo run --features compiler,cranelift,debug -- --use sharrattj/coreutils /prog/ate/wasmer-web/public/bin/dash.wasm
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `/prog/wasmer/target/debug/wasmer --use sharrattj/coreutils /prog/ate/wasmer-web/public/bin/dash.wasm`
# echo blah | cat
blah
#`

**Comment by john-sharratt** [comment]
```sh
cargo run --features compiler,cranelift,debug -- --use sharrattj/coreutils /prog/ate/wasmer-web/public/bin/dash.wasm
````

**Comment by john-sharratt** [comment]
[dash.zip](https://github.com/wasmerio/wasmer/files/9878593/dash.zip)

**Comment by fschutt** [comment]
Use the branch: https://github.com/john-sharratt/wasmer/tree/os

**Comment by fschutt** [comment]
port: https://github.com/john-sharratt/wasmer/tree/os/lib/wasi/src/fs

**Comment by theduke** [comment]
This was completed in #3422 .

**Comment by syrusakbary** [comment]
It just took a few months... but we got it!
