### ISSUE TITLE
Rename syscall should replace target_path when it it exists

### ISSUE THREAD

**Issue by Yesterday17** [wasmerio/wasmer#3228]
https://github.com/wasmerio/wasmer/blob/19e7e7af2727792ffae1e092e99585dc486a05b2/lib/wasi/src/syscalls/mod.rs#L2662-L2673

> If newpath already exists, it will be atomically replaced, so
> that there is no point at which another process attempting to
> access newpath will find it missing.  However, there will
> probably be a window in which both oldpath and newpath refer to
> the file being renamed.
>
> -- https://man7.org/linux/man-pages/man2/rename.2.html

**Comment by syrusakbary** [comment]
This should be fixed by #3230
