### ISSUE TITLE
How can I got notified when method like `link` and `symlink` are called within WasiFs?

### ISSUE THREAD

**Issue by Yesterday17** [wasmerio/wasmer#3232]
### Summary

I'm building a WASI-compatible system with a full virtual filesystem, hoping to redirect all fs-related operations to it. But I found some methods(like `link` and `symlink`) are handled by WasiFs directly, and not exposed to `FileSystem` trait.

**Comment by Michael-F-Bryan** [comment]
After reviewing with @syrusakbary, we think there should be some sort of `symlink()` method added to [`wasmer_vfs::FileSystem`](https://docs.rs/wasmer-vfs/latest/wasmer_vfs/trait.FileSystem.html) for creating a symlink. For hard links, it might be easiest to set them up manually when constructing your `FileSystem` implementation.
