### ISSUE TITLE
`path_symlink` panics when old_path is relative

### ISSUE THREAD

**Issue by Yesterday17** [wasmerio/wasmer#3233]
Assume we're calling `path_symlink("testing", 1234, "/test-target")`.

https://github.com/wasmerio/wasmer/blob/03e89116323f05ff5809029904e7c584d03b29aa/lib/wasi/src/syscalls/mod.rs#L2826-L2829

`source_inode` is got from `get_parent_inode_at_path`:

https://github.com/wasmerio/wasmer/blob/5db56ce0437c9f760e2fea2271b51094f7b07ecd/lib/wasi/src/state/mod.rs#L1274-L1294

Here `path` is `testing`, so we got `components = Components([Normal("testing")])`, So:

- `new_entity_name` = `testing`
- `parent_dir` = `""`

Since `parent_dir` is empty, `get_inode_at_path ` returns `base` directly.

https://github.com/wasmerio/wasmer/blob/03e89116323f05ff5809029904e7c584d03b29aa/lib/wasi/src/syscalls/mod.rs#L2830-L2833

So `source_inode` and `fd` here are actually referring the same thing. `path_depth_from_fd` return **`0`**. The minus opration **causes overflow**.

https://github.com/wasmerio/wasmer/blob/03e89116323f05ff5809029904e7c584d03b29aa/lib/wasi/src/syscalls/mod.rs#L2861-L2865

The overflow would not be panic in release build, but results in another panic where the `push` operation exceeds capacity of `relative_path` with `depth = 2**32 - 1`.

Also, I found the use of `Path` and `str` very confusing. Maybe it needs to be unified?

**Comment by syrusakbary** [comment]
Note: this issue seems related to #3228

**Comment by syrusakbary** [comment]
Note: this issue seems related to #3228
