### ISSUE TITLE
 Error while importing "env"."memory

### ISSUE THREAD

**Issue by penberg** [wasmerio/wasmer#3246]
I have the following C program:

```c
#include <stdio.h>

int main(int argc, char *argv[])
{
        printf("hello, wasm!");

        return 0;
}
```

that I compiled into WebAssembly as per these instructions:

https://depth-first.com/articles/2019/10/16/compiling-c-to-webassembly-and-running-it-without-emscripten/

That is, I cloned the https://github.com/CraneStation/wasi-libc.git repository, built and installed it, and then grabbed the https://github.com/jedisct1/libclang_rt.builtins-wasm32.a file before compiling `hello.c` as follows:

```console
clang --target=wasm32-unknown-wasi --sysroot /tmp/wasi-libc -nostartfiles -Wl,--import-memory -Wl,--no-entry -Wl,--export-all -o hello.wasm hello.c
```

when attempting this to run under latest Wasmer release (2.3.0), I see the following import failure:

```console
$ wasmer run tests/hello.wasm 
wasmer: /lib64/libtinfo.so.5: no version information available (required by wasmer)
error: failed to run `tests/hello.wasm`
│   1: failed to instantiate WASI module
╰─▶ 2: Error while importing "env"."memory": unknown import. Expected Memory(MemoryType { minimum: 2 pages, maximum: None, shared: false })
```

**Comment by knarkzel** [comment]
The web assembly is missing a memory export (in WAT):
```
(module
  (memory (;0;) 0)
  (export "memory" (memory 0)))
```

**Comment by penberg** [comment]
Right.

So I can reproduce the issue with:

```console
clang --target=wasm32-unknown-wasi --sysroot /tmp/wasi-libc -nostartfiles -Wl,--import-memory -Wl,--no-entry -Wl,--export-all -o hello.wasm hello.c
```

If I drop the `-Wl,--import-memory` option, then I no longer get that error:

```console
clang --target=wasm32-unknown-wasi --sysroot /tmp/wasi-libc -nostartfiles  -Wl,--no-entry -Wl,--export-all -o hello.wasm hello.c
```

@knarkzel, so this is a toolchain problem, nothing that concerns Wasmer?

**Comment by syrusakbary** [comment]
@penberg have you tried compiling your code with zig-c++ ? I think it's way easier to use and it will probably output the right Wasm file.
