### ISSUE TITLE
Investigate why wasi-wast / fd_append and path_symlink fail only when wasm files are compiled with nightly

### ISSUE THREAD

**Issue by fschutt** [wasmerio/wasmer#3250]
For now, some tests generated by wasi-wast are commented out / ignored in https://github.com/wasmerio/wasmer/commit/cae9f8e9e1f73a8857ccd08425734a0d5c916a2a

These tests did not fail when using older WASI versions, but they do fail on newer ones. We can ignore this for now, since the old fd_append and path_symlink tests still pass, but going forward this would make our testing infrastructure more brittle if we ignore this, maybe users start to run into problems if they compile on nightly.

Related: https://github.com/wasmerio/wasmer/pull/3240

**Comment by Michael-F-Bryan** [comment]
This may be related to https://github.com/wasmerio/wasmer/pull/3230.
