### ISSUE TITLE
Wrong code generation when compiling with optimizations on Cranelift and LLVM

### ISSUE THREAD

**Issue by HeliosPanoptes** [wasmerio/wasmer#3251]
### Describe the bug

```sh
echo "`wasmer -V` | `rustc -V` | `uname -m`"
wasmer 2.3.0 | rustc 1.63.0-nightly (490324f7b 2022-05-26) | x86_64
```

Compiling and running a specific WebAssembly module with either the LLVM or Cranelift compiler with optimizations turned on results in wrong-code generation when compared with NodeJS or the compilers with optimizations turned off.

### Steps to reproduce

Here is a zip file of a rust project that reproduces the behavior: [load-wasmer.zip](https://github.com/wasmerio/wasmer/files/9855884/load-wasmer.zip)

* Go to `load-wasmer`
* Compile with `cargo build`
* Run with `cargo run -- ./src/cranelift_optimizer_bug.wasm --compiler llvm --engine universal`
* Checksum printed out should be `9bdd1220`. This is also what NodeJS thinks the checksum should be.
* Run with `cargo run -- ./src/cranelift_optimizer_bug.wasm --compiler llvm --engine universal --optimize`
* Checksum should be `ef1039d0`
* Run with `cargo run -- ./src/cranelift_optimizer_bug.wasm --compiler cranelift --engine universal --optimize`
* Checksum should be `ef1039d0`

### Expected behavior

All of the checksums should be the same.

### Actual behavior

The checksums differ when compiled with `-- compiler cranelift --engine universal --optimize`, `--compiler llvm --engine universal --optimize`, and `--compiler llvm --engine dylib --optimize`.

Here is the text format of the program that causes the issue:
```webassembly
(module
  (type (;0;) (func (result i32)))
  (type (;1;) (func (param i32) (result i32)))
  (type (;2;) (func))
  (func (;0;) (type 0) (result i32)
    (local i32 i64 f32 f64 i32 i32 i64 i64)
    i32.const 0
    call 2  ;; Stuff after the call is also important
    i32.const 2
    i32.const 1
    i32.const 0
    f64.load offset=37 align=4
    i32.const 655
    f64.load offset=40 align=4
    f64.add
    f32.demote_f64
    f32.store offset=77 align=2 ;; This store is important
    i32.const 1  ;; i32 and return is just used to return the function early
    return       ;; without taking care of the types on the stack
  )
  (func (;1;) (type 0) (result i32)
    unreachable  ;; Uncalled. Just didn't want to reorder function types.
  )
  (func (;2;) (type 1) (param i32) (result i32)
    (local i32 i64 f32 f64 i32 i64)
    i32.const 663 ;; Memory address
    i32.const -2  ;; The negative for the value to be stored is important
    i32.store offset=36 align=1
    i32.const 0
  )
  (func (;3;) (type 2))
  (memory (;0;) 1)
  (global (;0;) (mut i32) i32.const 0)
  (global (;1;) (mut i32) i32.const -1)
  (export "_memory" (memory 0))
  (export "_main" (func 0))
  (export "_crc_globals" (func 3))
)
```

The negative value in function 2 seems to be important. When changed to a positive value, the problem behavior disappears. 

### Additional context

This issue might be related to #3190. However, there are a few differences between the two. First is that I haven't seen Cranelift produce wrong code before. In #3190, Cranelift produces the correct checksum. Second, this reduced code has no loop in it.

I couldn't manage to reproduce the behavior using the standalone CLI. If there's a way to more compactly reproduce the behavior, please let me know!

This test case is derived from a program created by Wasmlike, an Xsmith-based random program generator. https://www.flux.utah.edu/project/xsmith

**Comment by Michael-F-Bryan** [comment]
This may be related to #3190. Possibly an issue with the IR we generate.

**Comment by theduke** [comment]
Not stale.
