### ISSUE TITLE
Exit Code has wrong value when unreachable is reached

### ISSUE THREAD

**Issue by ptitSeb** [wasmerio/wasmer#3262]
### Describe the bug
According to wasi.fyi libc test suite, when `unreachable` is reached, like when compiling an `abort()` function with WASI, the error code return should be `132`. Wasmer return `1`.

The C program is here
```
#include <stdlib.h>

int main(void) {
    abort();

    return 0;
}
```
wich gives the attached wasm file. But basically, it's just an `unreachable` reached.
[abort.zip](https://github.com/wasmerio/wasmer/files/9880410/abort.zip)

Same issue with the "assert-false" test:
```
#include <assert.h>
#include <stdbool.h>

int main(void) {
    assert(false);

    return 0;
}
```

**Comment by syrusakbary** [comment]
This was fixed with #3266
