### ISSUE TITLE
[WASI] trying to fopen a folder should result in `ENOTCAPABLE` error and no handle

### ISSUE THREAD

**Issue by ptitSeb** [wasmerio/wasmer#3263]
According to wasi.fyi libc test suite, trying to fopen anything from a parent of a preopenned folder should result in a `ENOTCAPABLE` error and no file open. 
While wasmer forbid the operation, the error code doesn't seems correct.
`ENOTCAPABLE` should be the value 93

C code is
```C
#include <assert.h>
#include <errno.h>
#include <stdio.h>

int main() {
  FILE* file = fopen("fopen-directory-parent-directory/..", "r");
  assert(file == NULL);
  assert(errno == ENOTCAPABLE);

  return 0;
}
```

Attached is the wasm, that should be run with an existing `fopen-directory-parent-directory` folder  in the pre-openned folder
[fopen-directory-parent-directory.zip](https://github.com/wasmerio/wasmer/files/9880580/fopen-directory-parent-directory.zip)

**Comment by syrusakbary** [comment]
This was fixed with #3266
