### ISSUE TITLE
Openning parent folder with no preopen folder should result in `ENOTCAPABLE` error and no open file

### ISSUE THREAD

**Issue by ptitSeb** [wasmerio/wasmer#3265]
According to wasi.fyi libc test suite, openning the parent folder (of current folder) with no preopen folder should result in a `ENOTCAPABLE` error and no file openned.

```C
#include <assert.h>
#include <errno.h>
#include <stdio.h>

int main() {
  FILE* file = fopen("..", "r");
  assert(file == NULL);
  assert(errno == ENOTCAPABLE);

  return 0;
}
```

Attached is the wasm file.
[fopen-parent-directory.zip](https://github.com/wasmerio/wasmer/files/9880643/fopen-parent-directory.zip)

**Comment by syrusakbary** [comment]
This was fixed with #3266
