### ISSUE TITLE
Export `wasmer::sys::module::IoCompileError`

### ISSUE THREAD

**Issue by jvff** [wasmerio/wasmer#3267]
# Motivation

There's an error type returned from `Module::from_file` that is public but isn't exported from the crate. It's therefore impossible to import that type to match against the error in a project that uses the `wasmer` crate.

It's also impossible to do something like

```rust
#[derive(Debug, thiserror::Error)]
pub enum CustomError {
    #[error("Failed to load Wasm module")]
    InvalidModule(#[from] wasmer::IoCompileError), // How to import `IoCompileError`?

    // ...
}
```

# Solutions

The simplest solution might be to just export the error type from the root module of the `wasmer` crate.

An alternative is to change the error type returned by `Module::from_file`, if the `IoCompileError` shouldn't be public.

**Comment by fschutt** [comment]
Fixed in #3311, closing.
