### ISSUE TITLE
Build Failure due to missing sub module 'wit-bindgen' in 'wasmer/lib/wasi-types/'

### ISSUE THREAD

**Issue by canewsin** [wasmerio/wasmer#3278]
### Describe the bug

Using witbindgen dep via git url
Security Audit failing because of missing above submodule 

https://github.com/canewsin/zeronet-rs/actions/runs/3393271427/jobs/5640413699

https://github.com/wasmerio/wasmer/tree/master/lib/wasi-types

**Comment by canewsin** [comment]
@syrusakbary

**Comment by fschutt** [comment]
We renamed `wit-bindgen` to `wai-bindgen` to distinguish it from the bytecodealliance version. That is probably why it's failing because there is no `wit-bindgen-wasmer` crate anymore.

Instead of depending on GitHub, you can depend on crates.io: https://crates.io/crates/wai-bindgen-wasmer

**Comment by fschutt** [comment]
Internally, we should update all references from `wit-bindgen` to `wai-bindgen`, cc @syrusakbary

**Comment by fschutt** [comment]
Related to #3387

**Comment by Michael-F-Bryan** [comment]
This should have been resolved when we used the `wai-bindgen-xxx` crates from crates.io instead of a git submodule.
