### ISSUE TITLE
Error compiling module with C api

### ISSUE THREAD

**Issue by Jomy10** [wasmerio/wasmer#3279]
### Summary

I have some code written in wat, which exports some functions. I use wat2wasm to compile it to wasm and I can confirm it can be run.

Now I'm trying to load the module with the C api.

I read the wasm file into a `wasm_byte_vec_t wasm_bytes`. I can print out the bytes of this variable, so this should be ok.

Engine and store are created without errors.

When I create the module

```c
wasm_module_t* module = wasm_module_new(store, &wasm_bytes);

if (!module) {
  printf("Error compiling module\n");
  return 1;
}
```

I get the `Error compiling module` printed out. I have no clue why this is happening and I can't seem to find how to get an error message from wasmer.

**Comment by fschutt** [comment]
Hi, you can get the last error message with `wasmer_last_error_message()`:

```c
wasm_module_t* module = wasm_module_new(store, &wasm_bytes);

if (!module) {
  printf("Error compiling module\n");
  int error_len = wasmer_last_error_length();
  printf("Error len: `%d`\n", error_len);
  char *error_str = malloc(error_len);
  wasmer_last_error_message(error_str, error_len);
  return 1;
}
```

Technically any module that can be run should also be able to be compiled (since the engine is doing that internally). However, maybe the feature flags are different between the wasmer binary and the wasmer library.
