### ISSUE TITLE
[Rust] Importing host functions doesn't recognize proper function signature

### ISSUE THREAD

**Issue by parazyd** [wasmerio/wasmer#3280]
Hi.

I'm trying to have a host function through the imports! macro, but I'm not succeeding to add a function that has more than two arguments, even though the documentation says the signature is automatically detected.

Whenever I try to import a function with 3+ arguments, I get such a failure:

```
Error: WasmerInstantiationError("Error while importing \"env\".\"db_init_\": incompatible import type. Expected Function(FunctionType { params: [I32, I32], results: [I32] }) but received Function(FunctionType { params: [I32, I32, I32], results: [I32] })")
```

Any clues on what has to be done to fix this?
Thanks

**Comment by fschutt** [comment]
Thank you for reporting.

Our guess is that there is a mismatch between the host and what the guest expects. The `imports` macro is however used internally for all syscalls and many syscalls have >2 arguments, so it should be a problem in the usage, not in the macro itself.

Can you post a minimum example that is failing? Thanks!
