### ISSUE TITLE
Rename release assets for wasmer

### ISSUE THREAD

**Issue by ayys** [wasmerio/wasmer#3291]
### Motivation

When downloading the tar.gz files from wasmer releases, I had to map target triples with the tar.gz files. For example, 

`x86_64-linux-gnu` ➡️ `wasmer-linux-amd64.tar.gz `

### Proposed solution

Rename the release files `wasmer-{target-triple}.tar.gz`, e.g., `wasmer-x86_64-linux-gnu.tar.gz`

**Comment by theduke** [comment]
Not stale.
