### ISSUE TITLE
Windows link failure

### ISSUE THREAD

**Issue by ashtonmeuser** [wasmerio/wasmer#3298]
### Describe the bug

Using Wasmer library on Windows with MSVC fails at linking step. Reproduced with release assets for Wasmer `2.3.0` and `3.0.0-rc.2`.

The link step (`link /nologo /dll /out:build\wasmer-test.dll /implib:build\wasmer-test.lib /LIBPATH:wasmer\lib wasmer.lib instance.obj`) fails reporting unresolved symbols. A portion of the error messages include below.

```
wasmer.lib(std-ca7b0c28ec762872.std.5004ed98-cgu.0.rcgu.o) : error LNK2019: unresolved external symbol __imp_WSAStartup referenced in function _ZN4core3ops8function6FnOnce40call_once$u7b$$u7b$vtable.shim$u7d$$u7d$17h6b6ce4f995fc47ecE
wasmer.lib(std-ca7b0c28ec762872.std.5004ed98-cgu.0.rcgu.o) : error LNK2019: unresolved external symbol __imp_WSACleanup referenced in function _ZN4core3ops8function6FnOnce40call_once$u7b$$u7b$vtable.shim$u7d$$u7d$17h6b6ce4f995fc47ecE
wasmer.lib(std-ca7b0c28ec762872.std.5004ed98-cgu.0.rcgu.o) : error LNK2019: unresolved external symbol __imp_BCryptGenRandom referenced in function _ZN3std6thread5local4fast12Key$LT$T$GT$14try_initialize17h64953c3449a6dee7E
wasmer.lib(getrandom-db5d20707c078d45.getrandom.db5d2d1a-cgu.5.rcgu.o) : error LNK2001: unresolved external symbol __imp_BCryptGenRandom
wasmer.lib(std-ca7b0c28ec762872.std.5004ed98-cgu.0.rcgu.o) : error LNK2019: unresolved external symbol __imp_OpenProcessToken referenced in function _ZN3std3env8home_dir17hba8a03a06bf30198E
wasmer.lib(std-ca7b0c28ec762872.std.5004ed98-cgu.0.rcgu.o) : error LNK2019: unresolved external symbol __imp_GetUserProfileDirectoryW referenced in function _ZN3std3env8home_dir17hba8a03a06bf30198E
wasmer.lib(std-ca7b0c28ec762872.std.5004ed98-cgu.0.rcgu.o) : error LNK2019: unresolved external symbol __imp_freeaddrinfo referenced in function _ZN3std3net4addr19resolve_socket_addr17h861c24ae73ce36faE
wasmer.lib(std-ca7b0c28ec762872.std.5004ed98-cgu.0.rcgu.o) : error LNK2019: unresolved external symbol __imp_closesocket referenced in function _ZN3std3net3tcp9TcpStream15connect_timeout17h4e3ba0f009d56181E
```

I'm not very familiar with Windows C/C++ development, but this may be related to the way the library asset is organized. See [Issue#2680](https://github.com/wasmerio/wasmer/issues/2680).

### Steps to reproduce

I've created a minimal reproduction [here](https://github.com/ashtonmeuser/wasmer-test/actions/runs/3441914990). Note that the Linux and macOS builds succeed as expected.

To reproduce on a Windows machine:
1. Download and extract Windows release assets e.g. [2.3.0](https://github.com/wasmerio/wasmer/releases/download/2.3.0/wasmer-windows-amd64.tar.gz) or [3.0.0-rc.2](https://github.com/wasmerio/wasmer/releases/download/v3.0.0-rc.2/wasmer-windows-amd64.tar.gz).
1. Create a C example that `#include`s the Wasmer library. Any of the [C API examples](https://github.com/wasmerio/wasmer/tree/master/lib/c-api/examples) will work.
1. Build using [MSVC](https://visualstudio.microsoft.com/vs/features/cplusplus/).

### Expected behavior

The library properly links symbols. 

### Actual behavior

Link failure.

### Additional context

Like I said above, I don't know much about C/C++ development on Windows. A cursory search seems to suggest that the affected functions have declarations but no definitions.

**Comment by ashtonmeuser** [comment]
@madebr You seem to have worked around this issue in https://github.com/toge/conan-center-index/pull/1 which spawned https://github.com/wasmerio/wasmer/issues/2680. I am experiencing a similar issue and am at a loss when it comes to Windows development. To save others trying to use Wasmer on Windows, what precisely must change in the Wasmer build process to output the correct libraries? How would one work around this in a [minimum repro project](https://github.com/ashtonmeuser/wasmer-test/actions/runs/3441914990)?

**Comment by madebr** [comment]
The conan-center recipe does not do anything fancy.
It simply adds `bcrypt`, `userenv` and `ws2_32` when linking to a static `libwasmer.a` library. [See here](https://github.com/conan-io/conan-center-index/blob/1d470aa3b8caa59312edd0d15213b3ef4fe4a45e/recipes/wasmer/all/conanfile.py#L84-L85)
So I think you need to additionally pass `bcrypt.lib userenv.lib ws2_32.lib` to the linker.

**Comment by ashtonmeuser** [comment]
Thanks for the guidance! That was much simpler than I was making it out to be. Added system libs `bcrypt`, `userenv`, `ws2_32`, `advapi32.lib`. Closing this issue.

**Comment by ashtonmeuser** [comment]
@madebr The [example](https://github.com/ashtonmeuser/wasmer-test) now builds but outputs the following warnings:

```
cl /Foinstance.obj /c instance.cpp /TP /std:c++latest /nologo -W3 -GR /DWIN32 /D_WIN32 /D_WINDOWS /D_CRT_SECURE_NO_WARNINGS /I. /Iwasmer\include
instance.cpp
link /nologo /dll /out:build\wasmer-test.dll /implib:build\wasmer-test.lib /LIBPATH:wasmer\lib bcrypt.lib userenv.lib ws2_32.lib advapi32.lib wasmer.lib instance.obj
LINK : warning LNK4217: symbol 'wasm_byte_vec_new' defined in 'wasmer.lib(wasmer.wasmer.3102e54d-cgu.7.rcgu.o)' is imported by 'instance.obj' in function 'main'
LINK : warning LNK4217: symbol 'wasm_byte_vec_delete' defined in 'wasmer.lib(wasmer.wasmer.3102e54d-cgu.7.rcgu.o)' is imported by 'instance.obj' in function 'main'
LINK : warning LNK4217: symbol 'wasm_engine_delete' defined in 'wasmer.lib(wasmer.wasmer.3102e54d-cgu.5.rcgu.o)' is imported by 'instance.obj' in function 'main'
LINK : warning LNK4217: symbol 'wasm_engine_new' defined in 'wasmer.lib(wasmer.wasmer.3102e54d-cgu.5.rcgu.o)' is imported by 'instance.obj' in function 'main'
LINK : warning LNK4217: symbol 'wasm_store_delete' defined in 'wasmer.lib(wasmer.wasmer.3102e54d-cgu.2.rcgu.o)' is imported by 'instance.obj' in function 'main'
LINK : warning LNK4217: symbol 'wasm_store_new' defined in 'wasmer.lib(wasmer.wasmer.3102e54d-cgu.2.rcgu.o)' is imported by 'instance.obj' in function 'main'
LINK : warning LNK4217: symbol 'wasm_module_delete' defined in 'wasmer.lib(wasmer.wasmer.3102e54d-cgu.3.rcgu.o)' is imported by 'instance.obj' in function 'main'
LINK : warning LNK4217: symbol 'wasm_module_new' defined in 'wasmer.lib(wasmer.wasmer.3102e54d-cgu.3.rcgu.o)' is imported by 'instance.obj' in function 'main'
LINK : warning LNK4217: symbol 'wasm_func_call' defined in 'wasmer.lib(wasmer.wasmer.3102e54d-cgu.6.rcgu.o)' is imported by 'instance.obj' in function 'main'
LINK : warning LNK4217: symbol 'wasm_extern_vec_delete' defined in 'wasmer.lib(wasmer.wasmer.3102e54d-cgu.15.rcgu.o)' is imported by 'instance.obj' in function 'main'
LINK : warning LNK4217: symbol 'wasm_extern_as_func' defined in 'wasmer.lib(wasmer.wasmer.3102e54d-cgu.15.rcgu.o)' is imported by 'instance.obj' in function 'main'
LINK : warning LNK4217: symbol 'wasm_instance_delete' defined in 'wasmer.lib(wasmer.wasmer.3102e54d-cgu.9.rcgu.o)' is imported by 'instance.obj' in function 'main'
LINK : warning LNK4217: symbol 'wasm_instance_new' defined in 'wasmer.lib(wasmer.wasmer.3102e54d-cgu.9.rcgu.o)' is imported by 'instance.obj' in function 'main'
LINK : warning LNK4217: symbol 'wasm_instance_exports' defined in 'wasmer.lib(wasmer.wasmer.3102e54d-cgu.9.rcgu.o)' is imported by 'instance.obj' in function 'main'
```

Seems the symbols are defined twice. Once again, I'm at a loss. No warnings whatsoever building on Linux & macOS.

**Comment by madebr** [comment]
This is bug in wasmer.
The static library defines a `wasm_byte_vec_new` symbol.
Wasmer also uses `wasm_byte_vec_new` but uses it as a symbol declared as `__declspec(dllimport)` whereas for a static library it should have been declared without any `__declspec`.
So the symbols are defined with conflicting attributes.

**Comment by ashtonmeuser** [comment]
You've been incredibly helpful! Thank you for taking the time. I'll try to fix the issue and create a PR. If not, will open a new issue.
