### ISSUE TITLE
Backport Singlepass optimisations from Near

### ISSUE THREAD

**Issue by ptitSeb** [wasmerio/wasmer#3305]
Check if latest optimisation on the fork of the Singlepass compiler from Near can be backported to Wasmer.

**Comment by ptitSeb** [comment]
Check if latest optimisation on the fork of the Singlepass compiler from Near can be backported to Wasmer.

https://github.com/near/wasmer/pull/147 => already there
https://github.com/near/wasmer/pull/145 => https://github.com/wasmerio/wasmer/pull/3302
https://github.com/near/wasmer/pull/144 => https://github.com/wasmerio/wasmer/pull/3296
https://github.com/near/wasmer/pull/143 => https://github.com/wasmerio/wasmer/pull/3293
https://github.com/near/wasmer/pull/141 => https://github.com/wasmerio/wasmer/pull/3292
https://github.com/near/wasmer/pull/140 => https://github.com/wasmerio/wasmer/pull/3290
https://github.com/near/wasmer/pull/136 => not applicable as-is. Need to check the handling of locals with Partial_sum_map.

**Comment by Michael-F-Bryan** [comment]
All these optimisations should be implemented now.
