### ISSUE TITLE
Three-way wrong code generation between LLVM optimizations and universal or dylib engines

### ISSUE THREAD

**Issue by HeliosPanoptes** [wasmerio/wasmer#3323]
### Describe the bug

```sh
echo "`wasmer -V` | `rustc -V` | `uname -m`"
wasmer 2.3.0 | rustc 1.63.0-nightly (490324f7b 2022-05-26) | x86_64
```

Compiling and running a specific WebAssembly module results in three-way wrong code generation between LLVM/Universal/Optimize, LLVM/Dylib/Optimize, and everything else. For this bug report, I am replacing 'everything else' with LLVM/Universal, but it could be any other implementation, such as NodeJS.

### Steps to reproduce

Here is a zip file of a rust project that reproduces the behavior: 
[load-wasmer.zip](https://github.com/wasmerio/wasmer/files/10036327/load-wasmer.zip)

* Unzip load-warmer.zip
* Go to `load-wasmer`
* Compile with `cargo build`
* Run the test case with `./verify.zsh`, which will run each variation in turn and display the output
  * This is the output I received:
  ```
        A (LLVM/Universal) ==>          c39b7cee
        B (LLVM/Universal/Optimize) ==> f77dc7dc
        C (LLVM/Dylib/Optimize) ==>     62a776ae
  ```
* See that the three checksums are different

### Expected behavior

The three checksums displayed should be the same.

### Actual behavior

The three checksums are not the same.

To keep this bug report self-contained, I've used Wasmer/LLVM/Universal as the 'correct' implementation, which matches other implementations such as NodeJS. If needed, I can provide the NodeJS boilerplate that produces the checksum.

Here is the text format of the WebAssembly program that causes the issue:
```webassembly
;; A = Wasmer/LLVM/Universal -- agrees with NodeJS
;; B = Wasmer/LLVM/Universal/Optimize
;; C = Wasmer/LLVM/Dylib/Optimize

(module
  (type (;0;) (func (result i32)))
  (type (;1;) (func (param i32 f64) (result f32)))
  (type (;2;) (func (param f32) (result f32)))
  (type (;3;) (func))
  (func (;0;) (type 0) (result i32)
    i32.const 0 ;; store address
    i32.const 0 ;; arg 1
    f64.const 0 ;; arg 2
    call 1      ;; store value
    f32.store offset=59 align=1
    i32.const 21
    return) ;; Return without needing to reduce the stack
  (func (;1;) (type 1) (param i32 f64) (result f32)
    (local i32 i64 f32 f64 i32 f32)
    block (result f32)  ;; label = @1
      i32.const 1
      local.set 6 ;; This local is important
      ;; Replacing this block with an f32.const results in B and C agreeing with each other but not with A
      block (result f32)  ;; label = @2
        i32.const 1
        f32.const 0x1.ddfd56p+81 (;=4.51448e+24;)
        f32.store offset=72 align=2
        f32.const 0x1.b01acp+9 (;=864.209;)
      end
      f32.const 0x1.86c8d6p-75 (;=4.04062e-23;)
      f32.max ;; Removing this max makes only B differ
      global.get 1 ;; Must be this specific global variable.
      ;;f32.const -0x1.2feb5p-113 (;=-1.14322e-34;) 
      f32.const 1 ;; If set to 0, makes only C differ
      f32.min
      f32.sub
      loop (param f32) (result f32)  ;; label = @2
        i32.const 0
        i32.const 0
        i32.load8_u offset=9 ;; load is important
        if (result f32)  ;; label = @3 ;; This whole unused branch is important
          i32.const 1
          f32.const 0x1.7978d4p+9 (;=754.944;)
          f32.store offset=62 align=1
          local.get 7
          f32.const 0x1.bd60bap-4 (;=0.108735;)
          f32.min
          ;; !!! Putting an unreachable here makes all three implementations produce the same result !!!
          ;; unreachable
        else
          i32.const 0
          local.set 6
          i32.const 1
          f32.load offset=11 align=1
          ;; removing this loop makes B agree with C but not A
          loop (param f32) (result f32)  ;; label = @4
            f32.const -0x1.bd2fe2p+9 (;=-890.374;)
            f32.add
            local.get 6
            br_if 0 (;@4;)
          end
          global.get 1 ;;Must be a global
          f32.sub ;; Cannot replace with a drop
        end
        f32.store offset=66 align=2
        f32.const -0x1.9acb68p+56 (;=-1.15628e+17;)
        local.get 0
        br_if 1 (;@1;) ;; removing this branch results in a crash from B and C
        drop
        local.get 7
        f32.const 1
        f32.mul ;; Removing the mul results in C agreeing with A
        f32.add ;; Add is important
        local.get 6
        br_if 0 (;@2;)
        ;; putting a return here causes a crash in B and C
      end
      ;; same here
    end
    f32.floor) ;; Must be some kind of funop or a const and fbinop.
  (func (;2;) (type 3)) 
  (memory (;0;) 1)
  (global (;0;) (mut f32) (f32.const 0x1.c701dcp+9 (;=910.015;)))
  (global (;1;) (mut f32) (f32.const 0x1.0e8962p+8 (;=270.537;)))
  (export "_memory" (memory 0))
  (export "_main" (func 0))
  (export "_crc_globals" (func 2)))
```

I have reduced the test case as far as I am able. The main reason for the size is that modifying certain sections will make only one of the implementations differ, which I've noted as comments wherever I found them. Of particular interest are the uses of `global.get 1` and the commented out `unreachable` in the if statement.

There are no `global.set`s in the program, but if `global.get 1` is replaced with its initialized value, or even another global variable, the wrong code generation ceases.

The if statement begins by getting the ninth byte of memory, which nothing has touched and should be 0, meaning that the first arm of the if statement is 'dead'. If the `unreachable` instruction is uncommented, it confirms this, since none of the implementations will trap and produce an error. However, when uncommented, the wrong code generation is no longer present and all three implementations agree on the checksum.

Additionally, throughout the test case are `f32` unops and binops that should be able to be replaced with a `nop` or `drop`, respectively. When they are, all three implementations agree on the checksum.

Some of this behavior is most likely due to #3190 with the generation of broken LLVM IR. There are a few reasons why I chose to file this as a separate bug report. First is the three-way difference in the checksum. Second, the global variable usage and the required `f32` instructions cause a difference in output, but only all together. If any of them are changed, the three-way difference no longer happens. Last is the addition of `unreachable` to one arm of the if statement changing the output.

### Additional context

This test case is derived from a program created by Wasmlike, an Xsmith-based random program generator. https://www.flux.utah.edu/project/xsmith

**Comment by ptitSeb** [comment]
Thank you for the ticket and the detailled analysis.

I'll probably need to migrate the sample to wasmer-3.0, but then there is no more engine to choose from. Still, I assume the difference on checksum between universal and dylib run are some memory read that are not done at the correct place and read a incoherent value.
