### ISSUE TITLE
[mem_fs] `fd_write` inserts bytes instead of overwriting

### ISSUE THREAD

**Issue by corwin-of-amber** [wasmerio/wasmer#3326]
### Describe the bug

A seek followed by a write is supposed to overwrite the contents of the file at the given position, possibly extending the file if the number of bytes written exceeds (total length – position).
In `vfs::mem_fs::file::File`, the implementation would instead splice the data in like pasting does in a text editor.
https://github.com/wasmerio/wasmer/blob/58d8415e50b49a62444c31f4e20310ab10f62275/lib/vfs/src/mem_fs/file.rs#L997

(Using the development branch of Wasmer and Wasmer-JS, although my branch might be a little bit behind.)

I know that you are probably rewriting the mem_fs but I wanted this issue to be here for when you get to that point.

### Steps to reproduce

I am running `ocamlrun.wasm` from https://github.com/corwin-of-amber/ocaml-wasm/tree/wasm-4.12, but ofc a simpler test case would be plausible:
```c
char buf1[] = "01234567", buf2[] = "aaaa";
write(fd, buf1, 8);
lseek(fd, 4, SEEK_SET);
write(fd, buf2, 4);
```

### Expected behavior

The file should contain `0123aaaa`.

### Actual behavior

The file contains `0123aaaa4567`.

**Comment by corwin-of-amber** [comment]
Same here (when position is 0)
https://github.com/wasmerio/wasmer/blob/58d8415e50b49a62444c31f4e20310ab10f62275/lib/vfs/src/mem_fs/file.rs#L986

In fact there does not seem to be a need for special-casing 0.

Here is the code that I patched in for the general case:
```rust
            // The cursor is somewhere in the buffer: not the happy path.
            position => {
                let to = position + buf.len();
                if to > self.buffer.len() { self.buffer.resize(to, 0); }
                self.buffer[position..position + buf.len()].copy_from_slice(&buf[..]);
            }
```

**Comment by fschutt** [comment]
@corwin-of-amber This was fixed here IIRC: https://github.com/wasmerio/wasmer/pull/3269/files#diff-bcece65d45fcde9294131ef326ad2b7517e27af97f74e11b5ce05bfcd01589d4R1240-R1258

Right now I'm not working on the `mem_fs` code because we need to get it in line for the WASIX merge. 
But the switch from "append" to "overwrite" is there.

**Comment by corwin-of-amber** [comment]
Oh good @fschutt! I noticed a few occurrences of wasix in the code but could not find docs describing what it should encompass. I am feeling that your intentions overlap some work (or workaround?) I have done in [wasi-kernel](https://github.com/corwin-of-amber/wasi-kernel). Looking forward to see more of it.
