### ISSUE TITLE
Wasmer login returns something weird

### ISSUE THREAD

**Issue by syrusakbary** [wasmerio/wasmer#3329]
```
➜  ~ wasmer login
Please paste the login token from https://registry.wapm.io/me:":
```

The url provided is not valid. How come this passed tests? (either manual or automatic)

**Comment by fschutt** [comment]
Oh, I see, it should be `wapm.io/me`, not `registry.wapm.io/me`. It doesn't work in any case, since the redirect on the backend doesn't work yet.

`wasmer login [token]` however, works.

**Comment by fschutt** [comment]
Fixed by https://github.com/wasmerio/wasmer/pull/3339
