### ISSUE TITLE
Go language runtime

### ISSUE THREAD

**Issue by geloizi** [wasmerio/wasmer#333]
Out of curiosity I've tried to run a wasm binary produced by **go** compiler and unsurprisingly it didn't work. Is there any plans to support go and other languages?

**Comment by bjfish** [comment]
Hi @geloizi , we are working on supporting additional languages. There is some work in progress for golang support. Please see this issue regarding golang progress: https://github.com/wasmerio/wasmer/issues/378

**Comment by geloizi** [comment]
It seems there is no more activity in the `feature/golang` branch. Curios whether this task became abandoned?

**Comment by treeder** [comment]
There's also this work for Go to target wasi: https://github.com/golang/go/issues/31105

**Comment by Hywan** [comment]
Closing in favor of https://github.com/wasmerio/wasmer/issues/924.
