### ISSUE TITLE
Singlepass crash/assertion on Apple M1

### ISSUE THREAD

**Issue by sagacity** [wasmerio/wasmer#3343]
### Describe the bug

I am seeing heap_get_oob errors using the 'Singlepass' compiler on Apple M1. It does not appear on Cranelift and does not seem to appear on Linux.

This happens on the latest rustc 1.67.0-nightly (a28f3c88e 2022-11-20) on arm64. The repro case seems to work fine on rustc 1.65.0 (stable), but in more complicated scenarios I've also been getting "out of bounds memory access" errors with rustc 1.65.0. I have not yet been able to get these reproduced, though.

### Steps to reproduce

I have a reproduction repo with two steps: https://github.com/sagacity/wasmer-m1-singlepass-crash

### Expected behavior

Deserializing goes fine. The `host` application runs and exits cleanly.

### Actual behavior

A "HeapAccessOutOfBounds" trap is raised during the deserializing of a simple struct.

### Additional context

I'm not sure whether it's really wasmer being at fault. Perhaps the WASM code generated by rustc is faulty in some way. I'd be happy to do some more testing, but I could use some pointers in getting there :)

Additionally, I noticed that if the struct that's being deserialized is below a certain size, there are no crashes. In my reproduction scenario this happens if the `MyHack` struct does not contain the `inner4` field (so just inner/inner2/inner3).

Cross-compiling triggers an assertion inside `emitter_x64.rs` so I have not been able to test if cross-compilation would have solved the issue.

**Comment by ptitSeb** [comment]
Thank you for the detailled ticket. I reproduce the issue locally, I'll have a look to betterunderstand what's going on here.

**Comment by sagacity** [comment]
I've also tried with rustc 1.59, 1.61 and 1.63 and they give the same crash. I will spend some time seeing if I can downgrade some dependencies to see if that helps at all.

**Comment by sagacity** [comment]
Ok! The reason I was a bit suspicious that it would be rustc miscompilation is that we've seen similar deserialization issues when running this kind of code in Chrome (which is not using wasmer afaik). But perhaps those issues are unrelated.

**Comment by ptitSeb** [comment]
After some more testing, the crash also appear in Linux:/ARM64, so it's not something macOS ABI specific, but a bug in the Singlepass/ARM64 backend.

**Comment by syrusakbary** [comment]
This is now fixed in master. Closing the issue
