### ISSUE TITLE
wasmer wasmer/wabt not working as expected (multiple commands)

### ISSUE THREAD

**Issue by syrusakbary** [wasmerio/wasmer#3345]
When multiple commands are found, we should show the commands available. Right now we just directly try to run one of the commands without it being the entrypoint:

```
➜  ~ wasmer wasmer/wabt

wat2wasm: expected filename argument.
Try '--help' for more information.
```

**Comment by fschutt** [comment]
Yeah, try `--command wabt`

**Comment by fschutt** [comment]
Seems that `--command-name wabt` is ignored. I'll investigate this.

**Comment by syrusakbary** [comment]
No, the issue is that when multiple commands are given (unless there's an entrypoint), it should do something like:

```
$ wasmer run wasmer/wabt
The `wabt` package doesn't have a default entrypoint, but has multiple available commands: `wasm2wat`, `wat2wasm`, ...
You can run any of those by using the --command=COMMAND flag.
  -> wasmer run wasmer/wabt --command=wasm2wat ...
```

Also, we need to make sure that wapm2pirita only puts an entrypoint if there's only one command. If multiple commands are present, no default entrypoint should be set.
