### ISSUE TITLE
Wasmer not showing right stdout on CLI apps

### ISSUE THREAD

**Issue by syrusakbary** [wasmerio/wasmer#3346]
Wasmer stdout is outputting the incorrect thing when used in a simple CLI app:

```
➜  ~ wasmer dynamite-bud/ayush

Hello, world!package dynamite-bud/ayush ...
```

It should output:

```
➜  ~ wasmer dynamite-bud/ayush
Hello, world!
```

**Comment by fschutt** [comment]
Yeah that's an issue with `\r` not clearing stdout properly

It's a display thing, when running in headless mode it will work.

**Comment by syrusakbary** [comment]
We are also adding a `\n` apart of not clearing the stdout. We need to fix this
