### ISSUE TITLE
create-exe works on Ubuntu, but not Debian

### ISSUE THREAD

**Issue by fschutt** [wasmerio/wasmer#3354]
wasmer create-exe does not work on Debian 11, but it does work on Ubuntu 22.04.

```
wasmer create-exe --zig-binary-path ./zig/zig-0.10.0/zig --target x86_64-linux-gnu ./out.webc -o ./test
```

[errors.txt](https://github.com/wasmerio/wasmer/files/10068817/errors.txt)

**Comment by fschutt** [comment]
[out.webc.zip](https://github.com/wasmerio/wasmer/files/10067228/out.webc.zip)

**Comment by syrusakbary** [comment]
This ticket description is not what we should expect when opening issues in Wasmer. We can either close or add the necessary context
