### ISSUE TITLE
PowerPC64LE support

### ISSUE THREAD

**Issue by rjzak** [wasmerio/wasmer#3357]
Thanks for proposing a new feature!

### Motivation

Wasm3 currently is the only WebAssembly-WASI runtime available on PowerPC64LE. It would be nice to have a second.

### Proposed solution

Add PowerPC64LE support to Wasmer. Rust has good support for this platform.

**Comment by Michael-F-Bryan** [comment]
There is no plan to support PowerPC at the moment because we don't have access to the hardware. If you have a PowerPC machine, we would be happy to review a pull request adding support.
