### ISSUE TITLE
Provide Store Reference on Tunable Memory Creation Hooks

### ISSUE THREAD

**Issue by theduke** [wasmerio/wasmer#3398]
### Motivation

Memory creation might require access to some store/instance specific data to obtain some context.

An example use case is metering/metrics per instance.

(Also see https://github.com/wasmerio/wasmer/issues/3397) 

### Proposed solution

We add new methods to Tunables that receive a handle that allows accessing the store, as well as instance-specific user-provided data.  ( see https://github.com/wasmerio/wasmer/issues/3397 for the instance-specific data) 

To avoid a breaking change, we provide a default impl that calls the existing functions.

This should be removed in the future when we do another API break.

```rust
trait Tunables {
   ...
   
    fn create_vm_memory_with_context(
        &self,
        ty: &MemoryType,
        style: &MemoryStyle,
        store: &InstanceStoreHandle,
    ) -> Result<VMMemory, MemoryError> {
        self.create_host_memory(ty, style)
    }
    
   fn create_host_memory_with_context(...
}
```

Would appreciate your feedback, @syrusakbary , @ptitSeb .

**Comment by theduke** [comment]
> With Tunables now part of Engine, I'm unsure how adding a Store dependancy to Tunable will work.

Memory creation will usually be called for an instance, no? So we'd probably have the store available in that context?

> the store args is of type &impl AsStoreRef right?

Not quite, because we also need that instance-specific data.
So we might need a new `InstanceStoreRef` or similar, which also allows accessing that.

**Comment by ptitSeb** [comment]
This look overly complicated. Are you sure this is the bet way to answer you initial problem (that is a need for a hook on `memory_grow` calls IIRC)

**Comment by theduke** [comment]
I'm happy for alternative suggestions, but we do need a way to have custom memories by store and potentially by instance, both for metering and to handle workload memory limits.

**Comment by ptitSeb** [comment]
Both instance and Store, that's a lot of tracking. We need to think/talk about that.

**Comment by theduke** [comment]
I don't think this API change would imply any required overhead, because memory creation always happens with the context of a store / instance, right?

The new method would have a default impl that just uses the old method without any store reference.

Any additional overhead would be up to the user.
