### ISSUE TITLE
Spectests are failing in Rust nightly

### ISSUE THREAD

**Issue by losfair** [wasmerio/wasmer#34]
After updating to the latest nightly (`1.32.0-nightly (400c2bc5e 2018-11-27)`), the tests are broken.

The error is something like:

```
...
test spectests::elem::test_module_18 ... ok
test spectests::elem::test_module_2 ... ok
test spectests::elem::test_module_20 ... ok
error: process didn't exit successfully: `/***/wasmer/target/debug/deps/wasmer-24cae65d1f101576` (signal: 11, SIGSEGV: invalid memory reference)
```

rustc version:

```
rustc 1.32.0-nightly (400c2bc5e 2018-11-27)
binary: rustc
commit-hash: 400c2bc5ed292f77c49693320f4eda37bb375e90
commit-date: 2018-11-27
host: x86_64-apple-darwin
release: 1.32.0-nightly
LLVM version: 8.0
```

**Comment by lachlansneff** [comment]
We've had issues with running this on nightly rust. Stick to stable for now, and we'll go and fix nightly when we have time.

**Comment by syrusakbary** [comment]
Yup, rust nightly for whatever reason is failing, we are planning to fix it but now we are focused on the emscripten support.
If you want to help us investigate on why this happens it would be awesome :)

**Comment by jonas-schievink** [comment]
When are you planning the next patch release? The current release 0.1.4 still runs into this.
