### ISSUE TITLE
Panic hooks stop working after 2nd panic

### ISSUE THREAD

**Issue by cloutiertyler** [wasmerio/wasmer#3405]
### Describe the bug

I am having the exact same problem as in https://github.com/wasmerio/wasmer/issues/1333, but I am running on Wasmer 3.0.1. Panic `set_hook` works fine twice and then stops working.

```sh
 rustc 1.65.0 (897e37553 2022-11-02) | arm64
```

**Comment by ptitSeb** [comment]
Thank you for openning this ticket.

@cloutiertyler do you have a specific example for this issue, to easily reproduce the problem?
