### ISSUE TITLE
Re-enable WasiPipe support

### ISSUE THREAD

**Issue by fschutt** [wasmerio/wasmer#3410]
After the problems with printing in the 3.0.0 release related to WasiPipe, we still need to debug + re-enable it, since having custom I/O is important.

We should do that after the WASIX merge.

**Comment by ptitSeb** [comment]
Need to synchronise @theduke / @john-sharratt if it's still needed or not.

**Comment by fschutt** [comment]
Originally we needed this for Deploy, but we moved ahead without it. We need to sync whether it's still needed (it's a nice feature after all).

**Comment by theduke** [comment]
This should be fixed by the WASIX merge, which has a working pipe.
