### ISSUE TITLE
How to get the bug issues with the github API?

### ISSUE THREAD

**Issue by Zhangyx24** [wasmerio/wasmer#3418]
### Summary

Try to get the github issues from wasmer:
```
curl >tmp.json 'https://api.github.com/search/issues?q=type:issue+repo:wasmerio/wasmer+label:🐞 bug+&sort=created&per_page=100&page=1'
```

But it fails, seems like the 🐞 bug is wrong, how to write the 🐞 bug label in the url ?
![WechatIMG1525](https://user-images.githubusercontent.com/28601300/207050599-cb76afe4-e3b4-49d4-a5c9-d75c2233bd12.jpeg)

**Comment by fschutt** [comment]
We removed the emoji. It does work now using:

`curl >tmp.json 'https://api.github.com/search/issues?q=type:issue+repo:wasmerio/wasmer+label:bug+&sort=created&per_page=100&page=1'`

**Comment by Zhangyx24** [comment]
Thanks for your reply.
