### ISSUE TITLE
expose run_wasm host function to wasm

### ISSUE THREAD

**Issue by pannous** [wasmerio/wasmer#3420]
There is an interesting suggestion for WASI to add an
API to instantiate a module from wasm bytes: https://github.com/WebAssembly/WASI/issues/477

Since wasmer is often ahead of the curve, would you consider exposing a private experimental function
`run_wasm(buffer, length)` which allows for modules to dynamically run (tiny) other modules, within the same security context?

Use cases would be plugins for wasm programs, compilers running inside wasm etc…

The c function header might look like this:
```
__attribute__((import_module("wasi_private"), import_name("run_wasm")))  
extern long run_wasm(uint8* buffer, size_t buffer_length)
```

**Comment by ptitSeb** [comment]
@theduke would this be part of WASIX?

**Comment by theduke** [comment]
WASIX already supports spawning threads and even processes.

Allowing to spawn with just a raw Wasm module is the logical next step.
We definitely want that in WASIX.

Of course if it makes it into WASI we will also want to add support there.

**Comment by pannous** [comment]
Thanks, we will use https://docs.rs/wasix/latest/wasix/fn.proc_spawn.html as intermediate solution!

**Comment by theduke** [comment]
Note that this will not work with a `.wasm` file at the moment!

That is something that needs to be implemented.
