### ISSUE TITLE
Interrupt Running Instances

### ISSUE THREAD

**Issue by theduke** [wasmerio/wasmer#3421]
### Motivation

There are situations where actively interrupting a running instance is necessary.

The `Metering` middleware does allow the configuration of a static cost limit, but it does not allow actively changing the remaining score during a call into the instance.

### Proposed solution

Implement a variant of the Metering middleware that uses an atomic for the remaining fuel.

There also needs to be a cloneable and shareable (`Sync + Send`) handle that allows changing the remaining fuel during instance execution from a different thread.

**Comment by juchiast** [comment]
> Implement a variant of the Metering middleware that uses an atomic for the remaining fuel.

I think this solution has a high runtime cost, is there any alternative?

**Comment by rockwotj** [comment]
Personally I would like to see a solution where I could configure a time when the VM could be suspended and resumed periodically, the should allow for not having atomics in a hot path and still support this use case if you want to opt in.
