### ISSUE TITLE
create-exe does not work with packages with multiple commands

### ISSUE THREAD

**Issue by fschutt** [wasmerio/wasmer#3425]
When generating an executable from a package with multiple commands, we need to create the exe in a way where we can do:

```
output.exe --command-name command
```

**Comment by fschutt** [comment]
When creating the `output.exe` with `create-exe`, if the package specifies multiple commands, we should be able to generate the executable even if entrypoint doesn’t exist.

**Comment by syrusakbary** [comment]
@fschutt let's use `--command` instead of `--command-name` (we should also change that on the CLI in a backward compatible way)
