### ISSUE TITLE
not implemented: wasi::platform_clock_time_get(wasi::Clockid::ProcessCputimeId, ..)', lib\wasi\src\syscalls\windows.rs:45:13

### ISSUE THREAD

**Issue by koduki** [wasmerio/wasmer#3435]
### Describe the bug

I executed WASM generated from ruby, it works on Linux. But it doesn't work on Windows 11 and wasmer 3.1.0.
I might similar #3384, same WASM doesn't work on Linux and 3.0.2, and it was fixed on linux and 3.1.0. 

```sh
echo "`wasmer -V` | `rustc -V` | `uname -m`"
```

### Steps to reproduce
Same with below.
https://github.com/ruby/ruby.wasm/issues/116

### Expected behavior

Success run.
```
$ wasmer run ./my-ruby-app.wasm -- /src/my_app.rb
Hello
```

### Actual behavior

C:\Users\koduki\git\example-wasm>wasmer run ./my-ruby-app.wasm -- /src/my_app.rb
thread 'main' panicked at 'not implemented: wasi::platform_clock_time_get(wasi::Clockid::ProcessCputimeId, ..)', lib\wasi\src\syscalls\windows.rs:45:13
stack backtrace:
   0:     0x7ff6bcc7d14f - <unknown>
   1:     0x7ff6bcca4a4a - <unknown>
   2:     0x7ff6bcc72729 - <unknown>
   3:     0x7ff6bcc7fc1b - <unknown>
   4:     0x7ff6bcc7f89b - <unknown>
   5:     0x7ff6bcc801c9 - <unknown>
   6:     0x7ff6bcc800cd - <unknown>
   7:     0x7ff6bcc7dd87 - <unknown>
   8:     0x7ff6bcc7fda9 - <unknown>
   9:     0x7ff6bdf1a585 - <unknown>
  10:     0x7ff6bc26f3cc - <unknown>
  11:     0x7ff6bbc20b88 - <unknown>
  12:     0x7ff6bbcae288 - <unknown>
  13:     0x7ff6bbcb9fb8 - <unknown>
  14:     0x7ff6bbd997cd - <unknown>
  15:     0x7ff6bc70e6f2 - <unknown>
  16:     0x7ff6bbd7898b - <unknown>
  17:     0x7ff6bbba467b - <unknown>
  18:      0x15f170c5349 - <unknown>
  19:      0x15f1709061b - <unknown>
  20:      0x15f15d33da5 - <unknown>
  21:      0x15f170fa6b4 - <unknown>
  22:      0x15f170fe33a - <unknown>
  23:     0x7ff6bc70b971 - <unknown>
  24:     0x7ff6bc70b2f8 - <unknown>
  25:     0x7ff6bc70b32c - <unknown>
  26:     0x7ff6bc70e77b - <unknown>
  27:     0x7ff6bc707ce0 - <unknown>
  28:     0x7ff6bbd29ecf - <unknown>
  29:     0x7ff6bbbc278e - <unknown>
  30:     0x7ff6bbbc4c43 - <unknown>
  31:     0x7ff6bbbc20bc - <unknown>
  32:     0x7ff6bbbc7a11 - <unknown>
  33:     0x7ff6bbb4e2fd - <unknown>
  34:     0x7ff6bbb4db57 - <unknown>
  35:     0x7ff6bbb31006 - <unknown>
  36:     0x7ff6bbb3105c - <unknown>
  37:     0x7ff6bcc67ea1 - <unknown>
  38:     0x7ff6bbb31047 - <unknown>
  39:     0x7ff6bdec87e8 - <unknown>
  40:     0x7ff988135550 - BaseThreadInitThunk
  41:     0x7ff9886e485b - RtlUserThreadStart

**Comment by Michael-F-Bryan** [comment]
Thanks for finding this @koduki! This will probably be implemented when #3422 is merged.

CC: @theduke

**Comment by koduki** [comment]
Thank you for your comment! I'm look forward to that merge.

**Comment by theduke** [comment]
Also related, for future reference: #3388
