### ISSUE TITLE
Parallelize running integration tests with rayon

### ISSUE THREAD

**Issue by fschutt** [wasmerio/wasmer#3437]
Right now in #3353 we are running integration tests with a single thread, which is especially slow when running the `create-exe` tests because of compilation. We should run these tests in parallel, however the last time I tried doing that I ran into problems with `static_defs.h` being written to from multiple threads (race condition on disk). We should switch to temp directories when refactoring the create-exe code, then re-enable rayon.

**Comment by Michael-F-Bryan** [comment]
It'll be easier to work on this after #3430 is merged.
