### ISSUE TITLE
[C API] Memory leak

### ISSUE THREAD

**Issue by rt21q8** [wasmerio/wasmer#3438]
### Describe the bug
When whole `wasmer` related cleanup calls are done, not whole memory is released. This scenario can be also observed on slightly modified example files contained in this repository. Details described below. Is this known/expected behavior? 

```sh
$ echo "`wasmer -V` | `rustc -V` | `uname -m`"
wasmer 3.1.0 | rustc 1.63.0 (4b91a6ea7 2022-08-08) | x86_64
```

### Steps to reproduce

1. Go to `lib/c-api/examples`.
2. Put all logic from `main` function into infinite `while` loop for example files like `wasi.c` or `imports-exports.c` or `exports-function.c`.
3. Rebuild modified examples.
4. Run new executables.
5. Observe memory usage for started process in tool like `top`.
### Expected behavior

Memory usage should not keep growing continuously (there is cleanup logic at the end of main/loop - are these all required calls?).
### Actual behavior
Memory keeps growing.

**Comment by ptitSeb** [comment]
I think this has been fixed now, on master, with latest Instance memory leak. Can you check again and see if you still see memory leak?

**Comment by ptitSeb** [comment]
oh, ok. So it's another leak. Thanks for the testing, I'll investigate on this later.

**Comment by EclesioMeloJunior** [comment]
hello! I would like to mention that I've posted this issue https://github.com/wasmerio/wasmer-go/issues/393 on `wasmer-go` repository where I try to explain a memory leak I am facing that may be related to `wasmer-c-api`.
