### ISSUE TITLE
Integration with oss-fuzz fuzzing service

### ISSUE THREAD

**Issue by manunio** [wasmerio/wasmer#3442]
Hi, I would like to help integrate this project into [OSS-Fuzz](https://github.com/google/oss-fuzz).

- As an initial step for integration I have created this PR: https://github.com/google/oss-fuzz/pull/9276, it contains necessary logic from an OSS-Fuzz perspective to integrate wasmer.

- OSS-Fuzz is a free service run by Google that performs continuous fuzzing of important open source projects, you can find more details in our [FAQ](https://google.github.io/oss-fuzz/faq/).

-  If you would like to integrate, the only thing I need is a list of email(s), it must be associated with a google account like gmail ([why?](https://google.github.io/oss-fuzz/faq/#why-do-you-require-a-google-account-for-authentication)). by doing that, the provided email(s) will get access to the data produced by OSS-Fuzz, such as bug reports, coverage reports and more stats.

- Notice the email(s) affiliated with the project will be public in the OSS-Fuzz repo, as they will be part of a configuration file.

**Comment by syrusakbary** [comment]
Hey @manunio , we would love to have Wasmer integrated in OSS-Fuzz.

The emails (Google Account related ones) that we can use are:
* syrus@wasmer.io
* michael@wasmer.io
* felix@wasmer.io
* sebastien@wasmer.io

Let me know if we need to do something else

**Comment by syrusakbary** [comment]
Thanks a lot for doing the integration!
