### ISSUE TITLE
Run untrusted wasm modules

### ISSUE THREAD

**Issue by nanoqsh** [wasmerio/wasmer#3454]
### Summary

Hi! Can I call functions from untrusted modules and ensure they complete in some expected time?

On my system, I want to call a function and give it some amount of time. When the time exceeds the limit, I could kill the current call. This is acceptable if the function exceeds the limit for some small time, but at the same time it will definitely end sometime (including with my help).

### Additional details

I tried to implement my [middleware](https://docs.rs/wasmer/3.1.0/wasmer/trait.ModuleMiddleware.html), but I don't know how to do it reliably and optimally enough so as not to reduce the performance of the module significantly.

I could make some instruction counter, and when the counter exceeds some threshold, call a heavier callback that would measure the time from the start of the call and decide if it's time to kill the current one.

**Comment by Michael-F-Bryan** [comment]
@nanoqsh, you might be able to take inspiration from the [`examples/metering.rs`](https://github.com/wasmerio/wasmer/blob/f67e6beafb94ad983c7a8261d81bc1c26fa1ab7f/examples/metering.rs) example. 

If you've got more questions, feel free to re-open this ticket.
