### ISSUE TITLE
Harmonise the build and test CI workflows

### ISSUE THREAD

**Issue by fschutt** [wasmerio/wasmer#3457]
In order to release a new version, we currently still use the old build.yaml file, which has the same steps as in the test.yaml file, except for the last "release" step, which is missing from test.yaml. The build.yaml is a lot slower than the test.yaml (45 minutes vs 20 minutes).

We should merge them into one workflow and copy the release step to the test.yaml.

**Comment by ptitSeb** [comment]
Targetting 3.2 beta here, not alpha release.

**Comment by theduke** [comment]
We should ensure the same tests are run before a release, so I recommend having a `release.yaml` for building releases, which includes the `test.yaml` workflow and runs it before creating the release.
