### ISSUE TITLE
panic (left != right) left: XMM3,  right: XMM3'

### ISSUE THREAD

**Issue by AurelienFT** [wasmerio/wasmer#3461]
### Describe the bug

I run a simple instance of WASM compiled using singlepass using the following features : 

```rust
    const FEATURES: Features = Features {
        threads: false,
        reference_types: false,
        simd: false,           
        bulk_memory: true,     
        multi_value: false,   
        tail_call: false,      
        module_linking: false, 
        multi_memory: false,   
        memory64: false,      
        exceptions: false,
        relaxed_simd: false,
        extended_const: false,
    };
```

### Steps to reproduce

I'm having an error on a VPS where I have this information about the CPU : 
```
***@***.***:~# cat /proc/cpuinfo
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 6
model           : 13
model name      : QEMU Virtual CPU version 2.5+
stepping        : 3
microcode       : 0x1000065
cpu MHz         : 1996.230
cache size      : 512 KB
physical id     : 0
siblings        : 8
core id         : 0
cpu cores       : 8
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm nopl cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 x2apic popcnt aes xsave rdrand hypervisor lahf_lm cmp_legacy abm 3dnowprefetch ssbd ibpb vmmcall arch_capabilities
bugs            : fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass
bogomips        : 3992.46
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
...
```

### Expected behavior
Run without error

### Actual behavior
```rust
thread '' panicked at 'assertion failed: (left != right)
 left: XMM3,
 right: XMM3', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-compiler-singlepass-3.1.0/src/emitter_x64.rs:1752:40
```

### Additional context
I'm sorry I can't provide source that I'm using as it's part of a big project. I assume it's an error with the CPU architecture but if you can give me details it could be great.

**Comment by ptitSeb** [comment]
It seems you are using the SSE42 only emiter. This emiter is still quite experiemental. What happens here is that an unexpected case of a 3-way that has not been succesfully reduced to a 2-way operators.
I can try to code some workaround, but without an easy way to reproduce it will be tricky.

**Comment by sydhds** [comment]
> It seems you are using the SSE42 only emiter. This emiter is still quite experiemental. What happens here is that an unexpected case of a 3-way that has not been succesfully reduced to a 2-way operators. I can try to code some workaround, but without an easy way to reproduce it will be tricky.

Is this emitter (SSE42) a feature (that can be enabled or disabled)? Can we enable another emitter (one that have not this bug)?

**Comment by ptitSeb** [comment]
You "select" SSE4.2 or AVX in function of you CPU capability. 

In the mean time, I have create a branch with a potential fix: https://github.com/wasmerio/wasmer/pull/3462 if you can try it, that would be great.

**Comment by AurelienFT** [comment]
We will try to test it on our side and tell you if it change anything. Thanks for the fast answers

**Comment by sydhds** [comment]
> You "select" SSE4.2 or AVX in function of you CPU capability.
> 
> In the mean time, I have create a branch with a potential fix: #3462 if you can try it, that would be great.

I've tested it and it fixes our issue! Thanks!

@ptitSeb I see there is another assert in sse_round_fn and the check is not there in avx_round_fn. Is there any reason for this? If not can I provide a patch?

**Comment by ptitSeb** [comment]
I think this ticket can be closed now, right?

**Comment by sydhds** [comment]
> I think this ticket can be closed now, right?

Yes
