### ISSUE TITLE
Introduce a facade to ensure the sys and js APIs are identical

### ISSUE THREAD

**Issue by Michael-F-Bryan** [wasmerio/wasmer#3475]
### Motivation

The top-level `wasmer` crate is usable from both a "normal" OS and the browser. At the moment, we switch between a `pub use crate::js::*` or `pub use crate::sys::*` depending on the presence of the `sys` and `js` feature flags.

This is fine and works great, but at the moment there is nothing enforcing that the `sys` and `js` public APIs are actually identical. We've seen a couple occasions where parts of the API that aren't used so frequently will differ between implementations.

### Proposed solution

The Rust standard library has had to deal with a similar problem - that of exposing one consistent API backed by multiple very different implementations.

How they do this is by having a module structure somewhat like this:

- `sys/`
  - `mod.rs`
  - `linux/mod.rs`
  - `windows/mod.rs`
  - `wasm/mod.rs`
- `fs.rs`

Then your `sys/mod.rs` looks like this:

```rust
// sys/mod.rs

#[cfg_attr(windows, path = "windows/mod.rs")]
#[cfg_attr(unix, path = "unix/mod.rs")]
#[cfg_attr(target_os = "wasm", path = "wasm/mod.rs")]
pub(crate) mod imp;
```

The public facade then wraps types from `std::sys::imp` and defers to them for everything.

```rust
// src/fs/mod.rs

pub struct File(crate::sys::imp::File);

impl Read for File {
  fn read(&mut self, buffer: &mut [u8]) -> Result<usize, std::io::Error> { 
    self.0.read(buffer)
  }
}
```

The benefit of this approach is that the different implementations **must** have an identical API because otherwise they won't type-check. It also lets you put a clean boundary between platform-specific code and everything else, and means you only need to have docs in one place (the public wrappers) rather than copy/pasting the same docs to both implementations.

It'll add a bunch of extra boilerplate, but I think we should do something similar for the `wasmer` crate.

### Alternatives

One alternative would be to enforce API parity using tests. For example, we could copy [`cargo semver-checks`](https://github.com/obi1kenobi/cargo-semver-checks) use the JSON output from `rustdoc` to see what a crate's public API is.

### Additional context

@syrusakbary and I were talking about this because we found that the JS API doesn't give you a way to parse custom sections.

https://github.com/wasmerio/wasmer/blob/aaa23c63a6049ca0e7902db3463101ed63ad35f7/lib/api/src/js/module.rs#L568-L571

**Comment by syrusakbary** [comment]
This is now fixed by #3556
