### ISSUE TITLE
Improve --mapdir ergonomics / Add support for --mount

### ISSUE THREAD

**Issue by fschutt** [wasmerio/wasmer#3476]
It's never clear which way `--mapdir` and `[fs]` sections should map: `guest:host` or `host:guest`? It would be better to enforce it either via typing or via very clearly named structs.

**Comment by ptitSeb** [comment]
`--mapdir` was here for compatibility reason (with `wasmtimes`).
Having a syntax like Docker or linux mount would be much simpler and unambigious.

**Comment by ptitSeb** [comment]
`--mapdir` will need to be still supported but marked as deprecated
