### ISSUE TITLE
Investigate Compiled Module Artifact Reusability Crashes

### ISSUE THREAD

**Issue by theduke** [wasmerio/wasmer#3484]
In Deploy we are encountering crashes (SEGFAULTs) when loading compiled artifacts after updating the `wasmer-wasi` crate, even though no changes were made to the code.

We need to:

* Investigate why and how this happens
* Add validation to ensure invalid artifacts produce an error instead of crashes

### Steps to reproduce

Todo @theduke : find a simple way to reproduce

**Comment by Michael-F-Bryan** [comment]
This should have been fixed by #3693.
