### ISSUE TITLE
Rework filesystem mapping and partial overlap of --mapdir directories

### ISSUE THREAD

**Issue by fschutt** [wasmerio/wasmer#3492]
Currently when mapping directories in WASI with `.map_dir()`, the order of mapping is important, as `/lib/api/blah` could overwrite another mapping. Currently the order of mappings is important, but we should fix this in the next release or at least when we migrate / rework the `[fs]` mapping in the new Manifest format.

Also, duplicated mapping to `/` (root folder) aren't allowed, which makes dependency management impossible if two packages use the same folder name. (for example, having a dependency on python, which maps to `/ -> /usr/bin/python` and a dependency on ruby mapping `/ -> /usr/bin/ruby`). In the end `/ruby.wasm` and `/python.wasm` should both work, the only danger are conflicting file names (should be recognized and rejected when uploading).

**Comment by ptitSeb** [comment]
Related to #3476

**Comment by Michael-F-Bryan** [comment]
This is also related to #3678.

**Comment by syrusakbary** [comment]
Closing this in favor of https://github.com/wasmerio/wasmer/issues/3678
