### ISSUE TITLE
Figure out why adding an Option<Pages> to SerializableModule made compiled binaries fail

### ISSUE THREAD

**Issue by fschutt** [wasmerio/wasmer#3497]
Follow-up for #3496: We need to figure out why this PR fixes the CI failure of binaries compiled with `--object-format serialized`. My personal guess is that because we use `Option<>`, the binary format isn't stable (in difference to `rkyv::ArchivedOption`, which has a `#[repr(u8)]` tag).

**Comment by ptitSeb** [comment]
Actual root cause tracked on #3529, closing this one.
