### ISSUE TITLE
Add caching for PHP modules / compilation artifact caching to wasmer run

### ISSUE THREAD

**Issue by fschutt** [wasmerio/wasmer#3502]
Running PHP in wasm currently causes performance problems, we should merge the changes from @syrusakbary back into the main codebase in order to add compilation artifact caching to wasmer instances, so that wasmer run doesn't have to recompile the entire container from scratch.

**Comment by theduke** [comment]
We already have `wasmer_cache` (`lib/cache`), which is available in the CLI behind the `cache` feature and enabled by default.

The thing Syrus was talking about is using PHP bytecode caching (Zend opcache).
