### ISSUE TITLE
Add test / ability to run wasmer run and wasmer publish inside of wasmer run

### ISSUE THREAD

**Issue by fschutt** [wasmerio/wasmer#3505]
In order to prove that wasmer run can execute itself, we should write a test that `wasmer publish / wasmer run` inside of `wasmer run` works. This would create the ability to create and execute packages entirely on Deploy, without any local installation of wasmer. 

Ideally every subcommand of wasmer should run on the cloud with the `cloudcompiler.wasm` (once the WASIX networking code is sufficiently stabilized).

**Comment by syrusakbary** [comment]
I think `wasmer run` inside of wasmer might be challening. But I'm all in for `wasmer publish` as a new package
