### ISSUE TITLE
Respect main_args from the wasmer.toml file when running commands

### ISSUE THREAD

**Issue by fschutt** [wasmerio/wasmer#3514]
Currently the `wasmer.toml` file has a `main_args` field for setting default arguments for the runner, however those `main_args` are not being respected when actually running the .wasm file (they're not passed in).

Current:

```
wasmer run ciuser/customlambda@0.2.27 customlambda.py 55
```

Goal:

```
wasmer run ciuser/customlambda@0.2.27 55
```

The necessary changes for this are already implemented in https://github.com/wasmerio/wasmer/pull/3464/commits/a3d3550ea841420ca74b59364c3585fb7f42fb31#diff-bc54a1b8f8ed51b1b4d84d6e94de7a3cb3a059311cac846e470dc28f0a136218R141-R146 we just need to port them to master.

**Comment by syrusakbary** [comment]
We need to solve this by adding custom runner configuration into `wasmer.toml`
