### ISSUE TITLE
Segfault with `Memory::grow`/`MemoryView` interaction

### ISSUE THREAD

**Issue by Imberflur** [wasmerio/wasmer#3516]
### Describe the bug

https://docs.rs/wasmer/3.1.0/wasmer/struct.MemoryView.html documents:
> After a memory is grown a view must not be used anymore.

However, it is possible to do this in safe code and instead of producing an error or panicking this results in a segfault. So there is a soundness issue with the interaction of `Memory::grow` and `Memory::view`.

`wasmer v3.1.0 | rustc 1.66.1 (90743e729 2023-01-10) | x86_64`

### Steps to reproduce

```rs
use wasmer::{Memory, MemoryType, Store};

fn main() {
    // The default configuration gives memory plenty of room to grow in-place.
    let tunables = wasmer::BaseTunables {
        static_memory_bound: 4.into(),
        static_memory_offset_guard_size: 1024 * 64 * 4,
        dynamic_memory_offset_guard_size: 1024 * 64 * 4,
    };
    let engine = wasmer::EngineBuilder::headless().engine();

    let mut store = Store::new_with_tunables(engine, tunables);

    let memory = Memory::new(&mut store, MemoryType::new(10, None, false)).unwrap();
    let view = memory.view(&store);
    memory.grow(&mut store, 1024).unwrap();
    view.write_u8(0, 4u8).unwrap();
}
```

```shell
> cargo r
fish: Job 1, 'cargo r' terminated by signal SIGSEGV (Address boundary error)
```

### Expected behavior

One of the following:
* Producing an error, panicking, or aborting.
* An API that statically prevents this, e.g. by having the `Store` borrowed for the lifetime of `MemoryView`.
* An unsafe API.

### Actual behavior

Access to freed memory in safe code. Segfault.

**Comment by Michael-F-Bryan** [comment]
@ptitSeb was this resolved in #3580?
