### ISSUE TITLE
Rust program can not open a file

### ISSUE THREAD

**Issue by Kerollmops** [wasmerio/wasmer#356]
Hello,

It is probably highly related to #297 currently but I prefer posting this issue to track the progression of the "fix".

I am currently testing wasmer, it is an awesome project, it work great with Rust, especially when compiling for the `wasm32-unknown-wasi` target.

However I tried a little program just to display the content of a file and hit a little problem: It is not possible to open a file. Here is the minimum program to reproduce that:

```rust
use std::{fs, io};

fn main() -> io::Result<()> {
    let file = fs::File::open("README.md")?;
    Ok(())
}
```

The error returned [is thrown by the Rust std library](https://github.com/rust-lang/rust/pull/59727/files#diff-4407938b27c53216e4b5afb5fc21ef36R663):

```
Custom { kind: Other, error: StringError("failed to find a preopened file descriptor through which \"xxx\" could be opened") }
```

Thank you for helping :)

**Comment by huangjj27** [comment]
I think I met the same error here. when I use https://github.com/kubkon/rust-wasi-tutorial for test wasi but run the wasm as follow, I get some unexpected result:
```shell
$ wasmer run ./target/wasm32-unknown-wasi/debug/main.wasm in.txt out.txt
"RuntimeError: Instance exited"
```

**Comment by Kerollmops** [comment]
It seems like, in [the rust-wasi-tutorial](https://github.com/kubkon/rust-wasi-tutorial#running) they use `wasmtime` which [can grant access to a directory](https://github.com/CraneStation/wasmtime/blob/07a6ca8f4e1136ecd9f4af8d1f03a01aade60407/src/wasmtime.rs#L77) which the `wasmer` runner doesn't not currently provide.

**Comment by MarkMcCaskey** [comment]
Hi!  Thanks for the bug report,

I've started adding support for pre-opened file descriptors in #343 !

So you're right, it's both easy and a bit tricky.  The idea in #343 was to get a first-pass, unsandboxed working solution up and running and go from there.

Currently I'm running in to some extremely strange bugs when running the libsodium tests (some of them seem to fail for no reason during setup and adding irrelevant modifications to the source code of libsodium makes the tests pass -- so it's a really nasty bug.  That said, we'll use this as an opportunity to keep improving the debugging story with Wasmer and get it all working soon), so we haven't shipped it yet.  I'd like to get this fixed up soon, but unfortunately I won't be able to focus on this immediately.

I'll post updates as I learn/do more in regards to pre-opened FDs!

**Comment by Kerollmops** [comment]
Thank you for working on this issue and for the future updates you will put here!

**Comment by jedisct1** [comment]
What are the failing tests? How did you compile libsodium? What are you getting in the relevant `.log` files?

**Comment by MarkMcCaskey** [comment]
> What are the failing tests? How did you compile libsodium? What are you getting in the relevant `.log` files?

Hi!  Thanks for coming by!

I'm currently under the impression that it's likely to be a subtle bug somewhere in our WASI fs code and that I missed something while debugging.  You bring up a good point though, I didn't verify my set up with wasmtime or any other runtime yet, which seems like a good starting point.

I'm using clang with WASI support that I set up a while ago and using the normal libsodium test harness but modified to run wasmer instead of wasmtime.

24/69 of the minimal tests were passing the last time I ran it, `box_easy` was failing and `box` was passing.  I added a call to `printf` in one of the wrapper functions called by one of the tests (I believe it was `box_easy`) and it worked.

When I get some time to work on this again, I'll be able to write up what I've seen in more detail with better logs.

(I think these logs may have been generated with a version more up to date than what I've pushed to GitHub so far)

[box_easy.log](https://github.com/wasmerio/wasmer/files/3082393/box_easy.log)
[box.log](https://github.com/wasmerio/wasmer/files/3082394/box.log)

**Comment by jedisct1** [comment]
Unfortunately, I'm not familiar enough with your WASI code to make sense of these debugging logs.

But all tests perform the same thing: they write a `<test name>.res` file with the results of the tests, then load `<test name>.exp` which contains the expected output, and compare both.

They don't access any other files as far as I can remember.

**Comment by Kerollmops** [comment]
btw, would it be possible to change this issue label to be "features" instead of "bug" :)

**Comment by MarkMcCaskey** [comment]
Thanks @jedisct1 !  That's good to know, I tested it and verified that it works with wasmtime.

----

Hello, everyone!
I've started to look in to this again and I made a bit of progress... I've found out roughly where things are going wrong but I haven't found out why yet.

This is a section of the log from `box` with some ad-hoc memory inspecting printed on function calls.  Note the `buf_ptr` (103800) and the output with lots of `0x1FFF...`s (these are the 'all the rights' magic values I set)
```
[1555629974.253] wasmer-runtime(:329) wasi::fd_fdstat_get: fd=3, buf_ptr=103800

[1555629974.253] wasmer-runtime(:335) fdstat: Fd { rights: 536870911, rights_inheriting: 536870911, flags: 0, offset: 0, inode: Index { index: 0, generation: 0 } }

[lib/wasi/src/state.rs:337] Ok(__wasi_fdstat_t{fs_filetype:
                       match self.inodes[fd.inode].kind {
                           Kind::File { .. } => __WASI_FILETYPE_REGULAR_FILE,
                           Kind::Dir { .. } => __WASI_FILETYPE_DIRECTORY,
                           Kind::Symlink { .. } =>
                           __WASI_FILETYPE_SYMBOLIC_LINK,
                           _ => __WASI_FILETYPE_UNKNOWN,
                       },
                   fs_flags: fd.flags,
                   fs_rights_base: fd.rights,
                   fs_rights_inheriting: fd.rights_inheriting,}) = Ok(
    __wasi_fdstat_t {
        fs_filetype: 3,
        fs_flags: 0,
        fs_rights_base: 536870911,
        fs_rights_inheriting: 536870911
    }
)
box fdstat filetype: 3, fs_flags: 1, fs_rights_base: 1FFFFFFF, fs_rights_inheriting: 1FFFFFFF
```

Now here's box_easy, note the `buf_ptr` (102616) and the output (mostly zeroes)
```
[1555629577.988] wasmer-runtime(:329) wasi::fd_fdstat_get: fd=3, buf_ptr=102616

[1555629577.989] wasmer-runtime(:335) fdstat: Fd { rights: 536870911, rights_inheriting: 536870911, flags: 0, offset: 0, inode: Index { index: 0, generation: 0 } }

[lib/wasi/src/state.rs:337] Ok(__wasi_fdstat_t{fs_filetype:
                       match self.inodes[fd.inode].kind {
                           Kind::File { .. } => __WASI_FILETYPE_REGULAR_FILE,
                           Kind::Dir { .. } => __WASI_FILETYPE_DIRECTORY,
                           Kind::Symlink { .. } =>
                           __WASI_FILETYPE_SYMBOLIC_LINK,
                           _ => __WASI_FILETYPE_UNKNOWN,
                       },
                   fs_flags: fd.flags,
                   fs_rights_base: fd.rights,
                   fs_rights_inheriting: fd.rights_inheriting,}) = Ok(
    __wasi_fdstat_t {
        fs_filetype: 3,
        fs_flags: 0,
        fs_rights_base: 536870911,
        fs_rights_inheriting: 536870911
    }
)
box_easy fdstat filetype: 255, fs_flags: 0, fs_rights_base: 0, fs_rights_inheriting: 0
```

If we shift `box_easy`'s `buf_ptr` by 16, we get:
```
[1555630185.633] wasmer-runtime(:329) wasi::fd_fdstat_get: fd=3, buf_ptr=102616

[1555630185.633] wasmer-runtime(:335) fdstat: Fd { rights: 536870911, rights_inheriting: 536870911, flags: 0, offset: 0, inode: Index { index: 0, generation: 0 } }

[lib/wasi/src/state.rs:337] Ok(__wasi_fdstat_t{fs_filetype:
                       match self.inodes[fd.inode].kind {
                           Kind::File { .. } => __WASI_FILETYPE_REGULAR_FILE,
                           Kind::Dir { .. } => __WASI_FILETYPE_DIRECTORY,
                           Kind::Symlink { .. } =>
                           __WASI_FILETYPE_SYMBOLIC_LINK,
                           _ => __WASI_FILETYPE_UNKNOWN,
                       },
                   fs_flags: fd.flags,
                   fs_rights_base: fd.rights,
                   fs_rights_inheriting: fd.rights_inheriting,}) = Ok(
    __wasi_fdstat_t {
        fs_filetype: 3,
        fs_flags: 0,
        fs_rights_base: 536870911,
        fs_rights_inheriting: 536870911
    }
)

box_easy fdstat filetype: 3, fs_flags: 1, fs_rights_base: 1FFFFFFF, fs_rights_inheriting: 1FFFFFFF
```
which looks like exactly what we want...

by checking it in the wasi syscall after we write to it, we can see:
```
[lib/wasi/src/syscalls/mod.rs:340] unsafe {
    *(ctx.memory(0).view::<u64>()[(buf_ptr.offset() as usize + 8) /
                                      8].as_ptr() as *const u64)
} = 0
```

That the way we're setting memory just isn't working here 🙀 

Now, I'm not sure why this is, we're constructing a `Cell` in an unsafe block via our `WasmPtr` abstraction and from looking over the source code of `Cell` and `UnsafeCell`, it seems like it should be fine...  I probably won't figure this out today, but I think I'm close!

Feel free to contribute and/or wildly speculate if you all have any ideas about this 🤔

**Comment by MarkMcCaskey** [comment]
Okay, 74/77 of the libsodium tests are passing (all the pre-opened fd stuff works);  I'll be shipping the current implementation tomorrow (it'll take some time to clean up) which has some major limitations, but will work for basic cases and I'll follow up shortly after (hopefully tomorrow) and make it much more robust!

**Comment by Kerollmops** [comment]
Thank you @MarkMcCaskey for your great work :)
