### ISSUE TITLE
Ruby runtime for Wasmer?

### ISSUE THREAD

**Issue by aergonaut** [wasmerio/wasmer#358]
### Summary

I see that there are Python and PHP extensions to enable use of WASM via Wasmer in those languages. Is there a plan to support create a Ruby extension as well?

### Additional details

I am particularly interested in using Wasmer to allow users to upload small scripts that could be compiled to WASM and run in a tightly sandboxed environment. I think being able to run these scripts as WASM through Ruby would be great so I could expose small amounts of functionality from the main app to the scripts while still restricting what resources they have access to.

**Comment by Hywan** [comment]
> Is there a plan to support create a Ruby extension as well?

Should I answer “Hold my beer”?

I don't drink alcohol, but yeah, I'm going to do it :-).

**Comment by aergonaut** [comment]
Awesome! Can't wait 😃

**Comment by TomMarius** [comment]
@cbleser could we implement GC support for WASM as RISC-V extension?

**Comment by Hywan** [comment]
Here it is Sir, https://github.com/wasmerio/ruby-ext-wasm.
