### ISSUE TITLE
README's qjs demo hangs with one CPU at 100%

### ISSUE THREAD

**Issue by jsccast** [wasmerio/wasmer#3588]
### Describe the bug

README's qjs.wasm demo hangs with one CPU at 100%

### Steps to reproduce

On a recent Ubuntu (x64):

```sh
curl https://get.wasmer.io -sSfL | sh
wget https://github.com/wasmerio/wasmer/raw/master/lib/c-api/examples/assets/qjs.wasm
wasmer qjs.wasm
```

Input:
```
console.log("hello");
```

The process hangs with one CPU at 100%.

### Expected behavior

Works as described in the README.

### Actual behavior

Hangs with a CPU at 100%.

**Comment by ptitSeb** [comment]
This will be fixed with the rewrite of the WASI implementation coming with the 3.2

**Comment by theduke** [comment]
@jsccast this is fixed in current master and will be in the next release.

**Comment by theduke** [comment]
Closing , since basic QuickJS execution  is now also covered by a test (in `snapshot.rs`).

Feel free to re-open if you run into any additional issues.
