### ISSUE TITLE
Non-static offset initializer not supported in (data) section

### ISSUE THREAD

**Issue by kanaka** [wasmerio/wasmer#359]
Wasmer (0.3.0) does not seem to support non-static offset initializer code in the data section like `(data (global.get $memoryBase) ...)`. This functionality works fine in wasmtime.

For example:

```
$ RUST_BACKTRACE=1 ~/.wasmer/bin/wasmer run wasm/step0_repl.wasm
thread 'main' panicked at 'invalid global initializer when declaring an imported global', lib/clif-backend/src/module_env.rs:311:25
stack backtrace:
   ...
   5: std::panicking::begin_panic
   6: <wasmer_clif_backend::module_env::ModuleEnv as cranelift_wasm::environ::spec::ModuleEnvironment>::declare_data_initialization
   7: cranelift_wasm::sections_translator::parse_data_section
   8: cranelift_wasm::module_translator::translate_module
   9: wasmer_clif_backend::module_env::ModuleEnv::translate
  10: <wasmer_clif_backend::CraneliftCompiler as wasmer_runtime_core::backend::Compiler>::compile
  11: wasmer_runtime_core::compile_with_config
  12: wasmer_runtime::compile_with_config_with
  13: wasmer::main
  ...
```

If I switch the `(data (global.get $memoryBase) ...)` to a hard-code version `(data (i32.const 0) ...)` then that problem no longer manifests.

**Comment by lachlansneff** [comment]
Oh, didn't realize that was valid wasm now.

**Comment by lachlansneff** [comment]
We're about to start a redesign of the abstraction between the wasmer runtime and the individual backends. It'll be much easier to fix this afterwards.

Thank you for your bug report, should be fixed soon assuming that the refactor doesn't take more than a few days.

**Comment by lachlansneff** [comment]
I've looked into this more and we support global offset initializers when the global is imported. I thought I was following the wasm spec there, but perhaps it allows local global offset initialization as well.

**Comment by syrusakbary** [comment]
In the upcoming Wasmer 1.0, the offset initializer is now fully supported.

Closing the issue
