### ISSUE TITLE
Move wasi-types crate into wasi::types

### ISSUE THREAD

**Issue by fschutt** [wasmerio/wasmer#3596]
It would be better to move the `lib/wasi-types` crate into `lih/wasi` in order to reduce the dependency of `wasi-types` onto the main `wasmer` crate (already fixed in master, but it's not very clean right now). This used to cause circular dependencies with wasmer-js.

See https://github.com/wasmerio/wasmer/pull/3468 (discontinued) for a WIP "proper" fix.

**Comment by ptitSeb** [comment]
We should wait and see how things evolved (for example it might be usefull for bindings).

**Comment by ptitSeb** [comment]
@syrusakbary what are your thoughts about this?

**Comment by syrusakbary** [comment]
Yeah, happy to move wasi-types into wasi (I think it will remove some coupling)

**Comment by theduke** [comment]
It's not necessarily what we want, because there can/will be other consumers that need to work with the same types.

Like the `wasix` crate and the Rust `std` implementation.

At the moment these use their own types, I believe, but it would be preferable to not have duplication there.
