### ISSUE TITLE
Fix Disabled create-exe Integration Tests

### ISSUE THREAD

**Issue by theduke** [wasmerio/wasmer#3615]
During the merge of #3422 some of the create-exe tests were disabled.

We need to determine the cause , fix it and re-enable the tests.

Disabled tests:

* create_exe_works_multi_command_args_handling
* test_cross_compile_python_windows
* create_exe_with_object_input_serialized
* create_exe_serialized_works

@ptitSeb

**Comment by ptitSeb** [comment]
Fixed with #3636
