### ISSUE TITLE
Lack of _start export causes exception

### ISSUE THREAD

**Issue by kanaka** [wasmerio/wasmer#362]
### Describe the bug

wasmer 0.3.0 appears to assume that a wasm module exports a "_start" function. This should either be optional or dropped since (start ...) is already supported and is called before the exported "_start" routine.

### Steps to reproduce

The following wat file:

```
(module
  (memory 256)
  (export "memory" (memory 0))

  (import "wasi_unstable" "fd_write" (func $fd_write (param i32 i32 i32 i32) (result i32)))

  ;; __wasi_ciovec_t struct
  (data (i32.const 0) "\08\00\00\00") ;; buf: pointer to hello string
  (data (i32.const 4) "\0c\00\00\00") ;; buf_len: 12 characters
  ;; string
  (data (i32.const 8) "hello world\n")

  (func $main
    (drop (call $fd_write (i32.const 1) (i32.const 0) (i32.const 1) (i32.const 64)))
  )

  (start $main)
  ;;(export "_start" $main)
)
```

Will result in the following:

```
$ ~/.wasmer/bin/wasmer run wasitests/start.wasm
hello world
"ResolveError: ExportNotFound { name: \"_start\" }"
```

Note that the function specified by (start) is being called and then the exception is thrown. If both (start) and exported "_start" are used (uncomment export above) then the main function is executed twice as follows:

```
$ ~/.wasmer/bin/wasmer run wasitests/start.wasm
hello world
hello world
```

### Expected behavior

wasmer should not require "_start" to be exported since this functionality is already supported by the standard (start) mechanism.

**Comment by syrusakbary** [comment]
Good catch! Thanks for the report

**Comment by kanaka** [comment]
Related issue in lucet: https://github.com/fastly/lucet/issues/129#issuecomment-483915763 Based on discussion there seems like "_start" or something like it is needed (although I've suggested a different less confusing name) but the problem is that wasmer and lucet and throwing an exception when "_start" isn't exported (or is swallowing the exception).

**Comment by bjfish** [comment]
This is also being discussed here: https://github.com/WebAssembly/WASI/issues/19

**Comment by syrusakbary** [comment]
Closing the ticket here in favor of: https://github.com/WebAssembly/WASI/issues/19
:)
