### ISSUE TITLE
WASIX: Align Threads Implementation With Proposed Standard

### ISSUE THREAD

**Issue by theduke** [wasmerio/wasmer#3622]
Align the WASIX threads implementation with the proposed standard: https://github.com/WebAssembly/wasi-threads .

The only relatively minor required change is exposing stack information via globals instead of passing them in the spawn syscall.

**Comment by ptitSeb** [comment]
Needs some check

**Comment by syrusakbary** [comment]
This was fixed by #3774 . Closing

**Comment by theduke** [comment]
No this was not done, we only added support for upstream, we didn't switch WASIX to use the same abi.

**Comment by theduke** [comment]
@john-sharratt was there a reason for keeping the divergence (pointer arg vs return value)?

**Comment by john-sharratt** [comment]
not going to use the same ABI for this while its still under development once its properly standardized it can be reopened
