### ISSUE TITLE
Threads are enabled by default, contradicting the documentation

### ISSUE THREAD

**Issue by TethysSvensson** [wasmerio/wasmer#3645]
### Describe the bug

The [documentation](https://docs.rs/wasmer/3.1.1/wasmer/struct.Features.html#method.threads) on `Features` for v3.1.1 says that `threads` are disabled by default, however that is not the case.

### Steps to reproduce

The following code crashes:

```rust
assert_eq!(wasmer::Features::new().threads, false);
```

### Expected behavior

That the documentation matches the behavior.

**Comment by syrusakbary** [comment]
Good call. We need to fix this on the docs

**Comment by ptitSeb** [comment]
Need to check also the CLI to be able to disable threads.

**Comment by syrusakbary** [comment]
@ptitSeb we should enable them by default now (replicating browsers behavior), so we just need to update the docs
