### ISSUE TITLE
Support SSE 4.1 for the Singlepass compiler

### ISSUE THREAD

**Issue by sidenaio** [wasmerio/wasmer#3652]
Hello, could you add the support of SSE 4.1? A lot of CPU's don't have SSE 4.2 or AVX but their performance is enough to run wasm.

From your site: 

> ...or embed Wasmer into the language of your choice and run WebAssembly everywhere.

It will be more truthful if SSE 4.1 is supported.

**Comment by ptitSeb** [comment]
I have checked and SSE 4.1 should be enough for singlepass. I'll paln to add sse 4.1 support for singlepass.
