### ISSUE TITLE
Investigate New libffi C Dependency

### ISSUE THREAD

**Issue by theduke** [wasmerio/wasmer#3657]
We seem to inadvertently have added a dependency on `libffi` in the CLI.

We should investigate which dependency is the culprit, and then evaluate if this is something we want to allow or not.

**Comment by syrusakbary** [comment]
We probably don't want it / don't need it.

Long ago we use to have it (intentionally, in our repo), but we got rid of it

**Comment by ptitSeb** [comment]
It's part of llvm-sys, wich is used in inkwell. We'll have to wait for llvm-sys to move on this probably.

**Comment by syrusakbary** [comment]
We can probably use the `LLVM_ENABLE_FFI` flag in the llvm builds that we use, to disable libffi and see if things work with that
