### ISSUE TITLE
Engine: Re-add Inherent Methods Moved to NativeEngineExt

### ISSUE THREAD

**Issue by theduke** [wasmerio/wasmer#3673]
We moved some architecture specific methods on `Engine` to `NativeEngineExt`.

This is a breaking change though, since users now need to import the `Ext` trait to invoke   `Engine::new()`.

To not force a `4.0` release, we will re-introduce inherent methods on `Engine`, but mark them as deprecated.

**Comment by ptitSeb** [comment]
Done
