### ISSUE TITLE
`wasmer publish` does not take registry.url into account

### ISSUE THREAD

**Issue by ayys** [wasmerio/wasmer#3708]
### Describe the bug

When calling `wasmer publish` it always defaults to the wapm.io registry, unless a different one is explicitly 
defined via the `--registry` flag. 

### Steps to reproduce
```sh
$ wasmer config set registry.url "https://registry.wapm.dev/graphql"

$ wasmer config get registry.url
https://registry.wapm.dev/graphql

$ wasmer publish # uses the wapm.io registry
```

### Expected behavior

wasmer publish should use the registry specified in `wasmer config get registry.url`

### Actual behavior

It always defaults to wapm.io

### Additional context

```bash
$ wasmer -vV
wasmer 3.2.0-alpha.1 (45cb9 2023-01-25)
binary: wasmer-cli
commit-hash: 45cb95c1a83124ea98a0a75e9701962c10d7d7f5
commit-date: 2023-01-25
host: aarch64-apple-darwin
compiler: singlepass,cranelift
```

**Comment by Michael-F-Bryan** [comment]
I believe this was fixed in #4013.
