### ISSUE TITLE
JS runtime with support for web workers

### ISSUE THREAD

**Issue by john-sharratt** [wasmerio/wasmer#3714]
We should migrate and refactor the runtime in wasmer-web over to the wasmer repo so that it can be used by anyone and so that a regression test suite for the snapshots can be implemented.

When we do so we should also refactor this method
https://github.com/wasmerio/wasmer/pull/3710/files/4958ad4af9b74965d05511da6e681b3700bc93d1#diff-448c9592ede4a9270ff1c58d163143f3a4dd5071e9d5c57dbd35b8e8eb7ea580

**Comment by theduke** [comment]
This is now available in https://github.com/wasmerio/wasmer-js
