### ISSUE TITLE
Yes DELPHI  (pascal) / EMBARCADERO is missing ?

### ISSUE THREAD

**Issue by KITVIEWFR** [wasmerio/wasmer#3720]
Thanks for proposing a new feature!

### Motivation

A clear and concise description of what the motivation for the new feature is, and what problem it is solving.

### Proposed solution

A clear and concise description of the feature you would like to add, and how it solves the motivating problem.

### Alternatives

A clear and concise description of any alternative solutions or features you've considered, and why you're proposed solution is better.

**Comment by Michael-F-Bryan** [comment]
@KITVIEWFR can you update your ticket to fill in the issue template?
