### ISSUE TITLE
Rename unsafe Artifact deserialize functions

### ISSUE THREAD

**Issue by theduke** [wasmerio/wasmer#3727]
The unsafe methods and functions for deserializing rkyv serialized artifacts should be renamed to more clearly express their dangerous nature, especially since we added `deserialize_checked` methods recently.

Preferred name: `dangerous_deserialize_unchecked()`.

See https://github.com/wasmerio/wasmer/pull/3693 for related discussion.

**Comment by Michael-F-Bryan** [comment]
We agreed to make this change when we do the next breaking change.

**Comment by theduke** [comment]
Also need to make the checked functions unsafe again, because loading executable code is inherently unsafe.
