### ISSUE TITLE
default-singlepass and other features mentioned in docs, but inexistant

### ISSUE THREAD

**Issue by Razican** [wasmerio/wasmer#3728]
In the official documentation, some features such as `default-singlepass` are mentioned, but if enabled via cargo, it complains that they don't exist.

Here the link to the documentation: https://wasmerio.github.io/wasmer/crates/doc/wasmer/#features-for-the-sys-feature-group-enabled

**Comment by syrusakbary** [comment]
This is fixed in `3.2.1`
