### ISSUE TITLE
Package with dependencies fails to run

### ISSUE THREAD

**Issue by syrusakbary** [wasmerio/wasmer#3748]
This:

```
wasmer run https://wapm.dev/wasmer/wasmer-io
```

Should work (the package has a dependency with commands).
But it currently fails:

```
error: Cannot run wasmer/wasmer-io@0.2.0: package has no commands
```

**Comment by theduke** [comment]
This is currently only implemented in `wasix`, which will fall back to dependencies to discover the default command.

We can add that logic to the runner resolution, but  we should also add an explicit syntax for defering commands to a dependency - I'm not a huge fan of the auto fallback.
