### ISSUE TITLE
RuntimeError: call stack exhausted

### ISSUE THREAD

**Issue by hungryzzz** [wasmerio/wasmer#3760]
### Summary

When I use Wasmer to run a case which contains some recursive function calls, Wasmer will raise **_RuntimeError: call stack exhausted_**. The original Cpp program can run successfully. 

Can I adjust the call stack size of Wasmer to address this problem?

Thank you!

### Additional details

**wasmer version:** wasmer 3.2.0-alpha.1

**emscripten version:** 
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.24 (68a9f990429e0bcfb63b1cde68bad792554350a5)
clang version 16.0.0 (https://github.com/llvm/llvm-project 277c382760bf9575cfa2eac73d5ad1db91466d3f)
Target: wasm32-unknown-emscripten
Thread model: posix

**emscripten compile cmd:**
`emcc -sENVIRONMENT=shell -O2 -s TOTAL_MEMORY=1024MB -s WASM=1 ackermann.cpp -o ackermann.wasm`

[case.zip](https://github.com/wasmerio/wasmer/files/11185871/case.zip)

**Comment by Michael-F-Bryan** [comment]
@hungryzzz the stack size isn't configurable through Wasmer. This "call stack exhausted" may be because emscripten decides the stack size and the default size is quite small. Try passing something like `-s TOTAL_STACK=2MB` to `emcc` to modify this behaviour.

**Comment by hungryzzz** [comment]
@Michael-F-Bryan Hi, I've compiled with the option `-s TOTAL_STACK=2MB`, but Wasmer still raises the same runtime error.
I am wondering that, when Wasmer runs a wasm case, what is the default size of the execution stack space allocated to the case?

**Comment by theduke** [comment]
You should increase the stack size, because `5MB` is the default used by emscripten.

**Comment by hungryzzz** [comment]
@theduke Thank you, I've tried it under `50MB` but it still failed in Wamser.

**Comment by ptitSeb** [comment]
Can you run the program under a debugger to see if you have a segfault, and what would be the native backtrace when it occurs.?

**Comment by ptitSeb** [comment]
Fixed on master. use the `--stack-size` parameter to set a bigger stack
