### ISSUE TITLE
Implement `NativeWasmTypeInto` for `u32` and `u64` with the `js` feature.

### ISSUE THREAD

**Issue by kajacx** [wasmerio/wasmer#3762]
### Motivation

When using wasmer on the web (wasmer itself is compiled to WASM and then loads another WASM module) with the `js` feature, you cannot pass `u32` and `u64` as arguments from / to functions, because those types do not implement `NativeWasmTypeInto`.

### Proposed solution

Implement `NativeWasmTypeInto` for `u32` and `u64`.

### Alternatives

You can, of course, cast your unsigned integers to signed integers, but it is kind of annoying. Example:

```rust
// Plugin:
#[no_mangle]
pub fn add_ten(value: u32) -> u32 {
    value + 10
}

// Host, current workaround:
let mut value: u32 = 50;
let add_ten = instance
    .exports
    .get_typed_function::<i32, i32>(&store, "add_ten")
    .unwrap();
value = take_u32.call(&mut store, value as i32).unwrap() as u32;

// Host, with proposed change:
let mut value: u32 = 50;
let add_ten = instance
    .exports
    .get_typed_function::<u32, u32>(&store, "add_ten")
    .unwrap();
value = take_u32.call(&mut store, value).unwrap();
```

### Additional context

Not sure if implementing `NativeWasmTypeInto` for `u8` / `u16` / `i8` / `i16` makes sense in the same way, but that can be another feature request.

**Comment by syrusakbary** [comment]
That sounds good to me. Do you want to work on a PR @kajacx ?
