### ISSUE TITLE
Why nginx.wasm can't not be runned by wasmtime

### ISSUE THREAD

**Issue by huangjj27** [wasmerio/wasmer#377]
### Summary

I'm comparing wasmtime and wasmer, and found that the nginx.wasm example provided here can't not be run by wasmtime:
```
~/wasmer/examples/nginx$ sudo wasmtime nginx.wasm -- -p . -c nginx.conf
error while processing main module nginx.wasm: Instantiation error: Link error: env/enlargeMemory: no provided import function
```

Is it because that nginx.wasm is not WASI compatible ?

**Comment by losfair** [comment]
The nginx.wasm example is compiled against the Emscripten host API, which I think is not supported by wasmtime.

**Comment by huangjj27** [comment]
@losfair thanks!
