### ISSUE TITLE
failed to install v3.2.0 on macOS

### ISSUE THREAD

**Issue by hetian9288** [wasmerio/wasmer#3792]
### Describe the bug

Error occurred when installing Wasmer for the first time.
```
dyld: Symbol not found: __ZTTNSt3__119basic_ostringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE
  Referenced from: /Users/-----/.wasmer/bin/wasmer
  Expected in: /usr/lib/libc++.1.dylib
 in /Users/-----/.wasmer/bin/wasmer
```

### My system environment.
macos 11.7.6
llvm 16.0.1

**Comment by ptitSeb** [comment]
Currently, wasmer is built with llvm 14
Also, is that x86_64 or aarch64 macOS?

**Comment by hetian9288** [comment]
> 目前，wasmer是用llvm 14构建的，另外，那是x86_64还是aarch64 macOS？

x86_64

**Comment by hetian9288** [comment]
are there any methods to solve this problem?

**Comment by ptitSeb** [comment]
I don't reproduce the issue on my side. Do you know what executable is missing that symbol @hetian9288 ?

**Comment by hetian9288** [comment]
Just now I tried to install using the brew method and everything went smoothly.
