### ISSUE TITLE
Backends that haven't been compiled in shouldn't be listed

### ISSUE THREAD

**Issue by jedisct1** [wasmerio/wasmer#380]
`Backend::variants()` currently returns a static set of backends.

Which is quite confusing. The `wasmer run` help command always prints:

```text
OPTIONS:
        --backend <backend>                   [default: cranelift]  [possible values: singlepass, cranelift, llvm]
```

Even if neither `singlepass` nor `llvm` have been compiled in.

**Comment by lachlansneff** [comment]
Oh, good idea.
