### ISSUE TITLE
get.wasmer.io has an invalid certificate

### ISSUE THREAD

**Issue by jahands** [wasmerio/wasmer#3811]
### Describe the bug

Installing with `curl https://get.wasmer.io -sSfL | sh` fails because get.wasmer.io has an invalid certificate:
```shell
$ curl https://get.wasmer.io
curl: (60) SSL: no alternative certificate subject name matches target host name 'get.wasmer.io'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

### Steps to reproduce
Run `curl https://get.wasmer.io` or visit https://get.wasmer.io/ in a browser

### Expected behavior
It serves an install script

### Actual behavior
Certificate error

**Comment by syrusakbary** [comment]
Thanks for the ping. We are looking into it and will work on a fix asap

**Comment by syrusakbary** [comment]
This is now fixed. Apologizes for any issues this might have caused. Closing the issue
