### ISSUE TITLE
Wasmer stdout is not good

### ISSUE THREAD

**Issue by syrusakbary** [wasmerio/wasmer#3814]
Try to run spidermonkey js.wasm: https://firefoxci.taskcluster-artifacts.net/Wl0gB9DqTUOyBSenX32lXg/0/public/build/js.wasm

```
$ wasmer run js.wasm
1+1 // <---- This is what you input in the shell, and you press enter
js> 2
```

It should be:

```
$ wasmer run js.wasm
js> 1+1 // <---- This is what you input in the shell, and you press enter
2
js> 
```

**Comment by syrusakbary** [comment]
You can check with other runtimes how it actually runs properly

**Comment by ktock** [comment]
Maybe related to https://github.com/wasmerio/wasmer/issues/3790 ?

**Comment by syrusakbary** [comment]
Probably!
