### ISSUE TITLE
experimental-io-devices no longer builds

### ISSUE THREAD

**Issue by AfflatusX** [wasmerio/wasmer#3817]
### Describe the bug

Enabling feature experimental-io-devices causes build failure.

### Steps to reproduce

```sh
cargo build  --release --manifest-path lib/cli/Cargo.toml --features cranelift,singlepass,wasmer-artifact-create,static-artifact-create,wasmer-artifact-load,static-artifact-load --features="webc_runner,experimental-io-devices" --bin wasmer
```

### Expected behavior

Build should succeed

### Actual behavior

Multiple errors related to out-dated use statements and trait implementations

### Additional context
I found this project through the article mentioning adding fs based framebuffer solution to WASi - which is really cool. Unfortunately, looks like since https://github.com/wasmerio/wasmer/issues/2863 this feature has been un-maintained. I tried to build wasmer with the feature turned on but there are multiple issues preventing it from building.

Looks like FrameBuffer which implements VirtualFile now needs to implement Aysnc Read/Write/Seek - but it's still implementing the synchronous version right now.

If the feature is no longer maintained/supported, maybe we should just remove it. Otherwise we should keep it updated - even as an optional feature.

**Comment by ptitSeb** [comment]
Yes, I reproduce the issue.
Fixing it requires porting the current crate to async reading. It's quite a big task, so no defenitive planning date has been set

**Comment by theduke** [comment]
experimental-io-devices is no longer supported and removed from the codebase.
