### ISSUE TITLE
Broken docs.rs for more crates

### ISSUE THREAD

**Issue by Michael-F-Bryan** [wasmerio/wasmer#3826]
### Describe the bug

It looks like #3791 didn't fix the docs for all our crates. 

For version 3.2.1, the following packages don't build on docs.rs:

- [`wasmer-cache`](https://docs.rs/crate/wasmer-cache/3.2.1/builds)
- [`wasmer-wasix-types`](https://docs.rs/crate/wasmer-wasix-types/0.3.1/builds)
- [`wasmer-emscripten`](https://docs.rs/crate/wasmer-emscripten/3.2.1/builds)
- [`wai-bindgen-wasmer`](https://docs.rs/crate/wai-bindgen-wasmer/0.3.1/builds)

### Additional context

This is the same issue as #3787.

A fix was proposed in #3819, but because that uses a script which tries to emulate docs.rs rather than using docs.rs itself, it's missed a bunch of broken crates.

**Comment by ptitSeb** [comment]
Should be ok now, as there is a comprehensive test on the CI.
To be checked and closed after the 3.3 release
