### ISSUE TITLE
README: Slack link is flagged as unsafe by Chrome

### ISSUE THREAD

**Issue by achille-roussel** [wasmerio/wasmer#3835]
### Describe the bug

![image](https://user-images.githubusercontent.com/865510/235528327-b348dde2-acd7-4830-97d9-a81148330fd3.png)

### Steps to reproduce

Click the "Join Slack" link from the README.

### Expected behavior

A would expect to not be prompted with the risk to access an unsafe web site.

### Actual behavior

Chrome flags https://slack.wasmer.io as unsecure.

**Comment by syrusakbary** [comment]
We switched to Discord, and updated the links. Closing the issue
