### ISSUE TITLE
Refactor WASI globals logic

### ISSUE THREAD

**Issue by syrusakbary** [wasmerio/wasmer#3840]
As of the release of Wasmer 3.3 with JavascriptCore there are some issues with WASIX (related to globals).

That's ok for now since they are only caused when using special systemcalls that are not part of wasi. But it will be not ok when we release WASIX.
We need to move the globals logic from the store to the wasi crate, as a way to simplify the codebase and fix the issues

**Comment by syrusakbary** [comment]
Related: #3602

**Comment by ptitSeb** [comment]
Stretch goal.
