### ISSUE TITLE
Unexpected behavior related to a wrong alignment value

### ISSUE THREAD

**Issue by erxiaozhou** [wasmerio/wasmer#3846]
### Steps to reproduce
wasmer version:  5cab85f85fb8b1debdec2dbeeb56e4f354a747fc
```
make build-wasmer
target/debug/wasmer <test_case> -i to_test
```
[wasmer_alignment_to_check.zip](https://github.com/wasmerio/wasmer/files/11396864/wasmer_alignment_to_check.zip)

### Expected behavior
An exception indicates that "alignment must not be larger than natural"

### Actual behavior
The execution is not aborted.

**Comment by ptitSeb** [comment]
Mmm, ok, I can a test for that. I assume you are refering to the alignments rules from https://github.com/WebAssembly/design/blob/main/BinaryEncoding.md#memory-related-operators-described-here with that sentence `As an additional validation criteria, the alignment must be less or equal to natural alignment`
