### ISSUE TITLE
WASIX's file-based module cache will block the runtime thread

### ISSUE THREAD

**Issue by Michael-F-Bryan** [wasmerio/wasmer#3851]
### Describe the bug

The fs-based cache WASIX uses for compiled modules is called from `async` code, but uses synchronous IO for reading the file and deserializing. This happens in both the current version ([here](https://github.com/wasmerio/wasmer/blob/5cab85f85fb8b1debdec2dbeeb56e4f354a747fc/lib/wasi/src/bin_factory/module_cache.rs#L111) and [here](https://github.com/wasmerio/wasmer/blob/5cab85f85fb8b1debdec2dbeeb56e4f354a747fc/lib/wasi/src/bin_factory/module_cache.rs#L167-L171)) and the version introduced in #3841 ([here](https://github.com/wasmerio/wasmer/blob/e633eb3e52f0b5a8f27c726ee1ffd52f0070bf7f/lib/wasi/src/runtime/module_cache/filesystem.rs#L117-L152)).

We need to tweak the new `FileSystemCache` implementation to either use the `tokio::fs` module (typing the `FileSystemCache` to a tokio runtime) or make the `FileSystemCache` accept an `Arc<dyn VirtualTaskManager>` parameter in its constructor and do the blocking IO via `spawn_blocking()`.

**Comment by maminrayej** [comment]
Resolved by #4345.
