### ISSUE TITLE
Change Cache::load to be safe

### ISSUE THREAD

**Issue by theduke** [wasmerio/wasmer#3857]
Currently the `Cache::load` trait method is unsafe.

Since we recently introduced checked/safe artifact deserialization , which is a much saner default, we should also switch the method to be safe.

Users really wanting to use unsafe deserialization can do their own implementation.

NOTE: this is a breaking change.

See also #3856  and #3855 .

NOTE: this also relates to @Michael-F-Bryan work on new caching primitives.

**Comment by ptitSeb** [comment]
Cache load is always unsafe (by nature)
