### ISSUE TITLE
Supporting output array parameters for wasm functions

### ISSUE THREAD

**Issue by hrydgard** [wasmerio/wasmer#387]
Let's say I want to call the following function in a wasm module from the outside: 

```void mix_audio(float *samples, size_t num_samples);```

The function mix_audio inside the wasm module should write num_samples worth of audio data to the samples array owned by the caller. Of course, the reason why it's currently not possible to do this is that if you pass in a host pointer, it's intentionally inaccessible to the wasm module. 

But what if the caller could first allocate memory inside the wasm module, and then pass in the offset as a pointer parameter (and after the call to ```mix_audio```, later read out the contents)? One way might be for the caller to call any malloc and free functions exposed by the wasm module (this would of course depend on the language runtime running inside), but perhaps neater would be to be able for the caller to either allocate from the wasm module's stack, or simply to allocate blank pages from the wasm module's memory space (that would somehow otherwise not be visible to the memory allocator running inside the wasm module).

Does this seem reasonable?

**Comment by autodidaddict** [comment]
There are a number of different projects all working on various RPC-like implementations that allow you to pass more complex information across the Wasm/host barrier. 

For example, https://waxosuit.io is a Rust host runtime that uses wasmer to securely pass Protobuf messages into guest modules and allow guest modules to make host function calls, also passing protobuf messages as the function call parameters.

The WebAssembly standard itself, at least the current v1.0, can't be changed to allow multiple output parameters, and you definitely don't want to find ways to violate the memory security

**Comment by Hywan** [comment]
Hello,

There is nothing special to handle that. `samples` is a regular pointer, it's up to your code to manipulate this pointer accordingly.

I'm closing this issue since there is nothing specifically to do :-).
