### ISSUE TITLE
How do I allocate a buffer inside wasm module's heap memory?

### ISSUE THREAD

**Issue by ashenoyxyz** [wasmerio/wasmer#3876]
Hi -

I'm evaluating wasm runtimes for a project I am working on. I have read through the documentation available and it is not very clear to me whether it's possible to allocate a buffer inside the wasm module's heap memory and pass the corresponding address to the exported function within the wasm module. Although it's possible to export `malloc()` within the wasm module to achieve this, I'm try to avoid the additional overhead on the developers.

In comparison, [WebAssembly Micro Runtime](https://github.com/bytecodealliance/wasm-micro-runtime) already supports this capability through the **wasm_runtime_module_malloc()** API.

**Comment by kajacx** [comment]
You could try [wai bindgen](https://wasmerio.github.io/wasmer-pack/user-docs/concepts/wai/index.html#wai-bindgen), it has the ability to pass complex types between host and plugin, and does the "dirty work" of allocating memory for you.

However, I did not find any good tutorials or examples on how to use it, so you can try looking at this [minimal example](https://github.com/kajacx/wasm-playground/tree/wai-bindgen-simple-example) instead.

Alternatively, you can export "malloc", as you said. I'm not sure how wasm_runtime_module_malloc works, or if it could work with C# as the guest language for example.
