### ISSUE TITLE
Rename WasiRuntime

### ISSUE THREAD

**Issue by syrusakbary** [wasmerio/wasmer#3880]
Currently `WasiRuntime` holds a lot of information on how to run a package.
For example, Runners will take a `&impl WasiRuntime` in the `run_command` function (as in PR #3852). But this will make little sense on a EmscriptenRunner.

A simple way to resolve this would be to rename `WasiRuntime` to `RuntimeContext` ? (or other names)

**Comment by theduke** [comment]
~~Wasi~~Runtime is fine with me.

**Comment by ptitSeb** [comment]
so "Runtime"
