### ISSUE TITLE
mmap Support for Artifacts / deserialized Modules

### ISSUE THREAD

**Issue by theduke** [wasmerio/wasmer#3882]
Serialized module artifacts can currently only be used through deserialization, which means the embedded data has to be copied. 

We want have the ability to use module artifacts from an `mmap` backed buffer to make memory management easier.

`rkyv`, the serialization library we use, also provides a zero-copy mode via the `archive` feature.
See: https://rkyv.org/architecture/archive.html 

To make this possible, we need to change `Module` to optionally contain an Artifact backed by `ArchivedSerializableModule` instead of `SerializableModule`. 

Note: the `ArchviedXXX` types are generated by the rkyv derive macros.

This may requiring hiding all the access to different data elements behind accessor methods.

cc @john-sharratt

**Comment by Michael-F-Bryan** [comment]
I abstracted the "mmap-or-in-memory-bytes" type from the `webc` crate into [`shared-buffer`](https://lib.rs/shared-buffer).

One thought @john-sharratt and I had was to modify the deserialize method from `fn(&[u8]) -> Result<Artifact, Error>` to `fn(impl TryInto<shared_buffer::OwnedBuffer>) -> Result<Artifact, Error>` and reuse the buffer types from `shared-buffer`. That should let us keep things in memory-mapped files without breaking too much downstream code.

**Comment by theduke** [comment]
The buffer is the easy part.

The hard part is figuring out how we deal with `SerializableModule` vs `ArchivedSerializableModule`.
