### ISSUE TITLE
Fix Incredibly Slow write Implementation of TmpFs In-Memory Files

### ISSUE THREAD

**Issue by theduke** [wasmerio/wasmer#3903]
Currently writing to somewhere else than the end of a file always allocates a new buffer  in the mem fs.
That will have ... horrible performance.

Need to fix this.

This is bad enough to call it a bug.

https://github.com/wasmerio/wasmer/blob/458330edc6c62fa1d0fdc53084b319d27aade855/lib/virtual-fs/src/mem_fs/file.rs#L1323-L1327

**Comment by ptitSeb** [comment]
Stretch goal
