### ISSUE TITLE
get.wasmer.io down ? Server error 500

### ISSUE THREAD

**Issue by theagilecoder** [wasmerio/wasmer#3909]
### Summary

Installtion URL https://get.wasmer.io/ seems to be down. Server error 500. See attached pic.

### Additional details

Server error 500. See attached pic.

![image](https://github.com/wasmerio/wasmer/assets/5019222/5716441c-1347-425d-9d41-eb57bb829548)

**Comment by theduke** [comment]
This should be resolved.

Please let us know if it's still not working for you!

**Comment by AdamJSoftware** [comment]
still having issues

**Comment by theduke** [comment]
@AdamJSoftware @theagilecoder 

Things should be stable now, how are things for you?

**Comment by AdamJSoftware** [comment]
lgtm
