### ISSUE TITLE
Re-bindable imports object

### ISSUE THREAD

**Issue by kajacx** [wasmerio/wasmer#3915]
### Motivation

Currently, when creating a new `Instance`, an `Imports` object must be passed and is "binded" to that instance for the entirety of the instance's life.

This is limiting, because you cannot "re-bind" a different Imports object to the same instance while preserving the instance's state.

### Proposed solution

Add an intermediate step which would represent a stateful instance, but without an imports object, for example a `StatefulModule` struct.

Then, add a function that would create this `StatefulModule` from store and module, a function which would bind imports to get an Instance and also a function that would unbind the imports object from the Instance to get back this StatefulModule. Example:

```rust
impl StatefulModule {
    pub fn new(
       store: &mut impl AsStoreMut,
       module: &Module,
    ) -> Result<StatefulModule, InstantiationError> { ... }
}

impl Instance {
    // preserve existing new method
    pub fn new(
        store: &mut impl AsStoreMut,
        module: &Module,
        imports: &Imports,
    ) -> Result<Self, InstantiationError> { 
        // but change body
        Self::from_stateful(store, StatefulModule::new(store)?, imports)
    }
    
    // maybe name it: bind_imports ?
    pub fn from_stateful(
        store: &mut impl AsStoreMut,
        stateful_module: StatefulMedule, // take ownership
        imports: &Imports,
    ) -> Result<Self, InstantiationError> { ... }
    
    // maybe name it: unbind_imports ?
    pub fn into_stateful(self) -> StatefulMedule { ... } // returns owenrship
    
}
```

### Alternatives

I guess it is possible to serialize and deserialize the instance (I have never done it, but I assume you can define a different imports object when re-serializing). But that is a complete overkill. Changing the imports objects could be easily done while the module (including it's state) stays loaded in memory.

### Additional context

Alternatively, you could just change the imports object on an existing Instance to get similar behavior, like so:
```rust
impl Instance {
    pub fn set_imports(
        &mut self,
        store: &mut impl AsStoreMut,
        imports: &Imports,
    ) -> Result<(), InstantiationError> { ... }
}
```

But this is sub-optimal in cases where the Instance needs to live longer than the Imports object. Currently, the Imports object must be `'static`, so I have opened a feature request for that here: https://github.com/wasmerio/wasmer/issues/3916, which shows a full picture of these 2 feature requests working together,

**Comment by ptitSeb** [comment]
This seems like a "won't fix" ticket. @syrusakbary will follow up.

**Comment by kajacx** [comment]
> This seems like a "won't fix" ticket. @syrusakbary will follow up.

It's a little bit sad, but I understand this would be a non-trivial architectural change. There are other ways to change the imported function's behaviour, like putting a `Arc<Mutex<Box<dyn FnMut() -> ()>>>` into the imported function, and then changing that, so this issue is not super important.
