### ISSUE TITLE
llvm compiler on aarch64

### ISSUE THREAD

**Issue by y-ykcir** [wasmerio/wasmer#3939]
### Summary

Can aarch64 GNU/Linux support llvm compiler?

### Additional details

I installed wasmer with `curl https://get.wasmer.io -sSfL | sh` on Raspberry Pi 4 and encountered an error while using llvm
```
ricky@raspberrypi:~ $ wasmer compile --llvm -o 2mm.wasmu 2mm.wasm
error: failed to compile `2mm.wasm`
╰─▶ 1: The `llvm` compiler is not included in this binary.
```

**Comment by ptitSeb** [comment]
Yes, for now, Aarch64 build of Wasmer from the CI doesn't include LLVM.

**Comment by y-ykcir** [comment]
Okay, thank you for your reply, so can I compile wasm using llvm on other Linux platforms and run it on aarch?

**Comment by ptitSeb** [comment]
Yes you can, it's just a CI issue, you can build wasmer with llvm for linux/aarch64.

**Comment by y-ykcir** [comment]
thx
