### ISSUE TITLE
`wasmer login` does not respect the registry.url config

### ISSUE THREAD

**Issue by ayys** [wasmerio/wasmer#3959]
### Describe the bug

When running `wasmer login`, I always get the wapm.io settings page URL, even when I have changed the registry.

```sh
$ wasmer -vV; rustc -vV

wasmer 4.0.0-beta.1 (b45f9a5 2023-06-01)
binary: wasmer-cli
commit-hash: b45f9a51845ed3ea55b61ef8774f7410ac4904f9
commit-date: 2023-06-01
host: aarch64-apple-darwin
compiler: singlepass,cranelift
rustc 1.70.0 (90c541806 2023-05-31)
binary: rustc
commit-hash: 90c541806f23a127002de5b4038be731ba1458ca
commit-date: 2023-05-31
host: aarch64-apple-darwin
release: 1.70.0
LLVM version: 16.0.2
```

### Steps to reproduce

```sh
$ wasmer config get registry.url
https://registry.wasmer.wtf/graphql

$ wasmer login
Please paste the login token from https://wapm.io/settings/access-tokens:
```

### Expected behavior
I expect the URL in wasmer-login to be `https://wasmer.wtf/settings/access-tokens`

### Actual behavior

I get the URL to wapm.io.

I think https://github.com/wasmerio/wasmer/blob/master/lib/cli/src/commands/login.rs#LL10C1-L10C45 this could be the reason for this.

**Comment by Michael-F-Bryan** [comment]
I suspect this has the same root cause as #3708.
