### ISSUE TITLE
1 second delay when starting `wasmer run`

### ISSUE THREAD

**Issue by Michael-F-Bryan** [wasmerio/wasmer#3962]
### Motivation

Every time we run `wasmer run`, there seems to be a 500-1000ms delay before the WASI instance starts.

I believe this is because of the `wasmer_wasix::runtime::resolver::WapmSource` querying WAPM every time, but I'll double-check the logs.

### Proposed solution

The best way to avoid hitting the WAPM backend every time we start up is to cache the result of queries that have been made in the past. This could either be the original GraphQL queries or the more high-level *"which versions satisfy `some/package@^1.0`?"*

### Additional context

This delay is causing a fair amount of flakiness in Wasmer's CI because the [`run_test_caching_works_for_packages_with_versions`](https://github.com/wasmerio/wasmer/blob/e85be593f8bb9f21552e5d81be1602ae079158dd/tests/integration/cli/tests/run.rs#L479-L513) test relies on measuring a command's run time to infer whether we hit the cache or not.

**Comment by theduke** [comment]
I'd cache the result of package resolution, AKA a lockfile. 

We need a somewhat stable format for this anyway, so might as well define that now.
