### ISSUE TITLE
Wasmer 3.3. JS panics with `Option::unwrap()` on chrome/chromium

### ISSUE THREAD

**Issue by kobyhallx** [wasmerio/wasmer#3973]
### Describe the bug

Wasmer 3.3. JS panics with 

`Option::unwrap() on a None value, wasmer/lib/api/src/js/module.rs:79:63` 

RuntimeError from `Module::new` on Chromium browsers.

### Steps to reproduce

Call `Module::new` in Rust code which is then compiled with `wasm-bindgen`

### Expected behavior

Returns new module normally.

### Actual behavior

Panics as per description.

### Additional context
at [5eeda45](https://github.com/wasmerio/wasmer/commit/5eeda455a4c3928cfc13760e3515020543d4cd58) Release [3.3.0](https://github.com/wasmerio/wasmer/tree/v3.3.0) (#3842)

**Comment by ptitSeb** [comment]
@syrusakbary can you have a look at this issue?
