### ISSUE TITLE
Out dated wamser-wasi-types on crates.io

### ISSUE THREAD

**Issue by kvinwang** [wasmerio/wasmer#3979]
We are using `wamser-wasi-types` along with `Wasmer`. I got an error when I tried to update Wamser to 3.3:
```
error: failed to select a version for `wasmer-derive`.
    ... required by package `wasmer-wasi-types v3.1.0`
versions that meet the requirements `=3.1.0` are: 3.1.0
```

This is because version `3.2` and `3.3` of wamser-wasi-types hasn't been published on crates.io yet.

**Comment by theduke** [comment]
Hey, the crate was renamed to `wasmer-wasix-types` , alon gwith `wasmer-wasi` being renamed to `wasmer-wasix`.

**Comment by kvinwang** [comment]
> The crate was renamed to `wasmer-wasix-types` , alon gwith `wasmer-wasi` being renamed to `wasmer-wasix`.

Get it. Thanks.
