### ISSUE TITLE
Replace emscripten generated `select` syscalls with superior native alternatives

### ISSUE THREAD

**Issue by appcypher** [wasmerio/wasmer#40]
Emscripten uses `select` for polling. Select is an inefficient syscall.
We would like to replace the current `select` syscall impl with more efficient alternatives on respective platforms.

- `kevent` and `kevent` on macOS and BSD systems.
- `epoll` and co on Linux systems.

**Comment by syrusakbary** [comment]
Closing this issue for now, as we don't intend to fix it on the short term.
We'll reopen if necessary when the time comes
