### ISSUE TITLE
Running simple wasm file doesn't use Compiler Cache

### ISSUE THREAD

**Issue by ptitSeb** [wasmerio/wasmer#4016]
The compilation cache seems to not be used when running simple .wasm file.
It's ok for package.

After a bisect, the regression cames from one of the following commit
```
23f27396004e824acf5eb734cca9d833b327ffc0
eed8ac542355a949f51aa4206fda2ce176f87749
18620acbb9d8140e16c2b1a1b0c4d87bdfcb6afb
2c161b66e93f469e9b5cf620761cb5ce2cfbfe9c
d9df1c1f1c607d47d18c20e343e1317f3867af2e
464bcd4c9ed9c8b258c5e4252cb6e522d6e121de
2b4e3be245b5b6bbf8c60f4d2438ebc70a4a22eb
7c4834f74f180fd33a7bb4522782d1d539c03bf4
1e543310e51078559f45c190941756f75c521720
```

For testing, remove your cache folder `~/.wasmer/cache` and run a simple `.wasm` file: the cache folder stays empty.

**Comment by Michael-F-Bryan** [comment]
This is the offending section of code:

https://github.com/wasmerio/wasmer/blob/a8b5a05b7bdfde0cfd1d26a54efd03ccd5a34328/lib/cli/src/commands/run.rs#L575-L582

It should be fairly easy to fix by checking `runtime.module_cache()`.

```rust
let wasm = std::fs::read(path)?;
let engine = runtime.engine().context("No engine available")?;
pb.set_message("Compiling to WebAssembly");

let wasm_hash = wasmer_wasix::runtime::module_cache::ModuleHash::sha256(&wasm);
let module_cache = runtime.module_cache();
let tasks = runtime.task_manager();

let module = match tasks.block_on(module_cache.load(wasm_hash, &engine)) {
  Ok(module) => ...,
  Err(CacheError::NotFound) => Module::new(&engine, wasm)?,
  Err(e) => return Err(e),
};
```

See [Slack](https://wasmerio.slack.com/archives/C04193Z3RHS/p1687278049505869) for more context.
