### ISSUE TITLE
wasmer-wasix unkown import "env" "now"

### ISSUE THREAD

**Issue by WanderLanz** [wasmerio/wasmer#4037]
`wasmer-wasix` dependency `tempfile-v3.4.0` relies on `fastrand-v1.9.0` which still has [this issue](https://github.com/smol-rs/fastrand/issues/27) for `wasm32-unkown-unknown` (web) target related to feature flag misconfiguration with the `instant` crate (outlined in [this issue](https://github.com/sebcrozet/instant/issues/31)). This issue looks to be fixed in `fastrand-v2.0.0`, and `tempfile-v3.6.0` depends on `fastrand-v2.0.0` now. Also mentioned in wasm-bindgen on [this issue](https://github.com/rustwasm/wasm-bindgen/issues/2215#issuecomment-796244209) and in parking-lot on [this issue](https://github.com/Amanieu/parking_lot/issues/269).

```
wasmer-wasix v0.x.x
└── tempfile v3.4.0 <-- v3.6.0 uses fastrand v2.0.0
    ├── cfg-if v1.0.0
    └── fastrand v1.9.0 <-- misconfigured feature flags, sometimes makes feature resolver "fail"? fixed in v2.0.0?
        └── instant v0.1.12 (*) <-- origin of (import "env" "now" (func ...))
```

As a temporary workaround for anyone who encounters this issue, you can try and pin the `instant` crate itself, as mentioned [here](https://github.com/rustwasm/wasm-bindgen/issues/2215#issuecomment-796244209):

```toml
[dependencies]
instant = { version = "0.1", features = ["wasm-bindgen"] } # same version pinned as `fastrand` v1.9
```

I haven't seen anyone else mention this issue and it didn't even manifest until I tried to implement HttpClient, so this probably isn't an issue for everyone.

It might just be the resolver being weird, but I thought I'd give anyone a heads up.

EDIT: see below

**Comment by WanderLanz** [comment]
So sorry, I made a goofy mistake of checking the wrong tempfile source for the dependency graph. tempfile v3.6.0 still depends on fastrand 1.x, so it still needs the instant-pin fix. 

However, updating tempfile doesn't break anything and should have probably still been done just as with other dependencies, thank you for the quick response to this.

I should probably make a Minimum Reproducible Example for this, unless someone else is encountering this? - I'll edit this comment with a link when I've made one.

**Comment by Michael-F-Bryan** [comment]
This is no longer an issue as of the latest `master` (64ab03788e).

You can verify it using the following:

```console
$ cargo tree --package=wasmer-wasix --features=js,wasmer/js,wasmer/std --target=wasm32-unknown-unknown --edges=features
```
