### ISSUE TITLE
Different backend execute the same wasm file yields different results

### ISSUE THREAD

**Issue by luxinyi0105** [wasmerio/wasmer#4053]
### Describe the bug

I executed the same wasm file with singlepass and cranelift backend.
The cranelift backend outputs the correct checksum result, while the singlepass backend reports an error.

```sh
$ echo "`wasmer -V` | `rustc -V` | `uname -m`"
wasmer 3.3.0 | rustc 1.71.0-nightly (e77366b57 2023-05-16) | x86_64
```

### Steps to reproduce

[TestCase.zip](https://github.com/luxinyi0105/wasm_runtime_test/raw/main/TestCase.zip)

```sh
$ wasmer run --singlepass test.wasm
```

### Expected behavior

```sh
$ wasmer run --singlepass test.wasm
checksum = DCC5C612
```

### Actual behavior

```sh
$ wasmer run --singlepass test.wasm
error: failed to run `test.wasm`
│   1: module instantiation failed (compiler: singlepass)
╰─▶ 2: Validation error: func type returns multiple values but the multi-value feature is not enabled (at offset 0x59)
```

### Additional context

Actually, I tested it in the latest version(4.0.0), and the phenomenon still exists.

**Comment by ptitSeb** [comment]
Similar to https://github.com/wasmerio/wasmer/issues/3940

Singlepass is not handling multi-value function return correctly for now.
