### ISSUE TITLE
Backtrace not supplied when wasmer used as library and an out of bounds memory access occurs

### ISSUE THREAD

**Issue by yowl** [wasmerio/wasmer#4067]
### Describe the bug
When developing interop between c# and rust, getting a backtrace for out of bounds memory access should I believe be possible, but there is no trace in the err object.  This is using wasmer 4.0.0 and the wasm in the linked repo, I mostly use windows, but WSL is the same.

```sh
E:\GitHub\cs-runtime-example>cargo run
   Compiling cs-runtime-example v0.1.0 (E:\GitHub\cs-runtime-example)
warning: unused import: `Value`
 --> src\main.rs:8:11
  |
8 |     Type, Value,
  |           ^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: `cs-runtime-example` (bin "cs-runtime-example") generated 1 warning (run `cargo fix --bin "cs-runtime-example"` to apply 1 suggestion)
    Finished dev [unoptimized + debuginfo] target(s) in 2.53s
     Running `target\debug\cs-runtime-example.exe`
Std out: Hello, World!

Runtime Error: RuntimeError: out of bounds memory access

E:\GitHub\cs-runtime-example>
```

### Steps to reproduce

Download the repo at https://github.com/yowl/wasmer-repo and run
```sh
cargo run
```

### Expected behavior
There is a problem with the interop so an `out of bounds memory access` occurs, that is ok, but the backtrace should also be printed by `err.trace()` 

### Actual behavior
`err.trace()` is empty as you can see from the above output.

### Additional context
I'm a rust newbie, so may have made a stupid mistake.  Thanks.

**Comment by Michael-F-Bryan** [comment]
For more context, see our conversation [on Discord](https://discord.com/channels/1110300506942881873/1121242736411017276/1127865650459721799).
