### ISSUE TITLE
Upgrade rusqlite to 0.29

### ISSUE THREAD

**Issue by theduke** [wasmerio/wasmer#4070]
This is currently very awkward because the Edge CLI depends on the published version of wasmer-registry, and you can't have two versions of libsqlite-sys in a repo.

**Comment by Michael-F-Bryan** [comment]
Do we even need the SQLite database in the `wasmer-registry`? As far as I can tell, we only use it for something called "interfaces", but I've never heard anyone talk about that feature and it doesn't really seem to be documented.

**Comment by theduke** [comment]
I think @syrusakbary can shed some light on this.
