### ISSUE TITLE
How does wasmer specify rights for different functions?

### ISSUE THREAD

**Issue by orangeC23** [wasmerio/wasmer#4076]
In WASI, there are several rights (https://github.com/WebAssembly/WASI/blob/0ba0c5e2e37625ca5a6d3e4255a998dfaa3efc52/phases/snapshot/docs.md), and wasmer defines rights in bindings.rs.
For example, FD_DATASYNC.
<img width="772" alt="截屏2023-07-13 18 29 36" src="https://github.com/wasmerio/wasmer/assets/28601300/b3f34a94-df93-4891-b4f1-bc2dc8663869">

How does wasmer specify the rights for a concrete function, such as `fd_allocate` ?

## Example
The rust code is :
```
use std::fs::File;
use std::os::fd::AsRawFd;

fn main() {
    let file = File::open("Data/hello.txt").expect("Can not open.");
    let file_descriptor = file.as_raw_fd();
    println!("File descriptor {}", file_descriptor);

    unsafe{
        let p1:wasi::Fd = file_descriptor as u32; 
        let p2:wasi::Filesize = 0;
        let p3:wasi::Filesize = 400;

        println!("{:?}", wasi::fd_allocate(p1, p2, p3));
    }
}
```

How does wasmer specify the rights for the `fd_allocate` function ?

**Comment by Michael-F-Bryan** [comment]
> How does wasmer specify the rights for the `fd_allocate` function ?

I believe the `Rights` flags are for a fine-grained capability system. 

At the moment, Wasmer only uses course permissions like enabling/disabling networking or restricting filesystem access to only the directories specified by the user (e.g. via `--mapdir`).

You shouldn't need to do anything to specify rights for `fd_allocate`.
