### ISSUE TITLE
Use runners to run WASI-compatible `*.wasm` files

### ISSUE THREAD

**Issue by Michael-F-Bryan** [wasmerio/wasmer#4086]
### Motivation

At the moment, the CLI has two main ways it can run a WASI program... 

- If the user does `wasmer run python.wasm` to invoke the WASI binary directly, we'll call [`execute_wasi_module()`](https://github.com/wasmerio/wasmer/blob/3dbe13dfd611a440a96faa137fbbafc5cbb1f20f/lib/cli/src/commands/run.rs#L302-L304) which has [one way](https://github.com/wasmerio/wasmer/blob/3dbe13dfd611a440a96faa137fbbafc5cbb1f20f/lib/cli/src/commands/run/wasi.rs#L152-L232) of setting up a `WasiEnvBuilder`
- if the user runs a package (e.g. `wasmer run python/python`) we'll use [`run_wasi()`](https://github.com/wasmerio/wasmer/blob/3dbe13dfd611a440a96faa137fbbafc5cbb1f20f/lib/cli/src/commands/run.rs#L202-L221) to start the `WasiRunner` which has [a completely different way](https://github.com/wasmerio/wasmer/blob/aaa34d209198f2cf997b852f4246446158b4d9e6/lib/wasix/src/runners/wasi.rs#L136-L153) of setting up the `WasiEnvBuilder`

In theory, there should be a way to remove the duplication and make all WASI execution go through one code path.

### Proposed solution

The `webc` crate already has an internal [`AbstractWebc`](https://github.com/wasmerio/pirita/blob/6c40cfdf5fc760a19e2226db498824575ef3d2a8/crates/webc/src/container.rs#L181-L188) abstraction that it uses to abstract over the different parsers for the different versions of the webc format.

We already piggy-back off this mechanism to allow lazily loading a Wasmer project from disk (or a `*.tar.gz` from the registry) and exposing it as a `webc::Container` (wasmerio/pirita#143). In theory, there's no reason why we couldn't create another implementation that wraps a `*.wasm` binary and implements `AbstractWebc`.

### Alternatives

Alternatively, we could go the other way and modify the `wasmer_wasix::runners::Runner` trait so it isn't coupled to `webc::Container`. 

That sounds better on the surface, but means we lose a lot of the nice things that come from having a `webc::Container` (having access to commands and volumes from dependencies, having access to package and command metadata, etc.). It might *technically* be possible to modify the runners to keep those niceties, but I feel like it'll end up providing a worse developer experience because now every user needs to set these things up manually (with all the footguns and possibility for failure that implies).

CC: @syrusakbary

**Comment by theduke** [comment]
This was resolved with #4301 .
