### ISSUE TITLE
Slow startup?

### ISSUE THREAD

**Issue by yamt** [wasmerio/wasmer#4094]
### Describe the bug

when i benchmark toywasm, i run several engines including wasmer as well to get a baseline.
https://github.com/yamt/toywasm/blob/master/benchmark/startup.md
wasmer is a bit slower than i expected when loading a large module which is already cached.
(see the `wasmer (cached)` column in the graph on the above page. i expected a similar number as wasmtime.)
is it expected?
as interpreters like toywasm perform full validation of the module, i expect a cached run faster than them, especially when the module is large.

### Steps to reproduce

i was using these scripts.
https://github.com/yamt/toywasm/blob/master/benchmark/ffmpeg.sh
https://github.com/yamt/toywasm/blob/master/test/run-ffmpeg.sh

**Comment by matsbror** [comment]
I also noticed slow startup, and in particular on machines with many cores as there were many wasmer processes created. Did you notice this as well @yamt ?

**Comment by yamt** [comment]
my machine is:
```
MacBook Pro (15-inch, 2018)
2.2 GHz 6-Core Intel Core i7
```
it has at most a single wasmer process.

**Comment by matsbror** [comment]
Hm, maybe it's not multiple processes I get, but it definitely uses all cores.

**Comment by Michael-F-Bryan** [comment]
@yamt which version of the `wasmer` CLI are you using for your benchmark? In https://github.com/wasmerio/wasmer/pull/4031 (released as [part of v4.1.0](https://github.com/wasmerio/wasmer/blob/master/CHANGELOG.md#410---24072023)), we did some tweaks to the module cache that made loading a cached module considerably faster.

**Comment by yamt** [comment]
> @yamt which version of the `wasmer` CLI are you using for your benchmark? In #4031 (released as [part of v4.1.0](https://github.com/wasmerio/wasmer/blob/master/CHANGELOG.md#410---24072023)), we did some tweaks to the module cache that made loading a cached module considerably faster.

wasmer 4.0.0 installed by homebrew.

**Comment by ptitSeb** [comment]
Can you re-check with latest wasmer version, things should have improved now @yamt

**Comment by yamt** [comment]
> Can you re-check with latest wasmer version, things should have improved now @yamt

next time i happens to run the benchmark, i will use the latest wasmer available at homebrew at that point and report the result here.

**Comment by yamt** [comment]
> > Can you re-check with latest wasmer version, things should have improved now @yamt
> 
> next time i happens to run the benchmark, i will use the latest wasmer available at homebrew at that point and report the result here.

i rerun with wasmer 4.1.2 from homebrew. it seems it got worse from 4.0.0.
https://github.com/yamt/toywasm/pull/119
