### ISSUE TITLE
"Aborted (core dumped)" while executing wasm file

### ISSUE THREAD

**Issue by luxinyi0105** [wasmerio/wasmer#4105]
### Describe the bug

While executing the given wasm file, wasmer outputs "Aborted (core dumped)", although the correct checksum result is also provided. 
All three compiler backends(Singlepass, Cranelift, LLVM) will discover the problem.

```sh
$ wasmer -vV
wasmer 4.0.0 (6ccf29d 2023-07-24)
binary: wasmer-cli
commit-hash: 6ccf29df1ebab40b3e3e7676ceac7f9deab9a8a3
commit-date: 2023-07-24
host: x86_64-unknown-linux-gnu
compiler: singlepass,cranelift,llvm
```

```sh
$ rustc -vV
rustc 1.73.0-nightly (0308df23e 2023-07-21)
binary: rustc
commit-hash: 0308df23e621e783e31a27ca5beaa01b9df60d4a
commit-date: 2023-07-21
host: x86_64-unknown-linux-gnu
release: 1.73.0-nightly
LLVM version: 16.0.5
```

### Steps to reproduce

[TestCase.zip](https://github.com/luxinyi0105/wasm_runtime_test/raw/main/0725.zip)
```sh
$ wasmer run --singlepass testcase_1.wasm
```
You can replace "--singlepass" with "--cranelift" or "--llvm", this will get the same result.

### Expected behavior

```sh
$ wasmer run --singlepass testcase_1.wasm
checksum = DAFC642C
```
The expected result maybe something like above, just outputs the correct checksum result, or trigger wasmer's exception handling.

### Actual behavior

```sh
$ wasmer run --singlepass testcase_1.wasm
checksum = DAFC642C
thread '<unnamed>' panicked at 'misaligned pointer dereference: address must be a multiple of 0x4 but is 0x7f36643857f9', /home/oscar/Software/wasmer/lib/api/src/sys/mem_access.rs:63:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread caused non-unwinding panic. aborting.
Aborted (core dumped)
```

### Additional context

Actually, I don't know what the correct result of the test case should look like, either. 

So I used some other WebAssembly runtimes, such as wasmedge and wasm-micro-runtime(WAMR), to execute the same test case,  they output the correct checksum result without "Aborted (core dumped)".

**Comment by sug0** [comment]
https://github.com/near/wasmer/commit/62546ccc7f24b242e53e240d1bf186f43648000e
potentially fixed by this commit
