### ISSUE TITLE
wasix: Runtime::load_module API Improvements

### ISSUE THREAD

**Issue by theduke** [wasmerio/wasmer#4122]
### Motivation

`Runtime::load_module[_sync]` currently just takes a `&[u8]` of the WASM code. 

This is suboptimal for two reasons: 

* if the compilation should happen in a separate thread/thread pool, then the slice must be cloned to take ownership
* a feature like a shared lock to prevent concurrent compilation of the same module requires computing a module hash
  The module hash will often already be available in the outer context though, leading to duplicate hash compilation. 
  For large modules that can be somewhat expensive.

### Proposed solution

* Use `shared_buffer::OwnedBuffer` instead of a byte slice
* Add an (optional?) `ModuleHash` argument
   I realize this leads to a somewhat suboptimal API, becaue it requires the caller to pass in the correct module hash. 
   We can mitigate against this with a `debug_assert!()` that re-computes the hash.

cc @Michael-F-Bryan what do you think?

**Comment by Michael-F-Bryan** [comment]
> Use shared_buffer::OwnedBuffer instead of a byte slice

I like this idea. WebAssembly modules will mostly come from files on disk or a buffer in memory (either directly or via packages), which is the use case the `shared_buffer` crate aims to cater for. 

It also gives us a lot of niceties that an owned, reference-counted buffer of bytes gives us

> Add an (optional?) ModuleHash argument
> I realize this leads to a somewhat suboptimal API, becaue it requires the caller to pass in the correct module hash.
> We can mitigate against this with a debug_assert!() that re-computes the hash.

I think we might be able to leave out the `ModuleHash` argument. 

As a quick'n'dirty test, it took about 6ms to hash 10,000,000 bytes [on the playground](https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=4412c1e50be5f2ad673557ac3aed8bd4)'s commodity machines, so it's probably fast enough that we can compute a `ModuleHash` on demand. That really depends on Edge's time budget and what you deem to be acceptable, though.

A nice property of `shared_buffer::OwnedBuffer` is you can rely on it having a stable address and being cheap to clone. That means you could make an fast `HashMap<(*const u8, usize), (OwnedBuffer, Module)>` cache, based on the slice your `OwnedBuffer` derefs to, then fall back to a filesystem or network cache where the cost of `ModuleHash::sha256()` now becomes less important.
