### ISSUE TITLE
Will building wasmer from scratch update the current wasmer installation or do I need to uninstall it first?

### ISSUE THREAD

**Issue by JohnFrrr** [wasmerio/wasmer#4131]
### Summary

Will [building wasmer from scratch](https://docs.wasmer.io/developers/build-from-source) update the current wasmer installation or do I need to uninstall it first?
I didn't find any doc on how to uninstall wasmer, if necessary, can someone please tell me how?

### Additional details

OS: Fedora Linux

**Comment by theduke** [comment]
The install scripts will place the wasmer binary in `~/.wasmer/bin`.

If you install from a local checkout with `cd lib/cli; cargo install --path . -F cranelift,...`, the binary will be in `~/.cargo/bin`.

Which one is preferred depends on the ordering in your `PATH` env var.

The easy way to uninstall the old wasmer would be to just `rm ~/.wasmer/bin/wasmer`.

Closing, feel free to ask more questions if anything remains unclear.
