### ISSUE TITLE
Snapshot tests fail on windows-x64

### ISSUE THREAD

**Issue by Arshia001** [wasmerio/wasmer#4133]
Currently, all snapshot tests are required to have:

```rust
#[cfg_attr(any(target_env = "musl", target_os = "windows"), ignore)]
```

When running these tests on Windows, the tests fail with:

```
thread 'test_snapshot_fs_rename' panicked at 'Could not find wasmer binary: 'D:/a/wasmer/wasmer/target/x86_64-pc-windows-msvc/release/wasmer'', tests\integration\cli\tests\snapshot.rs:263:9
```

A sample run without the attribute is available [here](https://github.com/wasmerio/wasmer/actions/runs/5760653049/job/15617657063#logs).

**Comment by Michael-F-Bryan** [comment]
The issue is probably somewhere in the `get_wasmer_path()` function we use to find the compiled `wasmer.exe`. 

https://github.com/wasmerio/wasmer/blob/7602de387cd6a4cc940098c170320f9f5229a847/tests/integration/cli/src/assets.rs#L75-L136

We might have forgotten the `.exe` extension.
