### ISSUE TITLE
No available compilers for your architecture

### ISSUE THREAD

**Issue by dierbei** [wasmerio/wasmer#4145]
### Summary

First I installed `wasmer` :
```shell
cargo install wasmer-cli
```

Then I tried to run the sample program and got an error. I don't know how to solve it, please help me, thanks.
```shell
# wasmer run cowsay "hello world"
error: There are no available compilers for your architecture
```

### Additional details

![image](https://github.com/wasmerio/wasmer/assets/52097565/322746bf-0e2a-485d-a120-8633e90066c9)

**Comment by theduke** [comment]
You have to enable at least one compiler backend with `-F`.

`cargo install wasmer-cli -F cranelift,singlepass,llvm` for all the backends, or pick a subset.

**Comment by dierbei** [comment]
@theduke I have another question.

I have a problem running a rust http program and I don't know how to solve it. The error message is this:  `╰─▶ 1: Error while importing "wasi_snapshot_preview1"."sock_setsockopt": unknown import. Expected Function(FunctionType { params: [I32, I32, I32, I32, I32], results: [I32] })`

**Comment by dierbei** [comment]
Is this because web server is not supported? Or is there a relevant web server example?

**Comment by theduke** [comment]
See https://wasix.org/docs/language-guide/rust/tutorials/wasix-axum for an example Rust webserver.
