### ISSUE TITLE
`get.wasmer.io` is down.

### ISSUE THREAD

**Issue by lgarron** [wasmerio/wasmer#4177]
### Describe the bug

https://get.wasmer.io/ is down.

### Steps to reproduce

1. Try to access `get.wasmer.io`

### Expected behavior

It up.

### Actual behavior

It's down.

### Additional context

<img width="1016" alt="Screenshot 2023-08-24 at 00 43 19" src="https://github.com/wasmerio/wasmer/assets/248078/69452f68-7fd7-4226-bb87-30e83b381ff1">

https://downforeveryoneorjustme.com/get.wasmer.io
<img width="789" alt="Screenshot 2023-08-24 at 00 44 01" src="https://github.com/wasmerio/wasmer/assets/248078/05f806bf-598e-4faa-a91a-f25a9f659cb2">

According to our CI runs at https://github.com/cubing/twsearch/actions , it was up as of 21:11 Pacific time but down by 22:24 Pacific time (≈2.4 hours ago).

**Comment by theduke** [comment]
Should be back up.

Sorry for the inconvenience.
