### ISSUE TITLE
`get.wasmer.io` is serving a 400 error (was: infinite redirect)

### ISSUE THREAD

**Issue by lgarron** [wasmerio/wasmer#4183]
### Describe the bug

https://get.wasmer.io/ is serving an infinite redirect.

### Steps to reproduce

1. Try to access `get.wasmer.io`

### Expected behavior

Succesful request.

### Actual behavior

Infinite redirect.

EDIT: now a 400 error. https://github.com/wasmerio/wasmer/issues/4183#issuecomment-1694945939

### Additional context

<img width="502" alt="Screenshot 2023-08-25 at 21 20 16" src="https://github.com/wasmerio/wasmer/assets/248078/ed6ba823-8a90-4ad6-a091-9e5d41e6213a">

```shell
> curl -I "https://get.wasmer.io/" | grep location
location: http://get.wasmer.io/
```

https://downforeveryoneorjustme.com/get.wasmer.io
<img width="766" alt="Screenshot 2023-08-25 at 21 22 04" src="https://github.com/wasmerio/wasmer/assets/248078/5f6d9b8e-ec42-45a1-bfb9-2ed68e437e7d">

This is becoming a worrying pattern. Previous issues have had no transparency about why the site has been breaking:

- https://github.com/wasmerio/wasmer/issues/4177
- https://github.com/wasmerio/wasmer/issues/3909

If `get.wasmer.io` is not reliable, it's not safe to use in CI.

- Is the stability of `get.wasmer.io` a priority that we can rely on going forward? If not, are there any other recommended installation flows that we can use? Could the [GitHub action](https://github.com/wasmerio/setup-wasmer) use an installation method that doesn't rely on the live website, or at least implement a fallback?
- Do you have any transparency that you can offer about what happened these last few times?
- Do you have a plan for how to prevent it again, such as uptime monitoring that automatically alerts a `wasmer` maintainer?

I understand that the site (and even the [GitHub action](https://github.com/wasmerio/setup-wasmer)) come with no guarantees, and I appreciate the convenience during normal operation. But I have limited time to work around tooling issues, I'd like to make an assessment about whether to keep my eggs in this basket or move to another one.

**Comment by lgarron** [comment]
The infinite redirect is now gone, and replaced by the following 400 error:

<img width="653" alt="Screenshot 2023-08-27 at 20 21 06" src="https://github.com/wasmerio/wasmer/assets/248078/3c836bf5-2d1e-4103-a71e-49acc2bd71ce">

```shell
> curl -I "http://get.wasmer.io/"
HTTP/1.1 400 Bad Request
X-Edge-App-Version-Id: dav_WK0DIktQulQK
X-Wasmer-Request-Id: b1190fdd-c2bc-40b9-8339-c57340f9deeb
Date: Mon, 28 Aug 2023 03:22:37 GMT
```

**Comment by theduke** [comment]
Hey @lgarron , things should be fixed now, can you confirm on your end?

**Comment by theduke** [comment]
Also: sorry for the inconvenience!
We had some architectural and configuration changes for the site, and some associated bugs.

Things are expected to be stable from now on.
