### ISSUE TITLE
test failed to compile with llvm-7: No LLVM_SYS_70_PREFIX

### ISSUE THREAD

**Issue by huangjj27** [wasmerio/wasmer#419]
### Describe the bug
`make test` on WSL(Ubuntu 18.04, with initial llvm6 removed and llvm-7 installed by apt) fails:
```
error: failed to run custom build command for `wasmer-llvm-backend v0.4.0 (/home/huangjj27/wasmer/lib/llvm-backend)`
process didn't exit successfully: `/home/huangjj27/wasmer/target/debug/build/wasmer-llvm-backend-3d1adc9289268860/build-script-build` (exit code: 101)
--- stdout
Didn't find usable system-wide LLVM.
No suitable version of LLVM was found system-wide or pointed
                  to by LLVM_SYS_70_PREFIX.

                  Consider using `llvmenv` to compile an appropriate copy of LLVM, and
                  refer to the llvm-sys documentation for more information.

                  llvm-sys: https://crates.io/crates/llvm-sys
                  llvmenv: https://crates.io/crates/llvmenv

--- stderr
thread 'main' panicked at 'Could not find a compatible version of LLVM', lib/llvm-backend/build.rs:83:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

what value should be set to `LLVM_SYS_70_PREFIX`?

### Steps to reproduce
0. remove preinstalled llvm: `sudo apt remove llvm -y`, and install llvm-7: `sudo apt install llvm-7`
1. git clone git@github.com:wasmerio/wasmer.git to WSL
2. cd wasmer
3. make test

If applicable, add a link to a test case (as a zip file or link to a repository we can clone).

### Expected behavior

it should pass compile and run the tests

### Actual behavior

failed to compile test as shown

### Additional context

related to #364

**Comment by huangjj27** [comment]
And I found that the llvm-7 I installed have a config with commaned `llvm-config-7`

**Comment by penberg** [comment]
I see the same error on Fedora 30 if I install the `llvm7.0` and `llvm7.0-devel` packages. The issue seems to be that Fedora 30 switched to LLVM 8 by default and renames `llvm-config` of older versions to something else:
 
https://github.com/mesonbuild/meson/issues/5059

AFAICT, the fix is to bring back the version specific `llvm-config` discovery:

```patch
diff --git a/lib/llvm-backend/build.rs b/lib/llvm-backend/build.rs
index ab59748b..a48d5a9d 100644
--- a/lib/llvm-backend/build.rs
+++ b/lib/llvm-backend/build.rs
@@ -25,8 +25,8 @@ lazy_static! {
     static ref LLVM_CONFIG_BINARY_NAMES: Vec<String> = {
         vec![
             "llvm-config".into(),
-            // format!("llvm-config-{}", CRATE_VERSION.major),
-            // format!("llvm-config-{}.{}", CRATE_VERSION.major, CRATE_VERSION.minor),
+            format!("llvm-config-{}", CRATE_VERSION.major),
+            format!("llvm-config-{}.{}", CRATE_VERSION.major, CRATE_VERSION.minor),
         ]
     };
```

Unfortunately I was not able to make `cargo` pick up that change so I was not able to test it.

**Comment by syrusakbary** [comment]
We switched by default to use LLVM-8 so based on @penberg comments I believe that should fix the issue.

Please let us know if that's not the case.
Closing the issue :)
