### ISSUE TITLE
Wasmer's behavior maybe incorrect when pointer length out of bounds

### ISSUE THREAD

**Issue by luxinyi0105** [wasmerio/wasmer#4208]
### Describe the bug
While executing [the given testcase ](https://github.com/luxinyi0105/wasm_runtime_test/raw/main/09-08.zip)with wasmer and other runtime tools, the result are different.

```sh
$ wasmer -vV
wasmer 4.1.2 (98b1c6a 2023-08-28)
binary: wasmer-cli
commit-hash: 98b1c6a99746105e4fef66e93f78ba2a4d96a70f
commit-date: 2023-08-28
host: x86_64-unknown-linux-gnu
compiler: singlepass,cranelift,llvm
```

```sh
$ rustc -vV
rustc 1.73.0-nightly (0308df23e 2023-07-21)
binary: rustc
commit-hash: 0308df23e621e783e31a27ca5beaa01b9df60d4a
commit-date: 2023-07-21
host: x86_64-unknown-linux-gnu
release: 1.73.0-nightly
LLVM version: 16.0.5
```

### Actual behavior
```sh
$ ~/Software_new/wasmer/target/release/wasmer mutated_file.wasm
checksum = 72658C22
```

### Expected behavior
I use some other runtime tools, such as wasmtime, wasmedge and wasmi, to execute the same testcase. Wasmtime outputs runtime error due to pointer out of bounds, while wasmedge and wasmi do not output anything. The execution results of these tools are shown in the following figure.
![09-09](https://github.com/wasmerio/wasmer/assets/92167273/bf5c4272-6b92-47f6-bf7d-4d1c16b6d45d)
According to the issue I submitted in wasmtime: [bytecodealliance/wasmtime#6940](https://github.com/bytecodealliance/wasmtime/issues/6940), the length of the pointer, 952683808, is out of bounds. Wasmtime emits a `wasm traps` when handed an out-of-bounds pointer, while other runtime tools, such as wasmedge and wasmi maybe return `ERRNO_FAULT`. So, from this perspective, wasmer's running result maybe incorrect while meeting the situation that pointer length out of bounds.

### Additional context
The given testcase was simply mutated a wasm file, which was obtained by compiling C program generated with `Csmith` using `Emscripten Compiler` (Emcc).

The original C program is `c_file.c`, the compilation results with Emscripten is `wasm_file.wasm`, and its wat format is `wat_file.wat`.

We mutated the wat file to change its `i32.const 2` in line 20221 with `i32.const 3`. The result after mutation is `mutated_file.wat`, and its wasm format is `mutated_file.wasm`.

**Comment by theduke** [comment]
@ptitSeb is this already fixed, or does this look like a new unrelated issue?

**Comment by ptitSeb** [comment]
This is something new. It's behaviour with modified "wrong" binaries. It should trigger a OOB but doesn't.
