### ISSUE TITLE
wasix: Can't use `sock_bind` on Zig

### ISSUE THREAD

**Issue by nikneym** [wasmerio/wasmer#4217]
### Summary

Hi, I'm trying to use WASIX calls through Zig and currently unable to bind my socket to a local address. You can find the implementation [here](https://github.com/nikneym/zig-wasix) and my main function [here](https://github.com/nikneym/zig-wasix/blob/main/src/test.zig). A call to `sock_bind` always results with `INVAL` (`sock_connect` just works fine by the way). I've compared my declarations with wasix-libc but couldn't spot the issue.

In order to build & run the project I'm running these:
```sh
zig build -Dtarget=wasm32-wasi
wasmer run --enable-all -a 127.0.0.1:8080 zig-out/bin/wasix-test.wasm
```

**Comment by ptitSeb** [comment]
you need to enable network. the `--enable-all` is there to enable WASI features, not network.
So try with
```bash
wasmer run --enable-all --net -a 127.0.0.1:8080 zig-out/bin/wasix-test.wasm
```

**Comment by nikneym** [comment]
> you need to explicitly enable network. the `--enable-all` is there to enable WASI features, not network. So try with
> 
> ```shell
> wasmer run --enable-all --net -a 127.0.0.1:8080 zig-out/bin/wasix-test.wasm
> ```

Tried as you've claimed, I still get `INVAL`:
```sh
zig build -Dtarget=wasm32-wasi
wasmer run --enable-all --net -a 127.0.0.1:8080 zig-out/bin/wasix-test.wasm
```

**Comment by nikneym** [comment]
Turns out in order to create valid TCP/IP socket, address family must be `INET4` which is 1. I thought `AF_INET` (which is 2) is required for creating such socket. All is well now, sorry for the heads up!
