### ISSUE TITLE
Is it possible to change the mach dependency

### ISSUE THREAD

**Issue by AurelienFT** [wasmerio/wasmer#4222]
### Summary

When using `wasmer` version 4.2 we have a warning when running a `cargo audit` on a dependency that you have which is `mach`. The warning : https://rustsec.org/advisories/RUSTSEC-2020-0168 . They recommend to use an other crate called `mach2` which is more maintained. What do you think about this change ?

**Comment by Michael-F-Bryan** [comment]
I've assigned this to @Arshia001. Hopefully `mach2` will be a drop-in replacement and we can resolve this immediately, otherwise if switching requires more extensive modifications we may need to put it off until later.

**Comment by AurelienFT** [comment]
Any news on that ?

**Comment by Arshia001** [comment]
@AurelienFT I just pushed a change that should fix this, we'll know if `mach2` is compatible with `mach` if the CI turns green.

**Comment by Arshia001** [comment]
Actually, it turns out we have to wait for `region-rs` to publish a new version with the mach2 crate as a dependency.
