### ISSUE TITLE
Encountered problems while installing old version tools

### ISSUE THREAD

**Issue by luxinyi0105** [wasmerio/wasmer#4225]
### Summary

Recently, I was trying to install an older version of the wasmer tool and using the `grcov` tool to detect wasmer's execution coverage information. 

To use `grcov`, you need to modify the Makefile file of the wasmer tool, add relevant environment variables like [this](https://github.com/mozilla/grcov#example-how-to-generate-gcda-files-for-a-rust-project) and run `make build-wasmer` command in the `Nightly version` of the cargo tool. 

I have tried the above work on the latest version of the wasmer tool and ensured that there are no issues with the relevant steps. However, when applying the above steps to older versions of the wasmer tool, I meet error as the followng picture.
![截图 2023-09-22 14-49-27](https://github.com/wasmerio/wasmer/assets/92167273/1376bce8-2f1d-48eb-9855-28aca50eac00)
 

I have tried multiple versions of Wasmer tool, such as `2.0.0`, `2.1.0`, `2.2.0`, `3.0.0`, and the results are all the same. I don't know where the problem is, maybe the tool version of rustc/cargo is incorrect? I hope to receive your help.

**Comment by Michael-F-Bryan** [comment]
I'm guessing what's happened is you are using a newer version of nightly and the `proc_macro_span_shrink` feature has been removed from the language (or stabilised) since Wasmer 2.0 was released. You might have better luck by using a version of nightly Rust from around then.
