### ISSUE TITLE
Why it's possible to create 4GB memory, but it's not possible to allocate.

### ISSUE THREAD

**Issue by grishasobol** [wasmerio/wasmer#4264]
Hi, wasmer team! Have a question today about Linear memory. If you would check LinearMemory code, then you see that it's possible to make 4GB memory: 
https://github.com/wasmerio/wasmer/blob/9127dde836d3fd12dedfa74054508bb66ddd49df/lib/vm/src/memory.rs#L220-L236

But, if I have smaller initial memory and wanna to allocate some pages, so that memory would have 4GB size than it's impossible. Why so strange behaviour?
https://github.com/wasmerio/wasmer/blob/15e5e44b5718fd229df40f65a1056fa27f1441e4/lib/vm/src/memory.rs#L69-L77

**Comment by Arshia001** [comment]
Could this be an off-by-one error where we're using `>=` in one place and `>` in another?
