### ISSUE TITLE
https://wasmer.sh emulates x86 elf assembly differently

### ISSUE THREAD

**Issue by RefinedSoftwareLLC** [wasmerio/wasmer#4266]
### Describe the bug
Running asm
```
31 c0 # xor    eax,eax # eax = 0
40    # inc    eax     # eax = eax + 1
                       # eax == EXIT
                       # ebx == 0
cd 80 # int    0x80    # sys_call(eax, ebx) # exit(0)
```
via

```
>c chmod +x c &&>>c printf "\x7f\x45\x4c\x46\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x03\x00\x2E\x00\x00\x00\x2E\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x20\x00\x01\x00" && >>c printf "x31\xc0\x40\xcd\x80" && ./c ; printf "$?\n"
```
or
```
>c printf "\x7f\x45\x4c\x46\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x03\x00\x2E\x00\x00\x00\x2E\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x20\x00\x01\x00" && >>c printf "x31\xc0\x40\xcd\x80" && chmod +x c && ./c ; printf "$?\n"
```

should print
```
0
```
and cleanly exit

but instead prints
```
44
```
or
```
+x: function/utility not found
44
```
and sometimes hangs

### Steps to reproduce

This can be run in:
`https://wasmer.sh/` (right click to paste, bash-5.1)
`your cli` (right click or ctrl-shift-v to paste, fedora 38)
`https://copy.sh/v86/?profile=buildroot` (right click the serial console textbox to paste)
`https://bellard.org/jslinux/vm.html?url=alpine-x86.cfg&mem=192` (menu key to paste, https://en.wikipedia.org/wiki/Menu_key)

Only `https://wasmer.sh` echos 44, all the others echo 0 and never hang

### Expected behavior
exits with 0

### Actual behavior
exits with 44

### Additional context
`https://github.com/wasmerio/wasmer` seams to be the repo for `https://wasmer.io/wasmer/wasmer-sh@0.4.17/docs` and `https://wasmer.sh`...

These commands do not work in `https://wasmer.sh`:
`wasmer -v`
`about wasmer` (from the login header text)
`coreutils` (from the login header text)

**Comment by RefinedSoftwareLLC** [comment]
setting ebx with
```
31 db # xor    ebx,ebx # ebx = 0
b3 2a # mov    bl,0x2a # lowest byte of ebx = 42
```
does not fix the issue, as `https://wasmer.sh` still returns 44, while all the others return 42

**Comment by RefinedSoftwareLLC** [comment]
If `https://wasmer.sh` can't run even the most basic of x86 then the cli should print an error message saying so. It currently silently fails (you have to use `printf "$?\n"` to see the non-zero exit code).

**Comment by Michael-F-Bryan** [comment]
> If https://wasmer.sh can't run even the most basic of x86 then the cli should print an error message saying so.

@RefinedSoftwareLLC the https://wasmer.sh website is a WebAssembly virtual machine that runs Bash (and other packages on [the Wasmer registry](https://wasmer.io/)) that have been compiled to WebAssembly.

This is *not* an x86 emulator, so it isn't surprising that creating a file containing an x86 program and executing it doesn't work.

**Comment by RefinedSoftwareLLC** [comment]
> then the cli should print an error message saying so. It currently silently fails (you have to use `printf "$?\n"` to see the non-zero exit code).

@Michael-F-Bryan please rename this issue to whatever you want, but reopen it. This is a real issue that isn't resolved. wasmer's Bash is trying to make WebAssembly work seamlessly like native binary files, so native binary files should _not_ silently fail when a human is at the helm of the cli. For example, someone may try to run an executable created via `wasmer create-exe`.

- [ ] 1. I recommend showing an error on stderr.

- [ ] 2. Do executables created by wasmer create-exe reference their original wasmer.io | wapm.io link with (pinned?) version number? If so, in a wasm only environment, extracting that information and running its wasm version may be a useful fallback feature.

- [ ] 3. Maybe this is already being done, but I recommend to specifically check for an elf header or invalid binary then cleanly exit early. Something is inconsistent with the following example, that intermittently hangs the https://wasmer.sh website.

```
echo >c && ./c ; ./c ; printf "exited: $?\n" ;
```

In the firefox browser, this logs the following and silently exits 44, silently exits 1, or hangs without logging:
```
WARN /prog/wasmer/lib/wasix/src/bin_factory/mod.rs:81 Unable to load the package from disk path = "/c";
error = Unable to parse the WEBC file; 754.main.js:937:21
WARN /prog/wasmer/lib/wasix/src/syscalls/wasix/proc_exec.rs:250 failed to execve as the process could not be spawned (fork)[0] - not found 2 754.main.js:937:21
INFO src/pool.rs:723 worker shared started (index=1, type=Shared) 754.main.js:937:21
INFO src/pool.rs:723 worker shared started (index=2, type=Shared) 754.main.js:937:21
INFO src/pool.rs:790 worker closed (index=2, type=Shared) 754.main.js:937:21
NetworkError: Worker constructor: Failed to load worker script at data:application/javascript,onmessage%20%3D%20function%20(ev)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20let%20%5Bia%2C%20index%2C%20value%5D%20%3D%20ev.data%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20ia%20%3D%20new%20Int32Array(ia.buffer)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20let%20result%20%3D%20Atomics.wait(ia%2C%20index%2C%20value)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20postMessage(result)%3B%0A%20%20%20%20%20%20%20%20%7D%3B%0A%20%20%20%20%20%20%20%20 (nsresult = 0x80004005) 754.main.js:1038
```
