### ISSUE TITLE
Running `*.wasm` files directly doesn't sandbox the filesystem

### ISSUE THREAD

**Issue by yagehu** [wasmerio/wasmer#4267]
In wasmtime or other Wasm runtimes with WASI support, you have to explicit preopen a directory to have access to the host filesystem. With wasmer, it seems the cwd is opened by default.

For example, given this small Rust program:

```
fn main() {
    let f = std::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open("abc")
        .unwrap();
}
```

Running it as `wasmer run test.wasm` will just create a file named `abc` in cwd. Is it possible to disable this behavior. I only want host fs access if I explicitly enable it.

The above program is compiled with `cargo build --target wasm32-wasi`.

**Comment by Arshia001** [comment]
Hey @yagehu!

Are you sure you're not mounting the directory via `--mapdir /:.`? AFAIK, no directories are mounted automatically when running wasmer without `--mapdir` or `--dir`.

**Comment by Arshia001** [comment]
@yagehu never mind, I just ran it and it does indeed mount the cwd.

**Comment by theduke** [comment]
This was resolved in https://github.com/wasmerio/wasmer/pull/4301 .

**Comment by yagehu** [comment]
@theduke Will you publish the security advisory?

**Comment by theduke** [comment]
@yagehu which version of wasmer are you on, and which operating system?

**Comment by Arshia001** [comment]
@theduke you have to compile to `wasm32-wasi`, the issue does not exist in `wasm32-wasmer-wasi`.

**Comment by Arshia001** [comment]
never mind, it just doesn't happen with `cargo wasix run`, probably because `cargo-wasix` changes `wasmer`'s pwd to something else.

**Comment by yagehu** [comment]
> @yagehu which version of wasmer are you on, and which operating system?
> 
> Because this does not reproduce on wasmer `4.2.3` on Linux.

This reproduces with v4.2.3 Wasmer on Fedora 39 Linux. It does NOT reproduce with v4.2.4 Wasmer, so I'm assuming your commit fixed it. I'm just wondering if you will publish the security advisory since it impacts people running plain WASI (non WASIX) workloads.

**Comment by Arshia001** [comment]
@yagehu we ran into a bit of a hiccup with publishing the crates. That's been resolved and the advisory will be published soon. Tagging @syrusakbary

**Comment by Arshia001** [comment]
@yagehu the advisory is now published. I will close this issue.
