### ISSUE TITLE
WAPM registry giving 403 access denied

### ISSUE THREAD

**Issue by laurensV** [wasmerio/wasmer#4274]
https://registry-cdn.wapm.io/ gives a 403 AccessDenied message for all links..

**Comment by theduke** [comment]
Note: you can download a package with `curl -H "accept: application/webc" https://wasmer.io/namespace/package[@verison]`.

**Comment by theduke** [comment]
@laurensV we restored access to the old URLs for now.

**Comment by Michael-F-Bryan** [comment]
@theduke note that access to the old URLs will be removed again at some point. To facilitate private packages, we're moving access to all package files over to signed URLs so everything will need to go through the `-H "Accept: application/webc"` mechanism.
