### ISSUE TITLE
The wasmer can detective stack value of the wasm program running in runtime?

### ISSUE THREAD

**Issue by xubenji** [wasmerio/wasmer#4290]
like gdb, we can check the stack value of wasm program on live, and plus, 
For the wasm program, call 15 means to call the address saved in the stack?(offset 15 in stack)

**Comment by Michael-F-Bryan** [comment]
@xubenji can you elaborate on what you mean here? If possible, maybe try to share some example code of what you are trying to achieve or what you are doing at the moment.

**Comment by xubenji** [comment]
Simply say, I want to find out how we can check the stack value as the wasm program runs in the runtime.

**Comment by Michael-F-Bryan** [comment]
@xubenji by "the stack value", do you mean you want to read the entire WebAssembly stack, or just a single value from the stack? To the best of my knowledge, the stack is hidden from users and not accessible.
