### ISSUE TITLE
wasmer-wasix requires Tokio runtime now?

### ISSUE THREAD

**Issue by gluax** [wasmerio/wasmer#4295]
### Summary

It seems `wasmer-wasix` requires you to run a `tokio` runtime when `sys-thread` is enabled. And if that feature is not enabled, it panics?

There are not any docs that enable this feature require a `tokio` runtime.

Is there a way to handle this without a `tokio` runtime? If so, what's an example?

### Additional details

Corresponding snippets from the `wasmer-wasix` library.

```rust
let runtime = self.runtime.unwrap_or_else(|| {
            #[cfg(feature = "sys-thread")]
            {
                Arc::new(PluggableRuntime::new(Arc::new(crate::runtime::task_manager::tokio::TokioTaskManager::default())))
            }

            #[cfg(not(feature = "sys-thread"))]
            {
                panic!("this build does not support a default runtime - specify one with WasiEnvBuilder::runtime()");
            }
        });
```

```rust


impl Default for TokioTaskManager {
    fn default() -> Self {
        Self::new(Handle::current())
    }
}
```

**Comment by theduke** [comment]
Also note that some of the traits build on top of tokio traits like `AsyncRead/Write`, but you just need those trait definitions, nothing else from tokio. 
I think there is a separate crate that provides just the traits.

**Comment by gluax** [comment]
Got it, I was asking because I'm trying to upgrade from `wasmer` version 3 to 4.

Before the upgrade, I could do something like the following:

```rust
wasi_env
  .tasks()
  .block_on(...);
  ```

This migrated to:
```rust
wasi_env
  .runtime()
  .task_manager()
  .spawn_and_block_on(...):
  ```
  
  But it doesn't even make it to this section now since it panics when I finalize my `WasiEnv` builder since it's not in `tokio` environment, as it tries to access `tokion::runtime::Handle::current()`. This panic didn't happen before the upgrade.
  
  ```rust
  let mut wasi_env = WasiEnv::builder(function_name.clone())
        .envs(call_data.envs.clone())
        .args(call_data.args.clone())
        .stdout(Box::new(stdout_tx))
        .stderr(Box::new(stderr_tx))
        .finalize(&mut context.wasm_store)
        .map_err(|_| VmResultStatus::WasiEnvInitializeFailure)?;
       ```
       
       So we now need to create a custom runtime or get tokio to work with our current setup?

**Comment by gluax** [comment]
I don't think we are actually access the `host-fs` we had that feature enabled so it could block `async` tasks for us aha.

**Comment by theduke** [comment]
What's your current setup and requirements?
