### ISSUE TITLE
Ctx only exposes immutable memory, should expose mutable

### ISSUE THREAD

**Issue by autodidaddict** [wasmerio/wasmer#431]
Thanks for proposing a new feature!

### Motivation

If you expose a host function that returns anything more complicated than a simple number, then the host function will need to perform an allocation inside the WebAssembly module _and_ set the value. For example, if you expose a function that returns a string - this function needs to call the in-wasm allocator and then write bytes to the wasm module's linear memory, starting at the pointer position returned by the allocator.

Since wasmer host functions only have access to the `Ctx` struct, which only currently exposes immutable memory, it doesn't look like wasmer . host functions can return complex data structures.

### Proposed solution

Give the `Ctx` object the ability to grab mutable access to memory for the duration of the reference (e.g. with a mutex or RwLock)

### Alternatives

The hack here would be for the host function to call some other entity that has a mutable reference to the Wasm module and pray that works. Since the `Memory` object can't go between threads, nor can half the other wasmer structs, this makes it _really_ hard.

### Additional context

A simple host function like `get_string(param: i32)` requires mutable memory access.

**Comment by autodidaddict** [comment]
Hmm.. I think I may be far to uncaffeinated to have submitted this. It looks like the memory is immutable, but I can still use the memory view to set individual cells.

**Comment by autodidaddict** [comment]
Okay so it looks like I can write to the memory, but I can't call the in-wasm allocator because I don't have a reference to the instance. I can't share a reference to the instance because it's not Send. So I guess my issue isn't really about the immutability of the memory on ctx, but it's that I can't use ctx to make function calls on the module.

What is your recommendation then on how, in a host function, you could then make a call (like `malloc`) on the instance?

**Comment by CryZe** [comment]
I haven't actually fully looked into it yet, but I'm pretty sure the way the memory currently works in wasmer actually causes Undefined Behavior in pretty much all the imports.

**Comment by autodidaddict** [comment]
I got it working. I can write to the memory provided by the context. I
thought I was going to need to make a call to the module from inside a host
function, but thankfully found a design around that.

**Comment by thedavidmeister** [comment]
@autodidaddict how did this work?
