### ISSUE TITLE
WASI execution hangs without any messages

### ISSUE THREAD

**Issue by FranklinWaller** [wasmerio/wasmer#4312]
### Describe the bug

When running the cowsay demo (https://wasmer.io/syrusakbary/cowsay) on the latest master branch nothing happens an the runtime just hangs.

```sh
wasmer -vV; rustc -vV

wasmer 4.2.3 (9275275 2023-11-15)
binary: wasmer-cli
commit-hash: 9275275648ce374dd7f4fafedfbd12dfcfa8b8f8
commit-date: 2023-11-15
host: aarch64-unknown-linux-gnu
compiler: singlepass,cranelift
rustc 1.70.0 (90c541806 2023-05-31)
binary: rustc
commit-hash: 90c541806f23a127002de5b4038be731ba1458ca
commit-date: 2023-05-31
host: aarch64-unknown-linux-gnu
release: 1.70.0
LLVM version: 16.0.2
```

### Steps to reproduce

1. Compile the latest version of wasmer on the master branch
2. Run `./wasmer run syrusakbary/cowsay`
3. Nothing happens

In code (I took the `examples/wasi.rs`): 
```Rust
use std::io::Read;

use wasmer::{Module, Store};
use wasmer_wasix::{Pipe, WasiEnv};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let wasm_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/cowsay.wasm"
    );
    // Let's declare the Wasm module with the text representation.
    let wasm_bytes = std::fs::read(wasm_path)?;

    // Create a Store.
    let mut store = Store::default();

    println!("Compiling module...");
    // Let's compile the Wasm module.
    let module = Module::new(&store, wasm_bytes)?;

    let (stdout_tx, mut stdout_rx) = Pipe::channel();

    println!("Starting program");

    // Run the module.
    WasiEnv::builder("hello")
        // .args(&["world"])
        // .env("KEY", "Value")
        .stdout(Box::new(stdout_tx))
        .run_with_store(module, &mut store)?;

    eprintln!("Run complete - reading output");

    let mut buf = String::new();
    stdout_rx.read_to_string(&mut buf).unwrap();

    eprintln!("Output: {buf}");

    Ok(())
}

#[test]
#[cfg(feature = "wasi")]
fn test_wasi() -> Result<(), Box<dyn std::error::Error>> {
    main()
}

```

### Expected behavior

It should run the binary like normal or if there is something wrong throw an error

### Actual behavior

The execution just hangs and does nothing

### Additional context

I am using the devcontainer to compile and run the binary.

**Comment by Michael-F-Bryan** [comment]
@FranklinWaller cowsay isn't hanging, it's waiting for you to write to stdin. 

When you do `wasmer run syrusakbary/cowsay`, type some text then hit `<enter>` and send an EOF (`<ctrl-D>` in my terminal).

You can also do `echo "Hello, World!" | wasmer run syrusakbary/cowsay` or `wasmer run syrusakbary/cowsay -- "Hello, World!"` if you don't want it to wait for you to type some input.
