### ISSUE TITLE
Did 4.2.3 release get re-tagged?

### ISSUE THREAD

**Issue by chenrui333** [wasmerio/wasmer#4318]
👋 while regression testing rust 1.74.0, we found the checksum got changed, raise this issue to confirm if there was any re-tagging happened. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/154804

**Comment by theduke** [comment]
I believe there was some issue with the original tag, with subsequent build failures, so it was retagged.

Can you confirm, @Arshia001 , @dynamite-bud ?

**Comment by Arshia001** [comment]
@chenrui333 yes, the tag was pushed manually. Sorry for the inconvenience. We will try not to do that any more.

**Comment by chenrui333** [comment]
np, thanks for confirming it.
