### ISSUE TITLE
Flushing bug?

### ISSUE THREAD

**Issue by Userzxcvbvnm** [wasmerio/wasmer#4340]
### Describe the bug
The test case is uploaded:
[sync-wasm.txt](https://github.com/wasmerio/wasmer/files/13533753/sync-wasm.txt)
[sync-c.txt](https://github.com/wasmerio/wasmer/files/13533754/sync-c.txt)
 sync.c is uploaded as sync-c.txt, sync.wasm is uploaded as sync-wasm.txt.

### Steps to reproduce
wasmer run --dir=./Data sync.wasm

### Expected behavior
Successfully sync to the disk and prints "File data in 'Data/hello.txt' synchronized to disk successfully."

### Actual behavior
wasmer sync fails and prints:
Error synchronizing file data to disk.

### Additional context
We checked the wasmer source code and found that the bug could be in wasmer_wasix::fs:lib/wasix/src/fs/mod.rs.
This is because the fd_datasync method implemented in wasmer calls the flush method, which checks whether the current file descriptor has the FD_DATASYNC permission. If it does, it returns Errno::Access, causing the error in the output information. The permission check here needs to be corrected. It should be modified to return Errno::Access only if the permission is not included.
<img width="767" alt="截屏2023-12-02 16 51 52" src="https://github.com/wasmerio/wasmer/assets/151800801/213691da-b202-4c3a-af39-00875b1b36a1">

**Comment by theduke** [comment]
Looks related to #4323 .

**Comment by Userzxcvbvnm** [comment]
We add a pull request :https://github.com/wasmerio/wasmer/pull/4348
