### ISSUE TITLE
Problems Encountered in I/O Testing with Multi-Threading Disabled

### ISSUE THREAD

**Issue by maochenxi** [wasmerio/wasmer#4357]
### Describe the bug
I attempted three different methods to disable multi-threading in the Wasmer project, but none were successful.
This is my wasm source code, which comes from a universal testing suite  `llvm-testg-suite` .
```sh
#include <algorithm>
#include <cctype>
#include <cstdio>
#include <cstring>
#include <map>
#include <vector>
#include <unistd.h>

using namespace std;

int const bufsize = 4096;
int const wsize = 64;

class word_reader {
  int ws;
  char buf[bufsize + 1], *bptr, *word;
  FILE *input;

  bool fill();

public:
  word_reader(FILE *i)
      : ws(wsize), bptr(buf), word(new char[ws + 1]), input(i) {
    *bptr = *word = '\0';
  }
  int operator()(char const **);
};

inline bool word_reader::fill() {
  // int nread = read(fileno(input),buf, bufsize);
  int nread = fread(buf, sizeof(char), bufsize, input);
  buf[nread] = '\0';
  bptr = buf;
  // long pos = ftell(input);
  // printf("Current file position: %ld\n", pos);
  return nread > 0;
}

int word_reader::operator()(char const **w) {
  int len = 0;
  char c;
  while (*bptr || fill()) {
    if (isalpha(c = *bptr++)) {
      word[len] = tolower(c);
      if (++len == ws) {
        char *nword = new char[(ws *= 2) + 1];
        memcpy(nword, word, len);
        delete[] word;
        word = nword;
      }
    } else if (len > 0)
      break;
  }
  *w = word;
  word[len] = '\0';
  return len;
}

typedef map<char const *, int> counter;
typedef pair<char const *, int> hpair;

namespace std {
inline bool operator<(hpair const &lhs, hpair const &rhs) {
  return lhs.second != rhs.second ? lhs.second > rhs.second
                                  : strcmp(lhs.first, rhs.first) > 0;
}

template <> struct equal_to<char const *> {
  bool operator()(char const *s1, char const *s2) const {
    return strcmp(s1, s2) == 0;
  }
};
} // namespace std

int main() {
  int len;
  const char *w;
  counter hist;
  FILE *file = fopen("input.txt", "r");

  if (file == NULL) {
        perror("Error opening file");
        return 1;
    }


  word_reader wr(file);

  while ((len = wr(&w)) > 0) {

  }
  
  fseek(file, 0, SEEK_SET);
  char buf[10];
  fread(buf, 1, 10, file);
  fclose(file);
  printf("end");
  return 0;
}
```

### Methods one
I used the `--disable-threads` option from the help menu and executed the following command. However, it did not have the desired effect, and the `strace` results still indicate multi-threading.
```sh
strace -f wasmer run --disable-threads word.wasm --dir=. 2> wasmer.txt
```
### Methods two
I modified the implementation of the `Features` struct in the Wasmer source code, changing the default value of the `threads` field to `false`. After recompiling the Wasmer source with the `make wasmer-build` command, I executed my code. However, I encountered an “Error opening file: No such file or directory” error when executing the `fopen("input.txt");` function. When I commented out all I/O-related code and only executed a `printf("end");` statement, the program ran smoothly, but the `strace` output still showed multi-threading.
https://github.com/wasmerio/wasmer/blob/1abcd2cc63deeca13af6506add6029edaba4d657/lib/types/src/features.rs#L40-L61

### Methods three
I also tried modifying the `max_threads` and `enable_asynchronous_threading` properties in the Wasmer source code, attempting to disable multi-threading, but it resulted in the same outcome as with method two.
https://github.com/wasmerio/wasmer/blob/1abcd2cc63deeca13af6506add6029edaba4d657/lib/wasix/src/capabilities.rs#L10-L18
```sh
pub fn new() -> Self {
    Self {
        insecure_allow_all: false,
        http_client: Default::default(),
        threading: CapabilityThreadingV1 {
            max_threads: Some(1),
            enable_asynchronous_threading: false,
        },
    }
}
```

**Comment by theduke** [comment]
There is some related discussion here: https://github.com/wasmerio/wasmer/discussions/4299

At the moment the design of our WASI(X) implemenetation requires a separate scheduler and thread pool, so you'll need at least two threads, assuming that you also went with a custom Runtime implementation (as explained in the linked discussion).

We do realize that having a simple, non-tokio based official implementation would be good.
Stay tuned for some updates on this early next year.

**Comment by maochenxi** [comment]
Discrepancy in read System Call Timing with Wasmer's fread WASI Interface Compared to Other Runtimes.
I have been conducting a statistical analysis of the read system call execution time across different runtimes for a given source program. During this process, I have observed that the execution time for the fread WASI in Wasmer is approximately 10 times longer than that of other runtimes. Additionally, the read system call timing is also higher in Wasmer, about twice that of others. Intuitively, the read system call execution times for the same program should be similar across runtimes. Could this discrepancy be related to Wasmer's use of the Tokio runtime for asynchronous I/O operations? Any insights or clarifications regarding this would be greatly appreciated.
