### ISSUE TITLE
error: npm not installed 

### ISSUE THREAD

**Issue by Lemonjay** [wasmerio/wasmer#4364]
I have installed node and npm
Is any way,I can solve this problem below.

```
wasmer add dynamite-bud/sgp4 --npm
Querying Wasmer for package bindings
error: npm not installed ```
 
```

**Comment by Arshia001** [comment]
@Lemonjay do you have `npm` available on your PATH? Try running `npm --version` before running `wasmer` and see if you get the correct output. Depending on how you installed npm, you may need to restart your terminal or run additional scripts to make it available on PATH.
