### ISSUE TITLE
Cannot open a file with O_TRUNC and O_APPEND

### ISSUE THREAD

**Issue by yagehu** [wasmerio/wasmer#4376]
### Describe the bug

This might be a wontfix but I figure I should report this anyway since out of all the runtimes I've tested only Wasmer and wasmi have this behavior.  Native Linux also does not have this behavior.

Opening a file with O_TRUNC and O_APPEND together results in errno 28 `inval`. This is a result of the [host-fs `FileSystem`](https://github.com/wasmerio/wasmer/blob/master/lib/virtual-fs/src/host_fs.rs#L207) uses Rust `std::fs::OpenOptions`, which performs [this check](https://github.com/rust-lang/rust/blob/15755f38cd94f160713a6117829b0d1da2535b05/library/std/src/sys/unix/fs.rs#L1103).

I think Wasmtime doesn't have this behavior because it uses rustix which directly invokes the `open` syscall without this extra check.

```sh
$ zwasmer -vV; rustc -vV
wasmer 4.2.4 (0d782f1 2023-12-22)
binary: wasmer-cli
commit-hash: 0d782f18f99ba503f9aff89669c6ffd8e1631f53
commit-date: 2023-12-22
host: x86_64-unknown-linux-gnu
compiler: singlepass,cranelift
rustc 1.74.1 (a28077b28 2023-12-04)
binary: rustc
commit-hash: a28077b28a02b92985b3a3faecf92813155f1ea1
commit-date: 2023-12-04
host: x86_64-unknown-linux-gnu
release: 1.74.1
LLVM version: 17.0.4
```

### Steps to reproduce

Compile the snippet with wasi-sdk and run with wasmer, mounting a directory.

```c
#include <fcntl.h>
#include <stdio.h>

int main(void) {
    int fd = open("tmp/j", O_CREAT | O_RDWR | O_TRUNC | O_APPEND);
    if (fd == -1) {
        perror("open");
        return 1;
    }

    return 0;
}
```

### Expected behavior

It should create the file `tmp/j` and exit with no error.

### Actual behavior

> open: Invalid argument

**Comment by Arshia001** [comment]
@yagehu thanks for reporting this, it will be fixed in an upcoming release.

**Comment by maminrayej** [comment]
The combination of `O_TRUNC` and `O_APPEND` is considered nonsensical (more context is in the original [PR](https://github.com/rust-lang/rust/pull/30872) that implemented the functionality described in this [RFC](https://github.com/rust-lang/rfcs/pull/1252)). There is also a [clippy lint](https://rust-lang.github.io/rust-clippy/master/index.html#/NONSENSICAL_OPEN_OPTIONS) for it that [particularly prohibits combining these two flags](https://github.com/rust-lang/rust-clippy/blob/7fbaba856b711f9e945a59a4ba6647a973912564/clippy_lints/src/methods/open_options.rs#L170-L177).

But if it is desired to allow this combination, we have to bypass `OpenOptions` and call the `open` syscall directly.

cc @syrusakbary, @Michael-F-Bryan

**Comment by Arshia001** [comment]
Or, maybe we could detect the combination and keep only one of the two flags? I assume specifying both flags is undefined behavior in Linux?

**Comment by maminrayej** [comment]
When you combine `O_TRUNC` with `O_APPEND`, the file is first truncated when it's opened, and then all subsequent writes are appended to the end of the file. So, the behavior is well-defined, but it may not match the expectations of the user. So, I think returning an error is the right call here since combining these two doesn't have a practical use case anyway.

**Comment by Arshia001** [comment]
Well, yes, that's why rust gives you the error, but we're aiming for compatibility with the behavior of native binaries, be it as wrong or nonsensical as it may, so let's replicate the native behavior here.

**Comment by maminrayej** [comment]
Makes sense.

Then I think we should call the syscall directly.

**Comment by Arshia001** [comment]
@maminrayej keep in mind, Wasmer runs on Windows as well, so make sure any changes you make are also compatible with Windows.
