### ISSUE TITLE
Performance issue related to calling of standard output functions

### ISSUE THREAD

**Issue by ShuyaoJiang** [wasmerio/wasmer#4379]
### Summary
Hi, I ran the attached case (C program, compiled to Wasm by `Emscripten`) in different Wasm runtimes, and found abnormal performance in `Wasmer` compared with other runtimes. The execution time of this case (time interval from the start to the end of the execution of Wasm bytecode running command) on different runtimes is as follows:

- Wasmer: 1197ms
- Wasmtime: 13ms
- WasmEdge (AOT): 39ms
- WAMR (AOT): 33ms

#### Emscripten

- emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.49 (04a0cad4d4c9f5d62876821274d78cd0a52427af)
clang version 18.0.0 (https://github.com/llvm/llvm-project 269685545e439ad050b67740533c59f965cae955)
Target: wasm32-unknown-emscripten
Thread model: posix

#### Wasm Runtime Version

- Wasmer: 4.2.3
- Wasmtime: cli 15.0.0
- WasmEdge: 0.13.5
- WAMR: 1.2.3

#### Hardware & OS

- CPU: Intel(R) Xeon(R) E5-2686 v4 CPU @ 2.30GHz
- Memory: 16GB
- OS: Ubuntu 20.04.6 LTS

### Additional details
The attached source program is synthesized by a [Csmith](https://github.com/csmith-project/csmith) seed and a code snippet from another program. The inserted code snippet is on lines `56-61` of the source program, which is a statement calling a standard output function `fprintf()`. So, we think that this abnormal performance may be caused by some improper handling of this operation. Could you please check this situation? Thank you!

[1702321442279.zip](https://github.com/wasmerio/wasmer/files/13787663/1702321442279.zip)

**Comment by Arshia001** [comment]
Please see my comment on #4378
