### ISSUE TITLE
Runtime hooks

### ISSUE THREAD

**Issue by orsinium** [wasmerio/wasmer#4381]
### Motivation

I'm writing a programming language that compiles into WASM and uses wasmer as runtime for tests. There are several necessities I'd like to implement for the runtime:

1. **Coverage:** track which instructions were executed and how many times. Similar issue for wasmtime: https://github.com/bytecodealliance/wasmtime/issues/1151
2. **Debugger**: pause after certain instructions and inspect locals and the mutable globals. Similar issue: https://github.com/wasmerio/wasmer/issues/4174
3. **Profiler**: track how long each function took to execute.

### Proposed solution

A possible solution that covers all 3 use cases is to provide optional runtime hooks that are called with the current instruction offset and have access to the local and global registries (or provided the changes to the globals/locals since the last hook call). The runtime already knows this information, the only thing missed is the ability to hook into this.

### Alternatives

It is possible to work around the issue: emit on the transpiler side a call to the imported function with fixed arguments after each instruction, and then in runtime provide a host function that keeps track of the relevant changes. There are several problems with this approach:

1. The binary size doubles.
2. The binary is required to be modified. That means you can't take a faulty binary and debug it, you have to make a new one.
3. Instruction offsets change, which requires adjusting the DWARF offsets.
4. I'm sure I'm not the only one who can benefit from the feature, so it might be a good idea to implement it in the central place, which in this case is the runtime.

### Additional context

It's important to keep in mind the performance considerations. With the hooks provided, performance isn't a concern, considering the dev-only use cases for it. However, when no hooks are provided, the performance should stay as it is now, without the feature.

Oh, and Happy New Year! 🎄

**Comment by orsinium** [comment]
I don't have access to the linear workspace. I hope all relevant discussions happen here, on Github.

![image](https://github.com/wasmerio/wasmer/assets/9638362/247f4dbe-39a3-4b62-9b4c-8be1cf640876)

**Comment by Arshia001** [comment]
@orsinium don't worry, all discussion around open-source code always happens on Github. We use linear for our internal planning purposes only.

Regarding your proposed solution, since we use different compiler backends, it would be either impossible or very hard to translate the transpiled code back to the original WASM. However, one solution might be to add an interpreter backend to wasmer, which would allow us to have access to all the information we need to create a debugger. This will be very slow, but speed should not be a concern when debugging. The upside is that other backends are not affected and wasmer remains exactly as fast as it is right now.

**Comment by orsinium** [comment]
Today I was browsing wasmtime Rust API docs and I think such hooks can be already implemented in wasmtime with fuel consumption mechanism. Something like:

1. Enable [Config.async_support](https://docs.rs/wasmtime/latest/wasmtime/struct.Config.html#method.async_support)
2. Enable [Config.consume_fuel](https://docs.rs/wasmtime/latest/wasmtime/struct.Config.html#method.consume_fuel)
3. Set [Store.fuel_async_yield_interval](https://docs.rs/wasmtime/latest/wasmtime/struct.Store.html#method.fuel_async_yield_interval) to 1.

This, if I understand correctly, should yield code execution after almost every executed opcode (with a few exceptions, like nop). So, it should be possible to do that for cranelift without affecting the performance of non-instrumented code and without writing a new backend.

**Comment by Arshia001** [comment]
I'm not 100% familiar with cranelift, but I assume those settings will generate additional instrumentation code, same as we do for measuring instructions. That would mess up the instruction addresses, or at least require further translation and interpretation.

**Comment by orsinium** [comment]
Good point. I'll test it with wasmtime when I have time. Perhaps, changing instruction addresses isn't a problem as long as wasmer can show the original addresses in coredumps and stacktraces.
