### ISSUE TITLE
Add support for Haskell

### ISSUE THREAD

**Issue by ad-si** [wasmerio/wasmer#4399]
The latest versions of GHC include experimental support to compile to WebAssembly:
https://ghc.gitlab.haskell.org/ghc/doc/users_guide/wasm.html

**Comment by syrusakbary** [comment]
I believe Haskell now compiles to Wasm32-wasi so it should be possible to run the generated files directly with Wasmer (without any modification).

We'll keep this issue open until we test that the generated wasm32-wasi file work properly

**Comment by syrusakbary** [comment]
@ad-si do you mean running Wasm inside of Haskell? Or running haskell compiled to wasm with Wasmer?

The solution you posted is mainly for the latter, but it may be useful to have the former as well (running Wasm inside of Haskell via Wasmer). If that's the case please let us know on this thread

**Comment by ad-si** [comment]
I actually meant running Wasm inside of Haskell (referring to the table in the readme: https://github.com/wasmerio/wasmer#wasmer-sdk).
I just realized that compiling Haskell to Wasm is of course irrelevant for that 😅
But still interesting to know whether generated wasm32-wasi file work!

So maybe let's keep this issue for executing Haskell compiled to Wasm and open a new one for running Wasm inside of Haskell?
