### ISSUE TITLE
Wasix subprocess example on Windows crashes without any output

### ISSUE THREAD

**Issue by andrzejressel** [wasmerio/wasmer#4400]
### Describe the bug

Running subprocess wasix example on Windows does not output anything.

```sh
PS C:\wasix-rust-examples\wasix-subprocess> wasmer -vV
wasmer 4.2.5 (0460050 2023-12-23)
binary: wasmer-cli
commit-hash: 04600507844bae978239531c8e6265d410aefe6d
commit-date: 2023-12-23
host: x86_64-pc-windows-msvc
compiler: singlepass,cranelift,llvm
PS C:\wasix-rust-examples\wasix-subprocess> rustc -vV
rustc 1.74.0 (79e9716c9 2023-11-13)
binary: rustc
commit-hash: 79e9716c980570bfd1f666e3b16ac583f0168962
commit-date: 2023-11-13
host: x86_64-pc-windows-msvc
release: 1.74.0
LLVM version: 17.0.4
```

### Steps to reproduce
1. Clone https://github.com/wasix-org/wasix-rust-examples
2. Open wasix-subprocess in terminal
3. Run `cargo wasix build --release`
4. Run `wasmer run .`

### Expected behavior
Either ls outputs something or crash with visible stacktrace

### Actual behavior
Nothing 
```
PS C:\wasix-rust-examples\wasix-subprocess> wasmer run .
PS C:\wasix-rust-examples\wasix-subprocess> wasmer run .
PS C:\wasix-rust-examples\wasix-subprocess> wasmer run .
PS C:\wasix-rust-examples\wasix-subprocess> wasmer run .
PS C:\wasix-rust-examples\wasix-subprocess> wasmer run .
```

### Additional context

I'm sure it crashes, because after adding some debug printlns
```
use std::process::Command;

fn main() {
    std::env::set_var("PATH", "/bin");

    let mut cmd = Command::new("ls");
    cmd.arg("-l");

    println!("TEST1");
    let output = cmd.output();
    println!("TEST2");
}
```

Output is
```
PS C:\wasix-rust-examples\wasix-subprocess> wasmer run .
TEST1
```

**Comment by syrusakbary** [comment]
Hey @andrzejressel, by default the commands available will be added in the `/bin` directory depending on the Wasmer dependencies.

Although it seems that your command should either print an error or succeed, but is doing neither, so we need to investigate further.

Would you mind sharing the `wasix-subprocess` repository so we can also check the `wasmer.toml` file used? Thanks!

**Comment by maminrayej** [comment]
The issue seems to be fixed on later releases, since I can see the error by running the `wasix-subprocess` example:
```
$ ./target/release/wasmer.exe run wasix-subprocess.wasm
wasm execute failed [/bin/ls] - could not find binary '/bin/ls'
status: exit code: 11264
stdout:
stderr:
```

Also, when I run the package with the core-utils dependency, I see the expected result:
```
$ wasmer run .
status: exit code: 0
stdout: ---------- 1 somebody somegroup 0 Aug 22 21:29 bin
---------- 1 somebody somegroup 0 Aug 22 21:29 dev
---------- 1 somebody somegroup 0 Aug 22 21:29 etc
---------- 1 somebody somegroup 0 Aug 22 21:29 tmp
---------- 1 somebody somegroup 0 Aug 22 21:29 usr

stderr:
```

@andrzejressel feel free to reopen if the issue happened again.
