### ISSUE TITLE
Edge-CLI: The `wasmer app logs`: panic when no logs present

### ISSUE THREAD

**Issue by theduke** [wasmerio/wasmer#4417]
It appears the `wasmer app logs` command can currently run into a situation where retrieving the logs panics.

## Reproduction

```
`wasmer app create -t static-website ...
wasmer app logs XXX
```

```
thread 'main' panicked at 'range end index 1000 out of range for slice of length 10', /home/theduke/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmer-edge-cli-0.1.4/src/cmd/app/logs.rs:113:25
```

**Comment by theduke** [comment]
cc @maminrayej , might this be related to your recent refactoring?

**Comment by maminrayej** [comment]
Do you mean the metrics refactor? I don't think so.
Doesn't this command just send a request to backend? If so, I just added the `--watch` flag to the code path.
I'll investigate.
