### ISSUE TITLE
Mobile compatible wasmer engine

### ISSUE THREAD

**Issue by abe-njama** [wasmerio/wasmer#4432]
Thanks for proposing a new feature!

### Motivation

[Holochain](https://github.com/holochain) is currently working on a long-term project to run Holochain on Mobile devices and during our initial phase of development and discovery, we ran into Interpreted wasm issues related to iOS. While `wasmer` supports JavascriptCore, Apple has dropped support for `webassembly` and will not be bringing it back.

### Proposed solution

Either
1. Holochain could help Wasmer implement an interpreter backend or,
2. Holochain could help Wasmer implement a bridge to `WKWebView`

### Alternatives

Holochain could re-add `wasmi` as a possible `wasm` engine behind a feature flag. Based on the [poll](https://github.com/wasmerio/wasmer/discussions/3839), potential support for `Wasmi` seems to be ranking low. Although this could also be considered based on the evaluation of any model that Wasmer may propose to support `Wasmi` for the long-term.

### Additional context

Looking at points 2 and 3, does Wasmer have a model that allows open source projects, like Holochain, to benefit from the support of the Wasmer maintainers and community of Contributors to implement such specific requests?

cc @guillemcordoba @thedavidmeister @zippy

**Comment by syrusakbary** [comment]
Adding support for an interpreter toolchain is probably the lowest hanging fruit.

Feel free to schedule a call in https://cal.com/syrus so we can organize further

**Comment by abe-njama** [comment]
Thanks @syrusakbary I've scheduled a call for Monday 5th at 1.30PM.

**Comment by Arshia001** [comment]
@syrusakbary any updates from your meeting?
