### ISSUE TITLE
Upgrade to tlsv2

### ISSUE THREAD

**Issue by Avey777** [wasmerio/wasmer#4437]
Upgrade to tlsv2

```
(base) root@Jengro:~# curl https://get.wasmer.io -sSfL | sh
curl: (35) OpenSSL/3.0.11: error:0A000438:SSL routines::tlsv1 alert internal error
(base) root@Jengro:~# 
```

https://github.com/curl/curl/issues/10002

**Comment by theduke** [comment]
Hey @Avey777 , according to this our servers are fine: https://www.ssllabs.com/ssltest/analyze.html?d=get.wasmer.io&s=34.138.171.137

You might have seen an intermittent failure.
