### ISSUE TITLE
WASI Preview 2 Support

### ISSUE THREAD

**Issue by theduke** [wasmerio/wasmer#4439]
Add support for WASI preview 2.

https://github.com/WebAssembly/WASI/tree/main/preview2

Preview 2 has significant changes, most notably a switch to the component model.
Supporting the component model will require a significant amount of work.

The implementation must be additive: the previous WASI version must still be supported.

**Comment by trcrsired** [comment]
hi. can you tell me how preview2 abi works? I do not think it is well documented since i am trying to see whether i can implement component model in wavm.

**Comment by HarikrishnanBalagopal** [comment]
> hi. can you tell me how preview2 abi works? I do not think it is well documented since i am trying to see whether i can implement component model in wavm.

https://github.com/WebAssembly/component-model/blob/main/design/mvp/CanonicalABI.md
https://github.com/WebAssembly/component-model/blob/main/design/mvp/Binary.md
