### ISSUE TITLE
Fetching logs for an app fails

### ISSUE THREAD

**Issue by ayys** [wasmerio/wasmer#4442]
When fetching logs for an app that have many log entries, the CLI fails with the following error messsage,

```sh
$ wasmer app logs <app-name>
thread 'main' panicked at 'range end index 1000 out of range for slice of length 10', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-edge-cli-0.1.4/src/cmd/app/logs.rs:113:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I've made sure there are logs for the app, and those logs can be fetched via the registry.

### Steps to reproduce
```sh
$ wasmer app logs <app-name>
thread 'main' panicked at 'range end index 1000 out of range for slice of length 10', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-edge-cli-0.1.4/src/cmd/app/logs.rs:113:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Expected behavior
Logs for the app should appear.

### Actual behavior
The CLI errors out.

Could be related to #4441

**Comment by maminrayej** [comment]
I don't think it is related to #4441, since @theduke reported the same [issue](https://github.com/wasmerio/wasmer/issues/4417) a week ago.

I'll investigate today.
