### ISSUE TITLE
Broken on nightly because of ahash 0.7 (aka "update hashbrown")

### ISSUE THREAD

**Issue by Manishearth** [wasmerio/wasmer#4445]
`ahash@0.7` is as of yesterday broken on Rust nightly, even if you do not choose to opt in to its nightly features, because it autoenables features in build.rs. See https://github.com/tkaitchuck/aHash/issues/200.

This problem is fixed in `ahash@0.8`. However, this crate and its dependencies use ahash 0.7 via `hashbrown@0.11` and `hashbrown@0.12`, used by  `object@0.28` and `indexmap@1.9` respectively. `object@0.32` and `indexmap@2.0` are up to date.

Ideally wasmer should be updated to use the latest `hashbrown`.

I do have some alternate ways of solving this problem:

 - Fix in ahash: https://github.com/tkaitchuck/aHash/pull/202
 - Fix in hashbrown: https://github.com/rust-lang/hashbrown/pull/497 https://github.com/rust-lang/hashbrown/pull/498

however I think it's worth updating hashbrown anyway.

This breaks older versions of `wasmer` as well, ideally these deps can be updated for the wasmer 2.x and 3.x series.

Thanks!

**Comment by Manishearth** [comment]
This also needs fixing https://docs.rs/cranelift-egraph/latest/cranelift_egraph/

**Comment by theduke** [comment]
Thanks for the ping.
This will require some annoying dependency juggling.

**Comment by theduke** [comment]
So it seems hashbrown has fixed this in `0.7.8`, which means users can run `cargo update` and things will work.

We will also update the lockfile to have `ahash@0.7.8` reflected in there.

**Comment by theduke** [comment]
Closing as fixed upstream.
