### ISSUE TITLE
Login: error when HTTPS_PROXY is set

### ISSUE THREAD

**Issue by re-xmyl** [wasmerio/wasmer#4479]
### Summary
i couldn't to login 

### Additional details
wasmer login
error: failed to setup proxy for reqwest Client
╰─▶ 1: Could not connect to proxy: builder error: unknown proxy scheme

$ echo $https_proxy
https://127.0.0.1:7890/
$ echo $http_proxy
http://127.0.0.1:7890/

the proxy actually works good.
how to  fix my question?

**Comment by theduke** [comment]
HTTPS proxies should work just fine in theory, we will need to look into the cause of the issue.
