### ISSUE TITLE
Investigate potential WASIX breakage due to Rust 1.77 u128 alignment changes

### ISSUE THREAD

**Issue by theduke** [wasmerio/wasmer#4500]
Rust 1.77 will change the alignment of i/u128 to 16 bytes on x86.

We use u128 in exactly one place in WASIX, namely in the [StackSnapshot](https://github.com/wasmerio/wasmer/blob/b17ce9a3cdeea24ff7e432e419e5c89c7524b6ae/lib/wasi-types/src/wasi/wasix_manual.rs#L111).
This may cause breakage due to alignment shifts in the struct.

We need to investigate if this will break anything.

**Comment by syrusakbary** [comment]
One possible solution: use two u64 to represent it
