### ISSUE TITLE
Investigate and mitigate flaky TCP tests

### ISSUE THREAD

**Issue by theduke** [wasmerio/wasmer#4504]
We have some failing TCP tests in virtual-net , that previously already caused problems on musl and where disabled on that architecture, but now seem to fail in Linux as well.

We need to investigate.

If the flakiness is caused by tests interfering with each other, we can configure nextest to do automatic retries.

Example: https://github.com/wasmerio/wasmer/actions/runs/8316343390/job/22755708194?pr=4491#step:12:3197

**Comment by syrusakbary** [comment]
This is an hypothesis: the tests should be run serially, and if they are running in parallel (because of `cargo-nextest`) then this issue might arise

**Comment by syrusakbary** [comment]
We can probably mark it as a flaky test for 4.3
