### ISSUE TITLE
Investigate failing package compilations when using Singlepass

### ISSUE THREAD

**Issue by xdoardo** [wasmerio/wasmer#4516]
We got the result from `argus`' tests. Out of the 4090 tested packages 29 are failing to compile. Out of these 29, 5 are due to the use of V128 types. We shall investigate the remaining 24 tests and see if they compile correctly with other backends (i.e. cranelift to start with). 

Side quest: re-run the tests targeting x86_64.

**Comment by syrusakbary** [comment]
After investigation, the findings are reflected in: #4519
