### ISSUE TITLE
Time going backwards???

### ISSUE THREAD

**Issue by bjorn3** [wasmerio/wasmer#453]
### Describe the bug

```
thread 'main' panicked at 'supplied instant is later than self', src/libcore/option.rs:1036:5
```

### Steps to reproduce
1. Unpack [rustc_binary.wasm.zip](https://github.com/wasmerio/wasmer/files/3193868/rustc_binary.wasm.zip).
2. ```
   wasmer run rustc_binary.wasm --backend singlepass --dir . --dir $(rustc --print sysroot)  -- example.rs --sysroot $(rustc --print sysroot) -Zcodegen-backend=metadata_only --target x86_64-unknown-linux-gnu
   ```

### Expected behavior

No panic.

### Actual behavior

Panic.

### Additional context

Using Rust + WASI.

**Comment by bjorn3** [comment]
It seems to work every now and then.

**Comment by MarkMcCaskey** [comment]
Thanks for the report!  I'll add a regression test that exercises the clock code!

**Comment by MarkMcCaskey** [comment]
Okay, so I've figured out the issue!

There are two bugs with our time implementation:
- we were ignoring seconds
- we had the wrong IDs for clocks due to an assumption we made from the docs (https://github.com/WebAssembly/WASI/pull/41)
