### ISSUE TITLE
Work with (or take code and ideas from) https://github.com/nebulet/nebulet

### ISSUE THREAD

**Issue by leiserfg** [wasmerio/wasmer#46]

**Comment by appcypher** [comment]
Your issue does not provide clear describe in sufficient details what the ideas or code should. There are a lot of interesting things about nebulet, but not all of them will be appropriate for this project.
And Lachlan is a core contributor already so he's given/implemented numerous ideas from nebulet. The revamped heap impl is one easy example that comes to mind.
