### ISSUE TITLE
Reading directory permissions

### ISSUE THREAD

**Issue by willemneal** [wasmerio/wasmer#462]
### Summary

I'm currently implementing `ls`.  From my top level directory I invoke wasmer like this:
```
$ wasmer run --dir=./dist -- dist/ls.wasm ..
./dist/../.git
./dist/../.gitignore
```
From my understanding of Wasi, I thought that the directory you preopen became the root of the directory structure you're allowed to read.

**Comment by MarkMcCaskey** [comment]
Yeah, that's correct!  We should not be allowing files outside of the preopened directories to be accesed.  I'll look in to this -- thanks for bringing it to our attention!

**Comment by MarkMcCaskey** [comment]
To follow up on 
> I thought that the directory you preopen became the root of the directory structure you're allowed to read.

that's correct, but as far as I'm aware the behavior between multiple preopened dirs is not defined right now.  libpreopen seems to be making some assumptions and there are weird edge cases.  I've been meaning to investigate this and the wasi sysroot more but haven't had a good opportunity to yet.  I filed an issue on wasmtime's repo https://github.com/CraneStation/wasmtime/issues/111 .  

Also,  I haven't been able to reproduce this on wasmer's master branch yet:
```
$ cargo run --bin wasmer --release -- run ~/etc/hello-wasi/list-files.wasm --dir=./src -- src
"src/bin"
"src/installer"
"src/lib.rs"
"src/update.rs"
"src/utils.rs"
"src/webassembly.rs"
```

with list-files.rs being:
```Rust
use std::fs;

fn main() {
    let args = std::env::args();
    let dir = args.skip(1).next().unwrap();
    let read_dir = fs::read_dir(dir).unwrap();
    for entry in read_dir {
        println!("{:?}", entry.unwrap().path());
    }
}
```

**Comment by MarkMcCaskey** [comment]
I just reproduced it!  Yeah, that's bad

**Comment by willemneal** [comment]
It's all good.  Perhaps there should be a set of binaries designed to test capabilities, so that you could compare across runtimes.

**Comment by MarkMcCaskey** [comment]
That's a great idea!  People have mentioned creating spectests for WASI and I'm excited to help out there; I think that's probably still a few months away at the very least though.
