### ISSUE TITLE
Support partial `[package]` section in `wasmer.toml`

### ISSUE THREAD

**Issue by ayys** [wasmerio/wasmer#4626]
For unnamed packaged, we need to add support for certain fields, but not others. `wasmer.toml` should support two kinds of `[package]` sections:

## A minimal named `package` section

```
[package]
name = "someone/something"
version = "1.1.1"
```

## A minimal unnamed `package` section

```
[package]
```

## Invalid `package` section

```
[package]
version = "0.1.1"
```

## Valid `package` section

```
[package]
name = "someone/something" # this could be supported as publishing a hash to this package
```

**Comment by xdoardo** [comment]
Closing, resolved by https://github.com/wasmerio/wasmer/pull/4630.
