### ISSUE TITLE
llvm backend for android

### ISSUE THREAD

**Issue by tkkcc** [wasmerio/wasmer#4637]
attempt to ship wasmer runtime in an android app, the demo code on doc work. when i switch to llvm compiler, `llvm-sys` fail to compile.

reproduce commit: https://github.com/tkkcc/GameBot/tree/369c821d6d880df7273b7355234b20dbd297c941

the following build error says to set `LLVM_SYS_150_PREFIX`, i wonder how to do next for android. or is it even possible.

```txt
Compiling llvm-sys v150.1.3
error: No suitable version of LLVM was found system-wide or pointed
              to by LLVM_SYS_150_PREFIX.
       
              Consider using `llvmenv` to compile an appropriate copy of LLVM, and
              refer to the llvm-sys documentation for more information.
       
              llvm-sys: https://crates.io/crates/llvm-sys
              llvmenv: https://crates.io/crates/llvmenv
   --> /home/bilabila/.cargo/registry/src/index.crates.io-6f17d22bba15001f/llvm-sys-150.1.3/src/lib.rs:489:1
    |
489 | / std::compile_error!(concat!(
490 | |     "No suitable version of LLVM was found system-wide or pointed
491 | |        to by LLVM_SYS_",
492 | |     env!("CARGO_PKG_VERSION_MAJOR"),
...   |
499 | |        llvmenv: https://crates.io/crates/llvmenv"
500 | | ));
    | |__^

error: could not compile `llvm-sys` (lib) due to 1 previous error
```

**Comment by syrusakbary** [comment]
It shall be possible to include Wasmer + LLVM for Android, although we recommend on this case to use Cranelift or Singlepass as LLVM might be too heavy.

If you want to use LLVM compiler with Wasmer here, you'll need to set up the `LLVM_SYS_150_PREFIX` when compiling the crate, pointing to your local LLVM 15
