### ISSUE TITLE
Revisit --mapdir

### ISSUE THREAD

**Issue by MarkMcCaskey** [wasmerio/wasmer#464]
We recently implement `--mapdir` to allow renaming of preopened directories in the guest context.

We used the same order that wasmtime uses to be compatible.  (guest path : host path).  Given how things like docker and now wapm package filesystem declarations work, this order is a bit confusing.

We should consider having a preferred flag with the reverse direction or just break compatibility with wasmtime.

If you feel strongly either way, please leave a comment here!

**Comment by tiborvass** [comment]
This was one of the most confusing thing for me when I started playing with WASI !

**Comment by MarkMcCaskey** [comment]
To be honest, I'm still confused by it.  I only remember it by the fact that I typed `--mapdir=.:some/directory` to map some directory to my current directory one time

**Comment by MarkMcCaskey** [comment]
If you think about it from the perspective of the VM, it looks just like the hashmap it would use to look them up!

that's my rationalization of it.

The other direction makes more sense from a user perspective I think

**Comment by Hywan** [comment]
Closing this issue as it seems old now.
