### ISSUE TITLE
Feature: FS with flock/fcntl primitive support

### ISSUE THREAD

**Issue by tracker1** [wasmerio/wasmer#466]
### Motivation

There are a lot of libraries and functionality that require primitive file system access that includes flock and fcntl support.  A most recent one would be in order to implement LevelDB in WebAssembly.  There are a lot of legacy software, where porting to a more common runtime (wasm) would be a huge boon for portability.

The unix fcntl and flock libraries initially which are available on most Linux and BSD based platforms.

### Proposed solution

Work with emscripten, rust and other transpiler communities to extend virtual file system support to include references for fcntl and flock libraries for file-level and in-file range locks.

Unix environments should passthrough to the system librraries (if available), Windows should translate to the corresponding win32 api calls in the wasmer runtime.   Transpiled code should support fcntl/flock primarily and leave the win32 code un-translated in practice.

### Alternatives

I'm not aware of any clear paths in this context.

### Additional context

Behavior is described as "optional" in terms of implementation underneath, but in practice should have actual behavior utilizing the system libraries (as available) for this, with translation to the Win32 API provided by the wasm runtime.

**Comment by Hywan** [comment]
Hello,

`fcntl` is supported by the WASI-libc (so `clang`, `zig` and probably others), and is using `__wasi_fd_fdstat_get` and `__wasi_fd_fdstat_set_flags`, which are supported by [the `wasmer-wasi` crate](https://github.com/wasmerio/wasmer/tree/ec36089cbf4a65b768501ba38f3d63baad6badf3/lib/wasi).

Thank you for having opened this issue :-).
