### ISSUE TITLE
Security Reporting

### ISSUE THREAD

**Issue by willemneal** [wasmerio/wasmer#468]
### Motivation

I recently found a permissions issue.  Since this project is still in its early stages I think it's fine to publish these types of bugs as issues.  However, as it becomes more widely used then different versions of the runtime will be used in production.  Then it's a good idea to report security bugs more discretely.

### Proposed solution

Github now has a security reporting tab for just this purpose.

**Comment by syrusakbary** [comment]
I just added a [Security Policy file](https://github.com/wasmerio/wasmer/blob/master/SECURITY.md) with a link to draft a Security Advisory using Github:

https://github.com/wasmerio/wasmer/security/advisories/new

Hope this is a good first step!
Let us know if you have more suggestions :)

**Comment by willemneal** [comment]
Awesome!  I just tried the link and got a 404 error.  Could it be a permissions issue for the page?

**Comment by syrusakbary** [comment]
Oh! It seems Github only exposes this to Wasmer admins.

I just fixed the text to reflect a better way (using email):
> To report a security issue, email security@wasmer.io and include the word "SECURITY" in the subject line.
