### ISSUE TITLE
wasmer deploy fails with named local package and rejected package bump

### ISSUE THREAD

**Issue by theduke** [wasmerio/wasmer#4707]
### Describe the bug

Can't deploy with local named package without a version bump.

### Steps to reproduce

wasmer.toml:
```
[package]
name = "wasmer-tests/static-site"
version = "0.1.0"
description = "wasmer-tests/static-site website"

[dependencies]
"wasmer/static-web-server" = "^1"

[fs]
public = "public"
```

app.yaml:
```
name: xxx
owner: xxx
package: .
kind: wasmer.io/App.v0
```

* `wasmer deploy`
* Do you want to bump the package? => SELECT NO

=> ERROR
```
 endpoint=https://registry.wasmer.io/graphql
error: GraphQL query failed
╰─▶ 1: GraphQL API failure: This version of the package `wasmer-tests/static-site@0.1.0` already exists.
```

### Expected behavior

Command does not try to re-publish, but just uses the existing version.

### Actual behavior

Tries to republish, fails.

**Comment by syrusakbary** [comment]
Use case: a user has a named package, and want to publish (for testing) an unnamed package meanwhile (before bumping the version)
