### ISSUE TITLE
Support for FreeRTOS

### ISSUE THREAD

**Issue by SeaRoll** [wasmerio/wasmer#4742]
### Motivation

wasm-micro-runtime seems to support nuttx/freertos. are there any plans for wasmer to support freeRTOS? or what kind of limitations does exist regarding wasmer supporting FreeRTOS? Would be grateful for future references to see what kind of work is needed if this is in the timeline.

**Comment by syrusakbary** [comment]
Hey @SeaRoll ,

I assume your use case for Wasmer in NuttX/FreeRTOS would run in ESP32/ESP32-S2 chipsets.
If that's the case, then we would need the following:
1. Compiler support for ESP32 chipsets / OR / General interpreter support in Wasmer
2. (only needed for the compiler case) Support for the FreeRTOS in the Wasmer Virtual Machine (in case we need to hook in the trap controllers)
3. Enjoy

**Comment by SeaRoll** [comment]
Thank you so much! Seems like a great insight 😄
