### ISSUE TITLE
Downloading from github release is too slow

### ISSUE THREAD

**Issue by namse** [wasmerio/wasmer#4748]
"curl https://get.wasmer.io/ -sSfL | sh" seems to be trying to download Wasmer from the GitHub release.
I live in Korea, and I'm not sure if this is a problem specific to Northeast Asia, but it's too slow to download Wasmer.
I hope the download speed for Wasmer could be faster.

After downloading Wasmer, around 20% through, I attempted to write about this issue in my clumsy English and even sought an AI's review, but alas, the download still lingers at a mere 50% completion. For us Koreans, the so-called 'fast folk,' such a pace is simply unbearable! Haha!

**Comment by namse** [comment]
`https://github.com/wasix-org/rust/releases/download/v2023-11-01.1/rust-toolchain-x86_64-unknown-linux-gnu.tar.gz` is toooooo slow, more than 20 minutes.

**Comment by syrusakbary** [comment]
One of the things that we can do is to create a new flag `--use-edge` to the [wasmer-installer](https://github.com/wasmerio/wasmer-install)  that will request the file from the Wasmer Edge instead (as a proxy).

Kind of

```bash
$ curl https://get.wasmer.io/ -sSfL | sh --use-edge
Using https://installer-proxy.wasmer.app/ to download "https://github.com/wasix-org/rust/releases/download/v2023-11-01.1/rust-toolchain-x86_64-unknown-linux-gnu.tar.gz"
...
```

That way we could  speed up the download in such cases. Note that Wasmer Edge has nodes in Japan so hopefully that will provide faster times

**Comment by namse** [comment]
Is it only physical distance problem? I mean, is it fast in America or Europe?

**Comment by syrusakbary** [comment]
In America and Europe is very fast

**Comment by namse** [comment]
Something changed. Github release became very fast in Korea. hmmmm..
