### ISSUE TITLE
Use `wasmer` crate without `clap` dependency?

### ISSUE THREAD

**Issue by dsherret** [wasmerio/wasmer#4750]
### Summary

The wasmer 4.3.1 crate depends on wasmer-types 4.3.1, which depends on webc 6.0.0-alpha9, which has a pinned dependency on clap `=4.4.11` -- https://crates.io/crates/webc/6.0.0-alpha9/dependencies - This causes issues when dependending on clap `4.5x`.

Is there a way to use the `wasmer` crate without `clap`?

**Comment by syrusakbary** [comment]
That’s a great call, I don’t think Wasmer should depend on clap at all. We’ll investigate and fix

**Comment by syrusakbary** [comment]
Ok, after further investigation, wasmer-wasix depends on webc which depends on clap.

clap shall not be a mandatory dependency on webc. We should have a `webc-cli` crate for that, and remove any clap dependencies from `webc`.
