### ISSUE TITLE
type mismatch: values remaining on stack at end of block 

### ISSUE THREAD

**Issue by yizhuoliang** [wasmerio/wasmer#4757]
Hi, so I compiled a simple helloWorld.c into .wasm with my own libc (which is likely the cause of the issue). Then when I use Wasmer to run the .wasm module, I got the error

```
root@2299d4e20d1f:/lind-glibc/replace-sysroot/test# /wasmer/target/debug/wasmer run newhello.wasm
error: Unable to compile "newhello.wasm"
╰─▶ 1: Validation error: type mismatch: values remaining on stack at end of block (at offset 0x26a)
```

What does this error mean, and usually what is the cause of such error?

Thank you!

**Comment by yagehu** [comment]
Not maintainer. Just to answer your question. Wasm is a stack machine with an implicit stack. So an instruction like `i32.const 10` pushes a 32-bit integer with a value of 10 onto the stack. An instruction like `i32.add` pops 2 values off the stack, adds them, and pushes the result back onto the stack. This error can occur if the generated wasm did not "typecheck" (validate) successfully and there are values remaining on the stack. So a good block without any values remaining may look like:

```
i32.const 1 ; 1 value on the stack
i32.const 2 ; 2 values on the stack
i32.add     ; 1 value on the stack
drop        ; no values on the stack. All good!
```

**Comment by yizhuoliang** [comment]
Oh thank you for this information, yeah, I think I have a sense of what's wrong here. I think if I go over the components carefully, I can figure the error out. But I'm also wondering if there are some easier way to ping-poing the issue. When I use wasm2wat on the newhello.wasm, I got more detailed error description of the mismach
```
root@2299d4e20d1f:/lind-glibc/replace-sysroot/test# wasm2wat newhello.wasm -o newhello.wat
newhello.wasm:00001c6: error: type mismatch at end of function, expected [] but got [i32, i32]
```
Then is there a way to know what is this function that causes this?

**Comment by yizhuoliang** [comment]
Okay I see a good way, while `wasm2wat` checks the stack issue and give the offset of where the error occurs, we can use `wasm-objdump -d` to look at the offset position in the file, and know which function is causing the type mismatch

**Comment by theduke** [comment]
@yagehu thanks for jumping in...
