### ISSUE TITLE
CLI: "wasmer deploy" does not allow specifying a particular app.yaml anymore

### ISSUE THREAD

**Issue by theduke** [wasmerio/wasmer#4845]
In the recent refactors, "wasmer deploy" has lost the option to specify the path
to a speciic `app.yaml`.

Not having that option is annoying when you have multiple app.yamls for one package,
since it requires creating a separate sub-directory for each app...

**Comment by xdoardo** [comment]
The `--dir` flag allows to pass a path to the `app.yaml` file. 
We either: 
1. Change `--dir` to `--path` (breaking)
2. Leave `--dir` as it is and add `--path`

**Comment by theduke** [comment]
Option 2 sounds good to me.
