### ISSUE TITLE
Use `wasmer` crate without `toml`, `serde_yaml` and `tar` crates?

### ISSUE THREAD

**Issue by dsherret** [wasmerio/wasmer#4886]
### Summary

Just a followup to https://github.com/wasmerio/wasmer/issues/4750

I tried upgrading again, but:

* the `webc` crate that `wasmer-types` depends on pulls in `toml 0.7.8` and also `wasmer-config` which pulls in `toml 0.8.14`
* `webc` also pulls in `tar`
* `wasmer-config` pulls in `serde_yaml`

I kind of feel like all these dependencies should be unnecessary for just using the runtime?

**Comment by syrusakbary** [comment]
Indeed, those libraries shouldn’t be needed

**Comment by syrusakbary** [comment]
This was caused by having a `webc` dependency in the `wasmer-types` as you mentioned.

This issue was also exposed in #5041 and fixed in #5043. The fix is now in `main` and will be live in the next release of Wasmer
