### ISSUE TITLE
wasmer cli login has no security confirmation or CSRF protection

### ISSUE THREAD

**Issue by bitnom** [wasmerio/wasmer#4978]
Upon issuing the `wasmer login` command you are given a link for authorizing wasmer cli to access your account. Visiting the authorization link immediately grants access to your wasmer.io account without any confirmation dialog.

This is a security vulnerability since an attacker could craft a web page to load their authorization link in an iframe, obfuscated window, or redirect in order to gain control of the account.

Visiting a wasmer.io auth link should prompt the account holder with a confirmation button. Additionally, the button's action/endpoint should be protected from CSRF attacks.

**Comment by syrusakbary** [comment]
That's a good call. This should be approved by the user first. We'll work on this asap

**Comment by syrusakbary** [comment]
We just fixed this on production, thanks for reporting it @bitnom
