### ISSUE TITLE
Switch winapi dependency to windows/windows-sys

### ISSUE THREAD

**Issue by atouchet** [wasmerio/wasmer#4998]
The winapi crate is no longer maintained and there are now official windows/windows-sys crates from Microsoft. wasmer should transition from using winapi to windows/windows-sys.

**Comment by xdoardo** [comment]
Thanks for the suggestion. We won't have much time to work on this in the near future, but we'll be glad to accept contributions.

**Comment by maminrayej** [comment]
Thanks for opening the issue. This is resolved by #5001.
