### ISSUE TITLE
Use ___chkstk_ms for MinGW instead

### ISSUE THREAD

**Issue by ArchGuyWu** [wasmerio/wasmer#5002]
### Describe the bug

compiler-builtins defines [___chkstk_ms](https://github.com/rust-lang/compiler-builtins/blob/master/src/x86_64.rs#L16) for MinGW, while wasmer uses [___chkstk](https://github.com/wasmerio/wasmer/blob/main/lib/vm/src/probestack.rs#L45) for MinGW, which caused `ld.lld: error: undefined symbol: ___chkstk` when building.

**Comment by xdoardo** [comment]
Thanks for the report. We won't have much time to work on this in the near future, but we'll be glad to accept contributions.

**Comment by maminrayej** [comment]
Closing as the fix should be in the 4.3.6 release.
