### ISSUE TITLE
Add option to installer to keep dotfiles unchanged

### ISSUE THREAD

**Issue by tforgione** [wasmerio/wasmer#501]
### Motivation

Some people prefer to edit their dotfiles manually, and don't want the install script to mess with their dotfiles. Furthermore, when someone runs `wasmer self-update`, if a new version of wasmer is found, their dotfiles will be modified.

### Proposed solution

I guess the solution used in rust's installer is the best: it adds some interactive options and one can choose if they want to have their dotfiles modified or not. I guess the updater can be called with options so that the dotfiles are not modified.

**Comment by MarkMcCaskey** [comment]
That's a good idea!  Thanks for letting us know about this use case -- it's easy to overlook things like this!
