### ISSUE TITLE
cmdline installer for windows

### ISSUE THREAD

**Issue by KnicKnic** [wasmerio/wasmer#507]
### Motivation

cmdline is so much quicker than going to release page and downloading

### Proposed solution
Update page https://wapm.dev/help/install with a quick powershell script to install wamp, see https://chocolatey.org/install for an example.

### Alternatives

I would love to see Chocolatey support as well. The project I linked to is a a package manager for windows. There is nothing easier than using a package manager to install a package manager.

**Comment by syrusakbary** [comment]
We added a CMD installer in `master`.

You can now install Wasmer via the Powershell:

```powershell
iwr https://win.wasmer.io -useb | iex
```

You can find more install instructions here:
https://github.com/wasmerio/wasmer-install
