### ISSUE TITLE
Proctec authors

### ISSUE THREAD

**Issue by cancerberoSgx** [wasmerio/wasmer#511]
Guys, with the objective to make your initiative sucessfull, I take the boldness to give you this feedback, maybe too soon but I think is important and I know you are doing this with good intentions and hopefully succeeds solving this which I consider is a problem: **protect the authors**. 

Concretely I think a wasm repository like yours besides the publisher and the person who implement the wasm port, **above all must mention the original C/C++ authors**. 

I'm asking because I read the docs in you website and it didn't mention anything about authoring the only paragraph that way "author" is referring to publisher.

I think it is disrespect full not to mention the original C/C++library authors that probably don't nothing about this package manager, perhaps even about webassembly but they are authors. 

As a user if I install a wasm package I want to see both names, source library and porter and you might not ben mentioning neither, just the publisher. 

O realy think its a good initiative, and hope it solves the problem but **people won't be secure to start publish their packages if like currently they see as authors the owners of forks and names of people deserving that mention are not represented at all** (and original  licensing)

The only relevant paragraph I found is one mentioning that you won't be responsible  for if the information/licensing deliered to the person that install the package is missleading, etc and that might be fine but again, you are not mentioning detriment the **distribution might cause on the REAL AUTHORS**. Are you responsible when people violate the ownership/licensing ? 

You are dealing with a special situation here and as I hope you might grow from one day to another exponencially, I'm not saying you whould be responsible but personallyas a the user installing a package, if tomorrow for exapmle I intall WASM-ImageMacigk using wasmer and I don't see the knink and dlemstra, (and a very long list in this case), I expect you provide me with some tools to denounce that user and be sure it won't register again.

I could not found that kind of details in the website.

I know yuy have support to denounce projects at github level, but I don't think this is enough. 

And secondary, IMO you will deal with a new situation that didn't happen with npm, since as the first of its kind, **authors always had the opportunity to publish their projects before anybody else **.  Nor the C++ authors, and not the wasm port authors have the change of know or act  if anybody can publish a fork (Or create a new repo just copying)

I wonder what's your policy with forks , can anybody publish forks or only wasmer administrators?

Thinking quickly about it you have an interesting situation here that deserves more thought. And at least three persons now could be involved,:

 * The publisher (that might not be an author at all. Or it might be indeed updated an abandoned packages  and publish it in good will
 * ths wasm port author
* the original library authors. 

I think authorship merits goes from bottom to the up in that list and you, somehow should promote this visibiliiyty

Again, hoping this success, send you best regards.

**Comment by syrusakbary** [comment]
This issue might perhaps belong somewhere else. Please open it in the wapm-cli repo if you think the problem you exposed is more related to wapm.
