### ISSUE TITLE
Upgrade webc version in wasmer (patch version, update wasmer deps)

### ISSUE THREAD

**Issue by syrusakbary** [wasmerio/wasmer#5112]

**Comment by PolyProgrammist** [comment]
Hi @syrusakbary @xdoardo 
I would like to participate in RoSctober Fest. Can I take this issue?

**Comment by syrusakbary** [comment]
Hey @PolyProgrammist , this task will be needed to be done from someone from the Wasmer team.

This are some of the issues that you can work on as part of RoSctober Fest:
* https://github.com/wasmerio/wasmer/issues/4945
* https://github.com/wasmerio/wasmer/issues/4585
* https://github.com/wasmerio/wasmer/issues/4597
