### ISSUE TITLE
Choose emoji to represent C/C++ in the readme

### ISSUE THREAD

**Issue by styfle** [wasmerio/wasmer#512]
### Summary

The readme looks strange without an emoji for C/C++.

### Additional details

Consider using the old man emoji like this tweet from [@mnt_io](https://twitter.com/mnt_io/status/1138806726122188802).

Or see other options in this tweet from [@styfle](https://twitter.com/styfle/status/1133459667068362755).

**Comment by Hywan** [comment]
I propose 🌊 since it represents sea, so C :-p. No?

**Comment by piranna** [comment]
Or :eye: or :eyes: (`eye` or `eyes`, meaning see), or :see_no_evil: (`see_no_evil`) :-P

**Comment by styfle** [comment]
The wave is good. Here are some other interesting candidates:

⚓️ - anchor is holding the ship in place
🔑 - key as in critical, unlocks the door to more
⚙️ - gear as in the cogs underneath
➕- plus because C++
🕴️- levitating rude boy because roughly from the 1970s

**Comment by syrusakbary** [comment]
We ended using 🔗 as C is the "link" to other languages.

Feel free to open a PR if you think other emojis can fit better C/C++ :)
