### ISSUE TITLE
Add support for wasm files to wasm object file for Create-Obj

### ISSUE THREAD

**Issue by Germ210** [wasmerio/wasmer#5123]
To the developers of Wasmer,

I am making a compiler to wasm, but am unable to create an object file directly. So I would write a .wasm file and convert it to a .o. I saw that wasmer has a create-obj, but when I tried to create a wasm object file, it says that the target unsupported.

Using clang/zig cc, you could add support for compiling to .o files made for wasm.

**Comment by xdoardo** [comment]
Hello, thanks for reporting. Would you be comfortable sharing the .wasm file, your target (the triple of the machine you're running the command on) and the command you run, so we can look into it?

**Comment by Germ210** [comment]
As right now I cannot, but I can get it to you sometime today.

**Comment by Germ210** [comment]
Ok, so I am on Windows 11 for x86_64, and I am trying to run the command: wasmer create-obj --target=wasm32 out.wasm -o out.o

This gives the error: 
Compiler: cranelift
Target: wasm32-unknown-unknown
thread 'main' panicked at lib\compiler-cranelift\src\config.rs:71:45:
construct Cranelift ISA for triple: Unsupported
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I have tried the same command on arch with wsl, and that gives the same error. I have tried on llvm, but it still gives the error: 
Compiler: llvm
Target: wasm32-unknown-unknown
thread 'main' panicked at lib\compiler-llvm\src\config.rs:182:18:
not implemented: target wasm32-unknown-unknown not yet supported in Wasmer
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by xdoardo** [comment]
The `--target` flag specifies the target machine you want to produce the object file for: 

```
      --target <TARGET_TRIPLE>
          Compilation Target triple
          
          Accepted target triple values must follow the `target_lexicon` crate format.
          
          The recommended targets we try to support are:
          
          - "x86_64-linux-gnu" - "aarch64-linux-gnu" - "x86_64-apple-darwin" - "arm64-apple-darwin" - "x86_64-windows-gnu"
```

I'm not sure what's your objective targeting `wasm32`. Were you trying to compile a WAT file? 
If you want to simply produce an object file for windows, then you should use `--target=x86_64-windows-gnu`: let me know if you need any more help!

**Comment by Germ210** [comment]
Ok, thank you
