### ISSUE TITLE
Panic in spawned thread causes dead lock (?)

### ISSUE THREAD

**Issue by xxshady** [wasmerio/wasmer#5130]
### Describe the bug

See reproduction steps

```
wasmer 4.3.7 (c6c348d 2024-09-09)
binary: wasmer-cli
commit-hash: c6c348d00fa3582eb3b3fda07e69fdc695156193
commit-date: 2024-09-09
host: x86_64-pc-windows-msvc
compiler: singlepass,cranelift,llvm
rustc 1.81.0 (eeb90cda1 2024-09-04)
binary: rustc
commit-hash: eeb90cda1969383f56a2637cbd3037bdf598841c
commit-date: 2024-09-04
host: x86_64-pc-windows-msvc
release: 1.81.0
LLVM version: 18.1.7
```

### Steps to reproduce

```rs
fn main() {
    std::thread::spawn(|| {
        panic!("dead lock?"); // dead locks
    })
    .join()
    .unwrap();
}
```
run it with `cargo wasix run`

### Expected behavior

Process should exit with non-zero code, just like `cargo run` does
```
thread '<unnamed>' panicked at src/main.rs:3:9:
dead lock?
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at src/main.rs:6:6:
called `Result::unwrap()` on an `Err` value: Any { .. }
error: process didn't exit successfully: `target\debug\wasix-threading.exe` (exit code: 101)
```

**Comment by xdoardo** [comment]
Thanks, we'll investigate this issue.

**Comment by Arshia001** [comment]
@xxshady please be aware that when rust is compiled to WASM, you can't have unwinding panics; every panic is an abort. The fix to this problem would be to abort the entire WASIX process when a thread panics, which is also the native behavior with `panic = 'abort'`. This may not be what you expected the fix to be.

Interestingly, my testing shows that calling `exit()` from a non-main thread is also broken, with the same underlying reason as this issue.
