### ISSUE TITLE
Can Wasi ExitCode be negative?

### ISSUE THREAD

**Issue by gluax** [wasmerio/wasmer#5131]
### Summary

A clear and concise summary of your question.

I see that https://docs.rs/wasmer-wasix-types/0.27.0/wasmer_wasix_types/wasi/enum.ExitCode.html has an `i32` and as such when you ask for the raw exit code it gives an `i32`.

But after searching around a bit, I don't see a situation in which it would be negative. I see that `Errno` is `repr(u16)`. Can this actually be negative anywhere?

I could be missing it somewhere since a from impl exists:
```rust

impl From<ExitCode> for i32 {
    fn from(val: ExitCode) -> Self {
        match val {
            ExitCode::Errno(err) => err.to_native(),
            ExitCode::Other(code) => code,
        }
    }
}
```

### Additional details

N/A

**Comment by xdoardo** [comment]
Thanks for the report, seems like a bug on our side.
