### ISSUE TITLE
README of WASIX crate contains outdated example

### ISSUE THREAD

**Issue by xxshady** [wasmerio/wasmer#5132]
### Summary

README of WASIX crate contains outdated example [here](https://github.com/wasmerio/wasmer/tree/main/lib/wasix#usage)

**Comment by xxshady** [comment]
![image](https://github.com/user-attachments/assets/dc1f7411-7d4a-4877-92b3-b48022182511)

**Comment by xdoardo** [comment]
Thanks! Yes, you are right, the example is outdated. We will fix it for the next release.
