### ISSUE TITLE
Docs.rs build failing for 5.0.0

### ISSUE THREAD

**Issue by maboesanman** [wasmerio/wasmer#5192]
### Describe the bug

The builds for 5.0.0 have failed, resulting in incomplete documentation for the wasmer rust crate:

https://docs.rs/crate/wasmer/latest

**Comment by xdoardo** [comment]
Yep, I think we had a flag in `cranelift-codegen` that tried to write to the FS, which is read only in docs.rs' builds.

**Comment by maminrayej** [comment]
This is fixed now after the release of 5.0.1: https://docs.rs/crate/wasmer/latest
