### ISSUE TITLE
Fail to embed libwasmer_runtime_c_api.a in C.

### ISSUE THREAD

**Issue by mrpre** [wasmerio/wasmer#520]
Thanks for the bug report!

### Describe the bug

Fail to embed `libwasmer_runtime_c_api.a` in C.

```bash
wasmer 0.5.1 | rustc 1.35.0 (3c235d560 2019-05-20) | x86_64
```

### Steps to reproduce

1. Go to '…'
```
cat tmp.c
#include <sys/types.h>
#include <unistd.h>


int main(void) {
    ;
    return 0;
}
```
2. Compile with '…'
```
root@iZrj97ibqurmwnu9mj5htdZ:~/tengine/tengine# cc -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 tmp.c -Wl,--whole-archive /root/wasmer/raw/wasmer//target/debug/libwasmer_runtime_c_api.a -Wl,--no-whole-archive -lpthread -ldl -lm -lrt
/root/wasmer/raw/wasmer//target/debug/libwasmer_runtime_c_api.a(clzsi2.o): In function `__clzsi2':
clzsi2.c:(.text.__clzsi2+0x0): multiple definition of `__clzsi2'
/root/wasmer/raw/wasmer//target/debug/libwasmer_runtime_c_api.a(compiler_builtins-566972fa63f867ee.compiler_builtins.1t2dfk2k-cgu.0.rcgu.o):/cargo/registry/src/github.com-1ecc6299db9ec823/compiler_builtins-0.1.9/src/int/mod.rs:332: first defined here
collect2: error: ld returned 1 exit status
```  
If I don't use `-Wl,--whole-archive`, compile successfully.
3. Run '…'

If applicable, add a link to a test case (as a zip file or link to a repository we can clone).

### Expected behavior

Compile tmp.c successfully.

### Actual behavior

Compile tmp.c fail.

**Comment by Hywan** [comment]
Thanks for the bug report. How did you generate the static lib?

**Comment by mrpre** [comment]
@Hywan `cargo install --path .`

**Comment by syrusakbary** [comment]
To generate the static lib you will need to run the command:

```bash
cargo build -p wasmer-runtime-c-api --release
```

We also have a nice make command that will generate it for you and test it

```bash
make capi
```

This will generate the files:
* `libwasmer_runtime_c_api.so` (Linux)
* `libwasmer_runtime_c_api.dylib` (macOS)
* `wasmer_runtime_c_api.dll` (Windows)

You can also use the ones that we expose in our Release page, in the `Assets` section:
https://github.com/wasmerio/wasmer/releases/tag/0.6.0

Closing the issue.

Let us know if you have more questions!
