### ISSUE TITLE
Su Engine does not work on WSL

### ISSUE THREAD

**Issue by losfair** [wasmerio/wasmer#527]
### Describe the bug

Su Engine (PR #489 feature) does not work on Windows Subsystem for Linux (WSL).

### Steps to reproduce

1. Build and run Wasmer on WSL with singlepass backend. The WASM file provided must trigger a WebAssembly trap.
2. Error.

### Expected behavior

Wasmer correctly prints the backtrace and quits.

### Actual behavior

After the trap is triggered, Wasmer never quits and consumes 100% CPU (single core).

**Comment by syrusakbary** [comment]
After talking, we concluded:
* Needs some debugging in our side
* It might be a bug on WSL itself

We will see what's the issue after debugging.
