### ISSUE TITLE
C-Api cannot be built for 32bit targets

### ISSUE THREAD

**Issue by ubamrein** [wasmerio/wasmer#5303]
We tried to get the c-api backends to run/build on iOS/Android and found an issue on 32bit build-targets.
The following line fails to build on 32bit targets due to a overflow error (default integer type on 32bit targets is i32):

``` rust
        if self.inner.map.len() >= 1 << 32 {
``` 
Casting both sides to u64 solves the issue, and probably is also what is expected here. A problem would only arise for targets where `usize` uses more than 64bit, which as far as I know, does not exist yet.

We patched it on our fork, and I'm glad to make a pull request if you approve of this fix. Otherwise we are open for discussion:
https://github.com/wasmerio/wasmer/commit/fffca20649cfb5db4d72f0be004f67dadee7d3f3

**Comment by syrusakbary** [comment]
I think the fix is sensitive, so we could be good to go here
