### ISSUE TITLE
wasmer self-update ignores WASMER_DIR

### ISSUE THREAD

**Issue by nayeem-rahman** [wasmerio/wasmer#549]
Calling `wasmer self-update` ignores WASMER_DIR and installs to the default location, $HOME/.wasmer.

I imagine that this is because it calls [install.sh](https://github.com/wasmerio/wasmer/blob/master/install.sh), which [looks for INSTALL_DIRECTORY](https://github.com/wasmerio/wasmer/blob/0c4a8f77d2df41f8cb658909c1cb889ec288f8c5/install.sh#L367) instead of WASMER_DIR. The latter should obviously be used in the case of an update as opposed to an initial installation.

However, I think totally getting rid of INSTALL_DIRECTORY in install.sh and using WASMER_DIR for both cases would be far simpler and more consistent with the likes of [rustup](https://github.com/rust-lang/rustup.rs/issues/618#issuecomment-236232486).

To be clear this would mean an initial installation to /opt/wasmer would be done with:
`curl https://get.wasmer.io -sSfL | sudo WASMER_DIR=/opt/wasmer sh`
instead of:
`curl https://get.wasmer.io -sSfL | sudo INSTALL_DIRECTORY=/opt/wasmer sh`.

**Comment by MarkMcCaskey** [comment]
Good catch!  Thanks for reporting this
