### ISSUE TITLE
Using wasmer with assembly script?

### ISSUE THREAD

**Issue by ghost** [wasmerio/wasmer#571]
I was wondering if you intend to support https://github.com/AssemblyScript/assemblyscript or is there any way I can use it.

**Comment by MarkMcCaskey** [comment]
Yes!  AssemblyScript should work fine.

Wasmer can be used in a number of ways, when used to run Wasm modules as binaries `wasmer run your_wasm.wasm` we currently support Emscripten and WASI "ABI"s (which are like compile targets for Wasm that let us know how we should interact with your computer).

But we also support any kind of Wasm with any ABI when Wasmer is used as a library.  So if you have a program and want to run WebAssembly files as plugins (like mods for video games, or hot-swappable business logic, or running untrusted code), you can run Wasm and it's the host's (your program in this case) responsibility to provide the imports that the Wasm module asks for.  The imports are the way that the Wasm module can interact with your system or the outside world.

https://www.wapm.io/package/torch2424/wasm-matrix is an example on wapm (our Wasm package manager) of an Assembly script program compiled against WASI (source repo: https://github.com/torch2424/wasm-matrix).

Let me know if you run into any issues, I haven't had the chance to use AssemblyScript myself yet and I'd be interested to know if you have any trouble making things work.

**Comment by MarkMcCaskey** [comment]
I think this question is answered, closing now!
