### ISSUE TITLE
Export Emscripten imports so can be used from C-API

### ISSUE THREAD

**Issue by mrpre** [wasmerio/wasmer#574]
Thanks for proposing a new feature!

### Motivation

Command `wasmer run` can load `wasm` compiled by Emscripten but `c-api` interface can't.  
`Wasmer` has already supported the Emscripten/WASI.  

### Proposed solution
1. Support importing both custom functions and Emscripten/WASI functions.
2. Keep features like`callinfo`, `import custom function`remain by c-api.

**Comment by MeirShpilraien** [comment]
I also have this issue, I can run my program successfully with wasmer binary but not via the C-API.
I also tried to export myself the missing functions but it seems to be an issue with exporting namespaces that contains `.` (for example the `global.Math`).
Any ETA to support this?
