### ISSUE TITLE
emscripten C++ support. 

### ISSUE THREAD

**Issue by jalopezsilva** [wasmerio/wasmer#577]
I've been trying to execute in wasmer a WASM file compiled from C++ code using emscripten.

Here's the file that I'm trying to execute in C++:

```cpp
#include <iostream>

int main(int argc, char* argv[]) {
  std::cout << "Does this work?" << std::endl;
  return 0;
}
```

I'm using em++ to compile it to wasm with the following command:

```
~/emsdk/upstream/emscripten/em++  HelloWorld.cpp -s WASM=1 -o hello.wasm
```
Emscripten version is latest-upstream using llvm as a backend. Output of em++ -v: https://pastebin.com/5RbewmAs

When I try to run this on wasmer, I receive the following import errors:

```
examples ❯ wasmer run hello.wasm
....
execute_wasm: "Can\'t instantiate module: LinkError([ImportNotFound { namespace: \"env\", name: \"__cxa_uncaught_exceptions\" }, ImportNotFound { namespace: \"env\", name: \"__cxa_atexit\" }, ImportNotFound { namespace: \"env\", name: \"fabs\" }, IncorrectImportSignature { namespace: \"env\", name: \"abort\", expected: FuncSig { params: [], returns: [] }, found: FuncSig { params: [I32], returns: [] } }, ImportNotFound { namespace: \"env\", name: \"pthread_cond_broadcast\" }])"
```

I perfomed the following patches to add the missing imports: https://pastebin.com/mwGjxL5x

But unfortunately that doesn't work as I get a out-of-bounds access.
```
examples ❯ wasmer run hello.wasm
execute_wasm: "RuntimeError: WebAssembly trap occured during runtime: memory out-of-bounds access"
```

Is there no support for C++ or is this a consequence of using [emscripten with the llvm backend](https://v8.dev/blog/emscripten-llvm-wasm) ?

Output of wasmer/rustc/uname:  wasmer 0.5.7 | rustc 1.38.0-nightly (a7f28678b 2019-07-23) | x86_64

**Comment by Rochet2** [comment]
Using emsdk 3.1.19 and wasmer 3.0.0-beta the example seems to work fine for me on Linux.
