### ISSUE TITLE
"make bench" fails because metering_benchmark has no compiler specified

### ISSUE THREAD

**Issue by penberg** [wasmerio/wasmer#596]
When I run:

```
./build make bench
```

I get the following error:

```
     Running target/release/deps/metering_benchmark-771e924d5f51f188
Benchmarking Meter/No Metering: Warming up for 3.0000 sthread 'main' panicked at 'compiler not specified, activate a compiler via features', lib/middleware-common/benches/metering_benchmark.rs:168:5
```

Looking at the code, looks like none of the features were enabled:

```rust
#[cfg(not(any(feature = "llvm", feature = "clif", feature = "singlepass")))]
fn get_compiler(_limit: u64, metering: bool) -> impl Compiler {
    panic!("compiler not specified, activate a compiler via features");
    use wasmer_clif_backend::CraneliftCompiler;
    CraneliftCompiler::new()
}
```

If I try to enable the "backend-llvm" feature explicitly:

```
./build cargo bench --all --features backend-llvm
```

the benchmark fails in the exact same way.

I also tried to enable "llvm" feature:

```
./build cargo bench --all --features llvm
```

but it also fails:

```
error: Package `wasmer v0.5.7 (/wasmer)` does not have these features: `llvm`
```

Is the code broken or did I miss some magic to get `make bench` running?

**Comment by MarkMcCaskey** [comment]
Thanks for reporting this!

There are issues on our side, I did my best to clean them up.  I replaced `make bench` with `make bench-clif`, `make bench-llvm`, and `make bench-singlepass`

`make bench-llvm` doesn't seem to be working, I pinged our LLVM guy about it.

I'll bring up the idea of adding these to CI.  I don't know how long they take to run, but it's no good for things to break without us knowing.

**Comment by penberg** [comment]
@MarkMcCaskey Thanks for the clarification!

I don't see these new build targets in `master`, though:

```
$ make bench-clif
make: *** No rule to make target 'bench-clif'.  Stop.
$ make bench-llvm
make: *** No rule to make target 'bench-llvm'.  Stop.
$ make bench-singlepass
make: *** No rule to make target 'bench-singlepass'.  Stop.
```

**Comment by penberg** [comment]
Thanks for the update!

:+1: for adding the targets to a CI run.
