### ISSUE TITLE
Error: Compiling wasmer-runtime crate

### ISSUE THREAD

**Issue by kendatomas** [wasmerio/wasmer#617]
**When I try to compile wasmer-runtime = "0.6.0" with rustc 1.36.0 (a53f9df32 2019-07-03). I get compiling error in both libraries: errno v0.2.4 and page_size v0.4.1.** 

**I am on Ubuntu 18.04.2 LTS.**

[INFO]: Compiling to Wasm...
    Updating crates.io index
   Compiling errno v0.2.4
   Compiling page_size v0.4.1
error[E0433]: failed to resolve: use of undeclared type or module `sys`
  --> /home/idria/.cargo/registry/src/github.com-1ecc6299db9ec823/errno-0.2.4/src/lib.rs:35:9
   |
35 |         sys::with_description(*self, |desc| {
   |         ^^^ use of undeclared type or module `sys`

error[E0433]: failed to resolve: use of undeclared type or module `sys`
  --> /home/idria/.cargo/registry/src/github.com-1ecc6299db9ec823/errno-0.2.4/src/lib.rs:46:9
   |
46 |         sys::with_description(*self, |desc| match desc {
   |         ^^^ use of undeclared type or module `sys`

error[E0433]: failed to resolve: use of undeclared type or module `sys`
  --> /home/idria/.cargo/registry/src/github.com-1ecc6299db9ec823/errno-0.2.4/src/lib.rs:50:25
   |
50 |                 self.0, sys::STRERROR_NAME, fm_err.0),
   |                         ^^^ use of undeclared type or module `sys`

error[E0433]: failed to resolve: use of undeclared type or module `sys`
  --> /home/idria/.cargo/registry/src/github.com-1ecc6299db9ec823/errno-0.2.4/src/lib.rs:69:5
   |
69 |     sys::errno()
   |     ^^^ use of undeclared type or module `sys`

error[E0433]: failed to resolve: use of undeclared type or module `sys`
  --> /home/idria/.cargo/registry/src/github.com-1ecc6299db9ec823/errno-0.2.4/src/lib.rs:74:5
   |
74 |     sys::set_errno(err)
   |     ^^^ use of undeclared type or module `sys`

error[E0425]: cannot find function `get_granularity_helper` in this scope
  --> /home/idria/.cargo/registry/src/github.com-1ecc6299db9ec823/page_size-0.4.1/src/lib.rs:67:5
   |
67 |     get_granularity_helper()
   |     ^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `get_granularity`

error: aborting due to previous error
For more information about this error, try `rustc --explain E0425`.
error: Could not compile `page_size`.
warning: build failed, waiting for other jobs to finish...
error[E0277]: the size for values of type `str` cannot be known at compilation time
  --> /home/idria/.cargo/registry/src/github.com-1ecc6299db9ec823/errno-0.2.4/src/lib.rs:47:16
   |
47 |             Ok(desc) => fmt.write_str(&desc),
   |                ^^^^ doesn't have a size known at compile-time
   |
   = help: the trait `std::marker::Sized` is not implemented for `str`
   = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
   = note: all local variables must have a statically known size
   = help: unsized locals are gated as an unstable feature

error[E0277]: the size for values of type `str` cannot be known at compilation time
  --> /home/idria/.cargo/registry/src/github.com-1ecc6299db9ec823/errno-0.2.4/src/lib.rs:47:13
   |
47 |             Ok(desc) => fmt.write_str(&desc),
   |             ^^^^^^^^ doesn't have a size known at compile-time
   |
   = help: the trait `std::marker::Sized` is not implemented for `str`
   = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
   = note: required by `std::prelude::v1::Ok`

error[E0277]: the size for values of type `str` cannot be known at compilation time
  --> /home/idria/.cargo/registry/src/github.com-1ecc6299db9ec823/errno-0.2.4/src/lib.rs:48:13
   |
48 |             Err(fm_err) => write!(
   |             ^^^^^^^^^^^ doesn't have a size known at compile-time
   |
   = help: the trait `std::marker::Sized` is not implemented for `str`
   = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
   = note: required by `std::prelude::v1::Err`

error: aborting due to 8 previous errors

**Comment by kendatomas** [comment]
I tried with nigthly and get better results, but still with errors:

wasm-pack error: [INFO]: Checking for the Wasm target...
info: downloading component 'rust-std' for 'wasm32-unknown-unknown'
info: installing component 'rust-std' for 'wasm32-unknown-unknown'
[INFO]: Compiling to Wasm...
   Compiling proc-macro2 v0.4.30
   Compiling unicode-xid v0.1.0
   Compiling syn v0.15.39
   Compiling semver-parser v0.7.0
   Compiling serde v1.0.97
   Compiling libc v0.2.60
   Compiling ryu v1.0.0
   Compiling cc v1.0.37
   Compiling autocfg v0.1.5
   Compiling itoa v0.4.4
   Compiling failure_derive v0.1.5
   Compiling rustc-demangle v0.1.15
   Compiling rand_core v0.4.0
   Compiling memchr v2.2.1
   Compiling wasm-bindgen-shared v0.2.48
   Compiling arrayvec v0.4.11
   Compiling log v0.4.7
   Compiling cranelift-entity v0.31.0
   Compiling byteorder v1.3.2
   Compiling version_check v0.1.5
   Compiling cfg-if v0.1.9
   Compiling typenum v1.10.0
   Compiling cgmath v0.16.1
   Compiling winapi v0.3.7
   Compiling nodrop v0.1.13
   Compiling lazy_static v1.3.0
   Compiling scopeguard v1.0.0
   Compiling approx v0.1.1
   Compiling stable_deref_trait v1.1.1
   Compiling bitflags v1.1.0
   Compiling rand v0.4.6
   Compiling arrayref v0.3.5
   Compiling constant_time_eq v0.1.3
   Compiling bumpalo v2.5.0
   Compiling unicode-segmentation v1.3.0
   Compiling nix v0.14.1
   Compiling rayon-core v1.5.0
   Compiling rgb v0.8.13
   Compiling smallvec v0.6.10
   Compiling scopeguard v0.3.3
   Compiling crc32fast v1.2.0
   Compiling wasm-bindgen v0.2.48
   Compiling num-derive v0.2.5
   Compiling void v1.0.2
   Compiling hex v0.3.2
   Compiling page_size v0.4.1
error[E0425]: cannot find function `get_granularity_helper` in this scope
  --> /home/idria/.cargo/registry/src/github.com-1ecc6299db9ec823/page_size-0.4.1/src/lib.rs:67:5
   |
67 |     get_granularity_helper()
   |     ^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `get_granularity`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
error: Could not compile `page_size`.
warning: build failed, waiting for other jobs to finish...
error: build failed
Error: Compiling your crate to WebAssembly failed
Caused by: failed to execute `cargo build`: exited with exit code: 101

**Comment by bjfish** [comment]
It appears you may be trying to compiler `wasmer-runtime` to wasm (via wasm32-unknown-unkown). Is this correct?  This is not a currently supported target but it something that could be considered in the future.

**Comment by kendatomas** [comment]
Yes, I am trying to do that. OK. Thanks!!
