### ISSUE TITLE
The calls to wasm functions are slow

### ISSUE THREAD

**Issue by geloizi** [wasmerio/wasmer#625]
### Summary

I've done some basic benchmarks and found that calls to wasm functions take around 300 nano seconds

```
let func = instance.func("func").expect("")
func.call()  <--- 300ns
```

That's huge comparing this operation to a call in opposite direction (from wasm vm to native) which is just 5 nano seconds. Is there any way to improve the performance of calls?

**Comment by MarkMcCaskey** [comment]
Hi!  Thanks for the report.  I started work on some extra benchmarks a bit ago here https://github.com/wasmerio/wasmer/pull/517 .  This is something we're interested in, if it's too slow, then that does preclude using Wasmer from certain use cases entirely.

Is it correct that you're using our default clif-backend and everything else default in the example above?

**Comment by geloizi** [comment]
> Is it correct that you're using our default clif-backend and everything else default in the example above?

yes, the backend is the default one.

**Comment by Hywan** [comment]
We can close the issue now :-).
