### ISSUE TITLE
React Example or some SPA

### ISSUE THREAD

**Issue by ScriptedAlchemy** [wasmerio/wasmer#626]
### Motivation

It would be great to see this in action where an SPA like react did something like transform data within a WASM module, then rendered the result in normal JS

Really seeking ways to us eWASM within and hand in hand with modern FE apps

**Comment by syrusakbary** [comment]
We created the WebAssembly shell that is indeed a SPA react app that is using [@wasmer/wasi](https://www.npmjs.com/package/@wasmer/wasi) under the hood!

Hopefully that's a great starting example!

Closing the issue. Let us know if you have more ideas or would like to help us on creating the example :)

**Comment by Forpee** [comment]
Where would I find this example?
Because I've looked for it to no avail;

**Comment by syrusakbary** [comment]
WebAssembly Shell: https://github.com/wasmerio/webassembly.sh
Wasmer-JS: https://github.com/wasmerio/wasmer-js

**Comment by Forpee** [comment]
Thank you! :)
