### ISSUE TITLE
Crash when calling a WASM function with no result #22

### ISSUE THREAD

**Issue by ljulliar** [wasmerio/wasmer#662]
I initially posted this question/bug report (?) in ruby-ext-wasm but I'm pretty sure it ultimately relates to wasmer itself. Hence the cross-posting.

### Summary

I cannot call an exported WASM function from a wasmer instance. There seems to be some kind of runtime function and/opr static data wasmer is expecting from a WASM module but which ones ?

Any help is much appreciated

### Details

I wrote the following minimal webassembly module in WAT text file
```
(module $simple
  (export "memory" (memory $0))
  (export "set_freep" (func $set_freep))

  (memory $0 1)

  (func $set_freep (param $value i32)
    (i32.store (i32.const 20) (local.get $value))
  )

  (func $main)

)
```
then compiled it to WASM code with wat2wasm (from the wabt toolkit). It is a straight compilation from WASM text format to wasm binary format with no additional runtime code if any kind

FInally I'm trying to instantiate this WASM module with wasmer

```
require 'wasmer'

bytes = File.read('/tmp/simple.wasm')
instance = Instance.new(bytes)
instance.exports.set_freep(1)
```
This code keeps generating the following error:

```
hread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/slice/mod.rs:2686:10
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
fatal runtime error: failed to initiate panic, error 5
Aborted
```

And with stack trace 
```
<ExportedFunctions:0x000057fb04b3e500>
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/slice/mod.rs:2686:10
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
  7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:61
   9: wasmer::instance::ExportedFunctions::method_missing
  10: wasmer::instance::ruby_exported_functions_method_missing
....
....
```

**Comment by ljulliar** [comment]
I was able to determine that the problem comes from calling a WASM function that doesn't return anything. This is the case here for $set_freep.

I was able to reproduce the problem also with a modified simple.rs that returns nothing. Like:
```
#[no_mangle]
pub extern fn sum(x: i32, y: i32) -> () {
   x + y;
   return ()
}

fn main () {
}
```

I don't know yet if that problem comes from ruby-ext-wasm or from the lower level C API. Any help is much appreciated.

**Comment by Hywan** [comment]
Hello,

Thanks for the issue. Unfortunately, I can't replicate with `ruby-ext-wasm`. I tried with the following Rust program:

```rust
#[no_mangle]
pub extern "C" fn sum() -> () {
    ()
}
```

**Comment by pventuzelo** [comment]
I tried the first example using an old version of wasmer and got the same panic message.
I suppose we have fixed this index out of bound error in the meantime.

@ljulliar  Can you update your version of wasmer and tell us if it's ok?
@Hywan Do you when the next release of ruby-ext-wasm is planned?

**Comment by ljulliar** [comment]
I do confirm that wasmer 0.6.1 solves the problem. I don't think there is
any need to further update ruby-ext-wasm. @Hywan updated it recently
(version 0.0.3 from Aug 28) and it compiles fine.

Laurent

**Comment by pventuzelo** [comment]
Ok perfect, 
Thanks @ljulliar, can you close the issue if everything OK?
