### ISSUE TITLE
Callbacks between Wasm and Native code

### ISSUE THREAD

**Issue by tprk77** [wasmerio/wasmer#670]
### Motivation

I would like to use callbacks between Wasm and native code. I would like to implement a callback on the Wasm-side, pass it as an argument, and later invoke it from the native-side.

I basically want to do what's in this [StackOverflow question](https://stackoverflow.com/q/45387728), but with Wasmer and Rust.

### Proposed solution

On the native-side, which is embedding the VM, I want to receive a pointer to a function implemented on the Wasm-side, and somehow lookup and dispatch that function. I would like to be able to do this without any shims or exported functions.

It might look something like this:

```
// set_callback: (callback: extern fn(x: u32) -> ()) -> ()
pub fn set_callback(ctx: &mut Ctx, callback_ptr: u32) {
  // Somehow lookup callback_ptr in a table?
  ctx.get_func(callback_ptr).call(123);
}
```

### Additional context

I've attempted #245, but I haven't made any progress there. (Help please!)

I've implemented callbacks in my own [demo project](https://github.com/tprk77/experiments_in_ros2_rust_and_wasm), but it required some pretty undesirable work-arounds, like a export function shim.

There was also some [discussion on Spectrum](https://spectrum.chat/wasmer/general/is-it-possible-to-call-a-wasm-callback-from-rust~eee307f9-fdf9-4182-876c-59cf3395794c).

**Comment by MarkMcCaskey** [comment]
I believe this is the same as or very similar to #638 ;

Thanks for the report -- I agree that this is an important thing to be able to do!

**Comment by MarkMcCaskey** [comment]
I got this working in #803 with an example!!

**Comment by MarkMcCaskey** [comment]
Closing because #803 merged in.  If you have any issues, don't hesitate to reopen this issue or file a new one!

**Comment by tprk77** [comment]
This weekend I'll have time to integrate this change into my project. I'll let you know how it goes!
