### ISSUE TITLE
Can't capture wasm's exception under WASI and Emscripten

### ISSUE THREAD

**Issue by mrpre** [wasmerio/wasmer#681]
### Steps to reproduce
```c
#include <stdio.h>
char *ptr= NULL;
int main()
{
    *ptr = 1;
    return 1;
}
```
using `wasi-sdk` to compile
```
clang --target=wasm32-wasi --sysroot=xxx 1.c -o 1.wasm
```
run
```
wasmer run 1.wasm
```

### Expected behavior
Exception should be captured.   

### Actual behavior
An exception should be captured but nothing outputted by command `wasmer run`.

### Wasmer version
`wasmer 0.5.6 | rustc 1.36.0 (a53f9df32 2019-07-03) | x86_64`

## Emscripten 
Same Steps as WASI  

### Expected behavior
I embed `Wasmer` into my application but when exception happen, my application abort.  It's hard for me to run some unsafe code by `Wasmer`. The exception should be handled by embedder.

**Comment by nlewycky** [comment]
What's happened here is that your C code has undefined behaviour, and the resulting WebAssembly code produced by clang has no trap in it.

The relevant in the wasm file is:
```
  (func $__original_main (type 4) (result i32)
    (local i32 i32 i32 i32 i32 i32 i32 i32)
    global.get 0
    local.set 0
    i32.const 16
    local.set 1
    local.get 0
    local.get 1
    i32.sub
    local.set 2
    i32.const 1
    local.set 3
    i32.const 1
    local.set 4
    i32.const 0
    local.set 5
    local.get 2
    local.get 5
    i32.store offset=12
    i32.const 0
    local.set 6
    local.get 6
    i32.load offset=1024
    local.set 7
    local.get 7
    local.get 4
    i32.store8
    local.get 3
    return)
```
which doesn't have any reason to trap.

Here's a full trace of the execution using `wasm-interp` from [wabt](https://github.com/WebAssembly/wabt):
```
$ wasm-interp -t --run-all-exports 681.wasm 
>>> running export "_start":
#0.  260: V:0  | call @4
#1.    4: V:0  | alloca $8
#1.   12: V:8  | global.get $0
#1.   20: V:9  | local.set $8, 66576
#1.   28: V:8  | i32.const 16
#1.   36: V:9  | local.set $7, 16
#1.   44: V:8  | local.get $8
#1.   52: V:9  | local.get $8
#1.   60: V:10 | i32.sub 66576, 16
#1.   64: V:9  | local.set $6, 66560
#1.   72: V:8  | i32.const 1
#1.   80: V:9  | local.set $5, 1
#1.   88: V:8  | i32.const 1
#1.   96: V:9  | local.set $4, 1
#1.  104: V:8  | i32.const 0
#1.  112: V:9  | local.set $3, 0
#1.  120: V:8  | local.get $6
#1.  128: V:9  | local.get $4
#1.  136: V:10 | i32.store $0:66560+$12, 0
#1.  148: V:8  | i32.const 0
#1.  156: V:9  | local.set $2, 0
#1.  164: V:8  | local.get $2
#1.  172: V:9  | i32.load $0:0+$1024
#1.  184: V:9  | local.set $1, 0
#1.  192: V:8  | local.get $1
#1.  200: V:9  | local.get $5
#1.  208: V:10 | i32.store8 $0:0+$0, 1
#1.  220: V:8  | local.get $5
#1.  228: V:9  | drop_keep $8 $1
#1.  240: V:1  | return
#0.  268: V:1  | drop
#0.  272: V:0  | return
_start() =>
```

Here's a C example that triggers memory out of bounds in both wasmer and wasm-interp, as clang wasi-sdk 6 happens to compile it:
```
int main(void) {
  int x = 0x76543210;
  char *p = (char*)x;
  *p = '\0';
   ++p;
  return *p;
}
$ wasmer/target/debug/wasmer run example.wasm 
execute_wasm: "wasm trap occured: memory out-of-bounds access"
```
but of course there's no guaranteed behaviour of a C program that executes undefined behaviour. Wasmer can only guarantee behaviour relative to the wasm file it runs, not the original source code that produced the wasm. We do guarantee that we catch out of bounds accesses to WebAssembly linear memories.

As for catching the exception when using Wasmer as a library, the Instance.call produces a `CallResult` object which is a `Result<T, CallError>` and the CallError includes any traps encountered by the running program:
```
/// This error type is produced by calling a wasm function
/// exported from a module.
///
/// If the module traps in some way while running, this will
/// be the `CallError::Runtime(RuntimeError)` variant.
///
/// Comparing two `CallError`s always evaluates to false.
pub enum CallError {
    Resolve(ResolveError),
    Runtime(RuntimeError),
}
```
and
```
/// This is the error type returned when calling
/// a WebAssembly function.
///
/// The main way to do this is `Instance.call`.
///
/// Comparing two `RuntimeError`s always evaluates to false.
pub enum RuntimeError {
    Trap { msg: Box<str> },
    Error { data: Box<dyn Any> },
}
```
If wasmer is terminating instead, please see if you can collect a backtrace for us to debug!

**Comment by MarkMcCaskey** [comment]
It looks like this has been solved, if not please reopen it
