### ISSUE TITLE
Kernel Module for running WebAssembly

### ISSUE THREAD

**Issue by skyne98** [wasmerio/wasmer#70]
Hello there,
I would like to propose a feature, that, in my opinion, has great potential for making native WebAssembly modules more popular and useful. The idea is executing WebAssembly modules in ring 0, allowing it to communicate via usual function calls, instead of system calls.
WebAssembly standard itself provides a "guarantee", that the given code will be safe to run in the kernel environment, therefore eliminating the need to execute it in "user-space".
How hard will such an implementation will be in your more professional opinion?

On of the projects implementing the idea: WasmJit
The results of using such a method look very promising, boasting execution times smaller than the execution times of native libraries themselves!

**Comment by losfair** [comment]
Sounds like https://github.com/cervus-v/cervus

**Comment by losfair** [comment]
@skyne98 It depends on how you define "usable". For running basic WebAssembly programs it should be ready quite soon but for necessary security/stability hardening it needs more research since the Linux kernel's userspace isolation model is designed around hardware isolation but we're breaking the assumption.

Also please move to cervus-v/cervus for specific discussions on that project.

**Comment by skyne98** [comment]
@losfair, anyways, thank you for pointing me in an interesting direction! I will move there for further discussion.

**Comment by jdanford** [comment]
Looks like this issue can be closed?

**Comment by skyne98** [comment]
I think yes, @jdanford, but I think it depends a lot on whether it's a planned feature of wasmer (potentially) or not.

**Comment by jdanford** [comment]
Do you have a particular use case in mind? If you're focused on performance then #217 looks like the active issue, but if you're specifically thinking about using Wasmer as a Linux kernel module then that would require changing the project's license from MIT to GPL, which is sort of a whole issue in itself.

**Comment by lachlansneff** [comment]
As a heads up, changing the license to something more constricting, like GPL is probably not going to happen. However, I believe that our current license is GPLv3 compatible, so as long as the specific kernel module was licensed as GPL, it could depend on the wasmer-runtime.

**Comment by syrusakbary** [comment]
We just released an integration for running WebAssembly on the kernel:

https://github.com/wasmerio/kernel-wasm

**Comment by skyne98** [comment]
Nice! Now we just have to wait and see WASI extend/mature. Right now it's already very useful, however, as I understand, it cannot use threads, IPC communication, arbitrary syscalls, which makes it impossible to write GUI applications, or applications using modern linux systems like D-BUS.
