### ISSUE TITLE
Unified fault handling for all backends.

### ISSUE THREAD

**Issue by losfair** [wasmerio/wasmer#711]
### Motivation

Currently all of our three backends have their own code for handling faults (triggered on unreachable, division by zero, memory access OOB, etc.) and this is highly duplicated. With the introduction of OSR-based managed execution engine we now have a unified fault handling module in `runtime-core`, but is not yet turned on for unmanaged execution.

### Proposed solution

Change `llvm`/`clif`/`singlepass` to use unified fault handling in `runtime-core` by default.

**Comment by syrusakbary** [comment]
Thanks to the refactor we now have a unified trap handling across all compilers.
Closing issue
