### ISSUE TITLE
LLVM uses too much memory when compiling an emscripten test with stackmaps enabled

### ISSUE THREAD

**Issue by losfair** [wasmerio/wasmer#717]
### Describe the bug

When running the emscripten test `test_indirectbr_many`, memory usage goes up by >10GB and testing is not able to complete both on CI and on my computer.

### Steps to reproduce

1. Remove the `ignore` attribute on `fn test_test_indirectbr_many`.
2. Run: `cargo test --manifest-path lib/emscripten-tests/Cargo.toml --release --features llvm -- --test-threads=1` .
3. Watch the memory usage.

### Expected behavior

Test successfully finishes.

### Actual behavior

Memory usage keeps increasing until crash.

**Comment by Hywan** [comment]
Solved with the rewrite.
