### ISSUE TITLE
Is pthreads.h supported on wasmer. Error is coming right now saying threads support is not enabled.

### ISSUE THREAD

**Issue by shubham2398** [wasmerio/wasmer#718]
### Summary

Error when i try to run a file using wasmer run command  - "Can\'t compile module: ValidationError { msg: \"threads support is not enabled\" }"

**Comment by syrusakbary** [comment]
We are working on adding support for threads at the moment :)

If you could attach to this issue your wasm file it would be great, that way we can make sure it runs when testing it.

**Comment by shubham2398** [comment]
Thank you @syrusakbary ! I'll attach the file in some time. Also, I'm looking towards contributing to wasm in threading support. So is there some resource from where I could begin contributing to wasmer for the same. To start, it would be great to know how wasmer runtime works behind the scenes. 
Thank you again!

**Comment by shubham2398** [comment]
> If you could attach to this issue your wasm file it would be great, that way we can make sure it runs when testing it.

Here's the zip containing the C file and its compiler version using emsdk:
[code.tar.gz](https://github.com/wasmerio/wasmer/files/3540930/code.tar.gz)

Also @syrusakbary , by when will threads support be added so that it can be tried?

**Comment by Hywan** [comment]
I'm closing this issue. We are waiting [the Threads Proposal](https://github.com/webassembly/threads) to reach phase 3 (currently [phase 2](https://github.com/WebAssembly/proposals#phase-2---proposed-spec-text-available-cg--wg)).
