### ISSUE TITLE
[wasmparser library] index out of bounds in operators_validator::OperatorValidator::check_select

### ISSUE THREAD

**Issue by pventuzelo** [wasmerio/wasmer#723]
This bug is related to the 3rd party library [wasmparser](https://github.com/yurydelendik/wasmparser.rs) used in wasmer

The issue happen in the last version of `wasmparser` [0.37.0](b56f91d251055eb7787e7e5c42926a61635ca00a). The issue is present in the `wasmparser` version 0.35.1 used by `wasmer` 

The issue have been reported in `wasmparser` github repository (issue [#126](https://github.com/yurydelendik/wasmparser.rs/issues/126))

### Describe the bugs

Subtraction between `func_state.stack_types.len()` and `last_block.stack_starts_at` values generate an overflow value. The value `func_state.stack_types.len()` substrates with an hardcoded value is then used as an index array leading the program to panic with an index out of bound error. 

https://github.com/yurydelendik/wasmparser.rs/blob/b56f91d251055eb7787e7e5c42926a61635ca00a/src/operators_validator.rs#L615-L636

This issue is making wasmer to panicked.

### Expected behavior

The library should check properly the value, ensure that no overflow occurs and return an error otherwise.

### Status of my environment

wasmer version: commit 854b2013ea6f52d5d4d9a145e6607e5fa0cf573b

```bash
echo "`./target/release/wasmer -V` | `rustc -V` | `uname -m`"
wasmer 0.6.0 | rustc 1.38.0-nightly (ad7c55e1f 2019-08-07) | x86_64
```

### Steps to reproduce

Download 
[panic_wasmparser_index_oob_check_select.zip](https://github.com/wasmerio/wasmer/files/3540700/panic_wasmparser_index_oob_check_select.zip)

```
$ unzip panic_wasmparser_index_oob_check_select.zip
$ ./target/release/wasmer run panic_wasmparser_index_oob_check_select.wasm
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551613', /rustc/ad7c55e1fc55d9af4787b285cec1c64e3480ae84/src/libcore/slice/mod.rs:2704:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

### Actual behavior (release build)

```
$ RUST_BACKTRACE=1 ../target/release/wasmer run panic_wasmparser_index_oob_check_select.wasm
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551613', /rustc/ad7c55e1fc55d9af4787b285cec1c64e3480ae84/src/libcore/slice/mod.rs:2704:10
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:61
  11: wasmparser::operators_validator::OperatorValidator::process_operator
  12: <wasmparser::validator::ValidatingParser as wasmparser::parser::WasmDecoder>::read
  13: wasmer_runtime_core::codegen::validate_with_features
  14: <wasmer_runtime_core::codegen::StreamingCompiler<MCG,FCG,RM,E,CGEN> as wasmer_runtime_core::backend::Compiler>::compile
  15: wasmer_runtime_core::compile_with_config
  16: wasmer_runtime::compile_with_config_with
  17: wasmer::execute_wasm
  18: wasmer::main
  19: std::rt::lang_start::{{closure}}
  20: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  21: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  22: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  23: std::panicking::try
             at src/libstd/panicking.rs:275
  24: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  25: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  26: main
  27: __libc_start_main
  28: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by pventuzelo** [comment]
TODO: tag with fuzzer-trophy

**Comment by pventuzelo** [comment]
wasmparser have been patched (in this [commit](https://github.com/yurydelendik/wasmparser.rs/commit/28bcbcd1c20255e694cc9d1d1606bc96df819677)) and a new version available ([0.37.1](https://github.com/yurydelendik/wasmparser.rs/commit/f0b00091b250e8a41f2e65a065d92b8c1c79be9a)).

Upgrade to version 0.37.1 needed to fix this bug.
CAUTION: Some changes introduced in 0.37 are breaking wasmer compilation.

**Comment by bjfish** [comment]
We are at wasmerparser version `0.39.1` now and the example wasm now fails with:
```
Error: Can't compile module: ValidationError { msg: "Unknown opcode" }
```
So, I'll mark this as resolved.

**Comment by pventuzelo** [comment]
@bjfish awesome ;) 
Good for me as well ;)
