### ISSUE TITLE
Embedding wasmer into Node.js

### ISSUE THREAD

**Issue by MaxGraey** [wasmerio/wasmer#752]
### Motivation

It will be great have alternative Wasm engine and compare it with v8 especially with LLVM JIT backend. It also enhance development / testing experience when we could test WASI programs and it's interop the same time for v8 and wasmer (Cranelift).

**Comment by syrusakbary** [comment]
That's a great idea!

**Comment by torch2424** [comment]
@MaxGraey Oops, didn't see this was still open 😂 

Just for other people passing by this issue, as Max I think already knows, we launched [Wasmer-JS](https://github.com/wasmerio/wasmer-js) to accomplish this.

Thank you! 😄

**Comment by MaxGraey** [comment]
Thanks!
