### ISSUE TITLE
Trampoline API seems confusing

### ISSUE THREAD

**Issue by liamappelbe** [wasmerio/wasmer#755]
Not sure if this is a bug or I'm just misunderstanding the API. I'm trying to call back from WASM into C++. On the WASM side, my function just takes 2 int64s and returns another int64:
`extern int64_t my_callback(int64_t a, int64_t b);`

On the C++ side, I'm using wasmer.hh's trampoline stuff to call my function, but the calling convention seems odd. After some messing around I got it working like this:
```
int64_t my_callback(void*, int64_t* a, int64_t b) {
  std::cout << "my_callback " << a[1] << " " << b << std::endl;
  return 12345;
}
```

The void* is a context pointer I'm not using, so that makes sense, and the `b` arg is passed through normally. But the `a` arg gets put into the second slot of an array, rather than just being passed like `b`, so I have to do `a[1]` to get my arg. What's up with that?

In case it matters, my import looks like this:
```
  // Function imports.
  wasmer_trampoline_buffer_builder_t* builder =
      wasmer_trampoline_buffer_builder_new();
  uintptr_t tramp_idx =
      wasmer_trampoline_buffer_builder_add_callinfo_trampoline(
          builder, (wasmer_trampoline_callable_t*)my_callback, nullptr, 2);
  wasmer_trampoline_buffer_t* tramp =
      wasmer_trampoline_buffer_builder_build(builder);
  const wasmer_trampoline_callable_t* trampoline_callable =
      wasmer_trampoline_buffer_get_trampoline(tramp, tramp_idx);
  wasmer_import_t function_import =
      ToImport(module_name, ToByteArray("my_callback"),
               wasmer_import_export_kind::WASM_FUNCTION);
  wasmer_value_tag trampoline_params[] = {wasmer_value_tag::WASM_I64,
                                          wasmer_value_tag::WASM_I64};
  wasmer_value_tag trampoline_returns[] = {wasmer_value_tag::WASM_I64};
  function_import.value.func = wasmer_import_func_new(
      (void (*)(void*))trampoline_callable, trampoline_params,
      ARRAY_SIZE(trampoline_params), trampoline_returns,
      ARRAY_SIZE(trampoline_returns));
```

**Comment by syrusakbary** [comment]
@nlewycky @bjfish can you take a look?

**Comment by Hywan** [comment]
Hi :-),

The function that is registered by the trampoline API takes the following arguments: `local_context` and `arguments`, where `local_context` is a pointer to anything you want (e.g. a structure), and `arguments` is the list of the arguments. The context is set when calling the `wasmer_trampoline_buffer_builder_add_callinfo_trampoline`.

I didn't test the following code, but you'll get the idea:

```c
// 1. Define a context.
typedef struct {
    bool foo;
    // anything you want
} local_context;

// 2. Define the callback.
uint64_t callback(local_context* local_context, uint64_t* arguments) {
    // Read `a` and `b`. We do a bit-cast here.
    int64_t a = static_cast<int64_t>(arguments[1]);
    int64_t b = static_cast<int64_t>(arguments[2]);
}

// 3. Create a context.
local_context local_context = {
    .foo = true,
    // anything you want
};

// 4. Build the trampoline.
wasmer_trampoline_buffer_builder_t *trampoline_builder = wasmer_trampoline_buffer_builder_new();

unsigned long trampoline_index = wasmer_trampoline_buffer_builder_add_callinfo_trampoline(
    // The builder
    trampoline_builder,

    // The callback function pointer
    (wasmer_trampoline_callable_t *) callback,

    // The local context of the callback
    (void *) local_context,

    // Number of arguments of the callback, including the context, so local context (1) + arity of the callback (2 [`a` and `b`])
    1 + 2
);

wasmer_trampoline_buffer_t *trampoline = wasmer_trampoline_buffer_builder_build(trampoline_builder);

const wasmer_trampoline_callable_t *trampoline_callable = wasmer_trampoline_buffer_get_trampoline(trampoline, trampoline_index);

// 5. Use the `trampoline_callable` pointer as a regular function with the import API
wasmer_import_func_t *function = wasmer_import_func_new(
    (void (*)(void *)) trampoline_callable,
    inputs_signature,
    input_arity,
    outputs_signature,
    output_arity
);

// etc.
```

The thing is that in `callack`, you read arguments through the second argument. Notice that we start reading `a` and `b` from index 1. Indeed, index 0 is a `wasmer_instance_context_t`, which is helpful to retrieve an instance memory for instance, e.g.:

```c
uint64_t callback(local_context* local_context, uint64_t* arguments) {
    wasmer_instance_context_t *instance_context = (wasmer_instance_context_t *) arguments[0];
    const wasmer_memory_t *memory = wasmer_instance_context_memory(instance_context, 0);

    int64_t a = static_cast<int64_t>(arguments[1]);
    int64_t b = static_cast<int64_t>(arguments[2]);

    // etc.
}
```

You might enjoy this example, https://github.com/wasmerio/wasmer/blob/master/lib/runtime-c-api/tests/test-import-function-callinfo.c.

I hope I clarified your issue. Please tell me if you need more insights.

**Comment by liamappelbe** [comment]
Ok, I think the thing I missed was that `num_params` in `wasmer_trampoline_buffer_builder_add_callinfo_trampoline` includes the context, so I should have put 3 rather than 2. Fixing that means I can access both my args in the arguments array.

The fact that the `b` arg in `int64_t my_callback(void*, int64_t* a, int64_t b) {` happened to actually contain the correct argument must have been a coincidence (or something to do with the calling convention), because I was essentially reading random memory. That arg should actually have been in `a[2]`, but wasn't because I had put 2 in `num_params`, rather than 3.

It might be a good idea to update the comments in wasmer.hh to say that `num_params` includes the context.

**Comment by Hywan** [comment]
> It might be a good idea to update the comments in wasmer.hh to say that num_params includes the context.

Correct.

**Comment by liamappelbe** [comment]
How are floats and doubles passed to the trampoline callback? I assumed that the arg array was just a wasmer_value (a union of the 4 types), and this seems to be true for I32 and I64. But floats and doubles come out as nonsense when I interpret them this way.

**Comment by syrusakbary** [comment]
We improved by a great margin the APIs in the refactor. I believe this issue should be fixed once the refactor lands in master :)

**Comment by syrusakbary** [comment]
We just landed the refactor into `master`.

The trampoline APIs are now much easier to use, both with functions with static arguments and functions with dynamic ones.
Let us know if you need any help using the new APIs @liamappelbe .

**Comment by liamappelbe** [comment]
Where can I find the new API? In 0.17.1 the trampoline functions were deprecated. Now it seems they've been deleted, and I can't find their replacement. The deprecation mentioned exposing `DynamicFunc::new` to the C API. Any word on that?

Should I use `wasmer_import_func_new` directly? If so I'll need some more info than the function's documentation provides about how exactly to use the `void (*func)(void *data)`.
