### ISSUE TITLE
Could wasmer support mulitiering compilation?

### ISSUE THREAD

**Issue by MaxGraey** [wasmerio/wasmer#758]
### Summary

Like first starts Cranelift compulation while LLVM JIT compiled on background and hotswap after ready

**Comment by nlewycky** [comment]
It doesn't yet. Currently our compilation strategy is ahead-of-time ("AOT") with caching.

With tiering, you generally have code produced by multiple backends running at the same time, which necessitates shared design of parts of the VM. To make up an example, two backends couldn't choose to store Wasm global variables in different ways or else `global.set` in one wouldn't work with `global.get` in the other. While much of the VM is shared, there's a few pieces that aren't, such as how we detect when a memory access is out of bounds.

**Comment by Hywan** [comment]
It's not supported yet, and it's not in our immediate roadmap. I'm closing the issue :-). If you need this feature, please consider to re-open this issue, and we will discuss further.
