### ISSUE TITLE
Is it possible to give an explanation of what these codes do : wasmer/examples/

### ISSUE THREAD

**Issue by shrin18** [wasmerio/wasmer#775]
### Summary

I am experimenting with WASM and need to create a benchmark for 10 wasm programs in our experiment. For these we have selected the codes in wasmer/examples/
However, I do not know what each of these codes do since I am not familiar with WASM language. Is it possible to give an explanation of what these codes function ?

### Additional details

\Thanks in advance

**Comment by MarkMcCaskey** [comment]
Hi!  Thanks for reaching out.  Would updating the [readme](https://github.com/wasmerio/wasmer/blob/master/examples/README.md) be sufficient?

If you're looking for Wasm programs to run https://wapm.io has a good amount and you can easily install them with `wapm install project-name`, that will put them in a local folder called `wapm_packages`.

We'd love to improve our documentation, just let me know what you need!

**Comment by syrusakbary** [comment]
Note: there is a new util for benchmarking uploaded into wapm:
You can run it in your browser entering this url:

https://wapm.io/package/vshymanskyy/coremark#shell

And typing `coremark` and "Enter".

You can also run it locally by doing:

```bash
wapm install vshymanskyy/coremark
wapm run coremark
```

Closing the issue for now. Let us know if there is something that we can take an action from this issue
