### ISSUE TITLE
Get param/return type info for wasmer_import_descriptor_t

### ISSUE THREAD

**Issue by avasylev** [wasmerio/wasmer#789]
### Summary

Is there way to get param/return types for import function from module? 

### Additional details

I can get list of imports and their names via wasmer_import_descriptor_t. But not expected param/return types. Am I missing some other way?
Need this to dynamically generate callbacks.

**Comment by syrusakbary** [comment]
This is indeed a great use case.

You can use `wasmer_import_func_params ` and `wasmer_import_func_returns` for getting those types.

https://github.com/wasmerio/wasmer/blob/master/lib/runtime-c-api/wasmer.h#L465-L508

Closing the issue. Let us know if this will be sufficient, and in case is not we will reopen the issue!
