### ISSUE TITLE
Wasmer on Raspberry Pi?

### ISSUE THREAD

**Issue by moonheart08** [wasmerio/wasmer#826]
### Summary
The question is fairly simple: Does Wasmer support running on the Raspberry Pi? (In my case, a Raspberry Pi 3 B+)
This implies support for ARMv8

**Comment by syrusakbary** [comment]
We are very close to getting Wasmer running there ( #713 )

Stay tuned for updates!

**Comment by igrep** [comment]
Can't we use on ARM with the LLVM backend? I guess the singlepass backend is a different issue...

**Comment by syrusakbary** [comment]
Yeah, ARM in the LLVM backend is also possible.

Now that we merged #713 we should be good to go closing this issue as ARMv8 is now supported in Wasmer!
You can install it in your Raspberry Pi as normal:

```
curl https://get.wasmer.io -sSfL | sh
```

**Comment by leung85** [comment]
i got this message on raspberry pi 4:

`> The system architecture (armv7l) is not supported by this installation script.`

**Comment by syrusakbary** [comment]
@leung85 perhaps this guide might help:
https://conoroneill.net/2019/12/02/running-wasmer-on-a-raspberry-pi-4-with-64bit-userland.md/

Let us know if it worked!

**Comment by robinvanemden** [comment]
Running Wasmer on a Raspberry Pi 4 has become even easier. Just install Ubuntu server 64-bit for Raspberry Pi 4 by following the basic installation instructions [here](https://ubuntu.com/download/raspberry-pi). 

Then run the usual `curl https://get.wasmer.io -sSfL | sh` to install Wasmer and Wapm, and test drive your Wasmer install by running, for instance, `wapm install lhauspie/fibo@1.0.2` followed by `wapm run fibo 10`.

**Comment by FGasper** [comment]
@robinvanemden Is that supposed to work still?

When I try the regular installer on Ubuntu64 on RPi4, it tells me the platform (linux-aarch64) is unsupported.

When I try to _build_ Wasmer on the same box, the compile seems to hang when building `wasmer-wasi`.

Thanks for any insight you could share!
