### ISSUE TITLE
Wasmer dylib size requirements for various languages

### ISSUE THREAD

**Issue by MarkMcCaskey** [wasmerio/wasmer#837]
We want to ship more features to our language integrations but we need more information about shipping larger binaries for these libraries.

If you have knowledge of packaging in any of the languages we support, please share information here about the acceptable size of libraries in your ecosystem!

We have the option to have development vs production releases with customized features in the released version, but that adds a lot of complexity and makes the libraries harder to use.

For reference our latest release has the dylib at 2.33mb and the so at 5mb.  I was able to get the dylib down to about 740kb with just the Singlepass backend and about 1.3mb with the Singlepass and Cranelift backend.

There are some easy wins here from our last release, like stripping the symbol names, which I don't think our CI release pipeline is doing.

Results from commit 73137140fa4f2924df152c7778f70aa949135890

Table of sizes of the dylib on OSX:

| &nbsp; | Release normal | Release normal stripped | Optimized for size | Optimized for size stripped |
| - | ---: | ---: | ---: | ---: |
| Singlepass* | 1,863,564 | 1,467,732 | 1,451,780 | 894,668 |
| Cranelift | 2,881,740 | 2,301,060 | 2,346,100 | 1,471,788 | 
| LLVM | 25,257,176 | 22,255,440 | 24,880,472 | 21,715,320 |

*Singlepass was built with 2019-09-23 version of nightly, everything else was built with stable

Optimization for size is:
```toml
[profile.release]
opt-level = 'z'
debug = false
debug-assertions = false
lto = true
panic = 'abort'
codegen-units=1
```

There are further optimizations we can do -- I've gotten `Singlepass` down to ~748kb with these

**Comment by Hywan** [comment]
I think we could produce 4 shared libraries:
1. Singlepass only
2. Cranelift only
3. LLVM only
4. Singlepass + Cranelift

I love LLVM, but the shared library would be really too large.

This proposal is a first quick step. On the long term, I imagine that all language integrations must provide a way to compile a specific backend for the current target. Choosing the backends is a requirement, but I'm not super comfortable with sharing shared libraries. Users can easily get confused by the architecture, OS or something.

**Comment by MarkMcCaskey** [comment]
@Hywan I talked to Nick about optimizing the size of LLVM.  There are no standard supported ways to do it, but we can pick which .o files we include in our LLVM binary and cut out pieces to make it much smaller.  We then have to deal with the consequences of possibly missing these features in inkwell which means we'd have to have another level of editing.

It seems difficult and annoying but it should be possible if we really want to to massively reduce the size of LLVM.  When Rust uses newer LLVM and gets the new fancy LTO between C/C++ and Rust that was recently announced, then maybe it'll just get better.

**Comment by MarkMcCaskey** [comment]
I think we have a working solution for this so far. We can reopen this issue if there's more to talk about here but I'm going to consider this a solved problem for now

**Comment by Hywan** [comment]
Agree.
