### ISSUE TITLE
Use Wasmer in project

### ISSUE THREAD

**Issue by theobouwman** [wasmerio/wasmer#853]
### Summary

Hello, I would like to use Wasmer in a existing rust project. I just need to be able to call the run function from within my application. The idea is to create a server which executes a particular .wasm file based on events like http requests and other triggers.
It also needs to be able to handle many triggers/events at the same time with different .wasm files.

**Comment by MarkMcCaskey** [comment]
Hello!

That sounds like a neat project!

We have some examples which might help you get started:

- [callback example with no ABI wasm](https://github.com/wasmerio/wasmer/blob/master/examples/callback.rs)
- [WASI FS API plugin example](https://github.com/wasmerio/wasmer/blob/master/examples/plugin.rs)
- [parallel example](https://github.com/wasmerio/wasmer/tree/master/examples/parallel)

Feel free to ask questions and let us know if you run into any issues!

**Comment by theobouwman** [comment]
Tnx
