### ISSUE TITLE
Metering features

### ISSUE THREAD

**Issue by mikhailOK** [wasmerio/wasmer#890]
It would be nice to have the following features for metering:
1. Getting the points used when Module::instantiate fails in start_func(): in this case there is no Instance returned
2. Having a way to increment points_used in host functions called by the wasm code through ImportObject: currently it's possible to point at Instance from the state of ImportObject, but no way to do it for initializer before Instance is created

**Comment by Hywan** [comment]
Closing this issue since we have [the `wasmer-middlewares` crate](https://docs.rs/wasmer-middlewares/) that provides the `Metering` middleware. See it in action in https://github.com/wasmerio/wasmer/blob/c7f4bd28109ee1eaa18c5979c5abe6ada5beb67c/examples/metering.rs.
