### ISSUE TITLE
Error: error: unknown error with the singlepass backend

### ISSUE THREAD

**Issue by jedisct1** [wasmerio/wasmer#896]
### Describe the bug

Some libsodium tests fail with the `singlepass` backend:

```sh
wasmer run --backend singlepass xchacha20
```

```text
Error: error: unknown error
```

```text
wasmer 0.8.0 | rustc 1.40.0-nightly (c27f7568b 2019-10-13) | x86_64
```

### Steps to reproduce

Sample wasm file:
[xchacha20.zip](https://github.com/wasmerio/wasmer/files/3755404/xchacha20.zip)

**Comment by syrusakbary** [comment]
I've tested in current Wasmer `1.0.0-alpha4` and the file works properly with singlepass:

```bash
$ wasmer xchacha20.wasm  --singlepass
16661970000
```

Closing the issue
