### ISSUE TITLE
Standarize Singlepass traps

### ISSUE THREAD

**Issue by mikhailOK** [wasmerio/wasmer#903]
### Describe the bug

Running a wasm code that just crashes gives different errors in singlepass backend and singlepass + metering

Singlepass backend: `RuntimeError::Trap { msg }`
Singlepass backend with metering: `RuntimeError::Error { data }` where type of `data` is not a string or `ExecutionLimitExceededError`

### Steps to reproduce
Wat code:
```
(module
              (type (;0;) (func))
              (func (;0;) (type 0) (unreachable))
              (export "hello" (func 0))
            )
```

versions: 
```
wasmer-runtime = { version = "0.9.0", features = ["singlepass"] }
wasmer-runtime-core = { version = "0.9.0"}
wasmer-middleware-common = "0.9.0"
wasmer-singlepass-backend = "0.9.0"
```

singlepass compiler: 
```wasmer_singlepass_backend::SinglePassCompiler::new()```
singlepass compiler with metering:
```
    use wasmer_singlepass_backend::ModuleCodeGenerator as SinglePassMCG;
    <StreamingCompiler<SinglePassMCG, _, _, _, _>>::new(move || {
        let mut chain = MiddlewareChain::new();
        chain.push(Metering::new(limit));
        chain
    })
```

### Expected behavior
Code compiled with metering should return the same error as without

**Comment by syrusakbary** [comment]
Hi @mikhailOK, thanks for the report! It seems like a bug.

Would you like to help us on resolving it? We can provide as much guidance as needed! :)

**Comment by mikhailOK** [comment]
Actually I was wrong, it's not related to metering: it's actually cranelift vs singlepass (with or without metering)

**Comment by syrusakbary** [comment]
In the refactor, all compilers return the same errors (and we test it so). We should be able to close this issue once the refactor lands

**Comment by syrusakbary** [comment]
Thanks to the refactor, all compilers now behave the same way regarding traps.

Closing the issue
