### ISSUE TITLE
Cannot run Go wasm binary

### ISSUE THREAD

**Issue by alshdavid** [wasmerio/wasmer#924]
### Describe the bug

Failure when running a Go application compiled to wasm.

```go
package main

import (
  "fmt"
)

func main() { 
  fmt.Println("Hello World") }
}
```

```
wasmer run main.wasm --disable-cache

Error: Can't instantiate module: LinkError([ImportNotFound { namespace: "go", name: "debug" }, ImportNotFound { namespace: "go"
, name: "runtime.wasmExit" }, ImportNotFound { namespace: "go", name: "runtime.wasmWrite" }, ImportNotFound { namespace: "go", 
name: "runtime.nanotime" }, ImportNotFound { namespace: "go", name: "runtime.walltime" }, ImportNotFound { namespace: "go", nam
e: "runtime.scheduleTimeoutEvent" }, ImportNotFound { namespace: "go", name: "runtime.clearTimeoutEvent" }, ImportNotFound { na
mespace: "go", name: "runtime.getRandomData" }, ImportNotFound { namespace: "go", name: "syscall/js.stringVal" }, ImportNotFound { namespace: "go", name: "syscall/js.valueGet" }, ImportNotFound { namespace: "go", name: "syscall/js.valueSet" }, ImportNotFound { namespace: "go", name: "syscall/js.valueIndex" }, ImportNotFound { namespace: "go", name: "syscall/js.valueSetIndex" }, ImportNotFound { namespace: "go", name: "syscall/js.valueCall" }, ImportNotFound { namespace: "go", name: "syscall/js.valueNew" }, ImportNotFound { namespace: "go", name: "syscall/js.valueLength" }, ImportNotFound { namespace: "go", name: "syscall/js.valuePrepareString" }, ImportNotFound { namespace: "go", name: "syscall/js.valueLoadString" }])
make: *** [run] Error 1
```

```sh
echo "`wasmer -V` | `rustc -V` | `uname -m`"
zsh: command not found: rustc
wasmer 0.9.0 |  | x86_64
```

MacOS, installed via the shell script from the website.

### Steps to reproduce

```
mkdir gotest && cd gotest
go mod init gotest
echo "package main; import (\"fmt\"); func main() { fmt.Println(\"Hello World\") }" > main.go
go run main.go
GOOS=js GOARCH=wasm go build -o main.wasm
wasmer run main.wasm
```
### Expected behavior
It should say "Hello World"

### Actual behavior
Error

**Comment by Hywan** [comment]
The WebAssembly module representing the Go program needs imports. `go build` with `GOARC=wasm` generates a WebAssembly module for the Web mostly, and expects a collection of imported functions (aka host functions) to be defined. In your case, it is:

* `go.debug`,
* `go.wasmExit`,
* `go.runtime.wasmWrite`,
* `go.nanotime`,
* `go.runtime.walltime`,
* `go.go.scheduleTimeoutEvent`,
* `go clearTimeoutEvent`,
* `go.getRandomData`,
* `go.syscall/js.stringVal`,
* `go.syscall/js.valueGet`,
* `go.syscall/js.valueSet`,
* `go.syscall/js.valueIndex`,
* `go.syscall/js.valueSetIndex`,
* `go.syscall/js.valueCall`,
* `go.syscall/js.valueNew`,
* `go.syscall/js.valueLength`,
* `go.syscall/js.valuePrepareString`,
* `go.syscall/js.valueLoadString`.

You can define those host functions with [the `ImportObject` API](https://docs.rs/wasmer-runtime/0.9.0/wasmer_runtime/struct.ImportObject.html).

**Comment by Hywan** [comment]
To be clear: For the moment, Wasmer doesn't provide a host function collection for Go _yet_.

**Comment by rusenask** [comment]
ah, so if we are using go-ext-wasm we could just create these functions, create C definitions and then import then into the instance (using go namespace) and it should work then?

**Comment by Hywan** [comment]
Your last comment was correct :-). I'm closing this issue. Feel free to ask more help if you need!

**Comment by uloskae** [comment]
@Hywan  any news? how can i get those funciones into wasmer ;'(

**Comment by williamwebb** [comment]
I second @sdykae 's question. I don't know if this is an issue with the wasm golang generates, or wasmer. But trying to run a golang generate binary fails, and there is seemingly no documentation for what the correct path _should_ be.
