### ISSUE TITLE
Appending to file does not work

### ISSUE THREAD

**Issue by leonardas103** [wasmerio/wasmer#936]
I am trying to run a simple wasm program, see code [here](https://github.com/WilliamMartini/WASM/blob/master/rust/main.rs)

I am running: ```wasmer run --dir=. demo.wasm '{"a":"txt", "b":1}'```  
which should append ```txt 1``` to a ```log.txt``` file.  

However, the data is not appending but instead writing over. The same program compiled with native Rust (non-wasm) appends properly.

**Comment by CryZe** [comment]
If you execute it with wasmtime, does it have the same problem?

**Comment by CryZe** [comment]
Looks like there's no logic for append here: https://github.com/wasmerio/wasmer/blob/master/lib/wasi/src/syscalls/mod.rs#L1726-L1742

**Comment by leonardas103** [comment]
> If you execute it with wasmtime, does it have the same problem?

With wasmtime the program does not execute at all, I get the following error:
```
thread 'main' panicked at 'write failed: Os { code: 76, kind: Other, message: "Capabilities insufficient" }', src/libcore/result.rs:1084:5

```

**Comment by CryZe** [comment]
Looks like append isn't even part of the spec: https://github.com/WebAssembly/WASI/blob/master/phases/ephemeral/docs/wasi_ephemeral_preview.md#__wasi_oflags_t-uint16_t-bitfield

**Comment by MarkMcCaskey** [comment]
Thanks for reporting this!  I'll investigate and ship a fix
