### ISSUE TITLE
Java Language Bindings Support

### ISSUE THREAD

**Issue by benzap** [wasmerio/wasmer#950]
### Motivation

Java is an ecosystem that would really benefit from a stable and mature web assembly runtime. My personal motivation is to use wasmer within the java ecosystem, and to develop a DSL to target webassembly as a sandboxed scripting environment.

### Proposed solution

Write up wasmer bindings with JNI to support wasmer within the java ecosystem. This would allow it to be used by JVM-based languages (scala, kotlin, clojure). The solution would first support x86 and x86-64 until wasmer supports arm and arm64 in the future.

**Comment by Hywan** [comment]
We are working on it :-).

**Comment by zubivan** [comment]
@Hywan awesome news! Is there an issue somewhere we can use to track progress or maybe help you folks out?

**Comment by Hywan** [comment]
Not yet, but I hope to make the repository public in a couple of weeks (depending of other projects). Let's keep this issue open for the moment. Feel free to ping me at anytime :-).

**Comment by syrusakbary** [comment]
@zubivan we have started a private repo that we would open-source soon. Would you like to have access and help us on the bindings?

PS: invitation would be open for anyone that wants to help, if that's you... ping us and we will give you access before we make it public!

**Comment by benzap** [comment]
@syrusakbary, I would be interested in access. This gives me an excuse to learn some JNI. I would be willing to help with the documentation as well.

**Comment by azam** [comment]
@syrusakbary 
I might be able to help for Java side.
Also doing assessment of WASM runtimes on Java, so it would be great to be able to try it out as well.

**Comment by syrusakbary** [comment]
@benzap @azam I just gave you access to the repo. Let me know if you are able to access it :)

**Comment by benzap** [comment]
@syrusakbary I've looked around, and I haven't received a notification for access to any of your repositories. Can you point me in the right direction? I'm excited to see how it's coming along!

**Comment by azam** [comment]
@syrusakbary No notifications for me too :(

**Comment by syrusakbary** [comment]
@benzap @azam you can review the invitation here:

https://github.com/wasmerio/java-ext-wasm/invitations

Let me know if you can access! :)

**Comment by azam** [comment]
@syrusakbary Accepted and viewable now.
Will take a look in the morning.
Thanks!

**Comment by gatesn** [comment]
Is there a reason the Java bindings aren’t open source? Even if they’re WIP

**Comment by Hywan** [comment]
@gatesn No particular reason, it's just how we run experimentations. The Java binding is under heavy conception. Making it public right now is kind of useless for the users :-).

**Comment by SimonWoodburyForget** [comment]
Will the bindings support Java 8?

**Comment by gatesn** [comment]
@Hywan that makes sense. Would I be able to get an invite to have a look while you're experimenting?

**Comment by Hywan** [comment]
cc @syrusakbary ☝️ 

@SimonWoodburyForget yes, Java 8 :-).

**Comment by syrusakbary** [comment]
@gatesn are you still interested in contributing? I can invite to our repo!

**Comment by syrusakbary** [comment]
Apologizes for the delay, somehow I missed the mention.

@gatesn are you still interested in contributing? We are very close to the release, I can invite to our repo if you want to contribute or become a maintainer!

**Comment by macthestack** [comment]
Very interesting project. How is it going? Are we close to open source?

**Comment by syrusakbary** [comment]
We open sourced the java integration, but forgot to close this issue.

Here's the announcement: https://medium.com/wasmer/announcing-the-first-java-library-to-run-webassembly-wasmer-jni-89e319d2ac7c
Here's the Java integration: https://github.com/wasmerio/java-ext-wasm

Closing the issue now as it should be solved!
