### ISSUE TITLE
Any plans moving to Bytecode Alliance?

### ISSUE THREAD

**Issue by sudhakar3697** [wasmerio/wasmer#956]
Any plans for moving this project to https://bytecodealliance.org ?

**Comment by MarkMcCaskey** [comment]
Thanks for posting this!  This is the first time I've heard of it -- we'll definitely look into!

**Comment by syrusakbary** [comment]
I reached this morning the people there (via email) asking to get more info about the alliance.

Haven't got any response so far.

Adding @tyler (Fastly CTO), @tschneidereit (manager Mozilla) and @xwang98 (Intel) to this thread to see if they can shed some light about the Bytecode organization.

**Comment by Hywan** [comment]
I've also reached Till (@tschneidereit) this morning, we have an excellent relationship. We would love to join the alliance for sure :-).

**Comment by codefishd** [comment]
suggestion -----> make an alliance with @WAVM @EOSIO @V8 @emscripten_core you are the ones building webassembly.

**Comment by syrusakbary** [comment]
In order to give full transparency of the process, I will use this issue to document the steps that we have taken regarding Bytecode Alliance.

## First contact - Nov 12, 2019

I wrote for the first time to the Bytecode Alliance `hello@bytecodealliance.org` on Nov 12 2019:

```
Hi,

First, congrats on forming the alliance!
As founder of Wasmer, the first company 100% focused on WebAssembly, I believe that WebAssembly will become a key part for assuring safe execution of untrusted code.

I'd be interested in learning more about the Bytecode Alliance.


Best,
Syrus
````

## Second email - Nov 21, 2019

After a quick reply from @tschneidereit about 2 weeks ago (Nov 21, 2019) I expanded on my query:

```
Hi Till,

We were investigating if it could make sense or not for Wasmer to become part of the Bytecode Alliance (as an affiliated project).
Regarding mission, values and FAQ everything makes sense there.

Because of that, I wanted to follow up to get some guidance on how are you collaborating in-between companies and if you think that it would make sense for us to join the Alliance.

Right now there has been a lot of duplicated effort between projects, and we are hoping we can make collaboration for all of us easier in the future.
I think we now have an incredible opportunity to improve this in a way that is helpful for users. Such as: better runtime support across tools (WAPM, wasienv, cargo wasi), or collaborating on Wasm Interface Types more closely.

Specifically, if we can find a way that is not detrimental for any of the projects.
We feel like users could benefit if tooling in the ecosystem, such as cargo wasi and wasienv, could be flexible in the runtime tools they use. Creating an environment where any runtime is allowed and where we give more options for the users and the alliance acts more as a standardization body to push WebAssembly forward rather than fulfill company interests.


Best,
Syrus
```

To date, we haven't received any reply.
I feel hopeful we will receive a follow up from them soon 🙂

**Comment by codefishd** [comment]
this is not an alliance to build webassembly, but a handful companies who want to take control of it. webassembly doesn't need an alliance, but open discussions where everybody can have a say.

**Comment by appcypher** [comment]
@codefishd Exactly! Very sad.

**Comment by rofrol** [comment]
Bu Mozilla is also in this alliance.

**Comment by Hywan** [comment]
After several attempts and discussions, the BytecodeAlliance refuses to let us join the alliance, for no clear or neutral reasons. We tried, we did our best to openly and friendly discuss with them.

This is an alliance about WebAssembly. We are part of the major WebAssembly actors. But they keep excluding us. I believe the message is clear. I let everyone a freeroom to read between the lines. We aren't going to spend more time trying to join the BytecodeAlliance. I'm closing this issue 🙂.

**Comment by showyourfaces** [comment]
Maybe they don't want you to join because of this kind of thing: https://uspto.report/company/Wasmer-Inc
Don't try to be the victim here!

**Comment by syrusakbary** [comment]
That narrative doesn't reflect the reality @showyourfaces.
I assume your account was created with the best intentions in mind, but I'd appreciate to know who we are speaking with, to avoid unintended flameware 😉 

Some more context: The Bytecode Alliance vetoed Wasmer the same day the alliance was announced, on November 12 2019 (via direct message by one of their well-known members -now working at Fastly- to an investor of Wasmer). If you track the dates, you will see how things match :)

**Comment by syrusakbary** [comment]
Unless the BA members have future-reading abilities (which perhaps they have, who knows!), that narrative is hard to hold @showyourfaces.
I assume your account was created with the best intentions in mind, but I'd appreciate to know who we are speaking with, to avoid unintended flameware 😉 

Some more context: The Bytecode Alliance vetoed Wasmer the same day the alliance was announced, on November 12 2019 (via direct message by one of their well-known members -now working at Fastly- to an investor of Wasmer). If you track the dates, you will see how things match :)

**Comment by awsa2ron** [comment]
I don't want to comment, but I click the Star button after reading this issue. ✌🏽
