### ISSUE TITLE
[wasmer wasi FS] unwrap panic when wasi syscall failed

### ISSUE THREAD

**Issue by pventuzelo** [wasmerio/wasmer#963]
### Describe the bug

When a wasi module can't open a file descriptor, a panic error occurs. 
`wasmer` doesn't seems to panic himself so it's maybe more related to a 3rd party library. 
Need more investigation to understand exactly what's going on.

``` sh
$ wasmer run panic_unwrap_file_descriptor.wasm
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "failed to find a preopened file descriptor through which \"act1/..\" could be opened" }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Error: wasm trap occured: unknown
```

### Environment

```sh
echo "`wasmer -V` | `rustc -V` | `uname -m`"
wasmer 0.10.1 | rustc 1.38.0-nightly (2d1a551e1 2019-08-08) | x86_64
```
Commit: d64d070c9f3c80b72560f7da87d4c7b971dc725e

### Steps to reproduce

Download: [panic_unwrap_file_descriptor.zip](https://github.com/wasmerio/wasmer/files/3842106/panic_unwrap_file_descriptor.zip)

Run:
``` sh
$ unzip panic_unwrap_file_descriptor.zip
$ wasmer run panic_unwrap_file_descriptor.wasm
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "failed to find a preopened file descriptor through which \"act1/..\" could be opened" }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Error: wasm trap occured: unknown
```

### Expected behavior

Ideally, `wasmer` should throws the Error inside `Custom { kind: Other, error: "failed to find a preopened file descriptor through which \"act1/..\" could be opened"`

### Actual behavior

When running wasmer with the flag `RUST_BACKTRACE=1` or `RUST_BACKTRACE=full`, no extra information are returned. This behavior can confirm that the issue come from a 3rd party library.

``` sh
$ RUST_BACKTRACE=1 wasmer run panic_unwrap_file_descriptor.wasm
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "failed to find a preopened file descriptor through which \"act1/..\" could be opened" }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Error: wasm trap occured: unknown
```

### Additional context

The module is valid:
```
$ wasm-validate panic_unwrap_file_descriptor.wasm
$ wasmer validate panic_unwrap_file_descriptor.wasm
```

**Comment by MarkMcCaskey** [comment]
Hmm, without seeing the code I can't be sure what's happening.

I can't see any problems with Wasmer from this example.  The Rust code attempts to open a file but no preopened files were given so it fails.  The Rust code compiled to Wasm panics when this happens.

Looks like everything is working as intended!

**Comment by pventuzelo** [comment]
I just verify, you was right !! It's a false positive from the fuzzer.
