### ISSUE TITLE
Invalid trap on CoreMark SIMD with LLVM backend

### ISSUE THREAD

**Issue by kripken** [wasmerio/wasmer#969]
```bash
$ ~/.wasmer/bin/wasmer run --backend=llvm --enable-simd coremark-simd.wasm 
Error: wasm trap occured: memory out-of-bounds access
```

This problem doesn't happen in a build of the benchmark without SIMD.

I believe the file is valid, as the same wasm file runs ok in WAVM (running ok means it runs for 10-20 seconds and then prints some benchmark results). Also it is built with emscripten, and js+wasm versions (not standalone/wasi like this file) work with SIMD in V8, so the emitted SIMD is correct as far as I know.

[coremark-simd.wasm.zip](https://github.com/wasmerio/wasmer/files/3849001/coremark-simd.wasm.zip)

**Comment by syrusakbary** [comment]
Thanks for the report Alon! We are investigating it 🙂
