### ISSUE TITLE
Ability to catch a trap/panic

### ISSUE THREAD

**Issue by Hywan** [wasmerio/wasmer#986]
When a panic happens, it is caught and the trap API is run. It ends up panicking, and the end user seems to have no way to catch it.

That would be great to expose an API to register functions that can be executed when a trap is run, or better, an API to catch a trap/panic.

It will be super helpful to run untrusted Wasm modules from various users, or for language integrations (we can pipe the Wasmer panic/trap API to the targeted language panic API).

**Comment by fckt** [comment]
Is there any way to propagate panic which happened in the imported host function?

**Comment by Hywan** [comment]
All panics are now handled by the public API. This issue is no more relevant.
