### ISSUE TITLE
Remove Cranelift

### ISSUE THREAD

**Issue by codefishd** [wasmerio/wasmer#989]
Thanks for proposing a new feature!

### Motivation

1) SinglePass: fast compilation, bad performance
2) LLVM: slow compilation, excellent performance
3) CraneLift: somewhere in-between

Applications need either 1) or 2). Compilers have "debug" and "release" modes. No one uses something "somewhere in-between".

& CraneLift is Intel only.

### Proposed solution

Remove CraneLift. One less backend to maintain = time to improve other backends.

### Alternatives

If wasmer needs another backend: EOSVM or V8 = more useful.

**Comment by CryZe** [comment]
I don‘t agree with this. Cranelift has the advantage of being decently fast while still being entirely Rust. LLVM is a big C++ dependency, which makes it much harder to compile wasmer (in general).

**Comment by codefishd** [comment]
For testing -> SinglePass
For production -> LLVM

**Comment by nlewycky** [comment]
We're not ready to do this. Take a look at lib/spectests/tests/excludes.txt, there's more spectests failing with singlepass and llvm than with cranelift, and we can't remove our most conformant backend.

However, there are some steps we should take. Right now, we use the cranelift-wasm crate to turn wasm into cranelift IR. This causes us two problems: first, it goes directly from the wasmparser structures to the cranelift structures, which means that we can't update wasmparser without also updating cranelift (and we can't update cranelift without moving to whichever version of wasmparser they depend on). Second, not having our own cranelift-wasm means we can't add some additional features. This is why metering doesn't work with cranelift, for one. Having our own lowering from wasmparser to cranelift IR would reduce the maintenance burden of having cranelift as a backend. Maybe we could start with a wasmer fork of cranelift-wasm.

**Comment by syrusakbary** [comment]
> Remove CraneLift. One less backend to maintain = time to improve other backends.

In general, our strategy should always start with this question: "What the user needs?" and always push towards that direction. It seems removing Cranelift will just make things harder for the users right now, and that's something that might be in detriment of the ecosystem.

The good thing is: wasmer is built so it can adopt backends very easily, so if you would like to add support for v8 or eosvm on it we would be very happy with it.

> I don‘t agree with this. Cranelift has the advantage of being decently fast while still being entirely Rust. LLVM is a big C++ dependency, which makes it much harder to compile wasmer (in general).

Agreed.

**Comment by AdamSLevy** [comment]
>     1. SinglePass: fast compilation, bad performance
> 
>     2. LLVM: slow compilation, excellent performance
> 
>     3. CraneLift: somewhere in-between
> 
> 
> Applications need either 1) or 2). Compilers have "debug" and "release" modes. No one uses something "somewhere in-between".

I disagree with this analogy. The compilation done during development of software is different that the compilation done at runtime by the Wasm runtime. Cranelift isn't "somewhere in between" so much as it is a balance between compilation speed and execution speed of a wasm binary.

**Comment by syrusakbary** [comment]
Some days passed. Closing the issue :)
