### ISSUE TITLE
Allow different Instances to have distinct limits from the same compiled module

### ISSUE THREAD

**Issue by AdamSLevy** [wasmerio/wasmer#993]
### Motivation

As I understand the current metering code, a fixed limit is hard coded at compile time. This means that if different limits are desired for different instantiations of the same module, it must be recompiled each time with the distinct limit. 

Allowing a dynamic limit would allow caching the serialized module for many applications that use a dynamic limit per instance like smart contracts on a blockchain.

### Proposed solution

Use an additional `wasmer_runtime_core::vm::InternalField` to store a Limit that may be set at instantiation through an additional API: 
```rust
pub fn reset_limit(instance: &mut Instance, limit u64) {
    instance.set_internal(&INTERNAL_FIELD_LIMIT, limit)
}
```

Define an additional static InternalField is declared in the module so that we change this:
https://github.com/wasmerio/wasmer/blob/9e144c623b113e4dc83e048502dd4d43ad61217b/lib/middleware-common/src/metering.rs#L9

to this

```rust
static INTERNAL_FIELD_LIMIT: InternalField = InternalField::allocate();
static INTERNAL_FIELD_USED: InternalField = InternalField::allocate();
```

And then change this:

https://github.com/wasmerio/wasmer/blob/9e144c623b113e4dc83e048502dd4d43ad61217b/lib/middleware-common/src/metering.rs#L40-L110

to this:

```rust
impl FunctionMiddleware for Metering {
    type Error = String;
    fn feed_event<'a, 'b: 'a>(
        &mut self,
        op: Event<'a, 'b>,
        _module_info: &ModuleInfo,
        sink: &mut EventSink<'a, 'b>,
    ) -> Result<(), Self::Error> {
        match op {
            Event::Internal(InternalEvent::FunctionBegin(_)) => {
                self.current_block = 0;
            }
            Event::Wasm(&ref op) | Event::WasmOwned(ref op) => {
                self.current_block += 1;
                match *op {
                    Operator::Loop { .. }
                    | Operator::Block { .. }
                    | Operator::End
                    | Operator::If { .. }
                    | Operator::Else
                    | Operator::Unreachable
                    | Operator::Br { .. }
                    | Operator::BrTable { .. }
                    | Operator::BrIf { .. }
                    | Operator::Call { .. }
                    | Operator::CallIndirect { .. }
                    | Operator::Return => {
                        sink.push(Event::Internal(InternalEvent::GetInternal(
                            INTERNAL_FIELD_USED.index() as _,
                        )));
                        sink.push(Event::WasmOwned(Operator::I64Const {
                            value: self.current_block as i64,
                        }));
                        sink.push(Event::WasmOwned(Operator::I64Add));
                        sink.push(Event::Internal(InternalEvent::SetInternal(
                            INTERNAL_FIELD_USED.index() as _,
                        )));
                        self.current_block = 0;
                    }
                    _ => {}
                }
                match *op {
                    Operator::Br { .. }
                    | Operator::BrTable { .. }
                    | Operator::BrIf { .. }
                    | Operator::Call { .. }
                    | Operator::CallIndirect { .. } => {
                        sink.push(Event::Internal(InternalEvent::GetInternal(
                            INTERNAL_FIELD_USED.index() as _,
                        )));
                        sink.push(Event::Internal(InternalEvent::GetInternal(
                            INTERNAL_FIELD_LIMIT.index() as _,
                        )));
                        sink.push(Event::WasmOwned(Operator::I64GeU));
                        sink.push(Event::WasmOwned(Operator::If {
                            ty: WpTypeOrFuncType::Type(WpType::EmptyBlockType),
                        }));
                        sink.push(Event::Internal(InternalEvent::Breakpoint(Box::new(|_| {
                            Err(Box::new(ExecutionLimitExceededError))
                        }))));
                        sink.push(Event::WasmOwned(Operator::End));
                    }
                    _ => {}
                }
            }
            _ => {}
        }
        sink.push(op);
        Ok(())
    }
}
```

Are there any race condition considerations around the `INTERNAL_FIELD_LIMIT` with this approach?

**Comment by Hywan** [comment]
Hello,

This issue seems solved to me. The `Metering` middleware must be set on the compiler configuration ([see the documentation of `Metering`](https://docs.rs/wasmer-middlewares/2.0.0/wasmer_middlewares/metering/struct.Metering.html)), so the initial value is defined before the module is compiled. However, it is possible to update the remaining points for an instance with [`set_remaining_points`](https://docs.rs/wasmer-middlewares/2.0.0/wasmer_middlewares/metering/fn.set_remaining_points.html). So whatever the initial value you set when creating a `Metering`, you can define a new value before running any functions on the `Instance` with `set_remaining_points`.

The documentation contains examples. I'm not copy-pasting them here :-). We have another example that illustrates `set_remaining_points` in acition:

https://github.com/wasmerio/wasmer/blob/c7f4bd28109ee1eaa18c5979c5abe6ada5beb67c/examples/metering.rs#L157-L160

I'm closing the issue :-).
